### ISSUE TITLE
Future tests fails

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1009]
With <code>Concurrent</code> parameters
```java
    long WAIT_MILLIS = 0;
    int WAIT_COUNT = 10000000;
```
FutureTest fails. It seems <code>future.isComplete()</code> occurs before <code>future.onFailure()</code>

@danieldietrich this blocks rc3

**Comment by danieldietrich** [comment]
Just saw your fix. It's right, we saw race-conditions. Future behaves right. The onComplete actions are executed on separate threads of the underlying ExecutorService. Thx!

**Comment by danieldietrich** [comment]
@ruslansennov can be closed now, right?

**Comment by ruslansennov** [comment]
Sorry, I forgot

**Comment by danieldietrich** [comment]
All ok - just wanted to get sure. I'm preparing RC3...
