### ISSUE TITLE
Keep Monad clean, fix flatMap

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1018]
In order to ensure that we keep monadic behavior when composing Monads (e.g. by flatMapping), a re-design is needed. Example: We need it when composing AutoClosables that have to be all closed when an exception occurs.

* separate Monad.flatMap from specific flatMap methods by renaming Monad.flatMap to Monad.flatMapM ✓
* Monad needs to extend recursive self-type Kind1 ✓
* remove all methods from Monad other than map and flatMapM, especially filter ✓
* remove Value.getOption ✓
* re-implement flatMap of all Value impls in a clean way
* ~~remove filter from all Value impls other than Traversable, Gen and Arbitrary~~
* ...

**Comment by danieldietrich** [comment]
The `BiFunctor.bimap` function with argument

```java
Function<? super Tuple2<? super T1, ? super T2>, ? extends Tuple2<? extends U1, ? extends U2>>
```

made problems. Without loosing anything we can simplify it to

```java
Function<Tuple2<T1, T2>, Tuple2<U1, U2>>
```

Tested with IntelliJ IDEA:

```java
interface Test<T1, T2> {

    <U1, U2> HashMap<U1, U2> bimap(Function<Tuple2<T1, T2>, Tuple2<U1, U2>> f);

    static <T1, T2> Test<T1, T2> create() {
        return null;
    }

    static void test() {

        Test<Integer, Iterator<String>> test = create();

        // ok
        Map<Number, Seq<CharSequence>> r1 = test.bimap(entry -> Tuple.of(entry._1, List.ofAll(entry._2)));

        // ok
        HashMap<Integer, List<String>> r2 = test.bimap(entry -> Tuple.of(entry._1, List.ofAll(entry._2)));
    }
}
```

I will scan the other method signatures of Javaslang if we can simplify anything.

**Comment by danieldietrich** [comment]
I question the support of a BiMonad type. Currently `javaslang.collection.Map` implementations are the only `BiMonad`s. We could make them `Monad`s regarding the _Map values_ instead:

```java
final class HashMap implements Monad<HashMap<K, ?>, V> {
    <V2> HashMap<K, V2> flatMapM(Function<? super V, ? extends Kind1<HashMap<K, ?>, V2>> mapper);
}
```

However, Scala supports Map.flatMap:

```scala
scala> Map(1 -> "a", 2 -> "b", 3 -> "c")
res0: scala.collection.immutable.Map[Int,String] = Map(1 -> a, 2 -> b, 3 -> c)

scala> res0.flatMap(entry => List(entry))
res1: scala.collection.immutable.Map[Int,String] = Map(1 -> a, 2 -> b, 3 -> c)

scala> res0.flatMap(entry => List(entry._2))
res2: scala.collection.immutable.Iterable[String] = List(a, b, c)

scala> res0.flatMap(entry => List(entry._1))
res3: scala.collection.immutable.Iterable[Int] = List(1, 2, 3)
```

**Comment by danieldietrich** [comment]
In my opinion Map should be of type `Monad` over `Tuple1<K, V>` instead of type `BiMonad` over `K` and `V`.

The only caveat is that the `Monad.flatMapM` can't return the right type:

```java
interface MyType<T1, T2> extends Monad<MyType<?, ?>, Tuple2<T1, T2>> {
    // result can't be MyType<U1, U2> because we only have U
    <U> Monad<MyType<?, ?>, U> flatMapM(Function<? super Tuple2<T1, T2>, ? extends Kind1<MyType<?, ?>, U>> mapper);
}

interface MyType<T1, T2> extends BiMonad<MyType<?, ?>, T1, T2> {
    // return type ok
    <U1, U2> MyType<U1, U2> flatMapM(BiFunction<? super T1, ? super T2, ? extends Kind2<MyType<?, ?>, U1, U2>> mapper);
}
```

**Comment by danieldietrich** [comment]
The _flavor_ of the component type needs to be fixed. E.g. is it Object, Tuple2, ...

```java
public interface Functor<COMP, T extends COMP> {
    <U extends COMP> Functor<COMP, U> map(Function<? super T, ? extends U> f);
}

public interface Monad<M extends Kind1<M, ?>, COMP, T extends COMP> extends Kind1<M, T>, Functor<COMP, T> {
    <U extends COMP> Monad<M, COMP, U> flatMapM(Function<? super T, ? extends Kind1<M, U>> mapper);
    @Override
    <U extends COMP> Monad<M, COMP, U> map(Function<? super T, ? extends U> mapper);
}

public final class HashMap<K, V> implements Map<K, V>, Monad<HashMap<?, ?>, Tuple2, Tuple2<K, V>> {
@Override
    public <U extends Tuple2> Monad<HashMap<?, ?>, Tuple2, U> flatMapM(Function<? super Tuple2<K, V>, ? extends Kind1<HashMap<?, ?>, U>> mapper) {
        ...
    }
}
```

However, the Tuple2 elements of U are still missing...

**Comment by danieldietrich** [comment]
I currently redesign the Monad stuff because I have one thing in mind: we need to preserve the behavior of the underlying Monad.

I'm in fear of loosing 'state'. In [these examples](https://gist.github.com/danieldietrich/71be006b355d6fbc0584)) we allow to flatMap over a cascade of different Monads. This is possible because we relaxed the Monad Laws there. But Scala does not allow this in general:

```scala
import scala.util._

object tests {

  val f : (String, Int) => String = (s, i) => s + i

  //                     v-------------------------v type mismatch; found : Option[String] required: scala.util.Try[?]
  Try("hi").flatMap(s => Option(1).map(i => f(s, i)))
  
  for {
     s <- Try("hi")
     i <- Some(1) // <- type mismatch; found : Option[String] required: scala.util.Try[?]
  } yield f(s, i)

}
```

To be further investigated. Would be interesting to see how Haskell behaves.

**Comment by danieldietrich** [comment]
I will go back to the Monad we currently have - it is the best solution. But instead of Value, sub-classes/-interfaces of Value will implement Monad.

```java
interface Functor<T> {
    <U> Functor<U> map(Function<? super T, ? extends U> f);
}

interface Monad<T> extends Functor<T> {

    <U> Monad<U> flatMap(Function<? super T, ? extends Iterable<? extends U>> mapper);

    @Override
    <U> Monad<U> map(Function<? super T, ? extends U> mapper);
}

interface Traversable<T> extends Monad<T> {

    @Override
    <U> Traversable<U> flatMap(Function<? super T, ? extends Iterable<? extends U>> mapper);

    @Override
    <U> Traversable<U> map(Function<? super T, ? extends U> mapper);
}

interface List<T> extends Traversable<T> {

    @Override
    <U> List<U> flatMap(Function<? super T, ? extends Iterable<? extends U>> mapper);

    @Override
    <U> List<U> map(Function<? super T, ? extends U> mapper);
}

interface Map<K, V> extends Traversable<Tuple2<K, V>> {

    @Override
    <U> List<U> flatMap(Function<? super Tuple2<K, V>, ? extends Iterable<? extends U>> mapper);

    @Override
    <U> List<U> map(Function<? super Tuple2<K, V>, ? extends U> mapper);
}

interface Option<T> extends Monad<T> {

    @Override
    <U> Option<U> flatMap(Function<? super T, ? extends Iterable<? extends U>> mapper);

    @Override
    <U> Option<U> map(Function<? super T, ? extends U> mapper);
}
```

**Comment by johnmcclean-aol** [comment]
I haven't implemented any direct support for Map yet, AnyM only accepts one type so that would force you to either drop one type (key or value) or use a Tuple2 for a map.

For Tuple2 you would get something like this 

        AnyM<Tuple2<Key,Value>> map;

The main problem being that map and flatMap can return something other than a Tuple2, which makes that problematic, without putting special rules in place (e.g. if you return a Tuple2 both the key and value are changed, otherwise the monad is converted to a List of the returned values)

You could argue that inside an AnyM the value is the most interesting property, since operations effectively iterate rather than looking up by key 

        AnyM<Value> map;

But you then lose the ability to change the key.

The second approach is less powerful, but less likely to violate the principal of least surprise. Because you are inheriting from monad rather than wrapping it, not sure either of theses approaches is feasible for the javaslang Monad interface.

**Comment by danieldietrich** [comment]
Thank you! I will stick with the current behavior in Javaslang, just cleaning up a bit... slightly :-)

**Comment by johnmcclean-aol** [comment]
No worries, it's useful to think about, I should add support for Maps into cyclops at some point. Thinking a bit more about, it would be best (in cyclops) to let the user decide at AnyM creation time what properties they wanted to target (key, value or key and value) - for later the underlying datastructure would be converted to a List (at creation) for the other two only one property could be manipulated. I'd need to try a few experiments though.

**Comment by danieldietrich** [comment]
Javaslang has to be more restrictive. The method signatures of map and flatMap must match across the whole inheritance tree. The best I can do for Maps is to return sequences of mapped results (which might not be Tuples). I'm looking forward to see your solution.
