### ISSUE TITLE
Future onSuccess onFailure should return Future object

### ISSUE THREAD

**Issue by manu-m** [javaslang/javaslang#1020]
Future and Try both consist of onSuccess and onFailure methods. The Try's versions returns the Try object, the Future's versions are void methods. I would propose to change the Future's return type to Future and return the Future object. I personally like chaining these method calls:

```java
Future.of(() -> /* read person from database */)
    .onSuccess(val -> /* do something on success */)
    .onFailure(val -> /* do something on failure */)
```

From my point of view, it is more concise than:
```java
Future<Person> future = Future.of(() -> /* read person from database */);
future.onSuccess(val -> /* do something on success */)
future.onFailure(val -> /* do something on failure */)
```

What do you think?

**Comment by danieldietrich** [comment]
Yes, this would be great! I also thought about it. Scala does it not but Scala is not perfect.
Thank you!
