### ISSUE TITLE
Create Benchmark java.util.stream.Stream vs. javaslang.collection.Stream

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#103]
How does Javaslang's Stream, List etc. perform compared to Java's?

**Comment by danieldietrich** [comment]
Here is a benchmark created on my early 2011 macbook pro using Scala 2.11.6 and Java 1.8.0_40.

## Test setup

The test covers the creation of an infinite lazy stream of ints starting with 1, filtering even numbers and dropping 100 million elements. The first element of the remaining stream is taken.

1. Start time mesure
2. Execute command
3. Print time

## The results

| language | time | command |
| :--- | :-- | :--- |
| Java | 0,5 sec | <pre>IntStream.iterate(1, i -> i + 1)<br>    .filter(i -> i % 2 == 0)<br>    .skip(100_000_000)<br>    .findFirst()</pre> |
| Java | 1,5  sec | <pre>IntStream.iterate(1, i -> i + 1)<br>    .mapToObj(Integer::valueOf)<br>    .filter(i -> i % 2 == 0)<br>    .skip(100_000_000)<br>    .findFirst()</pre> |
| Java | OutOfMemoryError | <pre>IntStream.iterate(1, i -> i + 1)<br>    .parallel()<br>    .skip(100_000_000)<br>    .filter(i -> i % 2 == 0)<br>    .findFirst()</pre> |
| Javaslang | 15,8 sec | `Stream.from(1).filter(i -> i % 2 == 0).drop(100_000_000)` |
| Scala | 17,7 sec | `Stream.from(1).filter(i => i % 2 == 0).drop(100000000)` |

## Conclusion

Java's Stream is blazing fast.

_(-- long time nothing)_

Javaslang's Stream is a great alternative to Java's Stream. It is more concise and more powerful regarding the amount of operations. Starting with Java's Stream we come soon to the point that it is hard or even not possible to express something with the Stream API. Javaslang's Stream is slightly faster than Scala's Stream.

Java's Stream.parallel() feature does not convince me. It is a great tool to optimize carefully selected parts of our application but should be used with caution.

**Comment by danieldietrich** [comment]
This was just a little spike. Comes time and progress, there will be a complete benchmark of all methods of all relevant frameworks.

Also a more mature comparison makes sense. Structural data types vs. in-place operations. Reusability of instances, thread-safety and immutability. Primitive types vs. objects. Sequential vs. parallel processing. Conciseness, usability, etc. There is much to say...

**Comment by kant111** [comment]
Does this results still hold? Sounds like Vavr Stream is a huge performance hit compared to Java one. If so, shouldn't we be using Java 8 Stream?

**Comment by danieldietrich** [comment]
> Does this results still hold? Sounds like Vavr Stream is a huge performance hit compared to Java one. If so, shouldn't we be using Java 8 Stream?

There is only one think Vavr's Stream and Java's Stream have in common - the name :)

Really, Vavr's Stream is a persistent linked list, like List, but lazily evaluated, like Iterator. The main difference to Java's Stream is, that Vavr's Stream can be processed multiple times. Java's Stream really is a 'sophisticated' Iterator, very much like Vavr's io.vavr.collection.Iterator.

This is all aligned to the Scala world, so it is nothing new.

As an advice, I would use Java's Stream in a local context (like a method body) as a form of reduction or transformation of elements like java.util collections or arrays. If your code gets clumsy because you are in 'Collectors Hell', then it might be a viable solution to use Vavr's collections. You will trade conciseness against performance. However, it is still a solution to use Vavr's Iterator instead of Java's Stream.

**Comment by nfekete** [comment]
But the benchmark should in fact compare vavr `Iterator` with JDK `Stream`, isn't it? Apples to apples. Maybe it would be worth to see the numbers comparing those two.

**Comment by alshain** [comment]
Also, IntStream is specialized for ints, vavr will be using Integer which probably also makes a huge difference.

**Comment by baha2046** [comment]
world be interest if also running same test case on other 3rd party like RxJava and cylops

**Comment by danieldietrich** [comment]
Cyclops is a wrapper - it is not _that_ interesting to me. Rx Java has a different purpose (cold/hot streams etc).
