### ISSUE TITLE
Add Stream.continue functions

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1045]
Continues a finite stream.

```java
Seq<T> continue(T next);
Seq<T> continue(Supplier<? extends T> nextSupplier);
Seq<T> continue(Function<? super T, ? extends T> previousToNext);
```

Example:

```java
// = 1, 2, 3, 4, 5, 6, 7, ...
Stream.of(1, 2, 3).continue(i -> i + 1);
```

**Comment by patrox** [comment]
hi @danieldietrich, interesting idea, altough to confirm if I understand it correctly:

* Seq<T> continue(T next); // continues a stream with a constant value
* Seq<T> continue(Supplier<? extends T> nextSupplier); // continues a stream with result(s) taken from consequent `Supplier` applications
* Seq<T> continue(Function<? super T, ? extends T> previousToNext); // continues a stream with a value calculated by the provided `Function` which calculates the `next` value basing on the last item in the `Stream/Seq`.

Examples:

```java
Seq.of(1,2,3).continue(4); // 1,2,3,4,4,... (infinite stream)

Seq.of(1,2,3).continue(() -> coolFx()); // 1,2,3,<result of coolFx>,<result of coolFx>,... (infinite stream)

Seq.of(1,2,3).continue(i -> i +1) // Example which you've provided above 
```

**Comment by patrox** [comment]
After making some experiments, first two are quite simple, as you can do sth like (examples using just `Stream` API):

```java

Stream.concat(streamToContinue, Stream.generate(nextSupplier);

```

The one with constant value, could be done similarly (by concatenating the first stream with a stream produced by a constant supplier).

The third one is the trickiest one, as you can use the same pattern, but swap `Stream.generate` for `Stream.iterate` which takes a seed value and a `UnaryOperator` (which is just a `Function` with the same result type as it's argument) which will be used to produce the consequent values.

The trick is here that on order to obtain the seed value for `iterate` you need to traverse the whole first stream, which might be infinite and even if not, this seems quite expensive.

**Comment by danieldietrich** [comment]
Hi @patrox, yes - the solutions fit great. In the third case I have an Iterator in mind wrapped by a stream. Let's take the name `extend` because `continue` is a keyword.
I'm on my phone and give a prototype of the Iterator later.

**Comment by danieldietrich** [comment]
This should work:

```java
default Stream<T> extend(Function<? super T, ? extends T> f) {
    Objects.requireNonNull(f, "f is null");
    if (isEmpty()) {
        return this;
    } else {
        final Stream<T> that = this;
        return Stream.ofAll(new AbstractIterator<T>() {

            Stream<T> stream = that;
            T last = null;

            @Override
            protected T getNext() {
                if (stream.isEmpty()) {
                    stream = Stream.gen(last, f);
                }
                last = stream.head();
                stream = stream.tail();
                return last;
            }

            @Override
            public boolean hasNext() {
                return true;
            }
        });
    }
}
```

**Comment by patrox** [comment]
I was on a phone too :) so the code was a bit simplified ... I can continue on that since I already have a rough draft in my head.

**Comment by danieldietrich** [comment]
Nice, thank you!

**Comment by danieldietrich** [comment]
Hey @patrox,
I'm thankful for your support and am looking forward to integrate this new feature into 2.0.0.
Just for the planning: things committed before 15.3. will go into Javaslang 2.0.0. Then we have to make a code-freeze for 2.0.0 in order to get homepage and docs right.

**Comment by patrox** [comment]
Hi @danieldietrich, it willl be finished before that I promise !

**Comment by danieldietrich** [comment]
Thx! 👍🏽

**Comment by patrox** [comment]
@danieldietrich Here you are: https://github.com/javaslang/javaslang/pull/1144
I've added a couple of tests to validate some regular cases and some corner cases as well.

**Comment by danieldietrich** [comment]
Awesome, thanks!
