### ISSUE TITLE
Update website with new multi-module references

### ISSUE THREAD

**Issue by talios** [javaslang/javaslang#1062]
Now that 2.0-RC3 is out with the new project structure (yay - no more test code in prod), we should also update the website to mention the various sub-packages.

I see it's been updated to mention 2.0-RC3, but not the new structure.

**Comment by danieldietrich** [comment]
> yay - no more test code in prod

:+1: :smile: 

Yes, I'm on it. Website and documentation will get some love within the next days

**Comment by danieldietrich** [comment]
Done. This will be continued in more detail... (download links, api references etc.)
