### ISSUE TITLE
Add Stream.ofAll(Iterator)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1066]

**Comment by ruslansennov** [comment]
what about other collections?

**Comment by danieldietrich** [comment]
good question, I think all need it

**Comment by ruslansennov** [comment]
<code>Stream.ofAll(javaslang.Iterator)</code> is ambiguous because it implements both <code>java.util.Iterator</code> and <code>java.lang.Iterable</code>

**Comment by danieldietrich** [comment]
ok, we could name it `ofIterator()` and give a Javadoc hint that it is a shortcut for `ofAll(() -> iterator)`.
or we don't provide a special method to keep it simple...
your opinion?

**Comment by ruslansennov** [comment]
My opinion it is unnecessary method :)

**Comment by netzwerg** [comment]
I agree, once you are aware that `Iterable` is a functional interface, the method is unnecessary. But how to make people aware? Docs? Or maybe a cookbook or FAQ?

Since Javaslang complements the JDK, going back and forth between the two must be as easy as possible.

**Comment by danieldietrich** [comment]
> going back and forth between the two must be as easy as possible.

Yes, you are right. The API should be self-explaining. The easiest solution would be providing a method. We should do that. `ofIterator(Iterator)` is fine.

**Comment by danieldietrich** [comment]
> My opinion it is unnecessary method :)

I'm undecided - need to sleep on it

**Comment by danieldietrich** [comment]
Slept more than one night on it and think we don't need it. I will document it how to use Stream.ofAll(Iterable) with an Iterator. Also we will add a best-practice section to our documentation.
