### ISSUE TITLE
Stackless recursion with trampolines in Java

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#107]
Java does not support tail call elimination e.g. like Scala does. Trampolines are an alternative to trade stack for head. http://blog.higher-order.com/assets/trampolines.pdf

**Comment by ouertani** [comment]
French article http://www.infoq.com/fr/articles/trampoline-java8

**Comment by danieldietrich** [comment]
http://blog.richdougherty.com/2009/04/tail-calls-tailrec-and-trampolines.html

**Comment by mperry** [comment]
https://github.com/functionaljava/functionaljava/blob/master/core/src/main/java/fj/control/Trampoline.java

**Comment by danieldietrich** [comment]
Also this http://www.javacodegeeks.com/2015/10/stack-safe-recursion-in-java.html

**Comment by danieldietrich** [comment]
But I must admit that this seems not practical to me. It is more like a proof that there is an abstraction that makes it possible from a technical viewpoint.

If the underlying language (here: Java) has no _native_ support for tail recursion, we should find another way to express our business problem, i.e. it is better to not use recursion at all.

In the end we have to decide, what's more important: memory/performance or readability/purity.

**Comment by danieldietrich** [comment]
I will close this as not desirable for Javaslang. I can't suggest it to developers because of memory consumption of additional intermediate objects.
