### ISSUE TITLE
Update javadoc to link to java 8 not java 6 API

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#1071]
Title says it.

**Comment by danieldietrich** [comment]
Thank you! PR welcome

**Comment by danieldietrich** [comment]
@mvh77 Do you have an example? I made a full text search on the javaslang source repo for "oracle.com" and found only Java 8 references. Have you found a Java 6 reference?

**Comment by mvh77** [comment]
I mean that the generated javadoc, when it comes to stadard library classes, refers to java 6. For example if you go to Option.filter and click on the Predicate link, it'll take you to the java 6 page for Predicate, which does not exist.

http://javaslang.com/javadoc/2.0.0-RC3/javaslang/control/Option.html#filter-java.util.function.Predicate-

Javadoc and the maven javadoc plugin have a 'links' part where you can specify where to find the external links. Here's an example, but you don't seem to have the javadoc generation in the pom.

https://github.com/javactic/javactic/blob/master/pom.xml

**Comment by danieldietrich** [comment]
Aahh :) Didn't know that. Many thanks - will be fixed ASAP!
