### ISSUE TITLE
Add iterate(T, Function<T, T>) and/or fold(T, Option<T>) / foldRight / foldLeft

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1073]
See http://daily-scala.blogspot.de/2009/09/unfoldleft-and-right.html
See https://gist.github.com/aloiscochard/1334040

**Comment by mattjtodd** [comment]
@danieldietrich I'd quite like to see if I can help out on this feature.

**Comment by danieldietrich** [comment]
That would be great!

I want to see these methods in the Traversable interface. Other collections may override them with appropriate return type.

But before implementation we need to get a clear picture which methods we need

Following steps:

- Let's prototype the method signatures and define their purpose (iterate, fold, unfold. also foldRight, foldLeft?). Ideally we take a look at existing signatures from Scala and Scalaz!
- How does fold(T, Option)  differ from undold?
- How does fold(T, Option) differ from iterate?

Could you start with these points?

**Comment by mattjtodd** [comment]
Yes, will do.

**Comment by danieldietrich** [comment]
Thanks

**Comment by mattjtodd** [comment]
I think this issue can be closed now as the unfold and variants have been added in https://github.com/javaslang/javaslang/pull/1370?

I do have a few comments about the widening which are causing issues with some samples I'm working on.  Where / how would you prefer I raise these?

**Comment by danieldietrich** [comment]
Hi @mattjtodd ,
thanks for your feedback! Please create a new Github issue for the cases that cause trouble.
I will close this ticket now.
