### ISSUE TITLE
Add search to Seq

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1074]
See [java.util.Collections#binarySearch(List, Object)](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#binarySearch-java.util.List-T-)

I could imagine methods:

```java
interface Seq<T> {

    static <T> int binarySearch(Seq<? extends Comparable<? super T>> seq, T key) {
        ...
    }

    static <T> int binarySearch(Comparator<? super T> comparator, Seq<T> seq, T key) {
        ...
    }

}
```

/cc @netzwerg I defer this to 2.0.1 to get 2.0.0 through the door

**Comment by netzwerg** [comment]
Actually, `binarySearch` only makes sense for `IndexedSeq`, right? For `LinearSeq` it can only be a `linearSearch`.

Scala's [`Searching`](http://www.scala-lang.org/api/2.11.7/scala/collection/Searching$.html) hides this distinction behind a `search` method.

**Comment by danieldietrich** [comment]
Yep, right, LinearSeq will have a linear search. I didn't know Scala's `Searching` but I like the idea to hide the strategy behind a `search` method.

The `search` method that takes a Comparator can be an instance method:

```java
interface Seq<T> {
    int search(Comparator<? super T> comparator, T key);
}
```

If we use the natural Comparator `Seq<? extends Comparable<? super T>>` we have two choices:

1. We provide static methods in Seq and/or in IndexedSeq/LinearSeq and/or maybe in List/Stream/...

    ```java
    interface Seq<T> {
        static int search(Seq<? extends Comparable<? super T>> seq, T key);
    }
    interface IndexedSeq<T> {
        // or just 'search'
        static int binarySearch(IndexedSeq<? extends Comparable<? super T>> seq, T key);
    }
    interface LinearSeq<T> {
        // or just 'search'
        static int linearSearch(LinearSeq<? extends Comparable<? super T>> seq, T key);
    }
    interface List<T> {
        // or just 'search'
        static int linearSearch(List<? extends Comparable<? super T>> list, T key);
    }
    ...
    ```

2. We provide an instance method Seq.search(T key) and compute the natural comparator, which may throw a ClassCastException. Java's SortedSet and SortedMap work in this unsafe way. We already assume that the elements are sorted in ascending order, so assuming that they are comparable might be ok.
    ```java
    interface Seq<T> {
        // @throws ClassCastException if T is not Comparable
        int search(T key);
    }
    ```

What do you think? I like the second approach. It is easy to use, easy to implement - but unsafe. User has to take care that elements are sorted in ascending order, though.

**Comment by netzwerg** [comment]
I also like the second approach.

For the comparator variant, I would switch parameter order (to keep the signatures as close to `Collections.binarySearch` as possible).

To summarize:
```java
interface Seq<T> {
    int search(T key);
    int search(T key, Comparator<? super T> comparator);
}
```
With default implementations in `IndexedSeq` (binary search) and a `LinearSeq` (linear search).

Regarding return type: Would you stick to the JDK `int` approach or return a fancier type à la Scala (`SearchResult` with `Found(int)` | `InsertionPoint(int`)?

PS: You might want to rename the issue title to "Add search to Seq"

**Comment by danieldietrich** [comment]
We could return an int and save time & mem by not creating additional SearchResult instances:

* a positive int indicates the found position
* a negative int indicates the negated insertion position

Example:

```java
List<Integer> list = List.of(1, 3, 5, 7);
int elem = 4;
int index = list.search(elem);
if (index >= 0) {
    // elem found at index
} else {
    list = list.insert(-index, elem);
}
```

If we had a SearchResult, it would be

```java
List<Integer> list = List.of(1, 3, 5, 7);
int elem = 4;
SearchResult searchResult = list.search(elem);
if (searchResult.isFound()) {
    // elem found at searchResult.foundIndex()
} else {
    list = list.insert(searchResult.insertionPoint(), elem);
}
```

with

```java
public interface SearchResult {

    boolean isFound();

    // -1 if !isFound
    int foundIndex();

    // = foundIndex if isFound
    int insertionPoint;
}

public final class Found implements SearchResult { ... }

public final class InsertionPoint implements SearchResult { ... }

```

**Comment by netzwerg** [comment]
I would keep it as simple as possible, i.e. use an `int` with the same semantics as `Collections.binarySearch` (just like you described).

The `SearchResult` has a certain appeal, but only if the extra complexity brings something to the table in terms of usage. Off the top of my head:

```java
List<Integer> list = List.of(1, 3, 5, 7);
int elem = 4;
list.search(elem).
        whenFound(foundIndex -> System.out.println("Found " + foundIndex)).
        whenAbsent(insertionPoint -> list.insert(insertionPoint, elem));
```
With implementations in the `SearchResult` interface:
```java
default SearchResult whenFound(IntConsumer foundHandler) {
    if (isFound()) {
        foundHandler.accept(foundIndex());
    }
    return this;
}

default SearchResult whenAbsent(IntConsumer insertionHandler) {
    if (!isFound()) {
        insertionHandler.accept(insertionPoint());
    }
    return this;
}
```

But I would need to give this some more thought... Could `Match` be of any help here?

**Comment by danieldietrich** [comment]
There is a problem with effectively final vars:

```java
```

**Comment by danieldietrich** [comment]
Let's return an int :) That's not too bad!

**Comment by netzwerg** [comment]
Yep, good point!

> Let's return an int :) That's not too bad!

+1

**Comment by netzwerg** [comment]
I gave the binary search on `IndexedSeq` [a first shot](https://github.com/netzwerg/javaslang/commit/78441c626759cf9d67a68a98018c8f13d24ce666). If you would be interested in a PR, I could round it off with proper javadoc?

The actual implementation is taken straight from `Collections.binarySearch`. I additionally got rid of any code duplication (natural vs comparator variant) by abstracting over the `midToCmp` conversion.

IMHO, offering binary search on `IndexedSeq` is more urgent than linear search on `LinearSeq` (where a simple `find` can serve as a work around). Moreover, the linear search implementation cannot be copied straight from `Collections.binarySearch` (uses a `ListIterator` with `previous`). Thus a re-implementation probably needs some more thoughts and tests...

**Comment by danieldietrich** [comment]
Great :) Looking forward to review your PR!

**Comment by danieldietrich** [comment]
Done with #1088
