### ISSUE TITLE
Refine conversion methods

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1078]
* ~~toJavaMap should preserve insertion order (LinkedHashMap) and sort order (SortedMap)~~
* ~~toJavaSet should preserve insertion order (LinkedHashSet) and sort order (SortedSet)~~
* we need to add abstract `Map.toJavaMap()`, `SortedMap.toJavaMap()`, `LinkedHashMap.toJavaMap`, ...
* we need to override `SortedSet.toJavaSet()`, `LinkedHashSet.toJavaSet()`, ...
* additionally we need factory methods `<U extends Xxx<T>> U toXxx(Supplier<U> factory)` for java.util.Collection/List/Map/Set

**Comment by bartolom** [comment]
Dear Javaslang Team,

I just stumbe upon this ticket, as I'm looking forward to the 2.0 releases. So maybe you have had already discussions about this, so I just wanted to comment my impression about the semantics:

I find methods like toJavaXxx() a bit odd, as JavaSlang is also a Java library as far as I understand it.
Aren't you mapping between your collections implementation and the OpenJDK "Java Collections Framework"
https://docs.oracle.com/javase/8/docs/technotes/guides/collections/overview.html
As "JCF" is not really a established acronym what do you think about "JDK", which is a well established term in the Java/JVM community?

So you would have Map.toJdkMap(), though even I have to admit that Map.toJavaMap() looks a bit cleaner. Maybe just mentioning it in the javadocs is fine.

**Comment by danieldietrich** [comment]
Hi @bartolom ,

you are right, this is a bit confusing. On the one hand 'Java' is a language, on the other hand it is widely used as synonym for the runtime libraries shipped with the JDK - all libs and utils contained in Java _is_ Java.

The 'Java Collection Framework' (JCF) is also referred to as 'Java Collections'. So by 'toJavaList' we mean 'toJavaCollectionFrameworkList'. Because 'List' is a collection and (in general) 'toJavaCollectionFrameworkCollection' is redundant, it is just 'toJavaCollection'.

I also thought about 'toJdkList'. But the JDK is used by developers. Users use the JRE in general, which also includes the Java Collections. So both 'toJdkList' and 'toJreList' are not right. 'toJcfList' would be right but most people will not understand it.

I think you are right, the whole conversion topic (Javaslang back and forth to Java) needs to be covered, at least in the documentation. We should also add javadoc in the `Value` class, which contains most of the conversion methods.

**Comment by bartolom** [comment]
Naming can be tricky.
The naming of .toJavaXxx() is fine the way you explain it. I think javadocs with modern IDE support are a good solution.

Just as a note about .toJdkXxx() vs. toJreXxx():

Collection frameworks like JCF and your Javaslang are usually aimed at developers, as mainly they can "create" something meaningful with it. I as a developer use the "Development Kit" and tend to think in JDK like: "Why not use X (E.g. CompletableFuture) its now part of the JDK". I know that a Tomcat server might run in a JRE in production but that's the operation side.

For me saying "something is in the JDK" means I don't need to fiddle around in Maven/Gradle to get it.

**Comment by danieldietrich** [comment]
@bartolom yes, I understand

**Comment by danieldietrich** [comment]
Need to add unit tests for these:

* Value#toJavaCollection(Supplier)
* Value#toJavaList(Supplier)
* Value#toJavaMap(Supplier, Function)
* Value#toJavaSet(Supplier)
* Map/HashMap/LinkedHashMap/TreeMap#toJavaMap()
* Set/HashSet/LinkedHashSet/TreeSet#toJavaSet()

**Comment by danieldietrich** [comment]
Done with #1079. Pending tests moved to #477
