### ISSUE TITLE
Rename javaslang-algebra to javaslang-pure

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1082]
We will rename `javaslang-algebra` to `javaslang-pure`, that targets purely functional programming. The Reader / Writer / State monads fit perfectly in there! Additional state-capturing types will follow (mid-term), e.g. Lenses, Transducers, etc.

**Note:** The monads mentioned above target side-effect free programming by encapsulating and deferring side-effects. This is a step towards _purely functional_ programming. We bundle this functionality within the javaslang-pure project for **advanced functional programming**.

javaslang vs javaslang-pure
is like
scala vs scalaz

**Comment by danieldietrich** [comment]
Done with #1085

**Comment by jabrena** [comment]
Hi @danieldietrich, 

Where is possible to find `javaslang-pure`?

Juan Antonio

**Comment by danieldietrich** [comment]
Hi @jabtena, a removed the ...-pure module a long time ago. Java is not the right language for abstracting over monads because of missing type constructors (higher-kinded types).
There exist really ugly workarounds for HKTs in Java (using self-recursive generic interfaces). Don‘t use them - they cause problems!

**Comment by jabrena** [comment]
Hi @danieldietrich, don´t worry with this library I have enough for a good period... :)

Cheers

**Comment by danieldietrich** [comment]
Thx, great to hear :)
