### ISSUE TITLE
Future.parallel()

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1093]
Toward #186 we can create this static factory
```java
static <T> Future<Seq<T>> parallel(Iterable<? extends Future<? extends T>> futures) {
    Objects.requireNonNull(futures, "futures is null");
    return new FutureSet<>(DEFAULT_EXECUTOR_SERVICE, futures).result();
}
```
with implemented in <code>FutureModule</code>
```java
class FutureSet<T> {

    private Set<Future<? extends T>> uncompleted;
    private Seq<T> seq = Stream.empty();
    private final Promise<Seq<T>> result;
    private final Object lock = new Object();

    FutureSet(ExecutorService executorService, Iterable<? extends Future<? extends T>> futures) {
        uncompleted = HashSet.ofAll(futures);
        result = Promise.make(executorService);
        futures.forEach(f -> f.onSuccess(t -> {
            synchronized (lock) {
                uncompleted = uncompleted.remove(f);
                seq = seq.append(t);
                if (uncompleted.isEmpty()) {
                    result.success(seq);
                }
            }
        }).onFailure(result::failure));
    }

    Future<Seq<T>> result() {
        return result.future();
    }
}
```

**Comment by ruslansennov** [comment]
No, this makes no sense. We should to implement reactive lazy Stream...

**Comment by danieldietrich** [comment]
I think this is roughly the same as https://github.com/javaslang/javaslang/blob/b18fd49b2e5e09db4abecf4d43f62d2b0623e070/javaslang/src/main/java/javaslang/concurrent/Future.java#L422, isn't it?

**Comment by ruslansennov** [comment]
No, <code>parallel()</code> produces sequence in the order in which they were completed.

**Comment by danieldietrich** [comment]
Ok. Since the order is not predictable I see no benefit.

sequence() is a synchronization point - the result is there, if all futures completed.

paralles() would make only sense, if single results are accessible before all futures complete. But we do not need a wrapper for that. We can register callbacks at any single future to handle single results. To observer, if all are  completed, we could additionally fold over the futures, e.g. with a boolean value.

**Comment by ruslansennov** [comment]
> parallel() would make only sense, if single results are accessible before all futures complete

yes
