### ISSUE TITLE
Add Tree.Node.format()

### ISSUE THREAD

**Issue by lukaseder** [javaslang/javaslang#1098]
The `Tree.Node.toString()` implementation is already nice. But what about a `Tree.Node.format()` method? E.g.

```java
System.out.println(
    Tree.of("a", Tree.of("b", Tree.of("c"), Tree.of("d")), Tree.of("e", Tree.of("f"))).format()
);
```

The above would yield:

```
    a
   / \
  b   e
 / \   \
c   d   f  
```

I'm sure someone has already figured out an algorithm for this :)

**Comment by lukaseder** [comment]
This feature request is a classic case of:

![image](https://cloud.githubusercontent.com/assets/734593/13014794/f052b5c0-d1b5-11e5-8487-8152b8289e9a.png)

**Comment by danieldietrich** [comment]
Haha, thank you Lukas :-)

Already done. It is not part of javaslang core but you may use javaslang-render.

It supports ascii rendering:

```java
                             ┌───┐
                             │Ann│
                             └─┬─┘
              ┌────────────────┴──────┬────────────────┐
           ┌──┴─┐                  ┌──┴──┐       ┌─────┴─────┐
           │Mary│                  │Peter│       │Christopher│
           └──┬─┘                  └──┬──┘       └─────┬─────┘
    ┌───────┬─┴───────┐          ┌────┴────┐           │
 ┌──┴─┐  ┌──┴──┐ ┌────┴───┐  ┌───┴───┐ ┌───┴───┐   ┌───┴──┐
 │John│  │Karen│ │ Steven │  │ Paul  │ │Anthony│   │Samuel│
 └──┬─┘  └──┬──┘ │ Abbot  │  │Palucci│ └───────┘   └──────┘
    │       │    │Braddock│  └───────┘
 ┌──┴──┐ ┌──┴──┐ └────────┘
 │Avila│ │Frank│
 └─────┘ └─────┘
```

and graphviz:

![e752763c-ca02-11e5-8ddb-722f08c7987d](https://cloud.githubusercontent.com/assets/743833/13014916/76e0e49a-d1b6-11e5-8055-11c371287d37.png)

More rendering solution contributions are always welcome!

**Comment by lukaseder** [comment]
o_O

I bow before you. Just as you posted this, I've also discovered `Tree.draw()`.

**Comment by danieldietrich** [comment]
Note: Please note that Tree will change slightly to enable advanced tree processing (it will traverse nodes instead of elements). I also work on a new effective way to represent immutable trees with parent references (using two layers, each for one direction). See https://github.com/javaslang/javaslang/issues/1023 for more information.
