### ISSUE TITLE
Consider removing Function type reflection by Serialization

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1112]
Now that Match does not rely any more on Function reflection (for applicability checks), we should remove the feature from Javaslang. Also Functions do not need to be Serializable any more.

Reasons:

* it is a hack
* no public Java API
* has low performance
* is broken (i.e. does not work for all types of lambdas, e.g. method references)

**Comment by ruslansennov** [comment]
So sad, it was [part](https://github.com/javaslang/javaslang-jackson/blob/master/src/main/java/javaslang/jackson/datatype/serialize/SerializableSerializer.java) of jackson encode/decode...

**Comment by danieldietrich** [comment]
Don't see it - Values stay Serializable! Do you really use Function serialization, i.e. Function.getType()?

**Comment by danieldietrich** [comment]
Mhh, maybe for Lazy? Then Functions will stay Serializable. However, the getType() is not needed I think.

**Comment by ruslansennov** [comment]
I had to give [this](https://github.com/javaslang/javaslang-jackson/blob/master/src/test/java/javaslang/jackson/datatype/FunctionTest.java) link

**Comment by danieldietrich** [comment]
Ok, extending Serializable should be sufficient, right?
Thx for the hint!

**Comment by ruslansennov** [comment]
> Ok, extending Serializable should be sufficient, right?

Yes, should be
Thank you

**Comment by danieldietrich** [comment]
Reflection of Serializable Lambdas is considered harmful. I removed it.

See https://gist.github.com/danieldietrich/a4977c525734269348b0

![lambda_reflection](https://cloud.githubusercontent.com/assets/743833/13061278/4c1a2234-d437-11e5-89f8-84e2feecd79a.png)
