### ISSUE TITLE
Implement nonEmpty on Traversable and Option

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#1113]
Like in Scala.

**Comment by danieldietrich** [comment]
Is it realy (I mean \*really\* really) needed? Why isn't isDefined not sufficient?

However, if we add it, we could add it to Value:

```java
interface Value {

    ...

    default boolean nonEmpty() {
        // or maybe return !isEmpty();
        return isDefined();
    }
}
```

**Comment by mvh77** [comment]
Oh, I hadn't seen that isDefined was already on Value. Makes sense though. But is the meaning of that obvious? What is it on an Either or a Try? Is a List not defined when it's empty? Anyway, I guess we can live without.

**Comment by danieldietrich** [comment]
Yes, you are right, the name `isDefined` is confusing.

Javaslang differs from Scala in the way that we centralized specific features in a common base-class, namely `Value`.

Value is base-class of both single-valued and multi-valued types. For single-valued types `isDefined` is more intuitive, for multi-valued types `nonEmpty` is more intuitive.

**We should add `nonEmpty` to Value to be more complete.** isDefined and nonEmpty are equivalent.

```java
interface Value {

    // defined / undefined check
    isDefined()
    isEmpty()
    nonEmpty()

    // getters
    get()
    getOrElse(...)
    getXxx(...)

    // ...
    map(...)
    ...

    // pattern matching
    match(...)

    // conversion
    toXxx()
}
```

**Comment by mvh77** [comment]
Well, if you want my honest opinion, I don't see the benefit in having the Value type, because I'm never going to reason around that in an app. This is a bit like Functors and Monads, my business logic is never going to abstract around those lines, in any app. Maybe you could remove both nonEmpty & isDefined from Value (leaving only isEmpty) and add nonEmpty to Traversable and isDefined to Option and see if Either/Try etc need any of those. Just an idea.

**Comment by danieldietrich** [comment]
Maybe you are right. I could make Value package private and remove it from the public API. Less is more. It is good to have an internal base-interface.

isDefined will move to option, nonEmpty to traversable. Check!

**Comment by danieldietrich** [comment]
I've thought about it and will not remove Value from public API. Even if it not frequently used in real world programs, it is a fundamental part of the the type system, like Object in Java. Value represents the functional counterpart to Object.

However, I agree to move isDefined and nonEmpty as discussed. I will apply that change.

**Comment by danieldietrich** [comment]
Thank you for your mindful suggestions!

**Comment by mvh77** [comment]
As a side question, what is the point in Option#nothing(): Option<Void>? Because Void is a real bastard, it's neither the terminal object (scala's Unit) nor the bottom type (scala's Nothing). Option<Tuple0> could maybe make some sense in some situations where you want a Some without a value, but I'd avoid Void all the time.

**Comment by danieldietrich** [comment]
It is intended to be syntactic sugar for one of the rare use-cases where we have `Some(null)`, because `null` is the only instance of `Void` in Java.

The name `Option.void()` is not possible/a keyword, so I chose `Option.nothing()` because void is nothing.

I'm currently using it in pattern matching where I return

* `Option<Void>` instead of `Option<Tuple0>`
* `Option<T1>` instead of `Option<Tuple1<T1>>`
* `Option<Tuple2<T1, T2>>`
* `Option<Tuple3<T1, T2, T3>>`
* ...
