### ISSUE TITLE
Is Traversable#clear() really necessary

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#1134]
Hi,

clear sounds very dirty and mutable to me, is it really necessary? Is it for cases where you want a new empty instance of a Traversable but you don't know what concrete class you have? Would something like newEmpty() or something be better if it's really needed?

**Comment by danieldietrich** [comment]
Good point. Java folks is used to it in the mutable case. It might be useful to ge a new instance of same type. Could be just the name `empty()` but need to check that thare are no name-clashes...
Thanks!

**Comment by mvh77** [comment]
Well it will clash with the static empty() constructor, so that's not good, but if it's not used right now internally, I'd leave it out for now, it can always be added later. Like Josh Bloch said on API design, "when in doubt, leave it out!". :smile:

**Comment by danieldietrich** [comment]
I will remove clear() today for now. It can be added later if really necessary as you said.

**Comment by danieldietrich** [comment]
I've removed it and realized that we (internally) need an empty() method for abstract implementations of collections. I will take this opportunity and merge the two concepts of clear() and getEmpty() to a public empty() method.

**Comment by danieldietrich** [comment]
While doing that change it seems that is also not the right way (beside the name clash with the existing static methods). I will make that method internal and name it emptyInstance().
