### ISSUE TITLE
Remove javaslang.control.Option in favor of Optional?

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1140]
This is also a question.

We have to see this realistic, will Option be used at all? Everyone will use Optional outside of Javaslang.

Wouldn't it increase the interoperability when we also use Optional?

What would be the impact for this library?

**Comment by avitry** [comment]
I agree.  Interoperability is king. 
Translating back en forth  between related types with close or identical (List e.g) and refrain usage.

**Comment by ggalmazor** [comment]
I prefer Option's API because is more complete and coherent with Javaslang's other artifacts (in my apps I only use Option).

**Comment by ggalmazor** [comment]
Also, Optional is not serializable which makes it impossible to use with Apache Spark, for example.

**Comment by danieldietrich** [comment]
Yes, currently there are reasons to have an alternative Optional implementation. One of the most important is the ability to serialize it.

A mix of both Optional and Option in Javaslang is no viable alternative.

The creators of Optional suggest to use Optional only as intermediate computation result and not to persist the Optional state in form of an instance variable.

**Comment by ggalmazor** [comment]
Well, I can only guess that they're ok with nulls inside collections in a distributed computation... That's a luxury I can't afford :P

**Comment by danieldietrich** [comment]
Haha, yes :)

Option will stay but it is a pity that Java's impl isn't sufficient.

**Comment by talios** [comment]
@ggalmazor I believe `Optional` is not serializable as Oracle eventually want to take that to a value type, which won't be serializable as it'd just be `null`. One thing I like about Javaslangs Option is it's more richer API, Oracles is quite anemic ( like much of their "functional" interfaces ).

**Comment by mvh77** [comment]
Yes, Optional is garbage, Option is great, no touch! :smiley:

**Comment by danieldietrich** [comment]
Ok :-)

**Comment by ggalmazor** [comment]
@talios thanks for the explanation :)
