### ISSUE TITLE
Rename Iterator#gen to match Scalas

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#1143]
Scala's Iterator has:
```scala
def continually[A](elem: ⇒ A): Iterator[A]
def iterate[T](start: T)(f: (T) ⇒ T): Iterator[T]
```
and we have:
```java
static <T> Iterator<T>	gen(Supplier<? extends T> supplier)
static <T> Iterator<T>	gen(T seed, Function<? super T,? extends T> f)
```
I suggest renaming the latter to match the former (but we can still use just one generic alias and not two (A and T) :smile: )

Scala also has a from(Int, Int) that "creates an infinite-length iterator returning values equally spaced apart". This is different from the range methods that are not infinite.

We also have a repeat(T t) that's basically the first gen but with a constant value, I'd rename this to 'continually' as well.

**Comment by danieldietrich** [comment]
Yes, thank you. The same applies to Stream.

Scala's Iterator: https://github.com/scala/scala/blob/v2.12.0-M2/src/library/scala/collection/Iterator.scala#L65-L163

Scala's Stream: https://github.com/scala/scala/blob/v2.12.0-M2/src/library/scala/collection/immutable/Stream.scala#L1196-L1250

PR's very welcome :-)

**Comment by mvh77** [comment]
I'll try to do this tonight.

**Comment by danieldietrich** [comment]
Great, thanks for the helping hand!
