### ISSUE TITLE
Stream.cycle(int)

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1153]
```java
@Test
public void test() {
    // = List(1, 2, 3)
    System.out.println(of(1, 2, 3).cycle(0).toList());
    // = List(1, 2, 3)
    System.out.println(of(1, 2, 3).cycle(1).toList());
    // = List(1, 2, 3, 1, 2, 3)
    System.out.println(of(1, 2, 3).cycle(2).toList());
    // = List(1, 2, 3, 1, 2, 3, 1, 2, 3)
    System.out.println(of(1, 2, 3).cycle(3).toList());
}
```
Very strange behavior!
Also we should use <code>AbstractIterator</code> if it possible :smile:

**Comment by danieldietrich** [comment]
Oh - this is an off-by-one bug.

Stream is a special case. Here we don't use AbstractIterator, because the Iterator is used internally. In the next method no extra checks are needed, because it is guaranteed that hasNext() is called before each next(). It is ok.
