### ISSUE TITLE
Weird Either.get() behavior

### ISSUE THREAD

**Issue by vicmosin** [javaslang/javaslang#1166]
Just upgraded from 1 to 2 (RC 4) and found very weird thing: `either.get()` is actually `getRight()`!?
As a result, the most useful feature of either, give me either left or right is gone and need to build such an ugly construction:
```
resource.isLeft() ? resource.getLeft() : resource.get()
```
Could somebody explain what was the motivation of this?

**Comment by danieldietrich** [comment]
The background is that Either is now right-biased by default. That is a common use-case that can be also found on Scala mailing lists. Scalaz has an extra type for that but introducing a new type for the same functionality is weird.

Plus: now Either is a real monad.

Your can still use the left/right projections, they didn't changed.

**Comment by vicmosin** [comment]
@danieldietrich Would it be good to add some `getLeftOrRight` like `get` was?

**Comment by danieldietrich** [comment]
Please read this: http://robsscala.blogspot.de/2012/06/fixing-scalaeither-unbiased-vs-biased.html

This is the Xor (like in Scalaz) that has been suggested: https://github.com/javaslang/javaslang/issues/762

And this is what we finally made out of it: https://github.com/javaslang/javaslang/issues/882

**Comment by danieldietrich** [comment]
@vicmosin 

> Would it be good to add some getLeftOrRight like get was? 

But we get an Object. What is the use-case? We had that method because of a common interface for Left and Right. But does it make sense to get() an Object and we don't know what it actually is?

We should make the semantics explicit in our code by

```java
Either<L, R> either = ...;
if (either.isLeft() {
    // call either.getLeft()
} else {
    // call either.get()
}
```

That is a much cleaner way than:

```java
Either<String, String> either = ...;
Object obj = either.getLeftOrRight();
// how can I now decide what was the result!?
```

**Comment by vicmosin** [comment]
My point is - why should we care what exactly in Either? It's either left or right ))) One of them, so the further logics based on that fact.

**Comment by vicmosin** [comment]
I agree that since `Either` is right-biased now, it's useless to get either left or right, and it should be implemented explicitly as you suggested.

**Comment by danieldietrich** [comment]
Thank you! I will outline that new behavior / give it a special emphasis in the documentation to make it clear.

Thanks for reporting. If you find other odd things please let me know. I try to give the best Java 8 experience possible :-)

**Comment by danieldietrich** [comment]
whoops, I wanted to close it, too
