### ISSUE TITLE
Add message parameter to Try.filter

### ISSUE THREAD

**Issue by fredshonorio** [javaslang/javaslang#1176]
Very often I do an operation like `response = Try.of(httpGet(url));` and then want to validate the result, for instance `response.filter(r -> r.code == 200);`.
I use flatMap so that I could pass a predicate and choose an appropriate exception message, like so: `response.flatMap(Check.that(r -> r.code == 200, "Exception message!"))` but I end up having to copy and paste that `Check` class around various projects.

I think it fits more neatly with filter, so the result of `response.filter(r -> r.code == 200, "Exception message!");` would be
`Failure(java.util.NoSuchElementException: Exception message!)`
or 
`Failure(java.util.NoSuchElementException: Exception message! for X)` where X is the value.

What do you think?

**Comment by danieldietrich** [comment]
Hi,

yes - I see. The use case is too specific to include it into the base lib, for numerous reasons. One reason is, that the exception is fixated to NoSuchElementException.

I have similar tasks in my programming and would suggest to do it the following way:

```java
Try.of(httpGet(url))
   .flatMap(r -> (r.code == 200) ? r : Try.failure(new NoSuchElementException("error message!")));
```

To reduce code duplication, it might make sense to create a Responses utility class:

```java
Try.of(httpGet(url)).flatMap(r -> Responses.checkCode200(r, "error message!"));

class Responses {
    static Try<Response> check(Try<Response> it, String message) {
        return (it.isFailure() || it.get().code == 200) ? it : Try.failure(new NoSuchElementException(message));
    }
}
```

or even better

```java
Try.of(httpGet(url)).flatMap(Responses.check(r -> r.code == 200, "error message!"));

class Responses {
    static Function<? super Try<Response>, ? extends Try<Response>> check(Predicate<? super Response> pred, String message) {
        return it -> (it.isFailure() || pred.test(it.get())) ? it : Try.failure(new NoSuchElementException(message));
    }
}
```

If the Responses class has to be used in different modules / projects I would create a separate artifact/jar, which contains this (+additional) stuff.

Hope that helps!

I will close that ticket. Don't hesitate to ask if any questions.

Greets,

Daniel

**Comment by fredshonorio** [comment]
It would be just a "nice-to-have", I would not care about the class of the exception, in my case I just want a clearer message to log.
If you think this is out of scope, that's fine.
Anyway, thanks.
