### ISSUE TITLE
Error on main page carousel

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#1201]
The new web page has this nice carousel thingy with examples, of which one is:
```java
Try<R> result = Try.of(() -> mightFail())
   .recover(x -> ...)
   .getOrElse(defaultValue);
```
Shouldn't result be of type R, not Try&lt;R&gt; :wink:

**Comment by danieldietrich** [comment]
whoops :) Initially it was `val result`

Thank you, will fix it
