### ISSUE TITLE
OSGi-conformity: Document how to check API changes

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1225]
We split package versions and product versions (Javaslang 1, 2, 3, ...). There exist different (but similar) versioning schemes (see #1164).

API changes can be checked via

`mvn package org.apache.felix:maven-bundle-plugin:baseline -DcomparisonVersion=2.0.1 -DskipTests`

@jest offered to send a PR that add packageinfo files. We have package-info.java files. Maybe we can use @Version or @Export annotations for OSGi.

A future version of Javaslang will be compatible to Java 9 Modules. We will take a look how these and OSGi modules best work together.

**Comment by jest** [comment]
If you don't mind adding a single 15k JAR to the compilation dependencies (http://mvnrepository.com/artifact/org.osgi/osgi.annotation/6.0.1), that would be more than enough. It also allows us to mark some interfaces as `@ConsumerType`, which allows for more precise versioning consumer-vs-provider API.

**Comment by danieldietrich** [comment]
Hi Przemek, Javaslang must stay dependency free. That's one of the few restrictions I can't give up as an API designer. I know, it sucks.

**Comment by jest** [comment]
Sorry, I wasn't clear. It's only a compilation dependency. The annotations — also the ones mentioned by you, e.g. `@Version` — are used by the OSGi tools (e.g. Bnd via maven-bundle-plugin) to generate the MANIFEST and discarded by VM on class load.

**Comment by danieldietrich** [comment]
Hi @jest, ok, sorry that I misunderstood. Then please do it.
Generally I'm also conservative with adding compile time deps but I think that in this case it will help us (and the users) to make interface changes more transparent and therefore it adds value regarding production stability.
Thanks!

**Comment by danieldietrich** [comment]
Hi @jest,

I've read a little bit about module systems and have some thoughts:

* I plan to create Java modules as soon as project Jigsaw is released with Java 9.
* My vision is that Javaslang primary relys on pure Java, if possible.
* Having two module systems in Javaslang (midterm) will be error-prone due to duplicate configuration. I hope that Jigsaw will provide a solution to derive OSGi meta data.
* If we integrate OSGi now into Javaslang via additional dependencies and users will rely on it, it will be hard to remove it again later (when moving to Jigsaw modules).

I have the impression that the package versioning is only a form of documentation that attempts to provide API safety. It is some kind of duplication that is error prone. E.g. what if I forget to update the version annotation? In the end there is just code, which might change over time.

Having only a package version change does not provide users a migration path. Release notes with migration descriptions/hints are mandantory.

Taking this into account I think it is the best solution for Javaslang to

* don't include the OSGi package annotations
* use the baseline goal to document changes and compatibility issues in the release notes

Do I miss something? What do you think about it?

**Comment by jest** [comment]
I'm a little confused here... Simply speaking: how adding some OSGi-specific numbers to the manifest (package versions) can complicate anything, esp. to non-OSGi users?

I understand your concern about dependencies — if you don't want to use OSGi annotations, that's no problem. One `packageinfo` file per package is enough.

If you can use OSGi only for baselining tools, then so be it. It will just make OSGi people with no additional versioning info they need to reach the nirvana. :)

If you would like some more details about versioning in OSGi, please see (somewhat details) description [here](http://bnd.bndtools.org/chapters/170-versioning.html).

**Comment by danieldietrich** [comment]
I was concerned about having multiple versioning standards (OSGi + Jigsaw). But as long as Jigsaw is not here, it does not matter. I will take a look at it again, when Jigsaw is ready. I'm sure it will be compatible with OSGi in the sense of static package version numbers and exported APIs.

I think also we need to be able to compare baselines. Please go on as already planned.

**Comment by talios** [comment]
On 29 Mar 2016, at 22:37, Daniel Dietrich wrote:

>   * If we integrate OSGi now into Javaslang via additional dependencies and users will rely on it, it will be hard to remove it again later (when moving to Jigsaw modules).

As far as OSGi is concerned, you'd basically be adding to `META-INF/MANIFEST.MF`:

```
Bundle-Name: javaslang
Bundle-Version: 2.0.1
Export-Packages: javaslang.collection.*......
```

with no further dependencies.





-- 
Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by danieldietrich** [comment]
Yes. Currently we use the apache maven bundle plugin. It automatically generates:

```java
Manifest-Version: 1.0
Bnd-LastModified: 1459290180932
Build-Jdk: 1.8.0_74
Built-By: daniel
Bundle-Description: Javaslang is a Java standard library extension built
  for Java 8 and above.
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion: 2
Bundle-Name: Javaslang
Bundle-SymbolicName: io.javaslang
Bundle-Version: 2.1.0.SNAPSHOT
Created-By: Apache Maven Bundle Plugin
Export-Package: javaslang;uses:="javaslang.collection,javaslang.control"
 ;version="2.1.0",javaslang.collection;uses:="javaslang,javaslang.contro
 l";version="2.1.0",javaslang.concurrent;uses:="javaslang,javaslang.coll
 ection,javaslang.control";version="2.1.0",javaslang.control;uses:="java
 slang,javaslang.collection";version="2.1.0"
Import-Package: javaslang,javaslang.collection,javaslang.concurrent,java
 slang.control
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-3.0.0.201509101326
```

Personally I like it to keep the release version and the package versions in sync. If package versions differ I would be totally lost...

**Comment by danieldietrich** [comment]
@talios But it is clear that there will be chaos without a proper module concept. Adding package versions is ok. With Java 9 I will revisit the versioning topic.

**Example:** Changes on my current branch:

```java
[ERROR] javaslang: Version increase required; detected 2.1.0, suggested 3.0.0
[ERROR] javaslang.collection: Version increase required; detected 2.1.0, suggested 3.0.0
[WARNING] javaslang.concurrent: Excessive version increase; detected 2.1.0, suggested 2.0.0
[WARNING] javaslang.concurrent: Version has been increased but analysis detected no changes; detected 2.1.0, suggested 2.0.0
[WARNING] javaslang.control: Excessive version increase; detected 2.1.0, suggested 2.0.0
[WARNING] javaslang.control: Version has been increased but analysis detected no changes; detected 2.1.0, suggested 2.0.0
[INFO] Baseline analysis complete, 2 error(s), 4 warning(s)
```

**Comment by jest** [comment]
@danieldietrich Remember, that your feeling is only that; there are no technical reasons you should be concerned with package versions if you're not using OSGi. And OSGi users are used to different versions of different packages.

BTW, the log that you sent suggests you introduced some backward compatibility in `javaslang` and `javaslang.collection`. Is it your private branch, or I can check out the details?

**Comment by danieldietrich** [comment]
@jest Yes, my feeling says also that you are right :-) Package versions are only numbers. But they add valuable information regarding compatibility.

I have create a [PR](https://github.com/javaslang/javaslang/pull/1242) of my local branch for review. It is still work in progress.

Summed up changes:

* equals and hashCode calculation of collections are re-implemented. Internal hashCode caching is removed to reduce the memory footprint. The API does not change.
* There is one exception/API change: I want to remove the static method Traversable.hash(Iterable). It is used internally by the collection API and will be moved to the package private/internal class Collections. Maybe I will deprecate it instead of removing it immediately. But 2.0.0 is still young and I don't think people used it yet. It is very special. Better make a clear cut here and remove it.

The other baseline-changes are due to additions of the new Multimap collections, see #1240.

**Comment by danieldietrich** [comment]
For now we use `maven-bundle-plugin:baseline` and document changes on each release. See CONTRIBUTION.md.
