### ISSUE TITLE
Add FindBugs to the build infrastructure

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1229]
Thanks @mvh77 for the suggestion!

**Comment by pivovarit** [comment]
You could consider using https://github.com/TouK/sputnik (webside is down now, but should be up any minute)
It aggregates all most popular SCA tools and works nice with github.

This is how it work in practice:
https://github.com/TouK/ThrowingFunction/pull/11

**Comment by danieldietrich** [comment]
Hi Grzegorz, Sputnik looks great! I will give it a try.
I'm curious, in the past I got a little mad with PMD. Also some FindBug findings in Javaslang are no errors.
Thanks and happy easter!

**Comment by danieldietrich** [comment]
@pivovarit would that be something you could do (Sputnik integration)?

**Comment by pivovarit** [comment]
@danieldietrich this needs to be done by the someone who owns the repo. The good thing is that this can be just with a few clicks(2mins of work). Let me know if you need an assistance with this

**Comment by danieldietrich** [comment]
@pivovarit just one question: I'm curious why Sputnik needs admin-rights for repository webhooks and services. Aren't write right enough!?

![screen shot 2016-11-13 at 9 38 38 pm](https://cloud.githubusercontent.com/assets/743833/20248706/d241b8c6-a9e9-11e6-9c98-ac48529454fd.png)

**Comment by pivovarit** [comment]
CC: @pjagielski

**Comment by danieldietrich** [comment]
@pivovarit which checkstyle settings do you suggest? Default/Sub/Google? Currently I have Default selected but thinking about enabling Google...

**Comment by pivovarit** [comment]
@danieldietrich let's start with the default and then fine tune it. I suppose there will be a lot of tuning with such a codebase :) config files land in repo

**Comment by danieldietrich** [comment]
Hi @pjagielski, could you please clarify why Sputnik needs admin-rights (see [comment above](https://github.com/javaslang/javaslang/issues/1229#issuecomment-260211111))?

**Comment by pjagielski** [comment]
Yes. In Github with Travis setup it's not used at all. It was introduced to support CircleCI, because it doesn't start build on pull request submission. The hard thing is that we don't know in advance, whether you'd use Travis or CircleCI and it's easy to change from one to another. 

We need `admin` to delete webhooks when Sputnik is being tunb off (`write` if not enough).

I hope it's more clear now, maybe we can put this explanation somewhere in Sputnik wiki..

**Comment by danieldietrich** [comment]
@pjagielski Ok, I understand :) A hint somewhere might help users.
