### ISSUE TITLE
For2 comprehension doesn't generate a cross product of the elements when using lazy evaluation

### ISSUE THREAD

**Issue by benoitheinrich** [javaslang/javaslang#1230]
Hi,

After playing with the `For` comprehension loop I think I've found an issue that can easily be reproduced with the following test case:
```
        final Iterator<String> strings = For(List.of(1, 2, 3), List.of("a", "b"))
                .yield((i, s) -> s + i);
        assertThat(strings.toList()).containsExactly("a1", "b1", "a2", "b2", "a3", "b3");
```

If you use the nested syntax then it works:
```
        final Iterator<String> strings = For(List.of(1, 2, 3), i ->
                For(List.of("a", "b")).yield(s -> s + i)
        );
        assertThat(strings.toList()).containsExactly("a1", "b1", "a2", "b2", "a3", "b3");
```

Using a flatMap / map also works as expected:
```
        final List<String> strings = List.of(1, 2, 3).flatMap(i -> List.of("a", "b").map(s -> s + i));
        assertThat(strings.toList()).containsExactly("a1", "b1", "a2", "b2", "a3", "b3");
```

Please could you let me know if I'm doing something wrong or if this is a valid bug report?

Cheers,
/Benoit

**Comment by danieldietrich** [comment]
Hi Benoit,

you're right, it is a bug. For2 to For8 need to use Stream instead of Iterator internally.

I will prepare a fix 2.0.2.

\- Daniel
