### ISSUE TITLE
Add leftPadTo(int, T)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1238]
We already have [`Seq<T> padTo(int, T)`](https://github.com/javaslang/javaslang/blob/master/javaslang/src/main/java/javaslang/collection/Seq.java#L487).
Now we want to add `Seq<T> leftPadTo(int, T)` in a similar way.

Motivated by [this article](http://arstechnica.com/information-technology/2016/03/rage-quit-coder-unpublished-17-lines-of-javascript-and-broke-the-internet/).

**Comment by mvh77** [comment]
Meaning Javaslang won't be found on NPM after all? :stuck_out_tongue_winking_eye:

**Comment by danieldietrich** [comment]
Successfully finished.
