### ISSUE TITLE
Match/Case API in 2.0.1

### ISSUE THREAD

**Issue by jknack** [javaslang/javaslang#1246]
Hi Daniel,

 I [see](https://github.com/javaslang/javaslang/commit/661024c160ad89d378e1280f2b17f2c4cf648fcc) you removed the ```Case(T, Supplier<R>)``` method in 2.0.1.

 Can you explain why?

 In my mind think isn't only useful but also the preferred way of using the Match API.

 ```java
   Match(dbtype).of(
    Case("h2", H2Templates::new),
    Case("mysql", MySQLTemplates::new)
   )
 ```

In 2.0.1 we are forced to wrap the ```value``` with a ```$(...)``` pattern.

Thanks

**Comment by danieldietrich** [comment]
Hi Edgar,

there where ambiguities (see #1207). I had to remove Case methods to fix it.

I looks like I removed too many methods. In fact I can add more methods having a Supplier.

Only the `Case(T, Function)` needs to be removed because it introduces ambiguities.

I will fix that and prepare a 2.0.2 today. It will be available tomorrow. I have also a `For` fix in the pipeline.

Greets

Daniel

```java
import javaslang.API.Match.Case;
import javaslang.API.Match.Pattern0;

import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

import static javaslang.API.$;

public class Test {

    public static void main(String[] args) {

        // Case("1", o -> "ok"); // Not possible, would lead to ambiguities
        Case("1", () -> "ok");
        Case("1", "ok");

        Predicate<String> p = s -> true;
        Case(p, o -> "ok"); // Ambiguous, if Case *XXX* is present (see below)
        Case(p, () -> "ok");
        Case(p, "ok");

        Case(o -> true, o -> "ok"); // Ambiguous, if Case *XXX* is present (see below)
        Case(o -> true, () -> "ok");
        Case(o -> true, "ok");

        Case($("1"), o -> "ok"); // Ambiguous, if Case *XXX* is present (see below)
        Case($("1"), () -> "ok");
        Case($("1"), "ok");

    }

    // -- R

//    // *XXX* => leads to ambiguities (see above)
//    public static <T, R> Case<T, R> Case(T value, Function<? super T, ? extends R> f) {
//        return null;
//    }

    public static <T, R> Case<T, R> Case(T value, Supplier<? extends R> f) {
        return null;
    }

    public static <T, R> Case<T, R> Case(T value, R retVal) {
        return null;
    }

    // -- Predicate

    public static <T, R> Case<T, R> Case(Predicate<? super T> predicate, Function<? super T, ? extends R> f) {
        return null;
    }

    // not part of 2.0.1 but may be added
    public static <T, R> Case<T, R> Case(Predicate<? super T> predicate, Supplier<? extends R> f) {
        return null;
    }

    public static <T, R> Case<T, R> Case(Predicate<? super T> predicate, R retVal) {
        return null;
    }

    // -- Pattern0

    public static <T, R> Case<T, R> Case(Pattern0<T> pattern, Function<? super T, ? extends R> f) {
        return null;
    }

    // not part of 2.0.1 but may be added
    public static <T, R> Case<T, R> Case(Pattern0<T> pattern, Supplier<? extends R> f) {
        return null;
    }

    public static <T, R> Case<T, R> Case(Pattern0<T> pattern, R retVal) {
        return null;
    }
}
```

**Comment by jknack** [comment]
What if you provide a ```Case(T, *)``` where ```*``` is a Function or Supplier. Then inside the ```Case(T, *)``` you test for predicate or not:

```java
Case(T value, Supplier supplier) {
  final Predicate predicate;
  if (value instanceof Predicate) {
     predicate = (Predicate) value;
  } else {
     predicate = $(value);
  }
  return Case(predicate, supplier);
}
```

does it help?

Also, think a ```built-in``` default case will be helpful too:

```java
Match(value).of(
  Case(1, "1"),
  Case(2, "2"),
  Case_("?"),
);
```

Or:

```java
Match(value).of(
  Case(1, "1"),
  Case(2, "2"),
  Case_(() -> {
    throw new IllegalArgumentException(value);
  }),
);
```

I suggest ```Case_``` but this is just an example, you can pick a better name.

Ideally/Optionally, the special ```Case_``` could throw an Exception:

```java
Match(value).of(
  Case(1, "1"),
  Case(2, "2"),
  Case_(IllegalArgumentException::new);
  }),
);
```

What do you think?

**Comment by danieldietrich** [comment]
> does it help?

We don't need it. All the Case methods which are not commented out in the example I provided above are valid. Only the method I marked with \*XXX\* is not possible.

> Also, think a built-in default case will be helpful too

We write the default case like in Scala:

```scala
// scala
o match {
    case _ => "?"
}
```

```java
// javaslang
Match(o).of(
    Case($(), "?")
)

Match(o).option(
    // cases
).getOrElse("?")

Match(o).option(
    // cases
).getOrElseThrow(IllegalArgumentException::new)
```

> Ideally/Optionally, the special Case_ could throw an Exception

Actually it does. If no Case matches a MatchError is thrown.

**Comment by jknack** [comment]
my bad!

I didn't get the comments on ```XXX``` methods and yes! ```Match().option``` is what I need it!

Looking forward for ```2.0.2```

Thanks!

**Comment by danieldietrich** [comment]
Many thanks for your finding. Next time I will take more care when changing APIs.

**Comment by danieldietrich** [comment]
Edgar, I can't manage to publish 2.0.2 today. I'm on vacation with my family starting tomorrow for one week. I want to get the time to test it before it gets released.
\- Daniel

**Comment by jknack** [comment]
I can wait :)

Enjoy it!

**Comment by danieldietrich** [comment]
Thx! :)

**Comment by danieldietrich** [comment]
@jknack I managed to release it today. See https://github.com/javaslang/javaslang/releases/tag/v2.0.2

**Comment by jknack** [comment]
hehehe you rock man!

**Comment by danieldietrich** [comment]
:-)
