### ISSUE TITLE
Throwable in signature for partial application of CheckedFunctions

### ISSUE THREAD

**Issue by manu-m** [javaslang/javaslang#1257]
I do not really understand why the signature of methods for partial application of CheckedFunctions expects a Throwable, e.g.:

```java
default CheckedFunction1<T2, R> apply(T1 t1) throws Throwable {
    return (T2 t2) -> apply(t1, t2);
}
```

Partial application of checked functions become very unhandy under this circumstances and from my point of view it's unncessary to expect a Throwable at this point. But I think you see a sense behind this signature :-) so I would like to know the reason your design decision ;-)

**Comment by danieldietrich** [comment]
You are right! Partial `apply` should not throw. I will change that. It was an oversight.
