### ISSUE TITLE
Add 'computeIfPresent' to Map

### ISSUE THREAD

**Issue by enelson** [javaslang/javaslang#1261]
I very well may be missing it, but I don't see a function on the `Map` type that is similar to Java 8's `computeIfPresent`, where it will either return the value for a given key, or compute a value and add it to the map. Am I missing it? If not, I'm happy to take this on if you'd like.

**Comment by talios** [comment]
I don't believe there is one - I was looking for something similar the other day.  You'd want to add it to the new `Multimap` hierarchy as well.

**Comment by enelson** [comment]
I would also add `computeIfAbsent` as well. Both of these are useful.

**Comment by danieldietrich** [comment]
Yep, please compute, eh, implement them, they are absent. :)

**Comment by paplorinc** [comment]
Hmmm, isn't `withDefaultValue` and `withDefaults` used exactly for this purpose?
```
* Turns this map from a partial function into a total function that
* returns a value computed by defaultFunction for all keys
* absent from the map.
```

**Comment by danieldietrich** [comment]
Good point!

`computeIfAbsent` makes only sense for mutable collections. It comes handy when lazy evaluating values (e.g. for cache application). For example we use it in Function1:

```java
    @Override
    default Function1<T1, R> memoized() {
        if (isMemoized()) {
            return this;
        } else {
            final Lazy<R> forNull = Lazy.of(() -> apply(null));
            final Object lock = new Object();
            final java.util.Map<T1, R> cache = new java.util.HashMap<>();
            return (Function1<T1, R> & Memoized) t1 -> {
                if (t1 == null) {
                    return forNull.get();
                } else {
                    final R result;
                    synchronized (lock) {
                        result = cache.computeIfAbsent(t1, this::apply);
                    }
                    return result;
                }
            };
        }
    }
```

The mutable `cache` is automatically updated if the value is not present.

---

An immutable Map can't update its internal state. Therefore the updated collection has to be returned along with the value:

```java
Tuple2<V, ? extends Map<K, V>> computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction) {
    return getOption(key).map(value -> Tuple.of(value, this)).getOrElse(() -> {
        final V value = f.apply(key);
        return Tuple.of(value, put(key, value));
    });
}
```

The point of computeIfAbsent is to compute the value only once. Subsequent calls with the same key should return the 'cached' value. Function0..8 support this behavior using a `memoized()` version of the function.

---

Having this in mind we could achieve the same by using:

```java
Function<K, V> f = myMap.withDefault(mappingFunction).memoized();
```

Do you think `computeIfAbsent` is practicable?

* on each call Tuple instances are created
* the caller is responsible for updating the Map reference with the Map returned in the Tuple

**Comment by paplorinc** [comment]
@danieldietrich, I'm not sure what your question is :(

I think `computeIfAbsent` is something like:
```Java
return registry.get(user)
                      .getOrElse(List::empty);
```
i.e. get a list from the map, or if it's absent, return a default empty List, without modifying anything (unlike the Java version, which adds it to the collection also) ...
The problem with `withDefault` is that it doesn't return a map, therefore I cannot add back to it.

Would it be enough to add a method next to `get(key)` like `getOrElse(key, supplier)`?

**Comment by danieldietrich** [comment]
@paplorinc Currently I don't see the need for `getOrElse(key, supplier)`. Java 8's computeIfAbsent method does cache the value once it is computed.

The correct immutable implementation of `computeIfAbsent` is

```java
// Note: SortedMap.computeIfAbsent returns Tuple2<V, ? extends SortedMap<K, V>> etc.
Tuple2<V, ? extends Map<K, V>> computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction) {
    return get(key).map(value -> Tuple.of(value, this)).getOrElse(() -> {
        final V value = f.apply(key);
        return Tuple.of(value, put(key, value));
    });
}
```

The original question of this issue is to add `computeIfPresent`, which is relatively simple:

```java
Option<V> computeIfPresent(K key, BiFunction<? super K,? super V,? extends V> remappingFunction) {
    return get(key).map(value -> remappingFunction.apply(key, value));
}
```

**Comment by ruslansennov** [comment]
#1617
