### ISSUE TITLE
Question regarding AWS Lambda and javaslang

### ISSUE THREAD

**Issue by geolich** [javaslang/javaslang#1268]
Hi there! I am sorry if this is not the right place but I don't know where else to ask.
I am building a small application that will run on AWS Lambda and I use the javaslang library for it.
The problem I have is that when I invoke the function, I get the following error:
`javaslang/λ: java.lang.NoClassDefFoundError java.lang.NoClassDefFoundError: javaslang/λ`

The weird part is that the class is there in the packaged jar. When I use a shell to manually run the jar it works. 
Has anyone had similar problems? I maybe think it is a problem with AWS Lambda and not recognizing properly the λ character(ironic).

I know this is not the right place probably but I have been hitting my head for 2 days now.

**Comment by danieldietrich** [comment]
Hi @geolich, thx for using Javaslang. I haven't heard about that specific problem yet. It might be a known AWS Lambda problem that is not related to class names but to packaging of dependencies.

Please take a look at this: http://stackoverflow.com/questions/32782980/aws-lambda-noclassdeffounderror

There are links provided how to use the maven-shade plugin to circumvent that problem.

Greets

\- Daniel

**Comment by geolich** [comment]
Hi @danieldietrich Thanks for your quick reply. I found that it is a problem with AWS Lambda. I created a test λ.class and tried to run it and got the same error. It has a problem to load classes with special characters. A bit ironic that AWS Lambda cannot detect the lambda character.

Thank you for your help.

**Comment by danieldietrich** [comment]
Thx!
