### ISSUE TITLE
Use `Option.when`, whenever applicable

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1270]
Getting nullable or non-existent values often required a method which returns an Option as a result.
This was often constructed via ternary or an if statement, and often repeated the logic the parent method contained (which threw an exception if not valid).

This was unified in: https://github.com/javaslang/javaslang/pull/1269

**Comment by danieldietrich** [comment]
As stated on the PR, the code size is reduced by applying this change but we create an additional Supplier instance. This changes the runtime behavior of our collection. I'm afraid, therefore we can't apply this change.
