### ISSUE TITLE
Create a persistent `BitSet` data structure

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1271]
`BitSet` is extremely useful when you want to test the presence of some enumerable entity, i.e. a compact `Set` of `Booleans`.
We might want a pure one in Javaslang also.

It could be based on [Scala](https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/BitSet.scala)'s or  [Haskell](http://hackage.haskell.org/package/bitset)'s implementations.

**Comment by danieldietrich** [comment]
Nice idea. Basically we align to Scala (type hierarchy and naming). Looking at Haskell is better in terms of impl details because it is more clean/pure. However, when it comes to recursion we use iteration with mutable local method vars instead.

**Comment by ruslansennov** [comment]
@danieldietrich @paplorinc please take a look on this skeleton: b63602eeec6d4f70853b5e8691425cd6b78876c1 (copied from Scala implementation)

**Comment by ruslansennov** [comment]
#1334
