### ISSUE TITLE
Try::filter and custom throwable (supplier)

### ISSUE THREAD

**Issue by manu-m** [javaslang/javaslang#1273]
What do think about extending Try with an additional filter method that expects a throwable or throwable supplier? I have a use case where I would like to concretize a problem by a custom Throwable that is more meaningful than a NoSuchElementException if a specific filter is applied. This makes further processing and analyzing of the Try instance easier and more flexible.

If also think that this makes sense I could do a PR.

**Comment by danieldietrich** [comment]
Hi @manu-m,

yes, that is a good suggestion. I can't come up with a better solution.

Let's only take an additional `Supplier<? extends Throwable>` into account (to keep the number of filter methods small) as second argument for two new methods: `filter(Predicate, Supplier)` and `filterTry(CheckedPredicate, Supplier)`.
