### ISSUE TITLE
`Multimap` should implement `Map<K, Traversable<V>>`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1274]
We may have to segregate some interfaces, as it seems intuitive for `Multimap` to implement `Map`, but doing it creates some conflicts that should be addressed.
Opinions?

**Comment by danieldietrich** [comment]
It would be great to hear the opinion of @ruslansennov (currently in holidays). He created the Multimap. We talked about the interfaces and decided to inherit from Traversable instead of Map. I think the conflicts cannot be solved (with Java's type system). But let's wait to hear from Ruslan.

**Comment by ruslansennov** [comment]
Hi guys.
I believe it is impossible and, yes, the conflicts cannot be solved. I spent some time to make this but it was unsuccessful attempt. @paplorinc if you have any proposals, please show this, because it is very interesting

**Comment by paplorinc** [comment]
@ruslansennov, I played with it as well, but seeing that it wasn't, my only idea was to open an issue on separating the interfaces to smaller ones so that we can have a generic `Map` that contains only the common methods.

If you guys think it's an overkill, feel free to close the issue :)

**Comment by danieldietrich** [comment]
I think separating the interfaces is overkill. Let's keep it as simple as possible. I will close this issue for now. If it is really needed we may reopen it.
