### ISSUE TITLE
Fix `intersperse` in `Gen`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1275]
The current implementation is more complicated than it should be (e.g. `genSwitch = !genSwitch`) and the tests don't assert its behavior correctly (i.e. they pass if simply `other` is returned also).

**Comment by danieldietrich** [comment]
I think the intersperse method is correct. My test:

```java
Gen<Integer> gen = Gen.of(0).intersperse(Gen.of(1));
Random rnd = new Random();
for (int i = 0; i < 10; i++) {
    System.out.print(gen.apply(rnd));
}
```

Output:

```java
0101010101
```

- as expected.

**Comment by paplorinc** [comment]
You're right, will update the description.
`genSwitch = !genSwitch` confused me...

**Comment by danieldietrich** [comment]
yes, one of the rare _embedded_ assignment usages - for me ok here.

**Comment by talios** [comment]
@paplorinc the tests I added for that were rather minimal I confess. I wasn't quite sure the best way to cover them.  There is a test that checks the ordering bounces back and forth correctly tho.

**Comment by paplorinc** [comment]
Fixed in https://github.com/javaslang/javaslang/pull/1282
