### ISSUE TITLE
Simplify complexity of `removeAll`/`retainAll`/`containsAll` in `List`/`Stream`/`Vector`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1276]
Doing a `contains` on
```Java
final List<T> removed = List.ofAll(elements).distinct();
```
is linear (`O(n)`), changing it simply to
```Java
final Set<T> removed = HashSet.ofAll(elements);
```
would simplify it to constat time (`O(1)`).

Should be investigated for the whole codebase.

**Comment by danieldietrich** [comment]
Nice! Also the `removed.contains(element)` with be `O(log n)` instead of `O(n)` then.
