### ISSUE TITLE
Make `indexOf` return `Option<Integer>` instead of `-1` in `Seq`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1278]
Having non-intuitive error codes are a bad legacy, inherited from `C++`.

Since `indexOf` and `lastIndexOf` may return an index or an error, it should be modelled ideally in this way.

E.g. `Array.indexOf` should ideally look something like this instead:
```Java
@Override
public Option<Integer> indexOf(T element, int from) {
    for (int i = from; i < length(); i++) {
        if (Objects.equals(get(i), element)) {
            return Option.some(i);
        }
    }
    return Option.none();
}
```

**Comment by danieldietrich** [comment]
If I had the chance to create a new language, I would do it this way. But I think it is important to be consistent with Java and Scala. Both return `-1` in literally every indexOf method, see http://www.scala-lang.org/api/2.11.7/index.html#scala.collection.Seq@indexOf(elem:A,from:Int):Int.

Also the API for 2.x releases should stay fixated. The OSGi aficionado have an eye on us :) API changes will break backward compatibility.

Maybe this is something to think about for the next major release.

**Comment by paplorinc** [comment]
We have already introduced interface changes (see `CharSeq`.`split`) in this release.
However, we could annotate all non-option methods with `@Deprecated` and provide alternatives.

**Comment by danieldietrich** [comment]
I understand your point but I prefer to stay consistent with Java and Scala. `indexOf` is just a read-operation. Creating an Option instance and boxing the int may have negative implications. As I said, it may be part of the next major release.

Please note that Scala collections are also reworked (currently targeted for Scala 2.13). Our goal is to align Javaslang 3.0 collections to Scala 2.13 collections.

**Comment by danieldietrich** [comment]
As an alternative we could additional methods `indexOfOption`. We would preserve the regular Java/Scala behavior and offer a new approach at the same time.

We create default methods in Seq (for all parameter variations):

* indexOfOption
* indexOfSliceOption
* indexWhereOption
* lastIndexOfOption
* lastIndexOfSliceOption
* lastIndexOfWhereOption

These are quite some methods but they have to be only defined once within Seq, e.g.

```java
default Option<Integer> indexOf(T element) {
    final int index = indexOf(element);
    return (index == -1) ? Option.none() : Option.some(index);
}
```

Each `*Option` method should call its dual non-optional partner.

**Comment by paplorinc** [comment]
Yup, that's what I meant by `alternative`.
Will push a version shortly :)

**Comment by paplorinc** [comment]
@danieldietrich, what about `CharSeq` (and maybe others), that don't inherit them from `Seq`?

**Comment by danieldietrich** [comment]
Great!
CharSeq is A IndexedSeq, should be ok. If there are others (I don't think so) we have to duplicate code or move the impl to Collections. I would not introduce an additional interface to mix in the default method into unrelated types...
