### ISSUE TITLE
Unify code style and apply it to the whole codebase

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1280]
`Idea` (and maybe even `Eclipse` or `EditorConfig`) code style should probably be updated to explicitly define the settings in the latest of the `IDE`s.
Some of the styles can be specified via `Idea inspections`) (e.g. final variable without the `final` keyword) and some can even be defined with `structural search and replace`.

It should also be applied to the whole codebase for consistency (and to reduce unrelated changes in case of `PR`s).

These include - but are not limited to:
* force braces for `if`/`while`/`for` etc?
* `<p`> for empty lines in `JavaDoc`?
* align parameters in `JavaDoc`?
* `final` for local variables
* sort imports and use `*` for every case when more than one import is used from a package
* public non-test method without `JavaDoc`
* mutually exclusive `if`s without the `else` keyword
* nested ternary operators
etc.

Maybe we could borrow some of this from other `OS` projects?

**Comment by danieldietrich** [comment]
Great idea!

* force braces for `if/while/for` etc?

Yes

* `<p>` for empty lines in `JavaDoc`?

Yes

* align parameters in `JavaDoc`?

Yes

**Comment by danieldietrich** [comment]
(btw - I applied the label ⭐ because the is no other label matching. In general I label issues with ⭐ that are important or of special interest.)

**Comment by talios** [comment]
The other day I released ( and have made a few tweak releases ) a [Maven Plugin](https://github.com/talios/googleformatter-maven-plugin) which wraps the [Google Formatter library](https://github.com/google/google-java-format ) which implements the [documented Google code style](https://google.github.io/styleguide/javaguide.html).

Whilst I don't like 100% of their choices, I can certainly see why they're chosen them and are slowly coming around to them. I do appreciate being able to have consistent format separate from IDE, any thought to maybe using it?

**Comment by talios** [comment]
Interestingly - "align parameters in JavaDoc" is one of the things that the Google Format avoids ( and I didn't initially like). Reasoning being in the long run it's a pain when refactoring, introducing line changes purely for format reasons if you introduce/rename a field.

**Comment by danieldietrich** [comment]
One of the most important things I'm concerned with is preserving newlines. This drove me crazy in the past (hello Eclipse Formatter). IntelliJ IDEA's Formatter does a great job here.

In particular it is important for nested lambdas, Javaslang's Match API, ...

**Comment by danieldietrich** [comment]
However, the whole checkstyle & formatter infrastructure + code quality measure based on formatting rules is contra-productive - at least in the projects at $work. It hinders the team of being productive and focusing on the real work.

Concise and correct code + a great test coverage are the key for a healthy code base. We should primarily focus on that.

I want to keep things as simple as possible by having IntelliJ IDEA as main IDE for contributing to Javaslang. We need a well-defined formatter here.

This is how I see codestyle rules in real world development (as distinction of code covered by style-checker (left) and real world programming (right)):

```
[pain in the ass [helpful] not covered]
```

**Comment by paplorinc** [comment]
I agree, but let's configure `Idea` in a way that the default formatting doesn't change any lines (so that people are encouraged to format their work).

**Comment by danieldietrich** [comment]
Yep, would you do that?

After defining the formatting rules that make sense

- reformat the whole code-base (include: { *.java, maybe *.xml, ...}, exclude: { *.scala })
- `mvn clean test` to restore generated files
- export the IDEA settings and overwrite the old ones within `.ide/` (please take a look/update the `.ide/README.md`)

**Comment by paplorinc** [comment]
Sure, will do :)

**Comment by paplorinc** [comment]
We might be able to configure `Gradle` to fail the build in case it's unformatted: https://github.com/diffplug/spotless (I presume it's not working as nicely as Idea's formatter does)

**Comment by danieldietrich** [comment]
Instead of integrating it directly in the build maybe it is possible to create a quality report. The report could cover

* code style (our own rules, not too complicated. the [list above] is a nice start)
* findbugs, pmd, etc.

It would be great if the committers are automatically informed via email if a PR decreases the code quality.

We already have an issue for that (#1229).

On a side-note: I'm not convinced we should move to Gradle. Some love it, some hate it. Maven is still a the standard/most used build tool for Java and it works fine for us, so why change it? There is no necessity to do it. What I do not like about Gradle is that it is not fully declarative and is somehow like Ant.

**Comment by danieldietrich** [comment]
We've done some effort in the past to clean up our code. There is an issue to add findbugs/codestyle to our builds. Maybe https://github.com/TouK/sputnik can also help!
