### ISSUE TITLE
How to combine CompletableFuture.allOf with retries and failed tasks?

### ISSUE THREAD

**Issue by hugree** [javaslang/javaslang#1298]
Hi,

I have a simple case, I think, that I want to use your library for.

I have a list of tasks that and I want to retry each task a number of times. However, I want to be able to get results from all tasks even when one of them fails completely and retry doesn't change the outcome.

My problem is the CompletableFuture.allOf method that I use to run all my suppliers.

This is how I produce suppliers:
```java
CircuitBreaker circuitBreaker = CircuitBreakerRegistry
		.of(new CircuitBreakerConfig.Builder().onCircuitBreakerEvent(this::onBreak).build())
		.circuitBreaker("mybreaker");

Retry retryContext = Retry.custom().maxAttempts(3).waitDuration(Duration.ofMillis(1500)).build();

Supplier<String> decoratedWithCircuitBreaker = CircuitBreaker.decorateSupplier(() -> this::doStuff, circuitBreaker);
Supplier<String> decoratedWithRetry = Retry.decorateSupplier(decorateSupplier, retryContext);
```

After that I stream all suppliers and  use CompletableFuture.allOf, but when one of the doStuff tasks fails the whole processing stops and allOf doesn't produce results anymore.

What's the correct way to do this? How to setup the circuit breaker to "swallow" the exception after retrying fails?

Btw... how to combine checked exception within the doStuff method and decorateCheckedSupplier and CompletableFuture, which requires a regular supplier?

Thanks!

**Comment by danieldietrich** [comment]
Hi @hugree,

the javadoc of CompletableFuture says:

> If any of the given CompletableFutures complete exceptionally, then the returned CompletableFuture also does so, with a CompletionException holding this exception as its cause.

So the current behavior you observe, that no more results are produced, is correct.

I suggest to use Javaslang's [Future](http://www.javadoc.io/doc/io.javaslang/javaslang/2.0.2):

```java
// using javaslang.collection.Stream
Stream<Future<String>> futures = Stream.of(s1, ..., sn).map(Future::of);
Future<Seq<String>> result = Future.sequence(futures);

// using an arbitrary Iterable
Iterable<Future<String>> futures = java.util.stream.Stream.of(s1, sn).map(Future::of).collect(Collectors.toList());
Future<Seq<String>> result = Future.sequence(futures);
```

where `s1`, ..., `sn` are of type `CheckedSupplier`.

Hope that helps!

Greets,

Daniel

**Comment by danieldietrich** [comment]
Related to javaslang-circuitbreaker, therefore closed here (different project).
