### ISSUE TITLE
Wrong Traversable min/max contract

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1304]
The Javadoc states that the natural element order is used. This is confusing if an underlying element Comparator exists (like for TreeMap, TreeSet, ...).

We should change the javadoc of ~~all Sorted* collections (and the upcoming PriorityQueue!?)~~ Traversable min/max in the following way (example: min):

```java
/**
 * Calculates the minimum of this elements according to the underlying element {@code Comparator} if exists, or the natural order of elements.
 * ...
```

**Comment by eduardmanas** [comment]
@danieldietrich, wouldn't it be better to change the javadoc in `Traversable`?  (as opposed to changing the individual `min()/max()` javadocs in all Sorted collections).

The change in `Traversable` still makes sense, as it will only impact the Sorted* collections.

**Comment by danieldietrich** [comment]
Oh, sorry! Yeah, good catch. I meant to change the javadoc of Traversable and will change the comment above.
