### ISSUE TITLE
Deprecate `Option.get`?

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1307]
http://royvanrijn.com/blog/2016/04/deprecating-optional-get

Maybe we should consider it also.

**Comment by danieldietrich** [comment]
My first thought is that we should stay consistent with Scala and do not mix Java and Scala API.

**Comment by mvh77** [comment]
Definitely not! You're probably not using Javaslang if you don't understand the concept behind an Option.

**Comment by paplorinc** [comment]
Maybe, but if you do understand it, why would you use its `get` method?

**Comment by mvh77** [comment]
I've seen cases where you actually want to do stuff when you get a None. So you have ugly code like:
```java
if(option.isDefined())
  doSomthing(option.get());
else
  logThatWeGotNothing();
```
In Scala you'd obviously use a pattern match, but in Java you sometimes have to do stuff like that, forEach isn't enough.

**Comment by paplorinc** [comment]
Me too, it's the exact reason it was suggested to be deprecated.
You could still use that after deprecation, it would just signal that it isn't the way it was supposed to be used.

**Comment by danieldietrich** [comment]
As I said, we align to Scala.

The use of `Defined` is redundant, in most cases we will check emptiness before calling get.

```java
if (option.isDefined()) ... option.getIfDefined()) ... else ...
```

Another reason is that renaming it would have implications, e.g. what to do with these methods:

* Try.get()
* Future.get()
* Either.get()

Aligning to Scala is a clear direction. Making the API half Java, half Scala will lead to pain and suffering.

I close this ticket to give a clear direction. The Javaslang vision is to converge Java towards Scala, not the opposite direction.
