### ISSUE TITLE
Add `isNotEmpty` to `Traversable`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1316]
Similarly to how `Option` has
```java
default boolean isDefined() {
    return !isEmpty();
}
```
we may add the opposite of `isEmpty`, as `Java`'s `!` operator is hard to see (especially before an `i`)
```java
/**
 * Checks if this Traversable is not empty.
 *
 * @return whether this Traversable contains any elements.
 */
default boolean isNotEmpty() {
    return !isEmpty();
}
```

**Comment by danieldietrich** [comment]
All `Value`s have `isDefined()`. `isNotEmpy()` would be an alias, similar to `length()` and `size()`. Just saying, but it makes sense for collections to have that name.

**Comment by valery1707** [comment]
@danieldietrich, `Traversable` already have `nonEmpty` that have same behavior as discussed `isNotEmpy()`.
Is this issue need to be closed?

**Comment by paplorinc** [comment]
Unfortunatly @danieldietrich thinks this complicates the API: https://github.com/javaslang/javaslang/pull/1320/files#r62437967

**Comment by valery1707** [comment]
@paplorinc, method `Traversable#nonEmpty` was introduced in `2016-02-16` by @danieldietrich.
This discussion took place at `2016-05-08`, when method already exists.

If this issue stil actual - I don't understand what need to be done.

**Comment by danieldietrich** [comment]
@valery1707 you are completely right. This issue can be closed.

Value has isEmpty and isDefined. The latter is meant to reflect the non-empty state, especially for single-valued types.

Traversable inherits isEmpty and isDefined and adds nonEmpty for multi-valued types.

These method names are common in Scala.

@paplorinc I have to admit that I forgot to mention that we have nonEmpty already. Sorry! The point in the comment you are referring is, that we do not need additional API (with non-empty semantics) within the internal, non-Traversable collections like HashArrayMappedTrie or RedBlackTree.

Thank you for your engagement and keep up the great work!
