### ISSUE TITLE
Optimize `Array`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1322]
* create performance tests for `Array` (see `List` performance test for baseline)
* test whether it would be faster to add an `startOffset` to the class, which would result in incrementing a single value on `tail()`, instead of copying the whole array
 * maybe the same for `endOffset`, if we have important operations that need it (`dropRight`?)
* encapsulate all index calculations and hide if from the rest of the class (and from the API)
* optimize array copies by `if`-ing index `0` inserts or end inserts (i.e. to avoid unnecessary native array-copy calls)

It would also be nice to compare the results against `List`, and maybe even returning an `Array` instead of a `List` under a certain threshold, if it's quicker.

**Comment by danieldietrich** [comment]
What implications would these changes have for very big arrays? By using an offset, we cannot free the memory of an already allocated array, right?

**Comment by paplorinc** [comment]
As stated in https://github.com/javaslang/javaslang/pull/1321#discussion_r62435298, this makes many `O(n)` operations `O(1)`.

**Comment by danieldietrich** [comment]
I've spent more time on reading the code. Great changes!

**Comment by paplorinc** [comment]
Closed via https://github.com/javaslang/javaslang/pull/1321
