### ISSUE TITLE
Add Java-like Value.collect() methods to increase interoperability

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1332]
`java.util.stream.Stream` has:

* [`collect(Collector<? super T,A,R> collector)`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#collect-java.util.stream.Collector-)
* [`collect(Supplier<R> supplier, BiConsumer<R,? super T> accumulator, BiConsumer<R,R> combiner)`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#collect-java.util.function.Supplier-java.util.function.BiConsumer-java.util.function.BiConsumer-)

When we add these as `default` methods to `javaslang.Value`, Javaslang types will be _✨automagically✨_ convertible to **all libraries** that are built on top of `java.util.stream.Stream` (e.g. [jooq/jool](https://github.com/jOOQ/jOOL), [amaembo/streamex](https://github.com/amaembo/streamex), ...), but more important this allows us to re-use user-defined aggregation functions based on Collectors.

Because this is a conversion method, we implement it in `Value` (or `Convertible`) rather than in `Traversable`. `Iterator` will benefit from it because in a future Javaslang version `Iterator` will not extend `Traversable` any more (see [#1295](https://github.com/javaslang/javaslang/issues/1295#issuecomment-213835541)).

**Comment by danieldietrich** [comment]
Since this is a conversion method, we may implement it in `Value` (or `Convertible`) rather than in `Traversable`. `Iterator` would benefit from it because in a future Javaslang version `Iterator` will not extend `Traversable` any more. Instead `Value` is split into `Value` and `Convertible` and `Iterator` will extend `Convertible`. (see [#1295](https://github.com/javaslang/javaslang/issues/1295#issuecomment-213835541))

**Comment by mvh77** [comment]
Is this really necessary? You can just do .toJavaStream() and call collect(...) on that.

**Comment by danieldietrich** [comment]
It is more concise. Also it works for all Values. It might be confusing to stream an Option for example because `java.util.stream.Stream` is associated with collections.

**Comment by mvh77** [comment]
I'm not really against it and I thought about it myself some time ago, but it's a bit bloaty in my opinion since you can do without and it's something you need very rarely. And btw, Option is a kind of collection! :wink:

**Comment by danieldietrich** [comment]
I will think about it... we should only pull in changes that make sense.

**Comment by danieldietrich** [comment]
Finished, we will keep it because they increase interoperability. In particular Collectors of other libraries can now be used in conjunction with Javslang. Many thanks @earlzero.
