### ISSUE TITLE
Add PriorityQueue to Performance Characteristics table

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1333]
[Here](https://github.com/javaslang/javaslang/blob/master/javaslang/src/main/java/javaslang/collection/package-info.java) is a table

**Comment by ruslansennov** [comment]
I'm not sure that this is necessary, because a lot of methods are not implemented in PQ

**Comment by paplorinc** [comment]
Yeah, `Queue` is in the first list (sequential), while `TreeSet` is in the second.
Added it in the first, even though it doesn't fit perfectly.
