### ISSUE TITLE
IntelliJ Idea 2016.1.2 inspection

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1339]
I created another issue [IDEA-156131](https://youtrack.jetbrains.com/issue/IDEA-156131) about "wrong" inspection in IntelliJ Idea 2016.2 (<code>Stream::prependAll</code> for example).

It seems Idea is right but javac is wrong and we should specify explicit arguments like this
```java
    return Stream.<T>ofAll(elements).appendAll(this);
```

Just now I installed latest Java on my computer and saw that Javaslang doesn't compile with java9  :-1: Compilation fails exactly in those lines of code, which Idea pointed

**Comment by danieldietrich** [comment]
Uh, oh 😱 

(Thought: Javaslang 3.0.0 should be Java 9 ready. Replace our module hacks with real modules and internalize classes that are currently package-private, etc.)

**Comment by danieldietrich** [comment]
There are still problems with Java 9. We will track this outside of this issue.
