### ISSUE TITLE
Optimize `Vector`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1348]
We should optimize `Vector`, e.g. it's `slice`, `subSequence`, `drop`, `dropRight`, `dropWhile`, `dropUntil`, `init`, `tail`, `take`, `takeRight`, `takeUntil`, `takeWhile`, `remove`, `removeAt` should all be made `O(1)` time (some are close already) with greater structural sharing, possibly with an `offset` and `length`, as done in `Array` also.

Notes:
* `reverse` of a single element should also return itself
* `init` can be `dropRight(1)`, `tail` can be `drop(1)`
* `intersperce` should probably use `iterator()`
* equals can be: `return o == this || o instanceof Vector && Collections.equals(this, (Vector<?>) o)`

On a related note, we should create a `JMH` performance benchmark for all important interfaces (`Seq`, `Traversable`, `Map`, `Set`...) with their important methods.
We should be able to tell that way which implementations could be made faster and whether certain optimizations actually result in faster code.

**Comment by paplorinc** [comment]
@danieldietrich, I think this is mislabeled

**Comment by mvh77** [comment]
Is anybody working on [this](https://github.com/javaslang/javaslang/issues/568)?

**Comment by paplorinc** [comment]
@mvh77, I have 2 open PRs for `Vector` currently, one for benchmarks, the other for some optimizations.
