### ISSUE TITLE
HashMap.hashCode throws NPE after deserialization

### ISSUE THREAD

**Issue by zsolt-donca** [javaslang/javaslang#1353]
Hi, guys,

There is a bug in the latest release release (`2.0.2`) regarding `HashMap.hashCode`. The issue is that after a hash map is deserialized, calling it's [`hashCode`](https://github.com/javaslang/javaslang/blob/v2.0.x/javaslang/src/main/java/javaslang/collection/HashMap.java#L377) method throws NPE (the field `hash` is null).

This issue has been fixed on master by a [PR](https://github.com/javaslang/javaslang/pull/1242) made for a [refactoring/design improvement](https://github.com/javaslang/javaslang/issues/1235). The reason I'm opening this issue is to keep track of this issue on the latest release, and to be able to prioritize the upcoming release accordingly.

While investigating, I realised that the reason behind this problem is that the lazy [`hash`](https://github.com/javaslang/javaslang/blob/v2.0.x/javaslang/src/main/java/javaslang/collection/HashMap.java#L35) field is marked as `transient`. While it makes complete sense to throw away evaluated hash value while serialization (as the contents' hash values might change), still, there should be some additional serialization logic (e.g. `readObject` and `writeObject` methods) that should reassign the lazy `hash` field into its unevaluated state. Alternatively, the field `hash` could be made non-transient and the class [`javaslang.Lazy`](https://github.com/javaslang/javaslang/blob/v2.0.x/javaslang/src/main/java/javaslang/Lazy.java) could clear its calculated value upon serialization while serializing its _supplier_. I realize that this is the exact opposite of how `Lazy` is handling serialization right now (maybe we could make another lazy flavour for this?).

The above PR fixes this issue by removing the lazy `hash` field altogether.

It might worth mentioning that we stumbled upon this problem after we started using javaslang's persistent collections with [Apache Spark](http://spark.apache.org/), a distributed computing system that heavily relies on serialization of data. Our `HashMap` instances were put into other hash-based collections, hence the calls to `hashCode`.

**Comment by danieldietrich** [comment]
Hi @zsolt-donca,

thank you for using Javaslang and reporting this bug! We will fix it soon in a 2.0.3 release.

Storing the hash lazily for each node of a persistent collections may have a significant impact on memory (additional lazy objects and lambda instances), cpu (instance creation) and garbage collection, depending on the collection size.

Scala and Java do not store the hash, they also compute it every time hashCode is called.

I think most users will not use (large) collections as keys. There is another option (beside making hash lazy in Javaslang):

It might be practicable to create a specific object-wrapper type that lazily provides the hash of the underlying object:

```java
public final class HashKey<K extends Serializable> implements Serializable {

    private static final long serialVersionUID = 1L;

    private final K underlying;
    private transient Lazy<Integer> hash;

    public static <K extends Serializable> HashKey<K> of(K underlying) {
        return new HashKey<>(underlying);
    }

    private HashKey(K underlying) {
        this.underlying = underlying;
        this.hash = Lazy.of(() -> underlying.hashCode());
    }

    public K underlying() {
        return underlying;
    }

    @Override
    public int hashCode() {
        return hash.get();
    }

    @Override
    public boolean equals(Object o) {
        if (o == this) {
            return true;
        } else if (o instanceof HashKey) {
            return underlying.equals(((HashKey) o).underlying());
        } else {
            return false;
        }
    }

    // toString, readObject (initialize hash with a new Lazy), writeObject

}
```

I'm currently not sure if such a type would fit good into Javaslang. But you might implement your own.

What are your thoughts? Is that an option?

**Comment by zsolt-donca** [comment]
Hi, @danieldietrich ,

Thank you for your quick response!

I see and agree with that storing the hash lazily *can* have a significant memory overhead. Maybe it would make sense in Scala, a language that has native support for lazy fields, where most of the overhead (the `Lazy` instance, the lambda for the supplier, the `Integer` instance, and thus the implications on GC) would not be present. The fact that Scala's immutable collections don't do this is a good sign that, even in Scala, it still doesn't worth it *generally*.

When the benefits do outweigh the above overhead, such a wrapper class that you proposed seems perfectly feasible to me. We'll consider implementing that class given that our measurements confirm that it worths doing so. As a wise man once said: "Measure, don't premature!"

The fix for this issue in master is perfectly fine by me, and I'm looking forward towards your next release. :) Until then, we'll stick to your snapshot releases.

Keep up the good work!

**Comment by danieldietrich** [comment]
Hi @zsolt-donca, thank you.

I think the wrapper keys should significantly improve the memory footprint since there is only one wrapper (+ Lazy + Supplier + Integer) for a whole collection instance. If the lazy instance would be baked into the collection, then every value/entry within the collection would have the overhead.

I'm very interested in your insights/measurement. So it would be great if you share it here!

Thx!

**Comment by paplorinc** [comment]
Would it be possible to store all the `hashCode`s in a single static map in `Traversable` intead?
It could use [`Guava`'s cache builder](https://github.com/google/guava/wiki/CachesExplained) (or anything similar) with weak - System.identityHashCode - keys, and use the `iterator()` as the base for `hashCode` calculation.

This way `hashCode` would be lazy, the memory consumption would be minimal and the speed would be similar to the stored one.

**Comment by danieldietrich** [comment]
No, please let's follow best practice from other langs like Scala.

The `HashKey` approach sketched above is O(1) mem and cpu.

**Comment by paplorinc** [comment]
So is my suggestion, but for free (i.e. simpler client side code)

**Comment by danieldietrich** [comment]
I see. Let's not bake it into Javaslang for now.

**Comment by danieldietrich** [comment]
@paplorinc We should concentrate for now on benchmark coverage of our basic methods (the ones shown in the javadoc performance table). Voxxed gave us the opportunity to write a series of articles on Javaslang.

**I'm sure that the benchmarks will be _very_ interesting for the whole Java and Scala community!**

This could be a game changer for collection libraries and also for the acceptance of persistent data structures. It would be awesome to see an article here by you!!

**Comment by ruslansennov** [comment]
> I'm sure that the benchmarks will be very interesting for the whole Java and Scala community!

:+1:

**Comment by danieldietrich** [comment]
Already fixed, needs to be cherry-picked.
