### ISSUE TITLE
Bug in Try in 1.2.2

### ISSUE THREAD

**Issue by hamnis** [javaslang/javaslang#1366]
Trying to combine `Try` and `java.util.Optional` crashes with `java.lang.IllegalAccessError`

`Optional.of(Try.of() -> "hello")).flatMap(Try::toJavaOptional)` blows up.

`Optional.of(Try.of(() -> "hello")).flatMap(t -> t.toOption().toJavaOptional())` works.

**Comment by danieldietrich** [comment]
Hi,
thank you for reporting this!
Is it an option for you to migrate to Javaslang 2.x, there it works.
I remember you suggested some months ago to split Javaslang into smaller modules, right? Is that the reason that you stick to 1.x?
Greets
Daniel

**Comment by hamnis** [comment]
No, i have a lib that depends on javaslang 1. I am in the process of upgrading, but everything takes time. I have released a version of my lib that uses the workaround.

**Comment by danieldietrich** [comment]
I understand. We will fix it but it might need some time...

**Comment by danieldietrich** [comment]
Related to #1326

**Comment by danieldietrich** [comment]
Fixed with [724777e](v1.2.3) - will be available at maven central later today
