### ISSUE TITLE
Implement Seq#remove(Predicate<? super T>)

### ISSUE THREAD

**Issue by valery1707** [javaslang/javaslang#1367]
Some times I want to remove from List some items that does *not* satisfy the predicate, that created from Java lambda.
Now i must use this code:
```java
List<SomeDomainObject> src = List.empty();
//src = src .append(...);
java.util.List<SomeDomainObject> search = Arrays.asList(...);
List<SomeDomainObject> notFound = src.filter(((Predicate<String>) search::contains).negate());
```
I want to call: `src.remove(search::contains)`

StreamEx has such method: [StreamEx#remove(Predicate<? super T>)](https://amaembo.github.io/streamex/javadoc/one/util/streamex/AbstractStreamEx.html#remove-java.util.function.Predicate-)

Internally it can be implemented as:
```java
Traversable<T> remove(Predicate<? super T> predicate) {
    Objects.requireNonNull(predicate, "predicate is null");
    return filter(predicate.negate());
}
```
If this implementation is correct I can make PR

**Comment by ruslansennov** [comment]
Hi @valery1707 
PR welcome!

Let's name this new method `Seq#removeAll(Predicate<? super T>)`
I would implement common code in `javaslang.collection.Collections` (see `List#removeAll(T)` for example)

**Comment by valery1707** [comment]
Hi @ruslansennov 

I implement method in [commit](https://github.com/valery1707/javaslang/commit/990889fd5746c9a2753d15d333916f3637058138) - need I create PR for this commit?

**Comment by ruslansennov** [comment]
sure

**Comment by valery1707** [comment]
@ruslansennov here it: #1368
