### ISSUE TITLE
TreeMap.narrow() is not public

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1377]
Are there other static methods in impl classes that are package private but should be public?

**Comment by paplorinc** [comment]
We could move the tests to a separate package to see these problems.

I tried, but `HashArrayMappedTrie`, `RedBlackTree`, `Comparator` is not public and used in tests.

Also, the following methods are not public:
* `CharSeq.unfold*`, `CharSer.(CharFunction|CharUnaryOperator)`
* `Lazy.narrow`
* `PriorityQueue.(collector|tabulate|fill)`
* `Array.unfold*`
* `Vector.unfold*`
* `CharSeq.indexOfOption`
* `Queue.unfold*`
* `LinkedHashSet#ofAll(java.util.stream.Stream<? extends T>)`
* `Try.NonFatalException#of`

and `shouldMatchCustomTypeWithUnapplyMethod` and a few more from `APITest` aren't working.

I will commit the production code changes, without moving all the tests (let's do that when no PRs are pending).

**Comment by emmanueltouzery** [comment]
regarding the unfold* they were meant to be public. I missed it because I first added them to `List` and that's an interface, no need for the `public` there. I should have added the `public` when implementing it in classes, but I missed it. So yes, it should be made public.

**Comment by danieldietrich** [comment]
@paplorinc Thank you for providing the list of non-public methods!

> I will commit the production code changes, without moving all the tests (let's do that when no PRs are pending).

Please let's keep the tests in the current packages. This is junit best practice and saves us from headaches when performing package-private test scenarios. We will keep an eye on the static methods in our code-reviews. In the worst case a new method is not visible for the end-user. This can be fixed.

**Comment by paplorinc** [comment]
> when performing package-private test scenarios

We don't have many of those (nor should we do that often).

**Comment by danieldietrich** [comment]
@paplorinc Ok, I'm open minded to the idea of moving the test classes. Let's put the tests for classes `a.b.c/*` in a package `a.b.c/test/`.
