### ISSUE TITLE
Add Map#mapKeys(keyMapper)

### ISSUE THREAD

**Issue by valery1707** [javaslang/javaslang#1379]
Sometimes i want transform keys in map from one unique value to another unique value (for example, load entity by their id).
If key mapper converted to a not unique value, map will  be reduced and some values may be lost.
If this method is applicable to project rules, then I can implement it.

**Comment by emmanueltouzery** [comment]
note that haskell offers mapKeys & mapKeysWith:
https://hackage.haskell.org/package/containers-0.5.7.1/docs/Data-Map-Strict.html#v:mapKeys

the second call allows to provide a function to merge two values in case of conflict. I think that makes a lot of sense to offer the second call at least.
Also note that haskell gives a rule for the value in case of a conflict: it says "the greatest is kept". If there is no rule I guess you could get baffling behaviours where two sets which look the same map to two different sets (one or the other of the values is kept) depending on factors that don't seem relevant at first sight.

**Comment by valery1707** [comment]
I can implement `mapKeys(Function<? super K, ? extends K2> keyMapper, Function2<V, V, V> valueMerge)` too.

**Comment by valery1707** [comment]
@emmanueltouzery I am not familar with Haskel and dont know how Haskel internal store map.
My current implementation save value from `last key`, but only `TreeSet` store keys in predictable order and will process exactly same as Haskel. `HashMap` and `LikedHashMap` store keys without predictable order.

**Comment by emmanueltouzery** [comment]
Yes that map for which I gave the link is tree-based. There is a [HashMap](https://hackage.haskell.org/package/unordered-containers-0.2.7.0/docs/Data-HashMap-Strict.html) too but apparently it doesn't have the mapKeys function.

**Comment by valery1707** [comment]
`LinkedHashMap` have predictable keys order too.
Unpredictable behavior may be only in `HashMap#mapKeys(Function)`

**Comment by danieldietrich** [comment]
Sounds good.

> Unpredictable behavior may be only in `HashMap#mapKeys(Function)`

It is ok but has to be noted in the Javadoc

**Comment by valery1707** [comment]
@danieldietrich, ok I will add PR soon

**Comment by valery1707** [comment]
@danieldietrich - PR #1383 created
