### ISSUE TITLE
[discussion] would Try.lift() make sense?

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang#1380]
I wrote myself a little helper function, I wonder whether it would make sense to make a PR for javaslang.

my use-case is this:

```java
list.map(x -> runIoOperation(x, getParameterWhichCouldThrow()));
```

Can't do that because both runIoOperation & getParameterWhichCouldThrow() can throw checked exceptions.
I could extract getParameterWhichCouldThrow() in its own variable with `Try` wrapping too I guess.
I could also wrap `runIoOperation` in a new function which would return a `Try` too.

But I spotted for instance `CheckedFunction1.lift`, which is:
```java
static <T1,R> Function1<T1,Option<R>> lift(CheckedFunction1<T1,R> partialFunction)
```

So I wrote for myself:

```java
private static <T,U> Function1<U, Try<T>> tryLift(Try.CheckedFunction<U,T> tryGetter) {
    return x -> Try.of(() -> tryGetter.apply(x));
}

private static <U> Function1<U, Try<Void>> runLift(Try.CheckedConsumer<U> tryGetter) {
    return x -> Try.run(() -> tryGetter.accept(x));
}
```

(actually they could be overloaded)
with that I can do...

```java
list.map(runLift(x -> runIoOperation(x, getParameterWhichCouldThrow())));
```

Now actually that returns a `List<Try<Void>>` so I combine that with `sequence` to get a `Try<Void>`:

```java
Try.sequence(list.map(runLift(x -> runIoOperation(x, getParameterWhichCouldThrow()))))
    .map(x -> null);
```

In a way maybe this potential new `Try.lift` wouldn't make sense unless combined with `sequence`.. At least in this use case.

So I'm wondering whether I'm doing it wrong or whether it would actually be worth including such a `Try.lift` in javaslang?

**Comment by valery1707** [comment]
Look into #1381: you can use it like `list.map(CheckedFunction1.of(x -> runIoOperation(x, getParameterWhichCouldThrow())).trusted())`, or `recover` at needed steps

**Comment by danieldietrich** [comment]
Hi @emmanueltouzery, thank you for your suggestion.

I think the idea of @valery1707 is applicable to your use-case. With the addition of `CheckedFunction.liftTry` methods (see [this comment](https://github.com/javaslang/javaslang/issues/1381#issuecomment-226347471)) we have all we need.

Adding a `Try.lift` that makes use of `sequence` would be too special.

If you agree we can close this issue.

**Comment by emmanueltouzery** [comment]
Of course! I think `CheckedFunction.liftTry` is exactly what I suggested, so i'm a happy camper =D
