### ISSUE TITLE
Add CheckedFunction_#recover(Function_)

### ISSUE THREAD

**Issue by valery1707** [javaslang/javaslang#1381]
Sometimes I want to use trusted checked functions in work, and leave behind all exception handling.
Something like
```java
public class DigestTest {
	public static String digest(String algorithm, String value) throws NoSuchAlgorithmException {
		MessageDigest md = MessageDigest.getInstance(algorithm);
		md.update(value.getBytes(StandardCharsets.UTF_8));
		return toHexString(md.digest());
	}

	public static CheckedFunction2<String, String, String> digest = DigestTest::digest;
	
	public static Function<String, String> md5 = digest.apply("MD5").rethrow();

	@Test
	public void testMd5() throws Exception {
		assertThat(md5.apply("123")).isNotNull().isEqualToIgnoringCase("202cb962ac59075b964b07152d234b70");
	}
}
```

In some cases we know that function can not throw Exception, or we can not recover if it will be really throwed.

But this case can have more general purpose: recover from error.
This can be implemented somethis like this:
```java
    default Function1<T1, R> recover(Function2<? super T1, ? super Throwable, ? extends R> recover) {
        return (t1) -> {
            try {
                return this.apply(t1);
            } catch (Throwable throwable) {
                return recover.apply(t1, throwable);
            }
        };
    }

	default <X extends RuntimeException> Function1<T1, R> rethrow(Function<Throwable, X> exceptionMapper) {
		return recover(((t1, throwable) -> {
			throw exceptionMapper.apply(throwable);
		}));
	}

	default Function1<T1, R> trusted() {
		return rethrow(IllegalStateException::new);
	}

```

Compare API 

1. `CheckedFunction0<T1, R> func`:
  * `recover`
    * NEW: `func.recover(() -> new R())`
    * OLD: `CheckedFunction0.lift(func).andThen(o -> o.getOrElse(() -> new R()))`
  * `trusted`
    * NEW: `func.rethrow(ex -> new IllegalArgumentException("Message", ex))`
    * OLD: exception lost after `lift`
1. `CheckedFunction1<T1, R> func`:
  * `recover`
    * NEW: `func.recover(t1 -> new R(t1))`
    * OLD: arguments lost after `lift`
  * `trusted`
    * NEW: `func.rethrow(ex -> new IllegalArgumentException("Message", ex))`
    * OLD: exception lost after `lift`
1. `CheckedFunction2<T1, T2, R> func`:
  * `recover`
    * NEW: `func.recover((t1, t2) -> new R(t1, t2))`
    * OLD: arguments lost after `lift`
  * `trusted`
    * NEW: `func.rethrow(ex -> new IllegalArgumentException("Message", ex))`
    * OLD: exception lost after `lift`

**Comment by danieldietrich** [comment]
Hi @valery1707, I like that idea!

I have the following modifications of your initial idea in mind:

For N in {0, ..., 8}

```java
* `CheckedFunctionN.recover(Function2<TupleN<T1, ..., TN>, ? super Throwable, ? extends R>)` - returns a `FunctionN`
* `CheckedFunctionN.unchecked(Function<? super Throwable, ? extends RuntimeException>)` - returns a `FunctionN` that throws a `? extends RuntimeException`
* `CheckedFunctionN.unchecked()` - returns a `FunctionN` that throws an `IllegalStateException`
```

Note: `recover` needs to take a Tuple because 8 params + a Throwable arg exceeds max function arity (8).

Additionally we could provide static methods similar to `lift` (informal):

* `FunctionN<..., R>.liftTry(FunctionN<..., R>)` that returns a `FunctionN<..., Try<R>>`
* `CheckedFunctionN<..., R>.liftTry(CheckedFunctionN<..., R>)` that returns a `FunctionN<..., Try<R>>`

The code generator has to be changed because the `CheckedFunction`s are generated code. I can do that if you don't mind.

**Comment by valery1707** [comment]
@danieldietrich, I known Scala and want create PR, if you do not mind

**Comment by valery1707** [comment]
Implementation is ready, it remains to add some Javadoc and tests

**Comment by valery1707** [comment]
Remains only tests

**Comment by valery1707** [comment]
@danieldietrich, PR #1385 created
