### ISSUE TITLE
Either : missing method getRight

### ISSUE THREAD

**Issue by Pyeroh** [javaslang/javaslang#1384]
As the title says, there's a `getLeft`, but no `getRight` method in Either class, I need to use `right().get()`

**Comment by mvh77** [comment]
Either is right biased, so get() actually returns the value if it's a Right.

**Comment by Pyeroh** [comment]
Oh, thanks, i didn't noticed that.
Should I let this issue opened in case it needs modifications in the class, or close it ?

**Comment by mvh77** [comment]
Please close, this is the way it works everywhere (Option, Try, etc...).

**Comment by danieldietrich** [comment]
Yep, can be closed.
