### ISSUE TITLE
Class::isAssignableFrom native java method can't be implemented in GWT

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1389]
Task: Search for an alternate Pattern Matching implementation (while preserving the API).

**Comment by paplorinc** [comment]
Not sure if I got it right, but `instanceOf` might be an alternative: 
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/instanceof

**Comment by danieldietrich** [comment]
Maybe it is possible in JavaScript to use instanceof (see http://stackoverflow.com/questions/2943805/javascript-instanceof-typeof-in-gwt-jsni). But GWT has to translate the client side Java `instanceof` to such JavaScript. I don't know if this happens.

**Comment by ruslansennov** [comment]
We can generate another `API` class, especially for GWT module. This class will override old `API` and will implement problem methods and classes something like this:
```java
public static abstract class Pattern2<T, T1, T2> 
    implements Pattern<T, Tuple2<T1, T2>> {

    public static <T, T1 extends U1, U1, T2 extends U2, U2> Pattern2<T, T1, T2> 
    of(Class<? super T> type, Pattern<T1, ?> p1, Pattern<T2, ?> p2, Function<T, Tuple2<U1, U2>> unapply) {

        return new Pattern2<T, T1, T2>() {
                    @Override
                    public Option<Tuple2<T1, T2>> apply(T obj) {
                        try {
                            final Tuple2<U1, U2> unapplied = unapply.apply(obj);
                            return unapplied.apply((u1, u2) ->
                                    ((Pattern<U1, ?>) p1).apply(u1).flatMap(_1 ->
                                    ((Pattern<U2, ?>) p2).apply(u2).map(_2 -> (Tuple2<T1, T2>) unapplied)
                            ));
                        } catch (Throwable t) {
                            return Option.none();
                        }
                    }
        };
    }

    private Pattern2() {
    }
}
```
Use `try {} catch () {}` block is not so good, but it may work and I have no other idea.

**Comment by danieldietrich** [comment]
Mmhh, I don't know if it's worth the effort. Maybe it is better to just not provide the functionality.

**Comment by danieldietrich** [comment]
Issue moved to javaslang/javaslang-gwt#3
