### ISSUE TITLE
Add new Map methods

### ISSUE THREAD

**Issue by valery1707** [javaslang/javaslang#1401]
What you think about this methods in `Map` interface?
* `filter(BiPredicate<K, V>)`
* `filterKeys(Predicate<K>)`
* `filterValues(Predicate<V>)`
* `removeAll(BiPredicate<K, V>)`
* `removeKeys(Predicate<K>)` / `removeAllKeys(Predicate<K>)`
* `removeValues(Predicate<V>)` / `removeAllValues(Predicate<V>)`

**Comment by danieldietrich** [comment]
Thank you, this would be a great addition.

* we take the names `removeKeys` and `removeValues` instead of `removeAllKeys` and `removeAllValues`
* all (Bi)Predicate generic args are `? super`

**Comment by valery1707** [comment]
Good, I start implementing.
Yes, `<K>` and `<V>` was only example it will be `<? super K>` and `<? super V>`

**Comment by valery1707** [comment]
@danieldietrich, implemented in #1404

**Comment by danieldietrich** [comment]
@valery1707 `Multimap` has its own interface - it is not a `Map`. We need to add these methods in a separate PR (in addition to current #1404).

**Comment by danieldietrich** [comment]
Re-openend because of Multimap...
