### ISSUE TITLE
Add case classes/objects

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1403]
Project Halva has an interesting approach using an annotation processor: https://github.com/Randgalt/halva/blob/master/halva/src/main/java/io/soabase/halva/caseclass/README.md

I could imagine to also implement this feature using an annotation processor. We already have the module `javaslang-match` for processing pattern matching annotations. It contains two annotations `Patterns` and `Unapply`. These are needed to give a hint how to deconstruct arbitrary Java classes.

Case classes (and case objects) should also be pattern-matchable.

Does it make sense to put this feature in its own module `javaslang-case`?

**Comment by emmanueltouzery** [comment]
surely you're aware of http://immutables.github.io/ ? Maybe it's a little overreaching for javaslang, although `javaslang-match` support for such value objects would be great.

I've also had this issue described [on the immutables website](http://immutables.github.io/getstarted.html):

> Note: There's known issue with the interaction between the incremental compilation feature of javac and annotation processing. Build tools like Maven are also affected by this bug. Typically, commands such as mvn clean compile will resolve any such problems by a forcing full build. Disabling incremental compilation is also an option:
>
>     
>     <useIncrementalCompilation>false</useIncrementalCompilation>

Sadly for me this pom.xml setting did not prevent the issue in a test project, and I had to use `clean`. I plan to give it another try when I get 5 minutes.

**Comment by nbardiuk** [comment]
Just for reference regarding immutables

there is a request to add support of javaslang https://github.com/immutables/immutables/issues/383

and there is some discussion to add ADTs https://github.com/immutables/immutables/issues/47

**Comment by danieldietrich** [comment]
Out of scope for Javaslang. There are projects that do that (see above). Project Valhalla brings value types to Java.
