### ISSUE TITLE
Add Tuple2#swap

### ISSUE THREAD

**Issue by valery1707** [javaslang/javaslang#1406]
What you think about method `Tuple2#swap`?
Scala Tuple2 [have this method](http://www.scala-lang.org/api/current/#scala.Tuple2).

**Comment by paplorinc** [comment]
What should happen for `Tuple3-8`?

**Comment by valery1707** [comment]
@paplorinc, nothing I suppose.
Same as `Function1#identity` and `Function1#compose`.

**Comment by emmanueltouzery** [comment]
maybe it should just be present on `Tuple2`. Not present at all on 3+

**Comment by valery1707** [comment]
I propose this method only for `Tuple2`

**Comment by danieldietrich** [comment]
`swap` makes sense on `Tuple2`.

I currently see no use-case for rotating, so let's leave it away for Tuple3+ for now.
