### ISSUE TITLE
Optimize collections via `ObjectLayout`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1408]
A [recent video](https://www.youtube.com/watch?v=iKC2yoTwuvk) by Simon Ritter brought to my attention the [ObjectLayout](https://github.com/ObjectLayout/ObjectLayout) library.

It's meant to eliminate intermediate references in objects, i.e. continuous-memory-layout structs, instead of Objects with references - to speed up access by taking advantage of prefetching.
We could experiment with it - its especially well suited for immutability.

@danieldietrich, @ruslansennov, @eduardmanas, @zsolt-donca, could we take advantage of this in any part of the library?

**Comment by danieldietrich** [comment]
Thank you, I've watched the talk - it is interesting but I currently have no clue how to adapt the ideas and what impact to our library it would have.

Maybe we could experiment with, say Array, on a branch?

**Comment by paplorinc** [comment]
I think `Array` is already laid out correctly ...

**Comment by danieldietrich** [comment]
Ok. What about the bit-mapped vector trie?

**Comment by paplorinc** [comment]
I don't know, @ruslansennov?

**Comment by ruslansennov** [comment]
@paplorinc thank you for video.
ObjectLayout library uses java reflection and can't working without it, am I right?
Then I have these thoughts:
1. Our arrays in HAMT and in upcoming (?) bit-mapped vector trie are very small (size=32) and it is unclear that we will have some benefit from using this library. 
2. On other side, reflection is very slow, therefore creating inner arrays will be also very slow. This should be investigated, but I believe there will be significantly decreasing of update performance
3. It is not main goal, of course, but we plan to make Javaslang GWT-compatible. ObjectLayout library is GWT incompatible.

**Comment by paplorinc** [comment]
> we plan to make Javaslang GWT-compatible

would something like this help? https://github.com/WeTheInternet/xapi/tree/master/gwt/gwt-reflect

> On other side, reflection is very slow

It can be slow, I agree, but often it's jitted and has the exact same speed (and assembly). Let's profile it.

> it is unclear that we will have some benefit from using this library

Hence my question, it's unclear to me too :)

**Comment by danieldietrich** [comment]
To me it is not clear what to do. The current idea is 'there is a cool new feature which we do not understand but it might make things (a little/much more?) faster'. In order to decide how to further process we need to sketch a clear picture

* _how_ the collections should be modified (-> what is the impact to the current code-base?)
* _which_ collections can be modified (maybe the idea is not applicable to all collections)

If the _what_ is clear, we can start doing a spike and measure.

If the results are significantly better, then we can decide, if we want to change to code base, depending on the impact to the code.

**Comment by danieldietrich** [comment]
@paplorinc Can we close this for now? If we have suggestion of concrete optimizations we can create additional issues / PRs.

My target is to reduce the ever-growing issues towards zero inbox :)

**Comment by paplorinc** [comment]
Sure, it was rather a question :)

**Comment by danieldietrich** [comment]
Thx!
