### ISSUE TITLE
Misleading usages of Runnable interface

### ISSUE THREAD

**Issue by pivovarit** [javaslang/javaslang#1412]
Hi!

My colleagues pointed out to me that usages of Java's Runnable in a non-thread contexts is misleading.
They assumed that using Runnable implies something to be executed by a thread.

Their assumption was actually correct. Let's have a look at Runnable's JavaDoc:

> The Runnable interface should be implemented by any class whose instances are intended to be executed by a thread.

**Comment by danieldietrich** [comment]
Brian Goetz [answered](http://stackoverflow.com/questions/27973294/function-with-no-args-and-no-return-type-void-in-java-8?lq=1#comment44339647_27973294) to the StackOverflow questions:

**Person1:** "What's wrong with Runnable?"

**Person2:** "I'm sure that the existence of Runnable is why the Java designers felt they didn't need to add another functional interface."

**Brian Goetz:** "@Person2: Exactly so."

A `Runnable` is a functional iterface that does not take parameters and returns nothing. So let's also keep things simple and reuse existing concepts if possible. Bonus points: increased interoperability with existing APIs.

**Comment by pivovarit** [comment]
I am not really nazi about this one. Works for me :) thanks

**Comment by danieldietrich** [comment]
> I am not really nazi about this one.

haha, phew :sweat_smile:
