### ISSUE TITLE
can we revert to benchmark profile?

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1413]
Benchmark profile was deleted in #1398
Now maven goal `test` runs about 12 min.
I would revert this deletion and create special profile again.

cc @paplorinc

**Comment by danieldietrich** [comment]
The benchmarks should not run on a regular basis in our CI environments because subsequent benchmarks are not comparable (CI has no fixed hardware).

We once decided to run them manually. We need a distinct maven profile!!

**Comment by paplorinc** [comment]
This was highlighted in the commit message you both reviewed: assertions are checked for JMH benchmarks, no performance is measured, just correctness.

**Comment by paplorinc** [comment]
It's only ~3 minutes overhead (will be less after an optimization I created yesterday).
Please don't revert this too...

**Comment by danieldietrich** [comment]
We will revert nothing! It is just the `<module>javaslang-benchmark</module>` in the parent pom and the missing benchmark profile we discuss. We need fast builds, let's not execute the benchmark assertions on every CI run.

**Comment by paplorinc** [comment]
Let's not execute the rest of the tests either, we will have even faster builds...

**Comment by paplorinc** [comment]
I've found several bugs after I introduced the assertions (mentioned in the code review also). 
Benchmarks aren't tests (they don't validate behavior automatically), they do need tests.

**Comment by danieldietrich** [comment]
Yes, I've looked again at the assertions, they make sense.

90% of the assertions are related to 3rd party libraries (collections are constructed as excpected etc). If we have assertions that check the behavior of Javaslang, e.g. the head is the first element etc., this test should be part of the Javaslang unit tests. There is no reason to run the benchmark assertions on a CI build triggered by a Javaslang source code change.

I'm still convinced that we should create a separate profile for the benchmarks.

@paplorinc could you do that please?

**Comment by paplorinc** [comment]
> this test should be part of the Javaslang unit tests

Again, I'm testing with the asserts whether I'm bechmarking what I think I am (e.g. `cons` in `Clojure` `Vector` adds to the front (as in List), or to the end? Am I accidentally comparing a `prepend` to an `append`?). It would be naive to think this is any different from why we're testing production code -- i.e. for documentation purposes and to make everything modifiable.

If we don't run all tests for every build, they are useless.

If @ruslansennov feels that 3 extra minutes are unacceptable, I won't block him from separating it into another `Travis` job that is run in parallel with the unit tests.

**Comment by ruslansennov** [comment]
I think that the performance test should not be run on Travis service because it is completely useless. As Daniel said 

> The benchmarks should not run on a regular basis in our CI environments because subsequent benchmarks are not comparable (CI has no fixed hardware).

But on my home computer it runs 4:17 min (include 2:42 for benchmark), it is OK for me.

**Comment by ruslansennov** [comment]
It makes sense to compare Javaslang performance with other libraries. It can be done manually with `-Pbenchmark` option. On Travis server it just add some lines to log with no reaction on results

**Comment by paplorinc** [comment]
> should not be run on Travis service because it is completely useless

Please read my comments, that's why I'm writing them...

> on my home computer it runs 4:17 min

I will push a commit shortly that speeds things up - by caching the base `setup` and by removing `pcollections` and `fjava` results, since they're always slower (often by orders of magnitude).

**Comment by paplorinc** [comment]
Fixed in: https://github.com/javaslang/javaslang/pull/1414, please review.

**Comment by ruslansennov** [comment]
Actually now benchmarks does **nothing**, just says us something about memory consumption without any results that can change CI lifecycle. I would like to return a special profile
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Javaslang Parent ................................... SUCCESS [  1.314 s]
[INFO] Javaslang Match .................................... SUCCESS [  3.305 s]
[INFO] Javaslang .......................................... SUCCESS [02:46 min]
[INFO] Javaslang Benchmark ................................ SUCCESS [04:35 min]
[INFO] Javaslang Pure ..................................... SUCCESS [ 11.372 s]
[INFO] Javaslang Test ..................................... SUCCESS [ 27.041 s]
```

**Comment by danieldietrich** [comment]
Yes, I would love to see benchmarks running when running the `benchmark` maven profile!

**Comment by paplorinc** [comment]
> Actually now benchmarks does nothing

Currently the benchmarks run during the normal build phase check their consistency (and display memory usage info), i.e. a test phase for the correctness of the benchmarks, not for their speed.

> I would like to return a special profile

Let me see what I can do :)

@danieldietrich, congrats for the new profile picture, now I can finally identify you if you walk past me on the street ;)

**Comment by danieldietrich** [comment]
@paplorinc thank you. I add a new one roughly every year :)

**Comment by danieldietrich** [comment]
To test the assertions during unit-tests, we need only very short-running tests. I think we do not necessarily need memory-usage when unit-testing or do we try to detect memory leaks? I'm not sure if we would find such with the memory usage check.

Additionally we need one Maven profile for benchmarks. Those runs include the long-runners and memory usage checks.

**Comment by danieldietrich** [comment]
Parallelizing the javaslang-benchmarks/tests does not work. JMH seems to need exclusive JVM control:

```diff
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${maven.surefire.version}</version>
    <configuration>
+        <parallel>all</parallel>
+        <useUnlimitedThreads>true</useUnlimitedThreads>
        <includes>
            <include>**/*Benchmark.java</include>
        </includes>
    </configuration>
</plugin>
```

Output:

```bash
java.lang.RuntimeException: org.openjdk.jmh.runner.RunnerException: ERROR: Unable to acquire the JMH lock (/var/folders/7d/_cj3nvt94hj31jzk4hs30zwm0000gp/T//jmh.lock): already taken by another JMH instance, exiting. Use -Djmh.ignoreLock=true to forcefully continue.
```

**Comment by paplorinc** [comment]
could we disable it for that one module? Maybe put the benchmark assertions to a different build on a different Travis?

**Comment by danieldietrich** [comment]
Yes, I'm working on it.

**Comment by danieldietrich** [comment]
Does anyone use `mvn test -Pbenchmark -pl javaslang` to run benchmarks (as described in the parent pom)?

It does not work on my machine. I get the following error:

```bash
[INFO] --- exec-maven-plugin:1.5.0:exec (default) @ javaslang ---
Error: Could not find or load main class javaslang.JmhRunner
[ERROR] Command execution failed.
```

**Comment by paplorinc** [comment]
hmm, didn't we update that?
(note: if you update the description, feel free to update the `JMH` version also to `1.17`)

**Comment by danieldietrich** [comment]
will do

**Comment by danieldietrich** [comment]
**Note:** The benchmark assertions currently do not run. We will run them in a separate CI build.
