### ISSUE TITLE
Unify collection indexing: `int` or `long`?

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1417]
If we want to support very big collections (i.e. `BitSet`, `Vector` or `List` could reasonably support `> 2 billion` elements), we should change all `index` related operations to `long`s instead of `int`s, e.g.:
* `get(int index)`
* `int length()`
* `update(int index, T element)`
* `insert(int index, T element)`
* `removeAt(int index)`
* `indexOf(T element, int from)`
* …

If we're not planning on doing that, than we should unify all index related types to integers instead:
* `grouped(long size)`
* `drop(long n)` & `dropRight(long n)`
* `take(long n)` & `takeRight(long n)`
* `splitAt(long n)`
* `slice(long beginIndex, long endIndex)` & `sliding(long size, long step)`
* …

I don't see the advantage of keeping both versions.

ps. I can't even create a 1 billion element `Vector` on my laptop, we should only support it, if we can test it also :/

**Comment by paplorinc** [comment]
@danieldietrich, @ruslansennov, @eduardmanas, @zsolt-donca, opinions?

**Comment by ruslansennov** [comment]
also see #1024

**Comment by paplorinc** [comment]
Thanks, we should finish the task and apply it to the whole codebase consistently, as currently the `long` indices just cast to `int`s (lose-lose situation).

**Comment by danieldietrich** [comment]
> ps. I can't even create a 1 billion element Vector on my laptop, we should only support it, if we can test it also :/

Yes, you are aright. The trigger was the `java.util.stream.Stream`. It has `long` indices, e.g. [`#skip(long)`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#skip-long-).

However, it is only of interest when processing long-running Streams of data I think. When in doubt, we should do it like Scala's `Stream` and use `int`, see [`#drop(Int)`](http://www.scala-lang.org/api/2.11.8/#scala.collection.immutable.Stream).

Let's use `int`, if you are ok with that solution.
