### ISSUE TITLE
Behaviour of range methods when start > end

### ISSUE THREAD

**Issue by ashrko619** [javaslang/javaslang#1425]
```List.range(100,1)``` returns an empty List. It would be better if we either

-  Throw an exception (or)
-  Return a list in reverse order.

**Comment by danieldietrich** [comment]
Thank you for your suggestion. We align to Scala's `Range`, which works as follows:

```scala
scala> 0 until 10 // same as Range(0, 10)
res0: scala.collection.immutable.Range = Range(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

scala> 10 until 0 // same as Range(10, 0)
res1: scala.collection.immutable.Range = Range()

scala> 10 until 0 by -1 // same as Range(10, 0, -1)
res2: scala.collection.immutable.Range = Range(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)
```

In Javaslang it looks like this:

```java
// = List(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
List.range(0, 10);

// = List()
List.range(10, 0);

// = List(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)
List.rangeBy(10, 0, -1);
```

Changing the current `range` implementation would break semantics of existing source code. Also it would confuse developers (including me) to have different semantics than in other programming languages. So let's keep the currenty behavior and please use `rangeBy`. I will close this ticket.

**Note:** Throwing exceptions is (in general) no viable solution for Javaslang. Exceptions are concidered evil. Try to work with defined values whenever possible.
