### ISSUE TITLE
Simple methods fo convert Value into LinkedHasMap/TreeMap/LinkedHashSet/TreeSet

### ISSUE THREAD

**Issue by valery1707** [javaslang/javaslang#1434]
Now I can convert any `Value` into `HashMap` and `HashSet` only.
But sometimes I want save key order while convert `Iterable` into `Map`.

Current code:
```java
LinkedHashMap.ofEntries(stream.filter(...).map(...).sortBy(...).map(o -> Tuple.of(o.getKey(), o)))
```

Supposed code:
```java
stream.filter(...).map(...).sortBy(...).toLinkedMap(o -> Tuple.of(o.getKey(), o))
```

Supposed methods in `Value`:
* `toLinkedMap(Function<...>)`
* `toTreeMap(Function<...>)`
* `toTreeMap(Comparator<...>, Function<...>)`
* `toLinkedSet(Function<...>)`
* `toTreeSet(Function<...>)`
* `toTreeSet(Comparator<...>, Function<...>)`

**Comment by valery1707** [comment]
I can implement.

**Comment by danieldietrich** [comment]
Very nice, please implement it as you suggested.
