### ISSUE TITLE
missing method in Map class

### ISSUE THREAD

**Issue by tfij** [javaslang/javaslang#1439]
Map class has method map(BiFunction<? super K,? super V,Tuple2<K2,V2>> mapper) but doesn't have filter(BiFunction<? super K,? super V, Boolean> predicate) which could be very useful.
Maybe you can add mapValue method also, it is common case when we would like map only value of map and not change key (or mapKey when we don't change value).

**Comment by valery1707** [comment]
In release `2.1.0` `Map` will have meny new functions.
Please check 
1. #1401 
    * `filter(BiPredicate<? super K, ? super V>)`
    * `filterKeys(Predicate<? super K>)`
    * `filterValues(Predicate<? super V>)`
    * `removeAll(BiPredicate<? super K, ? super V>)`
    * `removeKeys(Predicate<? super K>)`
    * `removeValues(Predicate<? super V>)`
1. #1379
    * `mapKeys(Function<? super K, ? extends K2>)`
    * `mapKeys(Function<? super K, ? extends K2>, BiFunction<? super V, ? super V, ? extends V>`)

[`Map#mapValues()`](https://github.com/javaslang/javaslang/blob/master/javaslang/src/main/java/javaslang/collection/Map.java#L183) already exists.

**Comment by tfij** [comment]
awesome! this is what I expect :)
