### ISSUE TITLE
suggestion: add benchmarks for common java idioms against javaslang

### ISSUE THREAD

**Issue by mping** [javaslang/javaslang#1441]
The user guide has alot of suggestions: http://www.javaslang.io/javaslang-docs/#_usage_guide

I am suggesting a benchmark against equivalent java idioms (ex: pattern matching vs ifs) to see the performance penalty (if any) when using common functional idioms.

**Comment by danieldietrich** [comment]
Yes, we could also measure classical `for`-loops vs. Javaslang's `For` comprehension.

@mping Are you a volunteer to do such a benchmark? :-)

**Comment by mping** [comment]
@danieldietrich I'm gonna try and find some time, will post PR for review and comments.

**Comment by danieldietrich** [comment]
great, thank you

**Comment by mping** [comment]
@danieldietrich let me know how is it looking in #1456

**Comment by danieldietrich** [comment]
Thank you - I'm on it but it will take some time... my vacation is near and I have to do some stuff...

**Comment by danieldietrich** [comment]
We merged the PR. Benchmarks are an ongoing effort, this issue can be closed.

**Comment by mping** [comment]
Thanks Daniel, I saw that @paplorinc updated the code.

**Comment by danieldietrich** [comment]
@mping Thank you for adding these Benchmarks!

**Comment by paplorinc** [comment]
@mping, yes, some tweaking was necessary, otherwise the results would have been misleading.
I hope you don't mind.

**Comment by mping** [comment]
@paplorinc of course not, I'm glad you did it so I can learn. I think the `For` benchmark gets most of the penalty because of collection, but I'm kinda busy to investigate right now :). I'm glad you guys are constantly working on javaslang.
