### ISSUE TITLE
Converter Value to Map Java8-style

### ISSUE THREAD

**Issue by valery1707** [javaslang/javaslang#1445]
Current Value have `toMap(Function<? super T, ? extends Tuple2<? extends K, ? extends V>>)`, but sometimes I want to use method reference in method `toMap(Function<? super T, ? extends K> keyMapper, Function<? super T, ? extends V> valueMapper)`.
Before:
```java
Stream.of(items).toMap(i -> Tuple.of(i.getCode(), i.getWeight()))
```
After:
```java
Stream.of(items).toMap(Item::getCode, Item::getWeight)
```

I suggest add this `alias` with two functions to all methods converting `Value` to `Map`.

 If this methods is applicable to project rules, then I can implement it.

**Comment by danieldietrich** [comment]
Sounds good! Please do it.

**Comment by valery1707** [comment]
After #1434
