### ISSUE TITLE
Make `Javaslang` Java 9 compatible

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1465]
Related to https://github.com/javaslang/javaslang/issues/1339.

Steps:
- install `JDK 9` from e.g. https://jdk9.java.net/download
- add it to `Idea`
- change the project dependency to it
- try compiling it from `Idea`
- watch the compiler crash with `StackOverflowError` (maybe we should file a bug report for it)

The problems are mainly around `::compareTo`-like structures in `TreeMap` and `TreeSet`.
And with `Maven` in the `Scala` plugin for the generator.

**Comment by danieldietrich** [comment]
Does it compile with Java 9 and Maven on the command line (without IntelliJ IDEA)?

If it is an IntelliJ IDEA related problem we should file a bug.

**Comment by paplorinc** [comment]
It seems like a Java compiler bug again

**Comment by paplorinc** [comment]
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8164080

**Comment by danieldietrich** [comment]
I've created a bug report for the `T::compareTo` bug, internal review ID : 9044933.

See also [this Gist](https://gist.github.com/danieldietrich/9d91d3602a3f6b78cbea96326db8db82).
