### ISSUE TITLE
Multimap.replace() semantics are misleading/broken

### ISSUE THREAD

**Issue by docent** [javaslang/javaslang#1474]
I would expect that `multimap.replace(Tuple.of(k1, v1), Tuple.of(k1, v2))` should replace just one pair (k1, v) with (k1, v2). Instead an entire multimap key k1 is removed (including other values under k1) and the pair (k1, v2) is added. See the following example:
```java
Multimap<String, Integer> mm1 = HashMultimap.withSet().of("a", 1, "a", 2)
    .replace(Tuple.of("a", 2), Tuple.of("a", 3));
```
Expected contents of mm1: `("a": [1, 3])`
Actual contents of mm2: `("a", [3])`

The reason is the `replace()` code in Multimap:
```java
return (M) (containsKey(currentElement._1) ? remove(currentElement._1).put(newElement) : this);
```
Shouldn't that be:
```java
        return (M) (containsKey(currentElement._1) ? remove(currentElement._1, currentElement._2).put(newElement) : this);
```

**Comment by danieldietrich** [comment]
Thanks for reporting. I think you are right!
