### ISSUE TITLE
Revise `? extends Tuple*` declarations in receiver position

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1483]
Some methods take function with generic arguments of the form

```java
? extends Tuple
```

In general it makes no sense to widen the Tuple type because Tuple is final.

We should remove `? extends` in such cases (see MultiMap types).

**Comment by valery1707** [comment]
Duplicate #1241 ?

**Comment by danieldietrich** [comment]
Yep, will close this. Thx!
