### ISSUE TITLE
Add `Seq.update(index, element)`

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1490]
We need to replace values at a specific index. Interesting that this method is still missing.

Regarding the name please read [this](https://github.com/javaslang/javaslang/pull/1481/files#r74702381).

**Comment by valery1707** [comment]
What about [`javaslang.collection.Seq#update(index, element)`](https://github.com/javaslang/javaslang/blob/master/javaslang/src/main/java/javaslang/collection/Seq.java#L966)?

**Comment by danieldietrich** [comment]
Yes, better.

```java
// mutable/immutable get
val elem = seq[index];

// mutable set (immutable operation not possible this way)
seq[index] = elem;

// immutable update
var seq = seq.update(index, elem);
```

**Comment by danieldietrich** [comment]
You are right - it is already there o_O

**Comment by danieldietrich** [comment]
The names drive me crazy. We have `grouped` and `sorted` like in Scala, but `update` and `reverse`. Also `replace` instead of `replaced`, `prepend` instead of `prepended` etc. However, we will keep it as-is for now, `sorted` and `grouped` will be the only `xxx-ed` versions.
