### ISSUE TITLE
Make (final) classes explicitly Serializable

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1506]
This makes classes more robust regarding changes of super-interfaces.

**Comment by AlparSzabados** [comment]
Hi @danieldietrich,

Should only `final` classes implement `Serializable` explicitly, or every class that has a `serialVersionUID`?
e.g.: `(Checked)Function0-8`, `MatchError`, `AbstractMap`, `Queue`, `AbstractsQueue`, `Seq`...

Thanks!

**Comment by danieldietrich** [comment]
Hi @AlparSzabados, thank you for asking. I've re-read the Java API (Serializable, Class) and googled a bit. I cannot find a clear advice how Serializable is used throughout a type hierarchy. It boils down to:

1. Let an interface implement it to make it clear as part of the contract that implementations are Serializable (that's how we do it now)
2. See serializability as implementation detail because we cannot enforce/to be sure that implementations will _really_ implement Serializable. (however, I think it is a marker interface that does not need to be implemented)
3. everything in between 1. and 2. (like this issue)

Thinking again about it I think we should stay with 1. We do not need to be what I called 'refactoring-safe' because Serializable is part of the contract of the super-types.

Let every type that has a serialVersionUID implement Serializable seems unnecessary for me. Keeping things simple means leaving things away without changing functionality.

I will close this issue.

@AlparSzabados thanks again for asking!
