### ISSUE TITLE
Unify thrown exceptions

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1523]
`Stack`'s `pop` throws `NoSuchElementException` if the Stack is empty, while `Traversable`'s `tail` throws `UnsupportedOperationException` in the same case.

Since they're doing very similar things, I think the exceptions should also be unified.

In my opinion the former (`NSEE`) describes the problem better than the latter (`UOE`), as the problem is not with the operation itself, but with the state of the object.
Also, a `NSEE` would be consistent with e.g. http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/Deque.java#Deque.getFirst%28%29

**Comment by danieldietrich** [comment]
I see it different. The tail is not an element, it is a collection of elements. As usual, we align to Scala:

```scala
/** The empty list.
 *
 *  @author  Martin Odersky
 *  @version 1.0, 15/07/2003
 *  @since   2.8
 */
@SerialVersionUID(0 - 8256821097970055419L)
case object Nil extends List[Nothing] {
  override def isEmpty = true
  override def head: Nothing =
    throw new NoSuchElementException("head of empty list")
  override def tail: List[Nothing] =
    throw new UnsupportedOperationException("tail of empty list")
  // Removal of equals method here might lead to an infinite recursion similar to IntMap.equals.
  override def equals(that: Any) = that match {
    case that1: scala.collection.GenSeq[_] => that1.isEmpty
    case _ => false
  }
}
```

Source: [The Scala 2.12.x source code](https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/List.scala#L407-L425)

Therefore I will close this issue.
