### ISSUE TITLE
Extend `Vector` to implement `Queue` and `Stack`, similarly to Java's `ArrayDeque`

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1524]
Since `Vector` has symmetrical `prepend`-`append` and `head`-`last` operations, it's well suited for an `ArrayDeque` alternative.

The only required change is to add a `peekFirst` and `peekLast` operations to the corresponding interfaces -- otherwise `peek` would be ambiguous.
It's how the `Deque` interface does it also: 
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/Deque.java#Deque.peekFirst%28%29

I personally would unify the two interfaces slightly more: Java's [`Deque`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/Deque.java) would be a good place to start.
See also: https://github.com/javaslang/javaslang/issues/1523

A draft PR has been provided for convenience: https://github.com/javaslang/javaslang/pull/1525

**Comment by danieldietrich** [comment]
This would mix up our collections too much and confuse our users.

Our design goal is: choose the right collection for the right job. The collections are designed to do one thing best. There already is a Queue and List as Stack (where a linked list is a stack by definition, therefore Stack is not a Traversable).

We should close this issue.
