### ISSUE TITLE
Document how to run current benchmarks, get reports and add new benchmarks

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1527]
The comment within the parent pom.xml is outdated:

```
Run benchmarks:

* `mvn test -Pbenchmark -pl javaslang`
```

We need to check other docs also for outdated info (javaslang-docs, CONTRIBUTING.md, etc.).

**Comment by mping** [comment]
The benchmark profile was removed, you can run it like this: `mvn test -pl javaslang-benchmark`

**Comment by paplorinc** [comment]
Once all `Vector` related PRs are done, I will extend the existing benchmarks with the things I learned from optimizing `Vector` also, and I can finally write that article abut optimizing `Javaslang` performance :)

**Comment by paplorinc** [comment]
... wow, I forgot what a piece of crap Maven is (and how bad the documentation is) ... After Gradle it's like going back to SVN (though Gradle has its faults also).
After 3 hours I still can't make it work, I need some Maven expert (I just understood why it's called maven ... you have to be an expert [(i.e. maven)](https://www.google.ro/search?q=maven+define) to achieve the simplest things in it...)
See: #1560
