### ISSUE TITLE
Add Map/Multimap.getOrElse(K key, V defaultValue)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1543]
Currently we have only `Option<V> get(K key)`. In order to prevent creation of unnecessary `Option` instances we generally first check `map.contains(key)` and call `get(key)` if a value is present, otherwise we provide a default value. A call `get(key).getOrElse(defaultValue)` creates an additional `Option` instance.

The `contains()`  and `get()` methods both do a HAMT lookup, which is relatively costly because the hash code of the key is computed. We could do better by providing a method

``` java
interface Map<K,V> {
    V getOrElse(K key, V defaultValue);
}
```

Same for Multimap.

See also #1261: Add 'computeIfPresent' / 'computeIfAbsent' to Map

---

When we have this method, the implementations of `Multimap.Builder.ofEntries` needs to be optimized accordingly. Maybe others too.

**Comment by ruslansennov** [comment]
It seems we should return `Tuple2` as result of `computeIfPresent` / `computeIfAbsent` methods. Here is one of possible signature

```java
/**
 * If the specified key is not already associated with a value,
 * attempts to compute its value using the given mapping
 * function and enters it into this map.
 *
 * @param key key whose presence in this map is to be tested
 * @param mappingFunction mapping function
 * @return the {@link Tuple2} of current or modified map and existing or computed value associated with the specified key
 */
Tuple2<Map<K, V>, V> computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction);

/**
 * If the value for the specified key is present, attempts to
 * compute a new mapping given the key and its current mapped value.
 *
 * @param key key whose presence in this map is to be tested
 * @param remappingFunction remapping function
 * @return the {@link Tuple2} of current or modified map and the {@code Some} of the value associated 
 * with the specified key, or {@code None} if none
 */
Tuple2<Map<K, V>, Option<V>> computeIfPresent(K key, BiFunction<? super K, ? super V, ? extends V> remappingFunction);
```

**Comment by danieldietrich** [comment]
This makes sense. Let's swap the generic params of the return type to be consistent to Queue.dequeue():

```java
class Queue<T> {
    Tuple2<T, Queue<T>> dequeue();
}
```

**Comment by danieldietrich** [comment]
This is fixed.

If there is still sth missing regarding Multimap we will implement it with #1551
