### ISSUE TITLE
Add Map.unzip()

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1546]
As convenience method for `map.unzip(Function.identity())`.

**Comment by pivovarit** [comment]
Would unzipSelf() be a proper name for this?

**Comment by danieldietrich** [comment]
Hi @pivovarit,

`unzipSelf` would suggest that there is something like `unzip(another)`. It is always self that is unzipped. `unzipWithIdentity` would be a better name but no benefit over `unzip(identity())`.

The shorter version `unzip()` is similar to `sorted()`. Calling it on an instance should make it clear that the unzip function is applied to that instance. Because Map consists of pairs it is natural that unzip splits these pairs. It is dual to zip, which creates pairs.

Offtopic: Scala itself is not consistent regarding naming of methods. E.g. we have `sorted()` and `updated()` which state that we do not mutate the instance but return a new one. But `Map` has `put` and `Seq` has `reverse()`.

Maybe we will do it consistent in a future version of Javaslang and deprecate the inconsistent API...
