### ISSUE TITLE
Option.when() null confusion

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang#1548]
shell> Option.when(true, () -> null)
    $2 ==> None

That may be what we want (is it?). If it is what we want, maybe we should improve the apidoc, which currently states "Creates Some of suppliers value if condition is true, or None in other case".

**Comment by danieldietrich** [comment]
Hi, thanks for the hint! The apidoc is ok, it was a bug. The current SNAPSHOT is already fixed. I will close this ticket.

(Behavior relates to #1180 and #1197)

**Comment by danieldietrich** [comment]
Fixed here: #1272
