### ISSUE TITLE
Tuple cleanup

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1556]
# To be done before 2.1.0 release

We added static `Tuple*.sequence()` methods. These should be moved to `Tuple` instead.

Minor: We added Tuple*.append() and Tuple*.prepend(). These should be reordered alphabetically within the files.

**Comment by ashrko619** [comment]
@danieldietrich Can I work on this? :)

**Comment by danieldietrich** [comment]
Yes, that would be great! You are familiar with the code generator (Generator.scala), right?

**Comment by ashrko619** [comment]
@danieldietrich Yes, Once I make the changes -  I just need to run the gen code right?

**Comment by ashrko619** [comment]
@danieldietrich How do I run the code in Generator.scala ?

**Comment by emmanueltouzery** [comment]
just build the app IIRC: `mvn install` and it'll regenerate the generated code.

**Comment by ruslansennov** [comment]
`mvn install` also runs tests and benchmarks.
For your purposes `mvn generate-sources` is enough

**Comment by danieldietrich** [comment]
Yes, I also do a `clean`. Choose one of these:

* `mvn clean generate-sources` for fast results
* `mvn clean compile` to see if your generate code does compile
* `mvn clean test` to see if the unit tests still run after applying changes

Before pushing to Github we should also do a

* `mvn javadoc:javadoc` to see, if the doclint complains

**Comment by danieldietrich** [comment]
Fixed with #1559
