### ISSUE TITLE
Change primitive array args to varargs

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1569]
@paplorinc suggested the following:

```java
interface Stream<T> {

    // before: ofAll(int[] array)
    static Stream<Integer> ofAll(int... array) {
        return Stream.ofAll(Iterator.ofAll(array));
    }

    static Stream<Long> ofAll(long... array) {
        return Stream.ofAll(Iterator.ofAll(array));
    }
}
```

The test:

```java
public class Test {{

    // ok
    Stream<Integer> ints = Stream.ofAll();

    // IntelliJ IDEA complains: Required: Stream<Long>, Found: Stream<Integer>
    Stream<Long> longs = Stream.ofAll();

    // does also not work
    Stream<Long> longs = Stream.<Long> ofAll();
}}
```

However, unexpected behavior with varargs can only occur when we have reference types, e.g.

```java
// reference type T
public <T> void foo(T... params) { ... }

int[] arr = {1, 2, 3};

foo(arr); // passes an int[][] array containing a single int[] element
```

See also [this StackOverflow question](http://stackoverflow.com/questions/5405673/java-varags-method-param-list-vs-array).

I see no problem to switch to varargs for primitive types. There is no risk that the array is confused with a single object.

We should apply that change to all Javaslang types that have static factory methods `ofAll(<primitive array>)`.

**Notes:**

* We still need to check if the varargs argument is null.
* The change is considered backward compatible:

```java
public static void foo(String... string_array) { ... }

public static void bar(String[] string_array) { ... }

String[] arr = {"abc", "def", "ghi"};
foo(arr);  // accept
bar(arr);  // accept
foo("abc", "def", "ghi");  // accept
bar("abc", "def", "ghi");  // reject
```

**Comment by paplorinc** [comment]
Duplicate of: https://github.com/javaslang/javaslang/issues/1544

**Comment by danieldietrich** [comment]
@paplorinc thx
