### ISSUE TITLE
Use `null` as internal representation for empty RedBlackTree

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1581]
We need it because we will create a DescendingView on a RedBlackTree for navigable sets and maps. This requires the type hierarchy to be simple (on class for RedBedBlackTree).

See #1319

**Comment by valery1707** [comment]
Is this issue duplicate #1535 ?

**Comment by danieldietrich** [comment]
Yep, good catch. I will close this one as duplicate.

---

Off-topic: No 1 on my wish-list: zero issues inbox :)
I will move the parser-stuff to its own project soon. Also I will defer the reactive streaming topic. For the health of Javaslang core it is best to keep it thin. The collections add already a complexity that fills this module completely.
