### ISSUE TITLE
Add `T[] Value.toJavaArray(T[])`

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1582]
(See #1578)

These are our options:

```java
// unsafe
T[] toJavaArray(Class<? super T> componentType) // one size fits all

vs

// safe
T[] toJavaArray(Class<T> componentType) // variant for non-generic types
T[] toJavaArray(T[] array)
```

I think the first, unsafe variant is no viable solution.

Example:

```java
// before
Value<CharSequence> v = Option.of("");
CharSequence[] s = v.toJavaArray(CharSequence.class);

// after
Value<String> v = Option.of("");
String[] s = v.toJavaArray(CharSequence.class); // will eventually throw at runtime
```

The existing method `toJavaArray(Class<T>)` is still useful for non-generic types,
we do not need to deprecate it.

**Comment by paplorinc** [comment]
> T[] toJavaArray(T[] array)

Because of erasure I don't think it's possible to make this completely type-safe.

> I think the first, unsafe variant is no viable solution.

Doing it the `Java` way would result in the same unsafety 
```java
@SuppressWarnings("unchecked")
Option<Integer>[] options = singletonList(Option.some(1)).toArray(new Option[0]);
System.out.println(options[0].get());
```
i.e you cannot call `toArray` with `new Option<Integer>[0]` either ...

**Comment by danieldietrich** [comment]
@paplorinc you are right - it makes no sense to have `toArray(T[])`. That is the reason I introduced the simpler `toArray(Class<T>)`.

If an application of `toArray(Class<T>)` compiles, it is correct. Therefore this is the best solution we can come up with.

For now, we will not implement the unsafe case, I don't see the urge to do it. We have many other things to do.

**Comment by paplorinc** [comment]
> If an application of toArray(Class<T>) compiles, it is correct.

Unfortunately that's not true either:
```java
Array.of(1).toJavaArray(int.class);
```
errs at run time with:
```
java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
```

I still think the `<? super T>` variant was the best compromise.

**Comment by danieldietrich** [comment]
I'm not sure. Is it possible to fix our variant, e.g. by first checking `type.isPrimitive()` and then decide further how to proceed?

I will play around a bit.

_Safety first._

**Comment by paplorinc** [comment]
> checking type.isPrimitive() and then decide further how to proceed?

and throw a different kind of `RunTimeException`?

> Safety first.

I agree, but I din't think it's possible, because of type erasure, it's inherently unsafe :/

**Comment by danieldietrich** [comment]
See #1585
