### ISSUE TITLE
Be a little more Lazy

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1584]
We have methods that return `Xyz<Seq<...>, ...>`.

These should return a `Stream` instead of other `Seq` implementations in order to avoid unnecessay computations.

**Comment by ashrko619** [comment]
I see some more opportunities where a ```Stream``` can be used instead of other implementations.
Ex : https://github.com/javaslang/javaslang/blob/master/javaslang/src/main/java/javaslang/collection/AbstractsQueue.java#L62
Can I refactor them here or should they go in another PR ? 😄

**Comment by danieldietrich** [comment]
@ashrko619 please let's keep the scope of this PR focused on the methods that return wrapped Seq types.

> I see some more opportunities where a Stream can be used instead of other implementations.

We should discuss these by creating issues first. I would not 'refactor' the example you mentioned. A queue is backed on two lists: rear and front.

It makes most sense to switch to a Stream return type when having costly operations that can be deferred by making them intermediate/lazy. In your example of the Queue (link above) the List is only used to iterate elements. Also making the whole Queue lazy makes not much sense in my opinion because the elements are already known (they are enqueued and dequeued). Lazy evaluation makes most sense when the elements are not yet known.

**Comment by danieldietrich** [comment]
Fixed with #1605
