### ISSUE TITLE
Error in "Javaslang User Guide" in section "3.3.3 Lazy"

### ISSUE THREAD

**Issue by joes** [javaslang/javaslang#1593]
The [Javaslang User Guide](http://www.javaslang.io/javaslang-docs/) states in section "3.3.3 Lazy":

> Since version 2.0.0 you may also create a real lazy value (works only with interfaces):
>
> ```java
> CharSequence chars = Lazy.of(() -> "Yay!", CharSequence.class);
> ```

The above statement does not compile, it should be:

```java
CharSequence chars = Lazy.val(() -> "Yay!", CharSequence.class);
```

**Comment by danieldietrich** [comment]
Fixed, thank you :)

![screen shot 2016-09-30 at 1 48 45 pm](https://cloud.githubusercontent.com/assets/743833/18990802/ac62e550-8714-11e6-8e3d-29cb6081b0da.png)
