### ISSUE TITLE
Add more Map.replace and .replaceAll methods (also for Multimap)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1600]
From the Java 8 API docs:

``` java
// Replaces the entry for the specified key only if it is currently mapped to some value.
Map<K, V> replace(K key, V value)

// Replaces the entry for the specified key only if currently mapped to the specified value.
Map<K, V> replace(K key, V oldValue, V newValue)

// Replaces each entry's value with the result of invoking the given function on that entry until all entries have been processed or the function throws an exception.
Map<K, V> replaceAll(BiFunction<? super K,? super V,? extends V> function)
```

---

**Offtopic:** Interface and implementation popularity of Java mutable collections (presented on JavaOne 2016). It shows that Map is very popular.

![interface-popularity](https://cloud.githubusercontent.com/assets/743833/19022672/e7b852be-88dd-11e6-84dd-da38625c85a8.png)

![implementation-popularity](https://cloud.githubusercontent.com/assets/743833/19022673/eda92f72-88dd-11e6-8657-cf0c0ab7927f.png)

**Comment by benoitheinrich** [comment]
As discussed in gitter, here is an add-on for the requirements.

We would like to have the following function:
```
Map<K, V> replace(K key, Function1<Option<V>, V> f);
```

This way we could do stuff like:
```
Map<K, V> map = ...;
map.replace(key, old -> Match(old).of(
                Case(Some($()), some -> ...), // Here you can add some functional code which modify the value
                Case(None(), () -> ...) // Here you can add some functional code which provide a default value
        ));
```

A basic implementation could be something like that: 
```
    Map<K, V> replace(K key, Function1<Option<V>, V> f) {
        return put(key, get(key)
                .map(v -> f.apply(Option.some(v)))
                .getOrElse(() -> f.apply(Option.none()))
        );
    }
```

Thanks.

**Comment by danieldietrich** [comment]
Regarding the gitter discussion @benoitheinrich mentioned I came to the conclusion that we already have to more general method:

```java
<U extends V> Map<K, V> put(K key, U value, BiFunction<? super V, ? super U, ? extends V> merge);
```

There could be the following variations:

```java
<U extends V> Map<K, V> put(K key, Supplier<U> value, BiFunction<? super V, ? super U, ? extends V> merge);
Map<K, V> put(K key, Supplier<? extends V> value, Function<? super V, ? extends V> merge);
Map<K, V> put(K key, V value, Function<? super V, ? extends V> merge);
```

But adding these variations blows up the API. The existing `put(K, U, BiFunction<V, U, V>)` should be sufficient for now.

**Comment by danieldietrich** [comment]
@mduesterhoeft Great to have you onboard! This issue focuses only on the three additional methods mentioned in the [first comment](https://github.com/javaslang/javaslang/issues/1600#issue-180526237). (The other suggestions are in fact covered already by `put`.)

We have a Map hierarchy and a Multimap hierarchy. The impls of the existing replace* methods delegate to the internal Maps helpers.

Many thanks :)

**Comment by mduesterhoeft** [comment]
@danieldietrich think this could be closed?!

**Comment by danieldietrich** [comment]
@mduesterhoeft That's right - thanks :)
