### ISSUE TITLE
Add API#Unchecked methods that return unchecked Funtions

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1606]
We should add these to `javaslang.API` _after_  pulling in #1500.

**Goal:**

```java
// before
list.map(CheckedFunction1.of(elem -> ...).unchecked())

// after
list.map(Unchecked(elem -> ...))
```

We do this for Function0..8:

```java
<R> Function0<R> Unchecked(CheckedFunction0<R> f) {
    return f.unchecked();
}

<T, R> Function1<T, R> Unchecked(CheckedFunction1<T, R> f) {
    return f.unchecked();
}

...
```

I don't think we need to widen the generic bounds of the function argument here.

**Comment by valery1707** [comment]
PR #1500 has milestone `3.0.0`, but this issue has milestone `2.1.0`. It's incorrect.

**Comment by danieldietrich** [comment]
Yes. We will not change existing methods. So let's target 2.1.0 :)
