### ISSUE TITLE
GWT: Promise & Future support

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1615]
@dharezlak says in Gitter chat:

> I played a little with the Future/Promise pair on the other side of the fence (I mean the browser side). This required a few modifications which were super-sourcing the `ExecutorService` interface and providing a simple implementation for it. Simple use cases worked just fine.

I believe this makes sense.

**Comment by dharezlak** [comment]
@ruslansennov I also had to remove code using `Object#wait()|notify()` as these methods are not available in GWT. Also, some calls do not make sense on the client side such as `Future#get()|isEmpty()` as they use Java's notification mechanisms. One way to deal with this is to use GWT's replace mechanism which could use class implementations throwing exceptions for such cases (http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsDeferred.html#replacement).

**Comment by ruslansennov** [comment]
We can leave `<exclude name="concurrent/**"/>` entry in `Javaslang.gwt.xml`, but implement lightweight version of `Promise` and `Future` Javaslang's classes in GWT super-source folder. If you have played with it, could you try do this?

**Comment by dharezlak** [comment]
I'll try...

**Comment by dharezlak** [comment]
Where can I push the preliminary implementation?
