### ISSUE TITLE
Add Validation.getOrElseGet method

### ISSUE THREAD

**Issue by DanielGronau** [javaslang/javaslang#1618]
Currently, if you want to narrow down a `Validation` object to a single result value, the only way I found was to convert it to an `Either`, and then use `Either.getOrElseGet()`. It would be convenient to provide the same method directly in `Validation`. Alternatively, something like `leftFlatMap()` would work as well.

Note that `Validation.orElse(...).get()` is not sufficient, as you often need to evaluate the error value(s) in order to provide a proper "replacement" object.

**Comment by danieldietrich** [comment]
Makes sense!
(PRs greatly appreciated!)

**Comment by DanielGronau** [comment]
PR: https://github.com/javaslang/javaslang/pull/1619
