### ISSUE TITLE
Add Validation.fromOption method

### ISSUE THREAD

**Issue by DanielGronau** [javaslang/javaslang#1628]
There is already a `Validation.fromEither` method, but in my experience the need to convert from an `Option` arises more frequently. 

Currently, you can use e.g. `someOption.map(Validation::valid).getOrElse(() -> Validation.invalid("errorValue"))` to achieve this conversion, but a dedicated method `Validation.fromOption(someOption, () -> "errorValue")` would be more convenient.

Maybe there could be a `Validation.toOption` method (converting the error case to `Option.None`) analogous to `Validation.toEither`, but I have no strong opinion about this.

**Comment by danieldietrich** [comment]
The `from*` methods do not scale well, several types need them. Maybe we can add the missing `Value.toValidation()` methods, e.g.

```java
interface Value<T> {

    default <E> Validation<E, T> toValidation(E error) {
        return isEmpty() ? Validation.invalid(error) : Validation.valid(get());
    }

    default <E> Validation<E, T> toValidation(Supplier<? extends E> errorSupplier) {
        return isEmpty() ? Validation.invalid(errorSupplier.get()) : Validation.valid(get());
    }

}
```

Then we are able to call

```java
someOption.toValidation("errorValue");

someTry.toValidation(() -> "errorValue");

someFuture.toValidation(() -> "errorValue");

someEither.toValidation(() -> "errorValue");

someList.toValidation(() -> "errorValue");

...
```

 instead of

```java
Validation.fromOption(someOption, "errorValue");

Validation.fromTry(someTry, () -> "errorValue");

...
```

**Comment by danieldietrich** [comment]
@DanielGronau I think this is better:

```java
interface Value<T> {

    default <E> Validation<E, T> toValid(E error) {
        return isEmpty() ? Validation.invalid(error) : Validation.valid(get());
    }

    default <E> Validation<E, T> toValid(Supplier<? extends E> errorSupplier) {
        return isEmpty() ? Validation.invalid(errorSupplier.get()) : Validation.valid(get());
    }

    default <U> Validation<T, U> toInvalid(U value) {
        return isEmpty() ? Validation.invalid(get())) : Validation.valid(value);
    }

    default <U> Validation<T, U> toInvalid(Supplier<? extends U> valueSupplier) {
        return isEmpty() ? Validation.invalid(get())) : Validation.valid(valueSupplier.get());
    }

}
```

**Comment by DanielGronau** [comment]
Yes, this looks fine. BTW, do we need something similar for `Traversable` or so?

**Comment by danieldietrich** [comment]
Traversables are already convertable too all kind of Values vice versa, because Traversable is a Value and inherits all toXxx() conversion methods.

For example this will be possible:

```java
someList.toValid("someError");

someValidation.toList();
```

However, `traversable.toOption()` only considers the first value. Also Value.get() returns only the first value:

```java
List(1, 2, 3).toOption() == Some(1)
List().toOption() == None()

List(1, 2, 3).get() == 1
List().get() throws
```

@DanielGronau Do you still see a TODO for Traversable here?

**Comment by DanielGronau** [comment]
I'm not sure, but I could imagine that it is unexpected for a user that e.g. only the first value of a list is converted to an `Option`. So maybe we could have a second set of methods like `allToOption`, 
`allToValid`etc. on `Traversable`. 

But on the other hand I agree that the API shouldn't be polluted by too much methods.

**Comment by danieldietrich** [comment]
I think having one value is the only way that the Monad laws still hold. I will check that...

Also conversion methods should be symmetric, e.g.

```java
// currently
Some(1).toList() --> List(1)
None().toList() --> List()

// Not possible with Java.
// It could be done *only* if we know that the underlying type is Option<List>
Some(List(1, 2, 3)).toList() --> List(1, 2, 3)
Some(List()).toList() --> List()
None(List()).toList() --> ???
```
