### ISSUE TITLE
Override Value.splitterator() and Traversable.splitterator()

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1635]
With #1622 we added `Value.toParallelStream()`. To get the most out of it, we need to return a splitterator that reflect the characteristics of the underlying Value.

The are these [Splitterator characteristics](https://docs.oracle.com/javase/8/docs/api/java/util/Spliterator.html#field.summary):
- `CONCURRENT`\- Characteristic value signifying that the element source may be safely concurrently modified (allowing additions, replacements, and/or removals) by multiple threads without external synchronization.
- `DISTINCT` - Characteristic value signifying that, for each pair of encountered elements x, y, !x.equals(y).
- `IMMUTABLE` - Characteristic value signifying that the element source cannot be structurally modified; that is, elements cannot be added, replaced, or removed, so such changes cannot occur during traversal.
- `NONNULL` - Characteristic value signifying that the source guarantees that encountered elements will not be null.
- `ORDERED` - Characteristic value signifying that an encounter order is defined for elements. A Collection has an encounter order if the corresponding Collection.iterator() documents an order.
- `SIZED` - Characteristic value signifying that the value returned from estimateSize() prior to traversal or splitting represents a finite size that, in the absence of structural source modification, represents an exact count of the number of elements that would be encountered by a complete traversal.
- `SORTED` - Characteristic value signifying that encounter order follows a defined sort order.
- `SUBSIZED` - Characteristic value signifying that all Spliterators resulting from trySplit() will be both SIZED and SUBSIZED.

We have two cases:

**1) Value is single-valued (Option, Try, Lazy, Future, ...)**

**2) Value is multi-valued (all Traversables ...)**

---

All types can contain `null` (including Option.Some), so no type has the characteristic:
- `NONNULL`

Because we have persistent types, these characteristics apply to both cases:
- ~~`CONCURRENT`~~ conurrent modifications mean mutable in-place modifications here. Javaslang does not allow this by definition because collections are persistent/immutable.
- `IMMUTABLE`

The single-valued types have these characteristics:
- `DISTINCT`
- `SIZED`
- `SUBSIZED`

The multi-valued types have the following characteristics (in addition to the common as described above):
- Array - `SIZED`, `SUBSIZED`
- BitSet - `DISTINCT`, `ORDERED`, `SIZED`, `SORTED`, `SUBSIZED`
- CharSeq - `ORDERED`, `SIZED`, `SUBSIZED`
- HashMap -
  - key/values: `DISTINCT`, `SIZED`, `SUBSIZED`
  - values: `SIZED`, `SUBSIZED`
- HashMultimap -
  - key/values: `DISTINCT`, `SIZED`, `SUBSIZED`
  - values: `SIZED`, `SUBSIZED`
- HashSet - `DISTINCT`, `SIZED`, `SUBSIZED`
- Iterator - (??? none because may be infinite or SIZED/SUBSIZED because when it is infinite program will hang though)
- LinkedHashMap -
  - key/values: `DISTINCT`, `SIZED`, `SUBSIZED`
  - values: `SIZED`, `SUBSIZED`
- LinkedHashMultimap -
  - key/values: `DISTINCT`, `SIZED`, `SUBSIZED`
  - values: `SIZED`, `SUBSIZED`
- LinkedHashSet - `DISTINCT`, `SIZED`, `SUBSIZED`
- List - `SIZED`, `SUBSIZED`
- PriorityQueue - `ORDERED`, `SIZED`, `SORTED`, `SUBSIZED`
- Queue - `SIZED`, `SUBSIZED`
- Stream - (??? none because may be infinite or SIZED/SUBSIZED because when it is infinite program will hang though)
- Tree - `SIZED`, `SUBSIZED`
- TreeMap -
  - key/values: `DISTINCT`, `ORDERED`, `SIZED`, `SORTED`, `SUBSIZED`
  - values: `SIZED`, `SUBSIZED`
- TreeMultimap -
  - key/values: `DISTINCT`, `ORDERED`, `SIZED`, `SORTED`, `SUBSIZED`
  - values: `SIZED`, `SUBSIZED`
- TreeSet - `DISTINCT`, `ORDERED`, `SIZED`, `SORTED`, `SUBSIZED`

---

We just override Traversable.splitterator(). It will gather all characteristics from the new _introspection_ methods that will be implemented by the Traversable implementations listed above:
- `isDistinct()` - which implies DISTINCT. It reflects the characteristics of the Traversable and has nothing to do with the contained elements, e.g. `List(1, 2, 3).isDistinct()` returns `false`.
- `isOrdered()` - which implies ORDERED and SORTED. It means 'has a comparator' 

We already have these:
- `hasDefiniteSize()` - which implies SIZED and SUBSIZED
- `isTraversableAgain()` - not needed for characteristics(), yet

**Comment by v1ctor** [comment]
Hi! If I understand CONCURRENT description right neither of our cases apply for this characteristics, because we have immutable types. Am I right?

**Comment by danieldietrich** [comment]
Hi, you are right. I've re-read the specs and [CONCURRENT](https://docs.oracle.com/javase/8/docs/api/java/util/Spliterator.html#CONCURRENT) makes no sense when a collection is [IMMUTABLE](https://docs.oracle.com/javase/8/docs/api/java/util/Spliterator.html#IMMUTABLE). Thank you!

**Comment by v1ctor** [comment]
@danieldietrich Could I also ask you what do you mean by separating characteristics for key/values and values for maps? 
How I understand as our Map implement Traversable<Tuple2<K, V>> we will have Splititerator<Tuple<K, V>> and characteristics for this spliterator we could from introspection methods.
Also how I understand if we want to take spliterator for the values, we will do it like that: 
```java
map.values().spliterator();
```
But in this case, unfortunately, we can't have SIZED and SUBSIZED characteristics, because we return Seq<V> from values() and this class doesn't have fixed size.

I've already written some code, and I can create PR to see if I'm going to the right direction.

**Comment by danieldietrich** [comment]
@v1ctor 

> How I understand as our Map implement Traversable<Tuple2<K, V>> we will have Splititerator<Tuple<K, V>> and characteristics for this spliterator we could from introspection methods.

Yes, absolutely right!

> But in this case, unfortunately, we can't have SIZED and SUBSIZED characteristics, because we return Seq from values() and this class doesn't have fixed size.

We don't have to think about this case. The Spliterator of the returned Seq implementation will manage its own characteristics (by introspection). It is all right.
