### ISSUE TITLE
Why is Foldable.fold accumulator of type <T> and not generic?

### ISSUE THREAD

**Issue by cluelessjoe** [javaslang/javaslang#1639]
Hi

In Foldable, the current fold signature is:

`default T fold(T zero, BiFunction<? super T, ? super T, ? extends T> combine) {
    Objects.requireNonNull(combine, "combine is null");
    return foldLeft(zero, combine);
}`

but it could also be with a generic accumulator, just like foldLeft is actually, like this:

`default <U> U fold(U zero, BiFunction<? super U, ? super T, ? extends U> combine) {
    Objects.requireNonNull(combine, "combine is null");
    return foldLeft(zero, combine);
}`

Why isn't it this way? I was disappointed when I realized the return type was T, and at the time I didn't realize foldLeft has an accumulator of a different type.

Most likely you have a good reason, and I would love to hear it. 

On the other hand, if you wish so, I could do a PR for the above signature (with some added tests). 

Another suggestion may be to add some javadoc to explicit that the foldLeft method has a generic accumulator (it would have helped me at the time).

Thanks a lot for javaslang :)

++

**Comment by danieldietrich** [comment]
Hi @cluelessjoe (btw - awesome name ;)),

the answer is algebraic:

* foldLeft associates to the left
* foldRight associates to the right
* fold is _associative_, the traversal of elements is unordered/non-deterministic. We say that the arguments to fold form a [Monoid](https://en.wikipedia.org/wiki/Monoid).

The [original answer](http://stackoverflow.com/a/6255094/1110815) came from [Rúnar Bjarnason](https://twitter.com/runarorama).

**Comment by cluelessjoe** [comment]
Hi @danieldietrich 

Thanks a lot for your extensive and nice answer. :)

I've read Rúnar Bjarnason's Functional Programming in Scala and there he doesn't introduce such a fold method, so it felt like your was just some short cut/convenience for foldLeft (and looking at the code felt so, for the ones like me missing the different signature of foldLeft). As you spotted, I'm truly clueless and proud of it ;) (well, I do with it rather to be honest lol)

Anyway, glad it helped you improve the javadoc, it for sure helped me :) 

BTW, any plan for a parallel collection on your side? I haven't read of it, yet I would be very curious :)

thanks again

best regards

**Comment by danieldietrich** [comment]
Hi @cluelessjoe,

> any plan for a parallel collection on your side?

I thought about it but for the moment it would be too much additional complexity. My plans are to go deeper and not so expanding the lib more.

Currently I'm experimenting how Future/Promise could be integrated more tightly into the library. You can see a first step with #1640 (see also the recent [blog post](http://blog.javaslang.io/object-functional-concurrent-programming-with-javaslang/)).

Javaslang's Values (not only collections, also monads like Option, Try, Future, ...) are convertible to Java types (back and forth). In the current SNAPSHOT we can use

```java
List.of(1, 2, 3)
    .toJavaParallelStream()
    /*do parallel computations*/
    .collect(List.collector());
```

Each Javaslang collection has a `collector()` method. With #1635 the splitterators will be optimized for parallel streaming.

Thanks again for asking - I'm preparing the fold javadoc-fix right now! :-)

\- Daniel
