### ISSUE TITLE
Incorrect Span behaviour

### ISSUE THREAD

**Issue by yeyan** [javaslang/javaslang#1641]
java> List.of(1,1,2,2,1,1).span(x -> x == 1)
(List(1, 1), List(2, 2))
// It should (List(1, 1), List(2, 2, 1, 1)) The list is simply truncated here
java> List.of(1,1,2,2,4,4).span(x -> x == 1)
(List(1, 1), List(2, 2, 4, 4))

It seems it is using map behind the scene. 
I am using version 2.0.2

**Comment by danieldietrich** [comment]
Thanks for reporting! I will investigate and fix it.

**Comment by danieldietrich** [comment]
Iterator#takeWhile and Iterator#dropWhile are broken:

1) They continue to apply the given Predicate, even if the test returned false
2) null is used to indicate 'no more elements' but null is a valid element
