### ISSUE TITLE
Add a static transpose to all Traversables

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1659]
Showing it for List here:

```java
class List {

    // transforms the given rows to columns, truncating the columns to the minimum length
    static <T> Array<Seq<T>> transpose(Iterable<? extends Iterable<? extends T>> rows) { ... }

    // transforms the given rows to columns, filling the columns with the defaultValue to the maximum length
    static <T> Array<Seq<T>> transpose(Iterable<? extends Iterable<? extends T>> rows, T defaultValue) { ... }

}
```

Example:

```java
List<List<Integer>> list = List.of(
    List.of(1, 2, 3),
    List.of(4, 5, 6),
    List.of(7, 8, 9));

// = List((1, 4, 7), (2, 5, 8), (3, 6, 9))
List<Seq<Integer>> zipped = List.zip(list);
```

The resulting sequences need to be truncated to the minimum length here.

**Comment by danieldietrich** [comment]
Maybe we should be more specific regarding the component type of the argument in order to make use of the random-access property of IndexedSeq's when transposing.

Also we could make use of `<T>` instead of `<? extends T>` because we only change the structure, not the type, i.e.

```java
    // transforms the given rows to columns, truncating the columns to the minimum length
    static <T> Array<Seq<T>> transpose(Iterable<Array<T>> rows) { ... }

    // transforms the given rows to columns, filling the columns with the defaultValue to the maximum length
    static <T> Array<Seq<T>> transpose(Iterable<Array<T>> rows, T defaultValue) { ... }
```

**Comment by danieldietrich** [comment]
See also [Transposing arbitrary collection-of-collections in Scala](http://stackoverflow.com/questions/10662462/transposing-arbitrary-collection-of-collections-in-scala)

**Comment by danieldietrich** [comment]
We should define static methods in these (and only these) types:

```java
interface Array<T> {
    static <T> Array<Array<T>> transpose(Iterable<? extends Iterable<? extends T>> rows);
    static <T> Array<Array<T>> transpose(Iterable<? extends Iterable<? extends T>> rows, T defaultValue);
}

interface CharSeq<T> {
    static CharSeq<CharSeq> transpose(Iterable<? extends Iterable<Character>> rows);
    static CharSeq<CharSeq> transpose(Iterable<? extends Iterable<Character>> rows, char defaultValue);
}
```

and so on. We do this for all Seq implies, i.e. all types that have indexed elements:

* Array
* CharSeq
* Vector
* List
* Stream
* Queue

It is a good idea to implements `Collections.transpose(...)`. However, I think we can make it more type-safe than your suggested solution. Also we need to distinguish between different row types when calculating the size... (checked via instanceof Seq and instanceof java.util.Collection, ...)

**Comment by paplorinc** [comment]
Shouldn't the transposition of a transposition equal itself? How can you achieve that with a `CharSeq`?
And if we can transpose a `Queue`, why not a (Bit)Set` or `Tree` or `Map`?

**Comment by danieldietrich** [comment]
sorry wrong button on my mobile device :-)

**Comment by danieldietrich** [comment]
@paplorinc yes (A<sup>T</sup>)<sup>T</sup> should be A, i.e.

```java
// equals list
List.transpose(List.transpose(list))
```

In general we have rows of different length, e.g.

```java
List(
  List(1, 2)
  List(3, 4, 5)
  List(6)
)
```

The transposed result will be

```java
List(
  List(1, 3, 6)
  List(2, 4, ?)
  List(?, 5, ?)
)
```

And this one transposed again will be...

```java
List(
  List(1, 2, ?)
  List(3, 4, 5)
  List(6, ?, ?)
)
```

The ? is either `null` or a default value. I don't know what ? may be in the case of CharSeq. 0x0?

**Note:** We could narrow the parameter type, like

```java
interface List<T> {
    static <T> List<List<T>> transpose(List<List<T>> rows);
}
```

But I see no reason for that.

---

Your second question: I don't think it makes sense to add transpose to collections that aren't indexed. E.g. insertion order or comparator will not be sufficient or produce 'funny'. results...

**Comment by danieldietrich** [comment]
'Special' case (not really):

```java
List(
  List(1, 2)
  List(3)
  List()
)
```

Transposed:

```java
List(
  List(1, 3, ?)
  List(2, ?, ?)
)
```

Transposed:

```java
List(
  List(1, 2)
  List(3, ?)
  List(?, ?)
)
```

**Comment by paplorinc** [comment]
Should we even handle incomplete rows?

**Comment by paplorinc** [comment]
> I don't think it makes sense to add transpose to collections that aren't indexed

Only `Array`, `Vector` and `CharSeq` are indexed, and `CharSeq` cannot hold matrices, so only the first two qualify (though I think `List` should be fine also)

**Comment by danieldietrich** [comment]
@paplorinc

> Only Array, Vector and CharSeq are indexed

nope, all Seq's are indexed, the above are random access, i.e. get(index) is O(1). IndexedSeq does say us only s.th. about performance 

> CharSeq cannot hold matrices

right. however, it is indexed. A transpose makes sense. We should implement it, e.g. one or more of the following:

```java
final class CharSeq implements IndexedSeq<Character>, CharSequence {

    Seq<CharSeq> transpose(Iterable<? extends Iterable<Character>> rows) { ... }

  Seq<CharSeq> transpose(String... rows) { ... }

  Seq<CharSeq> transpose(CharSequence... rows) { ... }

}
```

(plus the variants with second argument defaultValue)

> so only the first two qualify

All Seq's should have transpose. We can't predict all use cases of our users. We do it consistent.

**Comment by danieldietrich** [comment]
* or return `IndexedSeq<CharSeq>`
* maybe also return `Seq<List>` instead of `List<List>` when taking Iterables
* or maybe return  and take `List<List>`

* what is best for our users?
* or should mathematical correctness be the main criteria? however, in mathematics we have not container types, only cross-products/relations.
* or do we have other criteria?

**Comment by danieldietrich** [comment]
@paplorinc is right, without having a default value this might be the better choice:

```java
List(
  List(1, 2)
  List(3)
  List()
)
```

Transposed:

```java
List(
  List(1, 3)
  List(2)
)
```

Transposed:

```java
List(
  List(1, 2)
  List(3)
)
```
