### ISSUE TITLE
Add aliases API.unchecked(CheckedFunction*)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1660]
(for CheckedFunction0..N)

Example:

```java
class API {
    static <T, R> Function1<T, R> unchecked(CheckedFunction1<T, R> methodReference) {
        return CheckedFunction1.of(methodReference).unchecked();
    }
}
```

(see Generator.scala)

**Comment by pivovarit** [comment]
Ok, I am on it. I will officially kill my https://github.com/TouK/ThrowingFunction project and redirect my stars here :)

So API class is the right place for all of those methods?

**Comment by danieldietrich** [comment]
Yes, we need them in API, additionally we may add `Function*.unchecked(CheckedFunction*)`.

**Comment by pivovarit** [comment]
Um, I am afraid this was already implemented (but not included in the latest release).

https://github.com/javaslang/javaslang/blob/cfb4f0f840a3b38545a61ed444cb1d3fdc48a96a/javaslang/generator/Generator.scala#L373

**Comment by danieldietrich** [comment]
Yes, also just found it o_O - forgot about it.

![screen shot 2016-11-06 at 9 17 12 am](https://cloud.githubusercontent.com/assets/743833/20036216/1a0c9e20-a402-11e6-81d4-980ff601c337.png)

I will close this issue.
