### ISSUE TITLE
Add Tuple*.narrow and (Checked)Function*.narrow

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1663]
Most other types alreay have narrow. Some generated types still need to implement the static narrow method.

**Comment by mfejzer** [comment]
@danieldietrich I'll add narrow to (Checked)Function during next few days, probably on Monday

**Comment by danieldietrich** [comment]
@mfejzer that sounds great! Looking forward to it :)

**Comment by mfejzer** [comment]
@danieldietrich I'm not sure if I understand covariance and contravariance correctly, but narrow defined on function should only work on result, right? Something like `Function<? super T1, ? extends R>` is "narrowed" to `Function<? super T1,  R>`, because we cannot cast T1 to anything meaningful.

**Comment by danieldietrich** [comment]
@mfejzer Functions are

* _Contravariant_ in their arguments, i.e. `? super T*`
* _Covariant_ in the result type, i.e. `? extends R`

Given a `Function<? super T, ? extends R> f` we say:

* **T is a _lower bound_** - in other words, if `f` takes a `T`, it also takes an `U` that extends `T`
* **R is a _upper bound_** - in other words, if `f` returns an `R`, it also returns an `S` that is super type of `R`

The _narrowed_ form erases all bounds. Given the above rules, we can say, `f` is also of type

```java
Function<T, R>
```

Does this make sense to you?

**Comment by mfejzer** [comment]
Yes, it makes sense

**Comment by danieldietrich** [comment]
Fixed
