### ISSUE TITLE
Either.mapLeft Javadoc seems incorrect

### ISSUE THREAD

**Issue by abhijitsarkar** [javaslang/javaslang#1670]
v2.0.4 [Either.mapLeft](http://static.javadoc.io/io.javaslang/javaslang/2.0.4/javaslang/control/Either.html#mapLeft-java.util.function.Function-) says:

> default <U> Either<U,R> mapLeft(Function<? super L,? extends U> leftMapper)
> Maps this right-biased Either.

Shouldn't it be "Maps this **left-based** Either"?

**Comment by danieldietrich** [comment]
Thank you. You are right, it is unclear. It is correct that the Either is right-biased, regardless if its left value or its right value is mapped. I will change the docs like this:

"Maps the left value of this Either, if present."

**Comment by abhijitsarkar** [comment]
@danieldietrich Thank you. I suggest that you also explicitly say "...is a no-op if the value is a Right", or something to that effect.

**Comment by danieldietrich** [comment]
Yes, the javadoc could be more mature throughout the project. We currently focus on the work of the other issues towards the bugfix release 2.0.5 and the next minor release 2.1.0.

Contributions, especially to javadoc, are welcome!

**Comment by abhijitsarkar** [comment]
I'd be happy to but do you really need contribution to add 35 characters? Perhaps 70, if `map` is updated as well.

**Comment by danieldietrich** [comment]
Of course not.
