### ISSUE TITLE
path from Option to Either?

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang#1677]
admittedly there are already many paths from various types to others in javaslang. So maybe this one is simply not important enough to be worth it.

Because I was wondering about possibly adding yet another one :-) from `Option` to `Either`. In haskell, the `errors` package provides such a path, through the `note` function =>
https://hackage.haskell.org/package/errors-2.1.2/docs/Control-Error-Util.html#v:note

so the new method in `Option<T>` would be `Either<U, T>  toEither(U left)`. We could name it `note` as in haskell, but I guess it's not really intuitive for this API.
An alternative would be a static `fromOption(U left)` method in `Either`.

One of the reason for that would be that `Validation` can be built from an `Either` not an `Option` and there is currently no easy way to build an `Either` from an `Option` that I can see.

Would you accept a PR adding such a method?

**Comment by danieldietrich** [comment]
I would love to see it as conversion method in Value:

```java
interface Value<T> {

    <L> Either<L, T> toEither(L left) {
        if (this instanceof Either) {
            return ((Either<?, T>) this).mapLeft(ignored -> left);
        } else {
            return isEmpty() ? Left(left) : Right(get());
        }
    }

    <L> Either<L, T> toEither(Supplier<? extends L> leftSupplier) {
        Objects.requireNonNull(leftSupplier, "leftSupplier is null");
        if (this instanceof Either) {
            return ((Either<?, T>) this).mapLeft(ignored -> left);
        } else {
            return isEmpty() ? Left(leftSupplier.get()) : Right(get());
        }
     }
}
```

**Comment by emmanueltouzery** [comment]
wow, even a `toValidation` in `Value`? Didn't dare mentioning it :-)
Sounds great! I'll take your code, add tests, add Validation, and submit a PR ASAP then!
