### ISSUE TITLE
leftMap vs mapLeft

### ISSUE THREAD

**Issue by emmanueltouzery** [javaslang/javaslang#1680]
We have `Validation.leftMap` and `Either.mapLeft`.
Probably we should unify the naming for 3.0?
We could add Validation.mapLeft or Either.leftMap, deprecate the one we don't like and remove it in 3.0.

Except if it's like that on purpose, for some reason?

**Comment by danieldietrich** [comment]
Good point. I think we should name it _mapError_ because of _getError_ (and deprecate _leftMap_).

| Validation | Either |
| --- | --- |
| isValid | isRight |
| isInvalid | isLeft |
| get | get |
| _getError_ | getLeft |
| map | map |
| _mapError_<br>~~leftMap~~ | mapLeft |
