### ISSUE TITLE
Gen choose fails with stream of instances of generic interface

### ISSUE THREAD

**Issue by gtrefs** [javaslang/javaslang#1699]
# Problem statement
```Java
Stream<Supplier<String>> strings = Stream.of(() -> "test", () -> "test2");
Property.def("Test")
         .forAll(Gen.choose(strings).arbitrary())
         .suchThat(s -> true)
         .check()
         .assertIsSatisfied();
}
```
fails with following stack trace:
```Java
Nov 22, 2016 1:46:12 AM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFORMATION: Discovered TestEngines with IDs: [junit-jupiter]

java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at java.util.ArrayList.toArray(ArrayList.java:408)
	at javaslang.Value.toJavaArray(Value.java:489)
	at javaslang.test.Gen.choose(Gen.java:205)
...
```
# Possible cause
This exception is thrown `if the runtime type of the specified array is not a supertype of the runtime type of every element in this list` (see [JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#toArray-T:A-)). I assume the `choose` method of `Gen` to be the culprit
```Java
final T[] array = stream.toJavaArray((Class<T>) stream.head().getClass());
```
Although `Supplier<String>` is a supertype of `stream.head()` the actual type of `stream.head()` is something like `test.Clazz$$Lambda$120/90205195`. In method `toJavaArray` of interface `Value`            
this type is used to indicate the component type of the resulting array:
```
final java.util.List<T> list = toJavaList();
return list.toArray((T[]) java.lang.reflect.Array.newInstance(componentType, list.size()));`
```
The type is correct for the first element, but not for the second. If the second `Supplier` is removed from the Stream, the test succeeds.
```Java
Stream<Supplier<String>> strings = Stream.of(() -> "test");
Property.def("Test")
         .forAll(Gen.choose(strings).arbitrary())
         .suchThat(s -> true)
         .check()
         .assertIsSatisfied(); // works fine
}
```
# Solution proposals
1. Use [TypeTokens](https://github.com/google/guava/wiki/ReflectionExplained) if appropiate
2. Add new choose method with additional class parameter
```Java
Gen.choose(strings, Supplier.class) // example
```

**Comment by danieldietrich** [comment]
Hi @gtrefs,

thank you for you detailed bug description - it helped me going straight to the cause of the problem.

I think the following solution fits best because it is minimal invasive. It does work for your test above:

### Buggy version

```java
static <T> Gen<T> choose(Iterable<T> values) {
    Objects.requireNonNull(values, "values is null");
    final Stream<T> stream = Stream.ofAll(values);
    if (stream.isEmpty()) {
        throw new IllegalArgumentException("Empty iterable");
    }
    @SuppressWarnings("unchecked")
    final T[] array = stream.toJavaArray((Class<T>) stream.head().getClass());
    return choose(array);
}
```

### Fixed version

```java
static <T> Gen<T> choose(Iterable<T> values) {
    Objects.requireNonNull(values, "values is null");
    final Iterator<T> iterator = Iterator.ofAll(values);
    if (!iterator.hasNext()) {
        throw new IllegalArgumentException("Empty iterable");
    }
    @SuppressWarnings("unchecked")
    final T[] array = (T[]) iterator.toJavaArray();
    return choose(array);
}
```

Also I realized that the javaslang-test package was written before we had javaslang.collection.Iterator. We can substitute (some) usages of Stream now with Iterator. I will create an issue to improve that.

If you do not find anything that is still in our way, could you please create a PR containing the fix sketched above?

Many thanks!

**Comment by danieldietrich** [comment]
(off-topic: I did the Iterator optimizations in #1700)

**Comment by gtrefs** [comment]
Ah... nice :). I did not find anything else. I will create a PR later this evening.
