### ISSUE TITLE
Move javaslang-gwt and javaslang-gwt-example to their own module

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1705]
These two modules do not belong to the javaslang core. GWT is a framework on its own, like Jackson (which has the javaslang-jackson module).

Additionally we have build problems because the gwt modules are currently build along with the other modules but they depend on deployed sources-jars of javaslang-core. This is a chicken-egg problem.

The actual builds fail because of this cyclic dependency, even locally. I had to remove the gwt modules from the parent pom (locacally/temporarily).

This will also speed up our builds again. The next steps are to re-activate the benchmark profile (or doing s.th. similar) and finally moving to Gradle builds.

I will create a Github project javaslang/javaslang-gwt.

/cc @ruslansennov

**Comment by ruslansennov** [comment]
/cc @dharezlak 

I'm afraid that this is a big mistake.

> These two modules do not belong to the javaslang core. GWT is a framework on its own, like Jackson (which has the javaslang-jackson module).

The Jackson module requires API stability only, but requirements of GWT module is more strong: it requires GWT-compatibility of internal core code. Each step can bring core into the state of inconsistency with GWT. 

> Additionally we have build problems because the gwt modules are currently build along with the other modules but they depend on deployed sources-jars of javaslang-core. This is a chicken-egg problem.

Yes, this is a known problem of Maven. But everything will be OK when we migrate to Gradle.

> The actual builds fail because of this cyclic dependency, even locally. I had to remove the gwt modules from the parent pom (locacally/temporarily).

My favorite command `mvn clean test -pl \!javaslang-benchmark` works well. What do you mean?

**Comment by danieldietrich** [comment]
I think it will not be a mistake - it is just a matter of build infrastructure / build topology.

When I try to understand dependencies I look at worst case szenarios. What if there are more frameworks than GWT that require Javaslang (source code) to behave in a specific way? Do they all need to be integrated into the `javaslang` module because we need fast build-feedback? I do not think so.

What we _really_ need is to _trigger_ the javaslang-gwt build **after** the javaslang core build ran successful. That should be no problem. If javaslang-gwt moves to its own repo we need to activate an after-build step to our travis-ci config. If travis does not support cross-repository build triggers (like Jenkins) then we could call a trigger-script that commits (a timestamp for example) to the javaslang-gwt project. That will trigger a new ci build on that project.

**Comment by ruslansennov** [comment]
> What we really need is to trigger the javaslang-gwt build after the javaslang core build ran successful.

Yes, this is good point. I don't know if this is possible on Travis, but it definitely possible on Cloudbees

**Comment by danieldietrich** [comment]
I already have a trigger in mind using git by committing a timestamp. No problem!

**Comment by dharezlak** [comment]
What happens to version management/releasing if the javaslang-gwt module is in a separate repository. Can this also be automated somehow?

**Comment by danieldietrich** [comment]
@dharezlak Javaslang core is released manually. Currently all repositories (of the Javaslang organization) that depend on the core need to be released afterwards (manually). I don't know if it is possible to implement a continuous delivery across all repositories &mdash; however, it would be cool!

**Comment by dharezlak** [comment]
@danieldietrich OK. I just want to make sure that the javaslang-gwt module will not be left behind :)

**Comment by danieldietrich** [comment]
Finished. See also javaslang/javaslang-gwt#1
