### ISSUE TITLE
Gen.frequency(0, gen) should never return gen

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1709]
Currently it may occur that a generator is returned that should occur with a frequency of 0.

This is a very theoretical case (because generators with a frequency of zero can be omitted at all) but we have to cover it.

**Comment by iref** [comment]
I can work on this issue if nobody started yet. I checked how Scalacheck handles this and they filter all generators without positive frequency out before they compute composite generator. Should we do the same thing? Or do you think that throwing `IllegalArgumentException`, which is case for negative frequencies now, is better?

**Comment by danieldietrich** [comment]
Hi @iref,

thank you for your suggestion! I prefer to do filtering is a behaviour that leads to a defined result. Throwing should be the least alternative, breaking the program at runtime is not a good idea.

I'm looking forward to your contribution :-)

\- Daniel
