### ISSUE TITLE
Remove head/tail optimizations of Vector again

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1748]
# For small n Vector.get(index) is O(n)

This is a no-go. `get()` is one of the most frequently used operations on a _random access_ collection. Vector is our default random access operation.

> Rule 3. **Fancy algorithms are slow when n is small, and n is usually small.** Fancy algorithms have big constants. Until you know that n is frequently going to be big, don't get fancy. (Even if n does get big, use Rule 2 first.)

Our current implementation is in breach of our **third rule** (see [CONTRIBUTION.md](https://github.com/javaslang/javaslang/blob/master/CONTRIBUTING.md)).

Our benchmark state nothing at all. Of course we can measure the performance for a big number of elements N. But if this does not happen in production, it is useless. Our implementation got tremendous more complicated.

If a fast head/tail operation is needed I suggest to use Array or List or Stream, depending of which other operations are important in the particular context.

**Comment by paplorinc** [comment]
Could you please elaborate on why it's linear? Only edits are linear for n < 32 (the same is true for any collection, e.g. an ArrayList is linear for n = 1)

> Our benchmark state nothing at all.

We have benchmarks for small number of elements also.

**Comment by danieldietrich** [comment]
I created this issue based on one of your recent statements that an operation takes linear time for small n. I wrote this ticket in a hurry from the top of my head. The description seems to be wrong but the problem seems to exist. However, until I find more detailed information I will close this ticket...

Sorry for confusing you. /cc @paplorinc
