### ISSUE TITLE
Multimap implementations don't have a method to create from java.util.Map

### ISSUE THREAD

**Issue by asarkar** [javaslang/javaslang#1767]
While `HashMap` has an `ofAll` method, `HashMultimap.Builder` doesn't. Also, the former has static creational `of` methods while the later doesn't and creating a builder first is required. I think I understand why though, the value for a multimap can be a general sequence or a set, but I'm not sure the inconsistency it introduces is worth the benefit, because whoever needs it can convert a `Seq` to a `Set` by various means.

**Comment by danieldietrich** [comment]
Yes, I also think the creational API of Multimap still can get _hardened_. I will take your suggestions into account when re-visiting the Multimap API before the 2.1.0-beta release.

**Comment by danieldietrich** [comment]
@asarkar I think @ruslansennov added all missing methods. Please give us a sign if still s.th. is missing.
