### ISSUE TITLE
Try.something( FunctionThrower )

### ISSUE THREAD

**Issue by xenoterracide** [javaslang/javaslang#1780]
This seems overly verbose, couldn't there be a static that takes the `FunctionThrower` directly?
```
strategies.map( s -> Try.of( () -> s.fileCreatorFor( file ) ).onFailure( log()::error ).get()  )
```

**Comment by danieldietrich** [comment]
Please give an example, how the following code could be simplified. What is `FunctionThrower`? Please show that interface.

Note: The example above is not correct. The final `get()` call may throw at runtime if the result of the Try.of() call is a Failure. What is `strategies`? A Traversable?

Please provide me with the missing details, e.g. make types explicit by adding variables.

**Comment by xenoterracide** [comment]
sorry, my brain did some interpolation as I've been playing with writing my own `Try`, the name here is `CheckedFunction`

`strategies` is just a `java.util.Stream`

`Stream.of(...).map(Try.of( ... ).onFailure( ... ) ). ...`

**Comment by danieldietrich** [comment]
Ok, that's something I can work with :-) Now we have the Stream.map() API:

```java
java.utill.Stream.map(Function<? super T,? extends R> mapper)
```

You write:

```java
Stream.of(...).map(Try.of( ... ).onFailure( ... ) ). ...
``` 

Given that map() takes a Function I interpret this in the way that you want Try to extends Function. But I think what you really want is this:

```java
java.util.stream.Stream.of(...).map(Try.asFunction(t -> trySomething(t)))...
```

with

```java
interface Try<T> {
    static <T, R> Function<T, R> asFunction(Function<? super T, ? extends R> f) {
        return t -> Try.of(() -> f(t)).getOrElse(???); // <-- not clear what to return in the case of a Failure
    }
}
```

As you see, there is still something missing:

* What to do in the Failure case?
* There is no way to add an `onFailure()` handler in my example above

---

I think what you really want is flatMap(), e.g.

```java
java.util.stream.Stream
    .of(...)
    .flatMap(t -> Try.of(() -> trySomething(t)).onFailure(...).toJavaStream())
    ...
```

You need to convert the Try to a Java Stream to be conform with Stream's flatMap() signature:

```java
java.util.stream.Stream.flatMap(Function<? super T,? extends Stream<? extends R>> mapper)
```

---

## Please give me more specific information what to do. E.g. sketch an implementation of the new functionality here. Especially provide an example of a specific input and the specific output for that case.

**Comment by xenoterracide** [comment]
I'm not sure about flatmap because I use map with `Optional` too (yay for them not making `map(...)` and `stream()` interfaces.... I'm of the believe that if you don't supply a value (or whatever) for `orElse` then it should return null, as if I didn't provide an alternative return value in a Supplier/Function, I would likely return a null.

for example in this brokenness that I'm likely to reimplement anyways. Logger is just an slf4j wrapper that just takes an exception. (note: the fileCreator stuff throws IOException, because dealing with InputStream's)

```
 Optional<FileCreator> fileCreator = strategies.map(
                s -> Try.of( () -> s.fileCreatorFor( file ) ).onFailure( log()::error ).get() )
                .filter( Optional::isPresent )
                .map( Optional::get )
                .findFirst()
                .map( fc -> Try.of( fc::createFile ).onFailure( log()::error ).get() )
                .filter( FileCreator::filter );
```
A simpler example ( that is terrible  as all simple examples are )
```
Stream.of( -1, 0, null, 1, 2, 3 ).map(  Try.function( i -> i % 2 ).onFailure( e -> log.error("{}", e ).magic? ).filter( Objects::nonNull ).collect( Collectors.counting ); // 5
```

**Comment by danieldietrich** [comment]
@xenoterracide as I already said, your code is broken because of Try...get() in the case of a Failure. Your test the 'happy path' - let it crash!

Run this and you will see what I mean:

```java
Optional<FileCreator> fileCreator = strategies.map(
                s -> Try.of( () -> { throw new Error("test") } ).onFailure( log()::error ).get() )
                .filter( Optional::isPresent )
                .map( Optional::get )
                .findFirst()
                .map( fc -> Try.of( fc::createFile ).onFailure( log()::error ).get() )
                .filter( FileCreator::filter );
```

You can replace the get() with a getOrElse(Optional.empty()).

---

## But I suggest to simplify your code by using Javaslang instead of Java ;)

### 1) This seems to be your code (I reconstructed the interfaces):

```java
public class BetterJava {

    void test(java.util.stream.Stream<Strategy> strategies, File file) {
        Optional<FileCreator> fileCreator = strategies.map(
                s -> Try.of(() -> s.fileCreatorFor(file)).onFailure(log()::error).get())
                .filter(Optional::isPresent)
                .map(Optional::get)
                .findFirst()
                .map(fc -> Try.of(fc::createFile).onFailure(log()::error).get())
                .filter( FileCreator::filter );
    }

    Log log() {
        return null;
    }
}

interface Strategy {
    Optional<FileCreator> fileCreatorFor(File file);
}

interface FileCreator {
    FileCreator createFile();
    static boolean filter(FileCreator fc) { return false; }
}

interface Log {
    void error(Throwable t);
}
```

### 2) This is how I would do it

```java
public class BetterJava {

    void test(javaslang.collection.Stream<Strategy> strategies, File file) {
        Try<FileCreator> fcs = strategies
                .flatMap(s -> s.fileCreatorFor(file).onFailure(log()::error)) // = Seq<FileCreator>
                .headOption().toTry()                                         // = Try<FileCreator>
                .flatMap(fc -> fc.createFile().onFailure(log()::error))       // = Try<FileCreator>
                .filter(FileCreator::filter);
    }

    Log log() {
        return null;
    }
}

interface Strategy {
    Try<FileCreator> fileCreatorFor(File file);
}

interface FileCreator {
    Try<FileCreator> createFile();
    static boolean filter(FileCreator fc) { return false; }
}

interface Log {
    void error(Throwable t);
}
```

Instead of `javaslang.collection.Stream<Strategy>` you might also use `javaslang.collection.Iterator<Strategy>` (if traversed only once).

**Comment by danieldietrich** [comment]
I hope you don't mind if I close this issue. There are a couple of ways to achieve your goal. We can't invent something new here, especially not Try.function() because we would loose the error.

**Comment by xenoterracide** [comment]
eh, not really, I already have a working-ish version of this, I was just looking a javaslang to see if it was doing it better, or would make my life easier in implementing.

**Comment by danieldietrich** [comment]
The one benefit I see is that all Javaslang types are Iterable. This makes flattening easier. In Java you need to map(), then filter(Optional::isPresent) and map(Optional::get), this can be done in one flatMap() step using Javaslang.

Maybe Optional can be stream()-ed in JDK 9, I don't know. Then flatMap() will be easier using a Java Stream.
