### ISSUE TITLE
List.hashCode throwing java.lang.StackOverflowError

### ISSUE THREAD

**Issue by thekaratekid05** [javaslang/javaslang#1795]
This looks like an issue with the recursive nature of the List$Cons.hashcode

```java
    List<Integer> aList = IntStream.range(0, 1000000)
          .boxed()
          .collect(List.collector());

    // throws java.lang.StackOverflowError
    aList.hashCode();
```

**Comment by danieldietrich** [comment]
Thank you @thekaratekid05! I can confirm your observation on the current master branch. The List.Cons.hashCode() implementation is based on a recursion of (head, tail).
