### ISSUE TITLE
Specific AbstractTraversableTest runs infinitely for (Hash/Linked/Tree)MultimapTest

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1797]
**Goal:** Investigate why *MultimapTest.shouldNotThrowStackOverflowErrorWhenCalculatingHashCodeOf1000000Integers()` does not return. It is currently `@Ignored` for all Multimap test classes.

See #1796

**Comment by ruslansennov** [comment]
fixed by #1831

**Comment by danieldietrich** [comment]
Great, thank you! 😊
