### ISSUE TITLE
Automatically trigger javaslang-gwt rebuild after snapshot was deployed

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1804]
It seems something wrong with credentials
```
$ .travis/trigger-build.sh javaslang-gwt
Triggering travis-ci build of javaslang/javaslang-gwt [master]...
{
  "@type": "error",
  "error_type": "wrong_credentials",
  "error_message": "access denied"
}
```

**Comment by danieldietrich** [comment]
Will take a look today

**Comment by danieldietrich** [comment]
@ruslansennov It works fine, I think is not an issue - all works fine. But another issue raised: we need to trigger builds _after_ we deployed a new snapshot. I will rename the issue an fix it.

There are two aspects that might be a little bit confusing:

## 1) PR builds do not (and must not!) trigger other projects

Everyone can submit a PR. Especially it would be a security risk, if external commiters would have read access to our credentials. I.e. they could be sent clear-text to a third party server by adding a simple `curl` line to our travis-ci script _before_ any code review takes place.

For this reason the travis-ci build environment does not load environment variables for a PR build.

## 2) The javaslang-gwt project references maven artifacts

Currently we first trigger the javaslang-gwt build and then deploy the new snapshot (my fault). Of course we need to it in reverse order. I will commit a change.

## Example: PR 2016 -> 2017

**The travis-ci configuration for the PR:**

<img width="701" alt="screen shot 2017-01-07 at 11 37 40" src="https://cloud.githubusercontent.com/assets/743833/21741145/cc85a852-d4cd-11e6-97a2-db77707caa98.png">

**The travis-ci configuration for the merged PR:**

<img width="814" alt="screen shot 2017-01-07 at 11 37 58" src="https://cloud.githubusercontent.com/assets/743833/21741148/d74c2bda-d4cd-11e6-9e8b-ac65fcd0d5d5.png">
