### ISSUE TITLE
Make interfaces Serializable

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1810]
@ggalmazor noted that we (unintentionally) changed the object serializability. E.g. Option isn't serializable any more (but Some and None are). This hinders us from adding fields of interface types (like Option) to serializable classes.

There are exceptions, stateful types should **not** implement Serializable:

* Future
* Promise
* Iterator

Also API specific types should not implement it:

* For
* Match, Case, Pattern
* ...

**Comment by danieldietrich** [comment]
@ruslansennov I will start to implement this. It might have an impact to our current javaslang-jackson version - we will see...

**Comment by ruslansennov** [comment]
No prob :)

**Comment by danieldietrich** [comment]
@ruslansennov it should have no impact on current javaslang-jackson impl - we added the Serializable tagging interface to some interfaces. But we did not remove or change something existing.
