### ISSUE TITLE
Add better Tuple support to (Checked)Function*

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1813]
```java
    default R apply(Tuple2<? extends T1, ? extends T2> t) throws Throwable {
        return apply(t._1, t._2);
    }

    R apply(T1 t1, T2 t2) throws Throwable;
```

**Comment by AlparSzabados** [comment]
Could you please write an example on how this differs from `.tupled()`?

Instead of
```java
@Test
public void shouldTupled() throws Throwable {
    final CheckedFunction3<Integer, Integer, Integer, Integer> f = (i1, i2, i3) -> i1 + i2 + i3;
    final Tuple3<Integer, Integer, Integer> t = API.Tuple(1, 2, 3);
    assertThat(f.tupled().apply(t)).isEqualTo(1 + 2 + 3);
}
```
it should be possible to do
```java
@Test
public void shouldTupled() throws Throwable {
    final CheckedFunction3<Integer, Integer, Integer, Integer> f = (i1, i2, i3) -> i1 + i2 + i3;
    final Tuple3<Integer, Integer, Integer> t = API.Tuple(1, 2, 3);
    assertThat(f.apply(t)).isEqualTo(1 + 2 + 3);
}
```
?

**Comment by danieldietrich** [comment]
@AlparSzabados Thank you for the example. You are right, there is no difference.

In fact it does not scale well to introduce special default methods that take Tuples.

For example HashMap.flatMap takes a BiFunction. If it would take a Function2 we could benefit from a default method that takes a Tuple2 but we can't pass a BiFunction any more.

```java
<K2,V2> HashMap<K2,V2> flatMap(BiFunction<? super K,? super V,? extends Iterable<Tuple2<K2,V2>>> mapper)
```

I remember once there was a suggestion to add special Tuple support to Functions and I decided not to do it. So we should close this ticket.

It is great to have a discussion. Sometimes it occurs that I have an idea without having analyzed it in depth. I create an issue because I do not want to forget it. The collection API is complex. There were many design decisions in the past. However, the conditions may change after some months. So thinking again and again about the same topic makes sense :)

Thank you!

**Comment by AlparSzabados** [comment]
No problem! Thank you for looking into it.
