### ISSUE TITLE
Is there any way to chain operations with both Try<Option<?>> monads together?

### ISSUE THREAD

**Issue by noorulhaq** [javaslang/javaslang#1817]
Hi,

Is there any way to chain operations with both Try<Option<?>> monads together?

Below is the example I tried.

```java
Try<Option<String>> str1 = Try.of(()->Option.of("Noor1"));
Try<Option<String>> str2 = Try.of(()->Option.of("Noor2"));

Try<Option<Try<Option<Tuple2<String,String>>>>> result =  str1.map(optStr1 -> optStr1.map( s1 -> str2.map(optStr2 -> optStr2.map(s2 -> Tuple.of(s1,s2)))));

Try<Option<Tuple2<String,String>>> result2 = Match(result).of(
                Case(Failure($()), ex -> Try.failure(ex)),
                Case(Success(None()), none -> Try.of(()->Option.none())),
                Case(Success(Some(Failure($()))), ex -> Try.of (()-> ex.get().get())),
                Case(Success(Some(Success(None()))),none -> Try.of(()->Option.none())),
                Case(Success(Some(Success(Some($())))), value -> Try.of (()-> Option.of(value.get().get().get())))
        );

System.out.println( result2 );
```

This is quite verbose. Any luck if I can use Monad Transformers?

**Comment by danieldietrich** [comment]
@noorulhaq Thank you for your question.

The following is equivalent to your solution:

```java
Try<Option<String>> str1 = Try.of(()-> Option.of("Noor1"));
Try<Option<String>> str2 = Try.of(()-> Option.of("Noor2"));
Try<Option<Tuple2<String, String>>> result = str1.flatMap(o1 -> str2.map(o2 -> o1.flatMap(s1 -> o2.map(s2 -> Tuple.of(s1, s2)))));
```

In most cases `flatMap` can be used to solve problems that involve combination of wrapped/monadic values.

Does this help?

**Comment by noorulhaq** [comment]
Damn it! I tried with flatMap but in wrong order. Thumbs up for your help and trillion thumbs down from myself.

**Comment by danieldietrich** [comment]
@noorulhaq please don't blame youself - the solution wasn't obvious.

**Comment by noorulhaq** [comment]
Thanks for the buck up. I am writting an article on funtional domain modeling in Java8 using your library. Once, I am finished with that I will share with you the article. We can then discuss some more functional possibilities that are easy to define.

**Comment by danieldietrich** [comment]
@noorulhaq that sounds great! please don't hesitate to contact me if you have any questions.
