### ISSUE TITLE
Add `of(String)` to collections

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1820]
`String` is often considered a "primitive object" in `Java`, as it has special language support (e.g. the `+` operator), therefore it could make sense to add support for creating a collection from its characters, e.g.

instead of:
```java
Vector.ofAll("hello".toCharArray())
```
we could write
```java
Vector.ofAll("hello")
```
of with `API` support:
```java
Vector("hello")
```

**Comment by danieldietrich** [comment]
I won't do that because it is 'too complicated' in the way that strings are no Collection and no Array but _implicitly_ concidered to be like an Array. I like to keep the API dead-simple.

**Comment by danieldietrich** [comment]
I hope you don't mind if I close the ticket.

**Comment by paplorinc** [comment]
The ambiguity would also be in case of the `API` support.
I don't mind, I respect that the final decision is yours. :)
