### ISSUE TITLE
List flatMap is absorbing Failure by evaluating to Empty List

### ISSUE THREAD

**Issue by noorulhaq** [javaslang/javaslang#1846]
**Exp1:** List.of("test").map(str -> Try.failure(new RuntimeException("test")))
**Output:** List(Failure(java.lang.RuntimeException: test))

**Exp2:** List.of("test").flatMap(str -> Try.failure(new RuntimeException("test")));
**Output:** List()

**Exp3:** List.of(Try.of(()->"test")).flatMap(str -> Try.failure(new RuntimeException("test")));
**Output:** List()

**Comment by danieldietrich** [comment]
flatMap gets elements out of containers like Try.

Given a type Try&lt;T>

* a Success(t) contains one element t
* a Failure(SomeException) contains no element (of type T)

If you want to learn more about this topic, please search for Algebraic Data Types, Sum Types and Product Types. There are many resources.

**Comment by noorulhaq** [comment]
Thanks for your reply. Right now Future is my problem. Why futre contains value stacked up this way:
Option<Try<Option>> instead of just Try<Option>

**Comment by danieldietrich** [comment]
Because it is --> eventually &lt;-- computed.

It returns None, if it is still conputing...

It returns Some, if the computation finished. The result may be a Success or a Failure.

Hope that helps.

**Comment by danieldietrich** [comment]
**Tip:** Use onCompleted() handler for async computations instead of pollong...
