### ISSUE TITLE
Deeply map a nested, monadic structure.

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#185]
@ggalmazor proposed:

```java
Monad<Monad<U>> result = ((Monad<Monad<T>>) unit).flatMap((λ<T,U>) mapper)
```

...for any number of depth levels.
... and any Monad type (Try, Option, Stream...)

**Comment by ggalmazor** [comment]
Specific example... 

```java

  static class Example {
    static Option<String> extract(String str) {
      if (str.length() >= 15) str)
      return Option.of(str.substring(10, 15);
      return Option.none();
    }
  }

  Stream<Option<Long>> sums = Stream.of("cocotero", "chuchu blabla pinpon")
        .map(Example::extract)
        .flatMap(String::chars)
        .flatMap(IntStream::sum);
```

If you collected the stream, you'd get one None() and one Some<Long>().

But i'm thinking that it might be impossible to check or infer the types right...

**Comment by danieldietrich** [comment]
Thank you for the example! I've `traverse(mapper)` in mind (like tree traversal). Nodes of the tree are monads, each monad has `traverse`. Will go into it later today...

**Comment by danieldietrich** [comment]
I have a local running version. Basically it is a recursive `map` with `Match` cases.

`Monad` gets a new method `treeMap` which traverses a tree of Monads and transforms values.

```java
interface Monad<T> {
    default <U, Z> Monad<Z, M> treeMap(Function<U, Object> mapper) {
        return (Monad<Z, M>) map(Match
                .<Object> caze((Monad m) -> m.treeMap(mapper))
                .caze((U u) -> f.apply(u))
                .build()
        );
    }
}
```

**Unsafety 1**
If the type of the domain of the mapper function does not match the 'real' type, then a ClassCastException will occur at runtime.

**Unsafety 2**
treeMap does cast the result via generic method parameter

**Thoughts**
Being unsafe is a fair balance between _type safety_ and _viability_. E.g. `Monad.flatten()` works in a similar unsafe way. It assumes that the `Monad<T>` is of the form `Monad<? extends Monad<U>>`. Also `Traversable.{min,max,sum,product,...}` assume s.th. about the component type and may throw at runtime.

```java
// Adaption of your example
public class Issue185Test {

    static Option<String> extract(String str) {
        if (str.length() >= 15) {
            return Option.of(str.substring(10, 15));
        } else {
            return Option.none();
        }
    }

    @Test
    public void shouldTreeMapStream() {

       final Stream<Option<Long>> sums = Stream.of("cocotero", "chuchu blabla pinpon")
                .map(Issue185Test::extract)
                .treeMap(String::chars)
                .treeMap(IntStream::sum);

        // sums = Stream(None, Some(447))
    }
}
```

I really love this issue. Especially it shows me where I need to tweak the Javaslang API a little bit, i.e. it shows that in addition to `Match` a `CheckedMatch` is needed because we also have a `CheckedMonad` which is implemented by `Try`. There we deal with checked functions.

After adding the missing parts and polishing the code, this will go into release 1.2.1.

**Comment by ggalmazor** [comment]
Wow, this is awesome :)

**Comment by danieldietrich** [comment]
Thx :)
