### ISSUE TITLE
Option.map does not convert null to None

### ISSUE THREAD

**Issue by eric239** [javaslang/javaslang#1852]
With `java.util.Optional`:
```
assert Optional.of("").map(v -> null).isPresent(); // fails, as null mapping is translated to empty
```
with javaslang `Option`:
```
assert Option.of("").map(v -> null).isDefined(); // succeeds, as the result is Some(null)
```
It seems that the former is more intuitive than the latter; I've been replacing java.util functional artifacts with those from javaslang but this behavior broke my code in a few places. Is this a bug or design choice, and if it is the latter, what's the rationale?

**Comment by danieldietrich** [comment]
Thank you for the answer and for using Javaslang. It was already questioned and answered several times. Will close this as duplicate to #1636

**Comment by timmattison** [comment]
Updated link from other issue - http://blog.vavr.io/the-agonizing-death-of-an-astronaut/
