### ISSUE TITLE
HashSet and HashMap have unnecessary Spliterator.ORDERED characteristic

### ISSUE THREAD

**Issue by orionll** [javaslang/javaslang#1853]
Since HashSet/HashMap are unordered collections, the characteristic Spliterator.ORDERED is unnecessary. This can make certain parallel operations on Streams slower. I can post an example if you need.

**Comment by danieldietrich** [comment]
Thank you, you are right. There is already an issue for revisiting the spliterator characteristics: #1635 

We should implement #1635 instead of fixing this issue directly. However, I will keep this issue open as bug.
