### ISSUE TITLE
Thoughts on Async Streaming

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#186]
Generally it would be cool to be compliant to https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.0/tck/README.md

How could this play together with Java's [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html)? http://blog.jooq.org/2014/09/23/asynchronous-sql-execution-with-jooq-and-java-8s-completablefuture

**Comment by danieldietrich** [comment]
Here is a comparision of _akka-streams_ and _scalaz-streams_: https://softwaremill.com/comparing-akka-stream-scalaz-stream/#toc-streaming-transforming-a-file

Here is an application of _rxjava-jdbc_ covering compositional jdbc processing: https://github.com/davidmoten/rxjava-jdbc

**Comment by danieldietrich** [comment]
Also this: http://projectreactor.io/docs/reference/#reactor-stream

**Comment by danieldietrich** [comment]
Also have a look at [jdk9 Candidate classes Flow and	SubmissionPublisher](http://cs.oswego.edu/pipermail/concurrency-interest/2015-January/013641.html)

See [java.util.concurrent.Flow](http://gee.cs.oswego.edu/dl/jsr166/dist/docs/java/util/concurrent/Flow.html)

**Comment by danieldietrich** [comment]
Relation between Java 8 Stream and RxJava Reactive Streams: http://www.infoq.com/news/2015/10/javaone-2015-preview

(Search for "Java 8 Stream API and RxJava Comparison: Patterns and Performance")

**Comment by danieldietrich** [comment]
This looks like a very nice tutorial: **[Functional Reactive Programming in Java](https://realm.io/news/droidcon-gomez-functional-reactive-programming/?utm_content=bufferf39fa&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)**

**Comment by johnmcclean-aol** [comment]
FYI : The latest cyclops-javaslang module has a reactive-streams Publisher and Subscriber implementation for javaslang traversables (https://github.com/aol/cyclops/tree/master/cyclops-javaslang)

**Comment by danieldietrich** [comment]
Nice, thank you John! Hopefully I will find some time soon to play around with it.

**Comment by danieldietrich** [comment]
@johnmcclean-aol I admire you for handling the complexity of all of the cyclops modules and the dependencies between them! That is not trivial. E.g. when versions or even API changes.

**Comment by danieldietrich** [comment]
I see different Java 8 libraries emerge which support bindings/abstractions for other libraries. [Cyclops](https://github.com/aol/cyclops) is one of them, [derive4j](https://github.com/derive4j/derive4j) is another.

Are there performance impacts when converting between the two worlds, e.g. by converting elements one-by-one, or do you follow the delegation principle?

**Comment by johnmcclean-aol** [comment]
cyclops is really just a series of extensions for JDK 8. 

Javaslang is like an alternative, more functional, JDK. The same extensions (such as AnyM, for-comprehensions, reactive-streams support) can be applied to either, there should be no performance penalty for choosing Javaslang over the JDK (for example).

Javaslang just doesn't need some of the extensions, because it has that functionality already (e.g. cyclops-functions), but some of the others could be migrated (for example the full async Streaming support in cyclops-streams) to cyclops-javaslang over the next few months.

Gradle is awesome, helps manage the build and dependencies. I much prefer building and managing lots of small independent projects to larger ones, where possible :)

**Comment by danieldietrich** [comment]
Sounds absolutely awesome. I'm looking forward to reactive streaming (I will focus on pull, mostly because I think that it is more easy to deal with back-pressure then).

I'm not familiar with gradle. I've heard pros and cons (as always, there isn't 'the perfect tool'). Think I should give it a try.

**Comment by danieldietrich** [comment]
out of scope for Javaslang
