### ISSUE TITLE
Interface support for replaceAt?

### ISSUE THREAD

**Issue by devinrsmith** [javaslang/javaslang#1862]
Hi,

A common operation that I find myself calling is

`removeAt(ix).insert(ix, value)`.

It seems like this might be a relatively common pattern, and could be more efficiently implemented with the interface

`replaceAt(ix, value)`.

Cheers.

**Comment by devinrsmith** [comment]
I see now that `patch` exists, but has slightly different semantics than `removeAt(ix).insert(ix, value)`. (It looks like `patch` silently coerces out of bounds indices.) I think `replaceAt` still has value!

**Comment by danieldietrich** [comment]
@devinrsmith I think you mean the existing `update(index, value)` function. Does it work for you?

**Comment by devinrsmith** [comment]
Ha!

Not sure how I missed that... it's a large interface, but still...

Thanks!

**Comment by danieldietrich** [comment]
Great, thank you :)
