### ISSUE TITLE
Is there a method to serialize Javaslang objects using Jackson?

### ISSUE THREAD

**Issue by DouglasBrunner** [javaslang/javaslang#1885]
Has anyone come across documentation related to returning Javaslang objects (ex: control or collection) from a SpringBoot controller (which in turn uses Jackson)?

When using SpringBoot and returning a Javaslang collection as I would normally return a Java collection a ``HttpMessageNotWritableException`` error is thrown.

```java
    @RequestMapping(value="list", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public List<String> returnList() {
        return List.of("Bob", "Alice");
    }
```

    Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: Direct self-reference leading to cycle (through reference chain: javaslang.collection.List$Cons["option"]->javaslang.control.Option$Some["option"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: javaslang.collection.List$Cons["option"]->javaslang.control.Option$Some["option"])

I've found that Javaslang provides helper functions to convert collections to native Java objects, which work as intended.

```java
    @RequestMapping(value="list", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public java.util.List<String> returnList() {
        return List.of("Bob", "Alice").toJavaList();
    }
```

However, it would be nice to have a solution where Jackson could serialize/deserialize Javaslang objects natively instead of having to first convert them to their Java equivalents.

**Comment by danieldietrich** [comment]
@DouglasBrunner Did you take a look at https://github.com/javaslang/javaslang-jackson ?

**Comment by DouglasBrunner** [comment]
Thanks for the suggestion Daniel. That was the exact solution.

I'll leave some documentation for future readers who may come across this.

Firstly, there is a Spring [blog post](https://spring.io/blog/2014/12/02/latest-jackson-integration-improvements-in-spring#jackson-modules) that explains how to use Jackson modules in SpringBoot.

Add the Javaslang dependencies to your POM file.

	    <dependency>
		<groupId>io.javaslang</groupId>
		<artifactId>javaslang</artifactId>
		<version>2.0.5</version>
        </dependency>
        <dependency>
            <groupId>io.javaslang</groupId>
            <artifactId>javaslang-jackson</artifactId>
            <version>2.0.5</version>
        </dependency>

Register the module in your application

	@SpringBootApplication
	public class DemoApplication {

		public static void main(String[] args) {
			SpringApplication.run(DemoApplication.class, args);
		}

		@Bean
		public Module jacksonBuilder() {
			return new JavaslangModule();
		}

	}

Return Javaslang objects directly in the controller. Nice and concise.

	@RestController
	@RequestMapping("/javaslang")
	public final class DemoController {

		@RequestMapping(value="list", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
		@ResponseBody
		public List<String> returnList() {
			return List.of("Bob", "Alice");
		}

		@RequestMapping(value="either", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
		@ResponseBody
		public Either<String, Boolean> returnLEither() {
			Either<String, Boolean> result = Either.left("Bob");
			return result;
		}

	}

**Comment by danieldietrich** [comment]
@DouglasBrunner many thanks!
