### ISSUE TITLE
Fix SortedMap extension

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1886]
Now `SortedMap<K, V>` extends `Ordered<K>` and there is two identical methods
```
Comparator<K> comparator();
Comparator<K> keyComparator();
```
I believe `SortedMap<K, V>` should extend `Ordered<Tuple2<K, V>>` to provide two different methods
```
Comparator<Tuple2<K, V>> comparator();
Comparator<K> keyComparator();
```
`Ordered` interface introduced in `2.1.0`, so we can do it in this milestone.
This issue also belongs to `Multimap` case (see #1694)

**Comment by danieldietrich** [comment]
Hi Ruslan, yes you are right, it is redundant. We can't assume that elements of type V are (naturally) comparable. Therefore A Comparator&lt;Tuple2&lt;K, V>> would effectively compare only the key elements (keys are unique, so this is sufficient).

I think we should leave it this way, **deprecate** keyComparator() and remove it in 3.0.0.

**Comment by ruslansennov** [comment]
@danieldietrich or we can just mark `keyComparator()` as deprecated? I bow to that decision
