### ISSUE TITLE
Vector.of() is ambiguous with GWT compiler

### ISSUE THREAD

**Issue by nfekete** [javaslang/javaslang#1896]
There are two static methods overloading `Vector.of()`. One is accepting a single [`T element`](https://github.com/javaslang/javaslang/blob/21858c024061c1bf1a248d75e01a5b63520e7c26/javaslang/src/main/java/javaslang/collection/Vector.java#L97), the other a varargs [`T... elements`](https://github.com/javaslang/javaslang/blob/21858c024061c1bf1a248d75e01a5b63520e7c26/javaslang/src/main/java/javaslang/collection/Vector.java#L111). The GWT compiler creates a method reference to the wrong method (`T element` instead of the varargs version) when inferring the method reference from the body of [`Vector.tabulate`](https://github.com/javaslang/javaslang/blob/21858c024061c1bf1a248d75e01a5b63520e7c26/javaslang/src/main/java/javaslang/collection/Vector.java#L128). This way, under GWT, the `tabulate` method will create a `Vector` of arrays instead of `Vector` of `T`.

Since AFAIK GWT uses the eclipse compiler, this probably causes problems with older version of eclipse too (haven't tested).

I think it's a bit unfortunate that the two methods share the same name since ambiguity can happen. What if I want a Vector of arrays? What if I want a vector of elements of the array. I think renaming the varargs version to `ofAll` would make sense and would align it to the other methods which accept either primitive varargs or iterables or streams.

Another solution could be to remove the `Vector.of(T element)` version altogether, since the varargs version should be enough, that's what varargs was invented for in the first place.

Personally, I like the first (rename) solution more , but the second one (remove) could be backwards source-compatible, while the rename will not.

**Comment by nfekete** [comment]
There might be other collections with the same ambiguity, I haven't looked thoroughly, but `List` has the same issue.

**Comment by danieldietrich** [comment]
All collections will have that issue. We aligned the naming to standard Java.

Example:

* [java.util.stream.Stream.of(T... values)](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#of-T...-)
* [java.util.stream.Stream.of(T value)](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#of-T-)

We reworked already the factory method API because of ambiguities, see #721.
For special cases, like array of arrays, an explicit cast or type hint behind the '.' has to be provided.

Maybe it is an Eclipse Compiler bug. Java's Stream has the same problem.

**Comment by danieldietrich** [comment]
@ruslansennov could you please add the following gwt/javascript tests to javaslang-gwt project:

Factory method tests:

* `assertThat(Set.of(1).contains(1)).isTrue()`
* `assertThat(Set.of(1, 2).contains(2)).isTrue()`

API alias tests:

* `assertThat(Set(1).contains(1)).isTrue()`
* `assertThat(Set(1, 2).contains(2)).isTrue()`

These should ensure that the generated javascript code calls the right methods.

**Comment by ruslansennov** [comment]
sure

**Comment by nfekete** [comment]
You could add this as well
`assertThat(Vector.tabulate(2, Function.identity()).contains(1)).isTrue()`

**Comment by ruslansennov** [comment]
@nfekete, thank you I confirm the problem. This test passes in GWT and of course fails in Java
```java
// GWT scope
public void testTabulate() {
    Vector<?> v = Vector.tabulate(2, Function.identity());
    // actually v is not {0, 1} but is {{0, 1}}
    assertTrue(v.size() == 1);  // true in GWT, false in Java
    Object[] head = (Object[]) v.get(0);
    assertEquals(head[1], 1);
}
```

**Comment by danieldietrich** [comment]
@ruslansennov isn't this a general problem for javascript? How to choose the right method in an untyped language:

```java
function of(element) { ... }

function of(elementArray) { ... }
```

In Javascript these are the same.

**Comment by ruslansennov** [comment]
Daniel, you're right, JavaScript is funny... 
We can change signature of internal `Collections.tabulate(...)` from
```java
C tabulate(int n, Function<? super Integer, ? extends T> f, C empty, Function<T[], C> of)
```
to something like
```java
C tabulate(int n, Function<? super Integer, ? extends T> f, C empty, Function<java.util.List<T>, C> of)
```
and this solves the problem.

**Comment by danieldietrich** [comment]
@ruslansennov thank you, that sounds good!

`of` will then be `ofAll`. It should be sufficient if it takes an Iterable (does not matter much here):

```java
C tabulate(int n, Function<? super Integer, ? extends T> f, C empty, Function<Iterable<T>, C> ofAll)
```

I would stay with the array:

```java
final T[] elements = (T[]) new Object[n];
```

and finally wrap the array as List:

```java
return ofAll.apply(Arrays.asList(elements));
```

**Comment by ruslansennov** [comment]
... and we should check all other factory methods in GWT

**Comment by nfekete** [comment]
Are you sure it's a JS problem? Somehow I assumed that the GWT compiler is there for us to work around JS funkyness (I'm using a mild word here), and was totally convinced that this bug is the GWT compiler's fault, more precisely the Eclipse compiler embedded and used by GWT.

**Comment by nfekete** [comment]
GWT compiler actually creates differently named js methods for overloaded java methods, so I really think this is not a JS problem. GWT (relying on info from the ECJ) just generates a reference to the wrong method.

**Comment by danieldietrich** [comment]
@nfekete To report a GWT bug we need a minimal example. S.th. like this:

```java
import java.util.function.Function;

public class Test {

    public static void main(String[] args) {
        new Test().run();
    }

    void run() {
        String result = test(this::of);
        if ("one".equals(result)) {
            throw new Error("'many' expected but found 'one'");
        }
    }

    <T> String of(T t) {
        return "one";
    }

    <T> String of(T[] ts) {
        return "many";
    }

    static <T> String test(Function<T[], String> of) {
        T[] ts = (T[]) new Object[] { null };
        return of.apply(ts);
    }

}
```
@ruslansennov could you run that code please in a GWT test/example (on the client side)?

**Comment by nfekete** [comment]
Now I'm really baffled. Something deeper is going on here. I tried your example by including it into the javaslang-gwt-example project and it works. The bug doesn't manifest itself.

**Comment by danieldietrich** [comment]
Interesting. Then we should strip down the Javaslang library to the classes and methods that are called (but keep the implementations as far as possible).

There are still differences, for example the Collections class is package private and so on.

I will create a stripped down example tomorrow, need some sleep.

**Comment by nfekete** [comment]
Okay, I figured out something. The method reference GWT generates is actually good. The `Test.of(T...)` gets referenced but the passed-in array of `T`s is actually a one-element array consisting of the array of elements that should get passed wrapped in as the first element of the array. So, in practice, the array argument gets wrapped in another array.

**Comment by nfekete** [comment]
Here's a small test case to reproduce the behavior:
```
import java.util.function.Function;

public class Test {

    public static void main(String[] args) {
        String[] array = new String[] { "1", "2" };
        first(array);
        Function<String[], String> fn = Test::first;
        fn.apply(array);
    }

    static String first(String... strings) {
        return strings[0];
    }

}
```

It seems this is a GWT problem, not Eclipse Compiler for Java problem. I'm gonna file a bug for GWT based on this.

Sorry for wasting your time with this, it has nothing to do with Javaslang.

**Comment by nfekete** [comment]
GWT issue filed at: https://github.com/gwtproject/gwt/issues/9497

**Comment by ruslansennov** [comment]
This blocks `javaslang-gwt` release. I'm not sure we should fix javaslang internals or should wait for next version of GWT, but I would reopen this issue for a while

**Comment by danieldietrich** [comment]
@ruslansennov it should not affect our 2.1.0 release. It [will be fixed](https://github.com/gwtproject/gwt/milestone/17) in GWT 2.8.1. If GWT 2.8.1 isn't out before Javaslang 2.1.0, we are able to release javaslang-gwt-2.1.1 without changing javaslang-2.1.0.

I would close this ticket.

**Comment by ruslansennov** [comment]
"The fix should be straightforward" - good news :)

**Comment by nfekete** [comment]
GWT fix landed in HEAD, which has snapshots built as maven version HEAD-SNAPSHOT, see here:
https://oss.sonatype.org/content/repositories/google-snapshots/com/google/gwt/gwt-servlet/HEAD-SNAPSHOT/
I tried the above repro snippet and it works correctly.

**Comment by nfekete** [comment]
`Vector.tabulate()` also works correctly with `gwt-HEAD-SNAPSHOT`.

**Comment by danieldietrich** [comment]
Great to hear!
