### ISSUE TITLE
Clarify backwards compatibility

### ISSUE THREAD

**Issue by skestle** [javaslang/javaslang#1912]
At https://github.com/javaslang/javaslang/blob/master/CONTRIBUTING.md#backward-compatibility it states 
> We distinguish between 3 kinds of (backwward-)compatibilty
and 
> We currently check for API changes (which may affect the binary compatibility)

I believe that javaslang is stating that it interprets Semantic Versioning's backward compatibility to mean binary compatibility (drop in jar replacement), and so all major versions will be binary compatible.

Is this correct/can the documentation be updated?

**Comment by skestle** [comment]
Somehow I messed this up and made #1913

**Comment by danieldietrich** [comment]
Hi,

> I believe that javaslang is stating that it interprets Semantic Versioning's backward compatibility to mean binary compatibility (drop in jar replacement)

Our versioning scheme is `<major>.<minor>.<bugfix>`.

**Bugfix** releases are drop-in replacements. Often semantics change when a bug is fixed (e.g. unexpected exception was thrown).

**Minor** releases (like the upcoming 2.1.0) are targeted to be binary compatible and therefore also drop-in replacements. We might change bounds of generics, which sometimes causes source backward compatibility problems. However, if the source is under control, this is no problem.

**Major** releases are meant to evolve Javaslang. This includes breaking backward compatibility by removing deprecated things. Please don't expect a major release to be backward compatible.

**Comment by danieldietrich** [comment]
> Somehow I messed this up and made #1913

Will take a look :)

**Comment by skestle** [comment]
Your first comment seems like it's in the documentation, but I didn't see it. That's way better than mine ;)

**Comment by danieldietrich** [comment]
I've edited the comment. You may copy it to your PR - your sentence needs to be changed.
