### ISSUE TITLE
Compile to TypeScript

### ISSUE THREAD

**Issue by paplorinc** [javaslang/javaslang#1928]
According to http://www.jsweet.org/candies-snapshots it should be possible to use `jsweet` to compile Javaslang to TypeScript/JavaScript.

@ruslansennov, do you think this could be [better than GWT](http://www.jsweet.org/comparing-the-gwt-transpiler-and-jsweet/)?

**Comment by ruslansennov** [comment]
Hi @paplorinc 
Sorry, I can't say anything... 
I'm not familiar with `jsweet` and with `TypeScript`, but your link looks very interesting

**Comment by danieldietrich** [comment]
@paplorinc I think it is different. Gwt can be used without leaving the Java world. Technically it compiles to Javascript but the developer does not need to know it. (However, the Gwt developer _may_ also add his/her own Javascript snippets)

**Comment by danieldietrich** [comment]
@paplorinc I think this issue does not fit well into the core javaslang project. We could create a new project `javaslang-typescript` but I don't think there is a real use-case.

Personally I'm doing some javascript (and typescript). Programmers that do Javascript will look in the JS ecosystem for libraries.

* There are already libraries present for FP, like [ramda.js](http://ramdajs.com).
* Also [scala.js](https://www.scala-js.org) is a type-safe way to create Javascript from Scala.

Beside that we can't substitute our Gwt project with this kind of Javascript compilation.

I think we should close this ticket.

**Comment by paplorinc** [comment]
Thanks for the documentation :)
What is the GWT project's purpose than, if you rather recommend other libs for javascript programmers?

**Comment by danieldietrich** [comment]
> What is the GWT project's purpose than, if you rather recommend other libs for javascript programmers?

_GWT and Javascript_ is like comparing _Coffee and Tee_.

GWT is 'web programming for Java developers'. Years ago I've done a bit GWT programming. The layout felt a little bit like Swing programming :-)

Vaadin integrates with/is built on top of GWT: https://vaadin.com/gwt

**Comment by danieldietrich** [comment]
@paplorinc This is GWT code: https://github.com/vaadin/gwt-polymer-elements/blob/master/demo/src/main/java/com/vaadin/polymer/demo/client/sampler/Sampler.java#L369-L386
