### ISSUE TITLE
Iterator caused Deadlock on Static Class Initialization

### ISSUE THREAD

**Issue by pli2014** [javaslang/javaslang#1941]
![image](https://cloud.githubusercontent.com/assets/6429799/24786234/7205c45a-1b92-11e7-913f-6c11ebb1ba1d.png)
https://bugs.openjdk.java.net/browse/JDK-8037567  

It got a dead-lock when multiple-threads call javaslang. 
Traversable.iterator-->AbstractIterator.clinit-->Iterator.clinit-->default中的Traversable

**Comment by ruslansennov** [comment]
duplicate #1773

**Comment by pli2014** [comment]
got it thks

**Comment by danieldietrich** [comment]
@pli2014 the new Version 2.0.6 includes the bugfix. Please update your version.
