### ISSUE TITLE
Iterator.max() returns None for one-element Iterator.

### ISSUE THREAD

**Issue by jezovuk** [javaslang/javaslang#1943]
Trivial test case:
`Iteartor.of(5).max().isEmpty() == true`

From source code, the problem seems to be in `Traversable.max()` where `isEmpty()` check is made _after_ conversion of current instance (Iterator, in this case) to `Stream`. Conversion to Stream consumes the first element of the Iterator, thus leaving the Iterator empty.

Conceptually, the problem is caused by non-immutable nature of Iterator (which makes it different from all other Traversable-s). In that respect, I'm looking forward to resolution of #1295.

**Comment by danieldietrich** [comment]
Wow, thank you for the finding! This corner case slipped through our test suite. We covered only min()/max() computation of multiple elements.
