### ISSUE TITLE
[Design Question] Should Traversable.head() return None<T>?

### ISSUE THREAD

**Issue by ggalmazor** [javaslang/javaslang#202]
Why does ```Nil.head()``` throw at the moment? Should it return ```None<T>``` instead?

Currently there isn't a "safe" direct way to get the head element, tail or last element from Traversables... We need to ```Try.of(()->list.head()).orElse()``` when using this.

[Java8's approach for Streams](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#findFirst--) does the trick. Maybe an overloaded findFirst() with no predicate should suffice.

If this breaks design, maybe we could have another set of "safe" methods that return Option values...

**Comment by danieldietrich** [comment]
Yes, I added this yesterday: #196 

I will release it with the groupBy() and sliding() features.

**Comment by danieldietrich** [comment]
Btw. - there's more in the pipeline. I will introduce all missing collection methods like scanLeft, scanRight, etc.

I'm looking at more sophisticated collection libraries than Java 8 Stream. E.g. Scala is way more sophisticated...

**Comment by danieldietrich** [comment]
Fixed by https://github.com/javaslang/javaslang/commit/e8321f5db2193e55b9e3545d64674520f6d1c81a
