### ISSUE TITLE
Create a new module javaslang-guava

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#219]
with an interface `Deguava` which converts Guava objects to Javaslang, in the same way like #218

**Comment by RobWin** [comment]
-1 
No compile dependency to guava please :)

**Comment by danieldietrich** [comment]
I will close this. We already have conversion methods for Iterables and standard Java collections. That is sufficient.

If the will be a great demand in future we can think again about special support for other libs like Guava (if it makes sense). But for not it is 'Schmuck am Nachthemd'.
