### ISSUE TITLE
[Epic] Extend the collection library

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#220]
This includes:

* #9 Tree transformation X
* #113 Tree extends Traversable ✓

Already finished:

* #102 Traversable.countOccurrences X
* #110 Traversable.groupBy ✓
* #170 Immutable HashMap ✓
* #214 Immutable TreeSet ✓
* #256 Re-organize collection.Tree ✓
* #271 More common TraversableOnce methods ✓
* #278 Immutable Stack ✓
* #279 Immutable Queue ✓
* #295 Immutable Array ✓
* #428 Add an immutable TreeMap to the javaslang.collection package ✓
* #429 Add an immutable HashSet to the javaslang.collection package ✓

Useful links:

* http://en.wikipedia.org/wiki/List_of_data_structures
* http://rosettacode.org/wiki/Rosetta_Code
* http://xlinux.nist.gov/dads/

**Comment by danieldietrich** [comment]
I've solved functionaljava/functionaljava#149 already for Javaslang but it will be interesting to track it anyway...

**Comment by danieldietrich** [comment]
An overview of the next version of Javaslang, especially the collection API (work in progress):

![javaslang-classes](https://cloud.githubusercontent.com/assets/743833/8150475/f0ca51d6-12eb-11e5-8f68-6d5730657740.png)

**Comment by danieldietrich** [comment]
`RedBlackTree` and `HashArrayMappedTrie` are backing data structures for the high-level collections `Map`/`SortedMap`, `Set`/`SortedSet` etc. I think it does not make sense to implement `Traversable`.

Here I want to share some thoughts on how to provide an appropriate abstraction for such data structures.

## Idea

1) The interfaces should be kept slim. We may add functionality to special interfaces like `RedBlackTree` in form of static methods. This functionality is called by high-level collections to implement the `Traversable` interface. I've seen this in Scala's [TreeSet](https://github.com/scala/scala/blob/v2.11.7/src/library/scala/collection/immutable/TreeSet.scala) which is used in conjunction with a [RedBlackTree companion object](https://github.com/scala/scala/blob/v2.11.7/src/library/scala/collection/immutable/RedBlackTree.scala).

2) Parent references will not be held.

3) **To be discussed:** I'm not sure if we will define general Tree methods which do not align very well with the nature of specific implementations. E.g. `getChildren()` makes not much sense for binary trees. Here we have a _left_ and a _right_ child. If we want a special Tree, like a BinaryTree, behave like a general Tree, maybe we should implement some sort of Views here. On the other hand - if we make our backing data structures public API, a full fledged general Tree interface would be nice.

## Interfaces

We may introduce a general `Tree` interface containing values of type `T`:

```java
interface Tree<T> {

    boolean contains(T value);

    // not sure about this, because of leaf trees with values only at leaves
    // T getValue();

    Tree<T> add(T value);
    Tree<T> remove(T value);

    boolean isEmpty();
    int size();

    // ...
}
```

`RoseTree` is the most general implementation of `Tree`.

Also we will need a top level interface `Trie`:

```java
interface Trie<K, T> {
    
    boolean containsKey(K key);
    boolean containsValue(V value);

    Option<V> get(K key);
    Trie<K, V> put(K key, V value);
    Trie<K, V> remove(K key);

    boolean isEmpty();
    int size();

    // ...
}
```

Both, `Tree` and `Trie`, do not inherit from each other and have no common base interface.

`RedBlackTree` will implement an interface `BinarySearchTree`:

```java
interface BinarySearchTree<T> extends Tree<T> {

    @Override
    BinarySearchTree<T> add(T value);

    @Override
    BinarySearchTree<T> delete(T value);
}
```

And then:

```java
interface RedBlackTree<T> extends BinarySearchTree<T> {

    @Override
    RedBlackTree <T> add(T value);

    @Override
    RedBlackTree <T> delete(T value);
}
```

and

```java
interface HashArrayMappedTrie<K, V> extends Trie<K, V> {

    @Override
    HashArrayMappedTrie<K, V> put(K key, V value);

    @Override
    HashArrayMappedTrie<K, V> remove(K key);
}
```

**Comment by ruslansennov** [comment]
<code>Trie.containsValue()</code> is a very strange method. It can be implemented by naive search along whole trie or by storing values in additional structure. I believe it must be removed from interface

**Comment by danieldietrich** [comment]
Yes, makes sense. I also think it belongs to the Map interface.

**Comment by danieldietrich** [comment]
I thought much about the Tree collections today and came to the following insight:

Javaslang's goal is to keep things as simple as possible - _when in doubt, leave it away_.

Therefore `HAMT` and `RedBlackTree` will not part of the standard collection type hierarchy. Instead they form an architectural _layer_ below our high-level collections (HashMap et. al.) as backing collections. However, they will definitely be public API because they have a high degree of reuse.

Given this, there is not need for the interfaces `Trie` and `BinarySearchTree` (for now). If they are needed in future, we will add them.

Under this condition, I will merge `Tree` and `RoseTree` and name it just `Tree`. Simple.

**Comment by danieldietrich** [comment]
Partial overview:

* `HashMap<K, V>` is backed by a `HashArrayMappedTrie<K, V>`
* `HashSet<T>` is backed by a `HashArrayMappedTrie<T, T>`
* `TreeSet<T>` is backed by a `RedBlackTree<T>`
* `TreeMap<K, V>` is backed by a `RedBlackTree<Entry<K, V>>` with key comparator

**Comment by danieldietrich** [comment]
![javaslang-2 0 0](https://cloud.githubusercontent.com/assets/743833/10067848/0483cd5c-62a0-11e5-96b1-6b4348082128.png)

**Comment by danieldietrich** [comment]
All of the stories of this epic are implemented.
