### ISSUE TITLE
List<Monoid<T>> standard reduction

### ISSUE THREAD

**Issue by ggalmazor** [javaslang/javaslang#221]
If a List contains Monoids of type T, it would be natural to reduce it just by calling reduce() with no args on the list, as the combination function and zero element is already defined for Monoids.

This would be helpful when working with ValueObjects that wrap around primitive types that are naturally combinable like Money, for example.

What do you think?

**Comment by danieldietrich** [comment]
Yes, we can do this. It would make an assumption regarding the runtime type of the List / Traversable. Like treeMap() and flatten().

Such methods are annotated with `@unsafe` to make clear that ClassCastExceptions can occure.

The empty List cannot be reduced, but this is clear. Therefore the zero element will never be used explicitely.

Let's do it!

**Comment by danieldietrich** [comment]
I think I was a little bit too fast with my answer - of course a type can be a Monoid regarding multiple operations. E.g. a currency can be multiplied (zero: 1) and added (zero: 0). It is not clear which monoid to take here.

I have an uneasy feeling with the whole `@unsafe` stuff (`flatten()` and `treeMap()`). We want to ship the best solution possible for creating robust programs. Being unsafe is contradictory.

Would you mind if I remove the unsafe methods in a future release? Do you use one of them? I regret the design decision to trade power with safety.

In the case of a `List<Monoid<T>>` we could provide s.th. similar to

```java
<U> Monoid<U> reduce(Function<? super T, ? extends Monoid<U>> f)

// example:
List.of(eur(10.0), eur(20.0)).reduce(Eur.product()); // = eur(200.0)
List.of(usd(10.0), usd(20.0)).reduce(Usd.sum()); // = usd(30.0)
```

**Comment by ggalmazor** [comment]
Of course! It's completely reasonable what you're arguing :) Don't worry about it. I don't like @unsafes too ;)

**Comment by danieldietrich** [comment]
Great! :+1:
