### ISSUE TITLE
Leverage Streams for Parallel Programming - E.g. Dataflow Programming / Functional Reactive Programming (FRP) / Communicating Sequential Processes (CSP) / Algorithmic skeleton (Parallelism Patterns)

### ISSUE THREAD

**Issue by sirinath** [javaslang/javaslang#231]
Libraries like http://www.paralleluniverse.co/quasar/, https://github.com/GPars/GPars, http://akka.io/ have this. It will be good to have similar features in this library also so you can have one cohesive library for similar needs.

**Comment by danieldietrich** [comment]
Thank you! Do you mean the feature of non-blocking streaming of data-chunks, which may be pulled from a source or may be also pushed from a source?

There has been some initial discussion in #79. At #186 I am tracking activities now.

**Comment by sirinath** [comment]
Something like this: 

```
Val<Integer> a = new Val<>();
Var<Integer> x = new Var<>();
Var<Integer> y = new Var<>(() -> a.get() * x.get());
Var<Integer> z = new Var<>(() -> a.get() + x.get());
Var<Integer> r = new Var<>(() -> {
    int res = y.get() + z.get();
    System.out.println("res: " + res);
    return res;
});

Fiber<?> f = new Fiber<Void>(() -> {
    for (int i = 0; i < 200; i++) {
        x.set(i);
        Strand.sleep(100);
    }
}).start();

Strand.sleep(2000);
a.set(3); // this will trigger everything
f.join();
```

(Sourced from: http://docs.paralleluniverse.co/quasar/)

**Comment by danieldietrich** [comment]
Without knowing how the classes are implemented this looks like some sophisticated implementation of the observer pattern with the addition of thread synchronization.

What I want is some few, strongly typed, composable building blocks. I haven't yet investigated what types of async abstractions are necessary to cover this whole topic with the minimum amount of types.

As said, without having deep-dived into that topic, the following dualities come to my mind:

* _concurrency_ (threads) vs. _distributed systems_ (clusters)
* _push_ vs. _pull_
* _blocking_ (sync) vs. _non-blocking_ (async)
* ...

Also non-functional aspects have to be covered, like

* automatic resource management (e.g. Autoclosables)
* automatic exception handling of composed _things_
* life-cycle management (when does information-flow end?)
* ...

**Comment by sirinath** [comment]
I guess GPars is the most complete implementation. Perhaps you can look under the hood for what is happening.

**Comment by sirinath** [comment]
In the JS world this is a very interesting implementation: http://noflojs.org/

**Comment by danieldietrich** [comment]
out of scope for Javaslang
