### ISSUE TITLE
Maximum arity of Function, Tuple et. al.

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#234]
I'm very interested in opinions about the maximum arity of Function, Tuple, etc. What does make sense?

**Comment by szarnekow** [comment]
In Xtend we support lambdas up to 6 params but I've yet to see a reasonable case with more than 4.

**Comment by danieldietrich** [comment]
Thx Sebastian, that helps!

**Comment by martin-g** [comment]
For lambdas lower number is OK.
But for Tuple I am not so sure.
I guess you already know that Scala supports arity of 22. There were many complains at http://slick.typesafe.com/ that sometimes the DB result/record could not fit in 22. So they replaced the usage of Tuple with HList.
In my personal experience I rarely needed something bigger than Triple.

**Comment by danieldietrich** [comment]
Thx @martin-g, Perspectively we should also add `HList`!

**Comment by danieldietrich** [comment]
Xtend uses 6, .Net/C# has 8, we stick with 8 for now (see #246)
