### ISSUE TITLE
Fan Out / Fan In Patterns in Streams

### ISSUE THREAD

**Issue by sirinath** [javaslang/javaslang#238]
Nice feature in Akka Streams (http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC2/scala.html?_ga=1.28851132.1234628154.1418042628) is the fan in and fan out patters. Perhaps you can have something similar in the stream related implementations.

E.g.

```
val writeAuthors: Sink[Author, Unit] = ???
val writeHashtags: Sink[Hashtag, Unit] = ???
val g = FlowGraph.closed() { implicit b =>
  import FlowGraph.Implicits._
 
  val bcast = b.add(Broadcast[Tweet](2))
  tweets ~> bcast.in
  bcast.out(0) ~> Flow[Tweet].map(_.author) ~> writeAuthors 
  bcast.out(1) ~> Flow[Tweet].mapConcat(_.hashtags.toList) ~> writeHashtags
}
g.run()
```

**Comment by danieldietrich** [comment]
A few weeks ago Roland Kuhn was here in Kiel and demonstrated the new Akka features at a Nordic Coding event - very impressive. I will take this into account for the 1.3.0 release, where this topic will be covered!

**Comment by danieldietrich** [comment]
Fan-in/fan-out is very similar to joining results in a parallel computation, as [explained here](https://zato.io/docs/progguide/patterns/fan-out-fan-in.html).

In Javaslang 2.0.0 we do this already for example with `Future`, which represents asynchronous computations handled by callbacks.

```java
final Promise<Z> promise = Promise.make();

final Future<T> task1 = Future.of(this::computation_1);
task1.onComplete(result1 -> {

    // fan-out
    final Future<U> task2 = Future.of(this::computation_2);
    final Future<V> task3 = Future.of(this::computation_3);

    // fan-in
    task2.zip(task3).onComplete(result23 -> promise.complete(...));
});

final Future<Z> task4 = promise.future();
```

To declare such flow akka-stream defines syntactic sugar `~>`. Maybe we can do s.th. similar in Javaslang. The example above could look like this:

```java
task1.pipe(task2::apply, task3::apply).pipe(task4::apply);
```

Here it is just the flow we sketch, callbacks is another story. The general idea is to circumvent the so-called 'callback-hell' (we know from Javascript for example) by _using Promise to escape the callback_.

**Comment by sirinath** [comment]
If you use a promise or future you can only generate one final value hence can you have an option for continuous data streams also.

**Comment by danieldietrich** [comment]
out of scope for Javaslang
