### ISSUE TITLE
Simulate ADT

### ISSUE THREAD

**Issue by sirinath** [javaslang/javaslang#239]

**Comment by jbgi** [comment]
You may be interested in https://github.com/sviperll/adt4j and a recent design discussion of the project: https://github.com/sviperll/adt4j/issues/20

**Comment by danieldietrich** [comment]
This is great!

We should take this into account when designing the collections. `List` and `Stream` are there, `Map` (#170) and `Set` (#214) are in the pipeline. I'm currently investigating which form of binary search tree to take in order to create efficient Map and Set implementations. Not only time complexity is important but also space complexity, particularly for HashMaps. There are important balanced tree impls, AVL and RedBlack. Scala uses binary encoded Tries in order to fail fast if a key/hash is not present. I'm into it - a very exiting topic!

**Comment by danieldietrich** [comment]
@sirinath Could you please provide some details, what to implement?

I think if it is a Java equivalent of Scala case classes, like adt4j project does, @jbgi mentioned above, it is out of scope for Javaslang. There already exists a great project that exactly does that!

**Comment by talios** [comment]
What would be nice is having some way that the two projects could intersect in user-land, which is in part the discussion @jbgi linked to - awhile ago I was thinking "it would be nice if these ADT4j classes were monads..."

**Comment by danieldietrich** [comment]
I'm against baking this annotation trickery into Javaslang. With [JEP 169](http://openjdk.java.net/jeps/169) there is already an official project to add Value Objects to Java. Beside that I don't like [annotations](http://www.annotatiomania.com) very well.

**Comment by danieldietrich** [comment]
@talios I think the Monad operations on one ADT can be expressed in multiple ways. It is likewise with Monoids (String concatenation, String multiplication, etc). It is better to express this explicitly.

**Comment by talios** [comment]
@danieldietrich True, altho going `FooMonad.map(foo, foo2 -> .... );` is kinda arse.

**Comment by danieldietrich** [comment]
@talios Yes, right...

**Comment by sirinath** [comment]
Also https://github.com/talios/javagadt/

**Comment by jbgi** [comment]
And now also https://github.com/derive4j/derive4j
(no special support for javaslang... yet!)

**Comment by danieldietrich** [comment]
Nice!

**Comment by jbgi** [comment]
In order to add special support for javaslang into derive4J, what I would need is a ```none``` and a ```some``` static factory method in the ```Option``` interface. the methods should return an ```Option``` (not a ```Some``` or a ```None```). Same for ```Either```, with ```left``` and ```right``` constructors.

**Comment by danieldietrich** [comment]
Can't this be declared as some sort of mapping file within derive4J? From the API perspective this does not scale very well. I mean, why isn't it possible to declare within derive4J which class is Option and how to create a None and a Some?

**Comment by jbgi** [comment]
The main problem is type inference. Derive4J use invariant generics: using explicit subtyping (```new Some()``` / ```None.instance()```) will probably breaks generated code.

**Comment by jbgi** [comment]
I did some tests, it complicate things a little bit but should be doable.
From a user point a view still thinks that having some/none constructors in Option that return Option is a good thing. Sub-typing complicate usage of parametric polymorphism a lot and I find the later far more useful for FP than the former.

**Comment by danieldietrich** [comment]
Great, this sound like the right direction!

**Comment by danieldietrich** [comment]
Too many ADT projects in Java land. We will wait for official Java support by oracle...
