### ISSUE TITLE
Add static methods to narrow Kind<F, T> to F<T>

### ISSUE THREAD

**Issue by jbgi** [javaslang/javaslang#251]
to follow a side discussion of #242:
> What is the use case you have in mind? It does not have a method of the shape of flatMap, i.e. it does not need the additional type information. The less the better...

I guess what I want is to be able to abstract over Monad/Functor/Apllicative (create methods that will work for every Functor) but then since the map method lose the kind (Functor is not 'Kinded'), For instance, if I pass a monad to a method that accept a functor an return the same functor after a call to map ; the result is now a Functor<> and I cannot recover its initial Monad nature (to use flatmap on it).
Also what I would need after that is a narrow method in each Kinded classes:
```java
    static <M extends Monad<M, ?>, T> Monad<M, T> narrow(Kind<M, T> option) {
        return (Monad<M, T>) option;
    }
    static <T> Option<T> narrow(Kind<Option<?>, T> option) {
        return (Option<T>) option;
    }
```

**Comment by danieldietrich** [comment]
This goes in the right direction. `narrow()` is tightly coupled with `Kind`:

```java
public interface Kind<TYPE extends Kind<TYPE, ?>, T> {

    /**
     * Performs a downcast, also known as <em>narrowing conversions</em>.
     * The resulting type approximately has the shape {@code TYPE<T>}.
     *
     * @return this instance casted to the type described by this kind.
     */
    Object narrow();
}
```

Then we have:

```java
interface Monad<M extends Monad<M, ?>, T> extends Kind<M, T> {
    
    @Override
    default Monad<M, T> narrow() {
        return this;
    }
}

interface Option<T> extends Kind<Option<?>, T>, Monad<Option<?>, T> {

    @Override
    default Monad<M, T> narrow() {
        return this;
    }
}
```

Clean version, no cast needed any more! In `Kind` the best we can say about the return type of `narrow` is, that it is an `Object`, but the interface is a contract, which defines the semantics. Should be ok!

**Comment by jbgi** [comment]
we need narrow to be static otherwise it is of no use (you call a method on Monad<M,T> to narrow it to Monad<M,T>: this is the identity function)
and the cast is unfortunately necessary (otherwise it would mean that we have safely solved higher kinded type in Java).

**Comment by danieldietrich** [comment]
I see, it should have been something like

```java
interface Kind<TYPE extends Kind<TYPE, ?>, T> {

    TYPE<T> narrow();
}
```

which isn't possible.

Would you mind to add the missing methods as Pull Request? I'm currently overloaded with the amount of incoming open tasks...

**Comment by danieldietrich** [comment]
@jbgi Btw - your method signatures look good!

```java
static <M extends Monad<M, ?>, T> Monad<M, T> narrow(Kind<M, T> option) {
    return (Monad<M, T>) option;
}
static <T> Option<T> narrow(Kind<Option<?>, T> option) {
    return (Option<T>) option;
}
```

I'm on a similar task with static `flatten()` methods...

**Comment by danieldietrich** [comment]
@jbgi I still don't understand why a direct type cast isn't sufficient instead of statically call a `narrow()` method, which does the same. Have you a code snippet for clarification?

If possible, I don't want to make the `narrow()` API puplic. It is internally used, only, isn't it?

**Comment by jbgi** [comment]
@danieldietrich the narrow method is here to isolate factorize the dirty work. Also it can be then used as a method reference. I agree that the method would need to be labelled "For advanced/internal usage only".
My use case is to factorize traversal code of the various optics.
What I would also need is a way to abstract over data constructors (for unit).
I will try to submit a PR for all of that. (I will be very busy in the next two weeks so that may be in a month or so).

**Comment by danieldietrich** [comment]
@jbgi This sounds exciting! Take your time to get it right, there is no hurry. I will be also on a short trip next weekend. Please try to cover the code with tests. This has saved me headaches in the past when it came to refactoring.

Have a great week!

**Comment by jbgi** [comment]
Thanks, you too!
Also, CONTRIBUTING mention eclipse_formatter.xml and idea-settings.jar files but I cannot find them... ?

**Comment by martin-g** [comment]
idea-settings.jar is in `.ide/` subfolder.

**Comment by jbgi** [comment]
@martin-g thanks!

**Comment by danieldietrich** [comment]
Given

```java
public interface Kind<TYPE extends Kind<TYPE, ?>, T> {
}
```

how would we define a Functor interface, which also works for Map?

```java
import java.util.function.Function;

public interface Functor<F extends Kind<F, ?>, A> {

    <B> Kind<F, B> map(Function<? super A, ? extends B> f);

    static <A> Functor<List<?>, A> lift(final List<A> list) {
        return list::map;
    }

    static <K, V> Functor<Map<?, ?>, Map.Entry<K, V>> lift(final Map<K, V> map) {
        // DOES NOT WORK, BECAUSE Map.map RETURNS A Seq
        return map::map;
    }
}

// placeholders, just examples
interface Traversable<T> {
    <U> Traversable<U> map(Function<? super T, ? extends U> mapper);
}

interface List<T> extends Kind<List<?>, T>, Traversable<T> {
    @Override
    <U> List<U> map(Function<? super T, ? extends U> mapper);
}

interface Map<K, V> extends Kind<Map<?, ?>, Map.Entry<K, V>>, Traversable<T> {

    @Override
    <U> Seq<U> map(Function<? super Entry<K, V>, ? extends U> mapper);

    // cannot be used for Functor
    <U, W> Map<U, W> map(BiFunction<? super K, ? super V, ? extends Entry<? extends U, ? extends W>> mapper);

    interface Entry<K, V> {}
}

interface Seq<T> extends Kind<Seq<?>, T>, Traversable<T> {
    @Override
    <U> Seq<U> map(Function<? super T, ? extends U> mapper);
}
```

/cc @jbgi

**Comment by jbgi** [comment]
well, map (from Functor) should preserve structure, so for a Map that would be:
```java
<V2> Map<K, V2> map(Function<V, V2> mapper);
```
given the above definition of map and one of (need to check if both compile correctly):
```java
interface Map<K, V> extends Kind<Kind<Map<?,?>, K>,V> ...
```
```java
interface Map<K, V> extends Kind<Map<K,?>,V> ...
```
then implementing Functor should work.

**Comment by danieldietrich** [comment]
Yes, great - wonder how Scalaz works here, need to check that.

However, here it will look like:

```java
public interface Functor<F extends Kind<F, ?>, A> {

    <B> Kind<F, B> map(Function<? super A, ? extends B> f);

    // intentionally not Map<? extends K, ? extends V> because K is fixed
    static <K, V> Functor<Map<K, ?>, V> lift(final Map<K, ? extends V> map) {
        return f -> map.iterator().map(entry -> entry.map(k -> k, f)).toMap(Map.Entry::toTuple);
    }
}

interface Map<K, V> extends Kind<Map<K,?>,V>, Traversable<Map.Entry<K, V>> {

    @Override
    <U> Seq<U> map(Function<? super Entry<K, V>, ? extends U> mapper);

    // cannot be used for Functor
    <U, W> Map<U, W> map(BiFunction<? super K, ? super V, ? extends Entry<? extends U, ? extends W>> mapper);

    Iterator<Entry<K, V>> iterator();

    interface Entry<K, V> {

        <X, Y> Entry<X, Y> flatMap(BiFunction<? super K, ? super V, ? extends Entry<? extends X, ? extends Y>> mapper);

        <X, Y> Entry<X, Y> map(BiFunction<? super K, ? super V, ? extends Entry<? extends X, ? extends Y>> mapper);

        <X, Y> Entry<X, Y> map(Function<? super K, ? extends X> keyMapper, Function<? super V, ? extends Y> valueMapper);

        Tuple2<K, V> toTuple();
    }
}
```

**Comment by danieldietrich** [comment]
Meanwhile...

Javaslang moved in a different direction. Kind isn't used any more. And Monad was re-added as semi-Monad, flatMap takes a function that returns Iterable.

Neartime we will add Validation and with it Applicative. It is different than in Scalaz (or Cats), we have no Apply for example.

I think the monadic layer above Javaslang, as I suggested, is obsolete now. And going adhere with it probably also this issue. I will close it if you agree.

/cc @jbgi
