### ISSUE TITLE
Create a user-guide

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#280]
Take a look at asciidoc, gitbook, etc.

**Comment by danieldietrich** [comment]
We need a user guide. What are our _business_ and _technical_ requirements?

* which input format, e.g. markdown, ...
* which output format(s) (pdf, html, ...)?
* infrastructure, e.g. how to maintain/deploy?

Additionally we need a draft of an outline.

**Comment by RobWin** [comment]
Do you want to focus on source code examples? 
* AsciiDoctor is better than Markdown, if you want to show code examples and highlight important parts.

Do you want to be able to update the documentation on a tablet using just a Browser instead of using a developer notebook with Git and other tools installed?
* You could use GitHub, TravisCI and AsciiDoctor for that
* Or readme.io

Do you need offline documentation?
* AsciiDoctor can generate the same documentation in HTML, PDF and EPUB.

**Comment by lukaseder** [comment]
XML + XSLT = Any format! :)

**Comment by jasoet-gdp** [comment]
How about markdown. I think Github Flavoured Markdown is sufficient and a lot of people comfortable to write in markdown.

i will take a look to AsciiDoctor.

**Comment by jasoet-gdp** [comment]
How about integration with javaslang.com website. I think it cooler if documentation available on website too. So reader no need to look at github wiki.

**Comment by RobWin** [comment]
GitHub wiki sucks.
AsciiDoctor documentation looks like this. http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/
Table of Content can also be on the left or right side.
As I said Markdown sucks compared to AsciiDoctor, but the syntax is quite similar.

**Comment by jasoet-gdp** [comment]
AsciiDoctor seem nice.

+1 for AsciiDoctor

**Comment by jasoet-gdp** [comment]
any idea for draft of an outline?

**Comment by danieldietrich** [comment]
+1 for AsciiDoctor

@RobWin @jasoet-gdp I also thought about using Markdown because of simplicity. But asciidoc seems to be the right tool here. It is also simple but more powerful. It is a standardized way to produce documentation targeting different formats (print, web, ...). Let's take it! Compared to readme.io I prefer asciidoc because we have no vendor dependency and we are free to build our own build and deployment chain with the tools of our choice.

@lukaseder it may be tempting to use XML + XSLT. I've done it years ago with apache fop :-) My resumé: simple things are possible - complex things are masochistic ;-)

**Comment by danieldietrich** [comment]
@jasoet-gdp I will write an outline this evening (GMT+1 here)

**Comment by danieldietrich** [comment]
@RobWin The Griffon Guide looks awesome!

**Comment by lukaseder** [comment]
Why masochistic? It's fun! What do you mean by "complex"? Our docs are all done with XSLT: http://www.jooq.org/learn

**Comment by danieldietrich** [comment]
Maybe I'm a little out-dated here. I used fop 9-10 years ago. I'm sure that it emerged in the mean-time.

I prefer non-xml formats for readability reasons (less noise).

**Comment by RobWin** [comment]
No one wants to write text in XML! :)

Have a look at http://www.asciidocfx.com/ as a nice tool to write in AsciiDoctor with a live view.

**Comment by danieldietrich** [comment]
@robwin there needs to be a business case for lukas. The consumer of the documentation will see no difference I guess. However, a xslt from xml to asciidoc should be seemlessly possible :-)
/cc @lukaseder

**Comment by RobWin** [comment]
But the writer does see the difference, if you dont use a tool for docbook.

**Comment by jasoet-gdp** [comment]
Okay.  I'll try AsciiDoctor tonight. GMT+7 Here :)

**Comment by danieldietrich** [comment]
Great!

**Comment by danieldietrich** [comment]
Note:

We should target all of these output formats: HTML, PDF and EPUB.

Also the documentation should be integrated on the website. Maybe we will open a new tab for now because the website is a single page.

**Comment by RobWin** [comment]
Have a look at Spring Boot Docs too see how they are doing it with Maven

https://github.com/spring-projects/spring-boot/tree/master/spring-boot-docs

**Comment by jasoet-gdp** [comment]
Noted

**Comment by danieldietrich** [comment]
We will remove `slice(beginIndex)` since it has exactly the same semantics as `drop(count)` (even if slice() takes an index and drop() take a count).

However, `subSequence(beginIndex)` is still needed because it throws on invalid index.

**Comment by lukaseder** [comment]
> there needs to be a business case for lukas

Exactly. I can change stylesheet, layout, versioning, formatting, etc. *extremely* easily using XSLT. But if you don't need that, I agree that XML is more tedious to write. It's always a tradeoff.

**Comment by danieldietrich** [comment]
:+1:

**Comment by danieldietrich** [comment]
The **User Guide** should give an overview over the Javaslang 2.x functionality. Here is a draft/first shot of the outline:

Lines starting with `-` are hints to the corresponding methods/functions, e.g. `- memoized`.

```
Tuples
Functions and Lambdas
  Unchecked vs. Checked Functions
  Function Memoization
    - memoized
  Curried Functions
    - curried
  Function Composition
    - andThen
    - compose
  Lambda Type Reflection
    - getType
Interface Iterable
  Equality
    - equals
    - eq
    - corresponds
Values
  Capturing State and Monadic Operations
    - get
    - isEmpty
    - map
    - flatMap
    - filter
  Conversion Operations
    - toXxx
  Side Effects
    - forEach
    - peek
    - out
    - stdout
    - stderr
Lazy Evaluation
Controls
  Option: Null Safety
  Try: Failure Handling
  Either: Disjoint Union Type
  Pattern Matching
Collections
  Interface TraversableOnce
  Interface Traversable
  Sequences
    Indexed Sequences
    Linear Sequences
  Sets
  Maps
  Concrete Immutable Collection Classes
  Arrays
  Character Sequences
  Iterators
  Conversions Between Java and Javaslang
    - ofAll
    - toXxx (see Value)
  Performance Characteristics
Concurrency
  Future
  Promise
Property Checking
  Generators
  Arbitrary Objects
  Properties
  Check Results and Assertions
```

**Comment by danieldietrich** [comment]
We should add an additional first-level section **Idioms**, which provides deep insight into the design of Javaslang.

**Idiom: Static Factory Methods**

Javaslang's collection interfaces like Seq, IndexedSeq, ..., Set, ... are similar to Scala's. But there is one important difference: Javaslang does not provide static factory methods for _inner interfaces_ (read: non-terminal types) like Seq. Exception: List, but this is not really an exception, because List is composed of Nil and Cons, so we need factory methods in the List interface.

**Example:**

```java
// Scala: Seq[Int] = List(1, 2, 3)
val seq = Seq(1, 2, 3)

// Javaslang: Seq<Integer> = List(1, 2, 3)
Seq<Integer> seq = List.of(1, 2, 3)
```

What we see is, that Scala provides a default implementation for Seq, which is List. In Javaslang, we keep the (Java) code clean of any kind of implicit defaults, conventions over configuration magic etc. Everything is explicit, the user has to choose the behavior. This makes the code readable and predictable and we are able to reason about it.

**Comment by danieldietrich** [comment]
@jasoet-gdp @RobWin in a first step we should setup asciidoc within our project. E.g. by adding it to the pom.xml. The resources should not be included in a 'normal' build/jar. It is ok, if we build it locally 'by hand' in a first step, i.e. it is not necessarily needed to be built automatically with a travis-ci build for now.

Question: Are there any best practices for the (maven) folder/project structure, e.g.

* src/main/asciidoc
* doc/...
* src-doc/...

If we have the build up and running, the second step is to create the outline (without content). It would be cool to see html, pdf and epub at this stage :-)

**Comment by RobWin** [comment]
Is Javaslang a standard GitHub account or an organsiation?
Create another repo or maven module called `javaslang-docs` and the folder `src/main/asciidoc`.
Create an `index.adoc` which includes all other files and specifies some constants. See as an example https://github.com/spring-projects/spring-boot/edit/master/spring-boot-docs/src/main/asciidoc/index.adoc

**Comment by danieldietrich** [comment]
Thx! Javaslang is currently a GitHub account. I hesitated to convert it to an Organization because there is no way back and I don't know the benefits. Can you explain?

**Comment by RobWin** [comment]
Add the AsciiDoctor maven plugin
```,xml
<plugin>
						<groupId>org.asciidoctor</groupId>
						<artifactId>asciidoctor-maven-plugin</artifactId>
						<version>1.5.2.1</version>
						<executions>
							<execution>
								<id>generate-doc</id>
								<phase>generate-resources</phase>
								<goals>
									<goal>process-asciidoc</goal>
								</goals>
								<configuration>
									<sourceDocumentName>index.adoc</sourceDocumentName>
									<backend>html5</backend>
								</configuration>
							</execution>
						</executions>
					</plugin>
```

**Comment by jasoet-gdp** [comment]
I think its better if javaslang converted to Organization. So more people (github account) can associate with it. 

For AsciiDoctor there are a lot of example using maven plugin https://github.com/asciidoctor/asciidoctor-maven-examples. We just need to pick what we need.

@danieldietrich so, which repository that we will use to store User-Guide. I think its better if user-guide repository separated from main javaslang repository.

**Comment by RobWin** [comment]
In an organisation you can have multiple repos under one common name and you can create teams and add members to teams which are allowed to contribute to different repos.

**Comment by jasoet-gdp** [comment]
@danieldietrich @RobWin and if javaslang in an organization, we can create a repo contains example usage for `javaslang` in conjunction with other framework such as `Spring Framework`, `Spring Data JPA`, `Jackson JSON Module`, etc.

**Comment by danieldietrich** [comment]
@jasoet-gdp @RobWin this all sounds really exiting. The only stopper of progress can be only 'fear' - as always in life... My fear is to loose control, e.g. about growth. Let me sleep one night about that and I will create an organization :-)

**Comment by danieldietrich** [comment]
@jasoet-gdp @RobWin Done. Javaslang is now an organization. Feels good :-)

**Comment by danieldietrich** [comment]
Wooaah - this turns out to be complicated. Whom to invite to the organization an whom not??

**Comment by danieldietrich** [comment]
@jasoet-gdp @RobWin I've created a new repo [javaslang-docs](https://github.com/javaslang/javaslang-docs). You will get write permissions there when joining the organization.

**Comment by RobWin** [comment]
You dont have to add us as Team members. We still can and should contribute via PRs.

**Comment by danieldietrich** [comment]
Ok. What is your suggestion regarding whom to invite to take part of the open source organization? How do other companies it?

**Comment by danieldietrich** [comment]
I like to have a team of committers - active or not.

**Comment by danieldietrich** [comment]
PR's are important. They need to be mentioned in the CONTRIBUTION file (which needs a rewrite). I like the [Typelevel Scala CONTRIBUTION.md](https://github.com/typelevel/scala/blob/2.11.x/CONTRIBUTING.md).

**Comment by danieldietrich** [comment]
Documentation has now its own home (and issues). We close this ticket. Next we will create an outline. 

See javaslang/javaslang-docs#7
