### ISSUE TITLE
Add retry functionality to Try

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#293]
@RobWin had the idea to extend `Try` with a retry functionality, s.th. like

```java
Try.of(Retry.of(3,supplier)).onFailure(x -> { println("whoops"); }).get()
```

which will execute `onFailure` at most once, regardless how often the supplier is _retried_.

This is a great Idea. In general the exception handling can be augmented this way with additional functionality. Examples:

```java
Try.of(CircuitBreaker.of(Retry.of(3, supplier))).get();
Try.of(Metrics.of(supplier)).get();
// etc.
```

The remaining question is how to integrate `Retry` without blowing up the number of classes too much.

One solution is to add a static `retry` method to `CheckedSupplier` and `CheckedRunnable`, i.e.

```java
interface CheckedSupplier<T> {

    T get() throws Throwable;

    /**
     * Tries {@code supplier.get()} n times before throwing.
     */
    static <T> CheckedSupplier<T> retry(int n, CheckedSupplier<T> supplier) {
        if (n < 1) {
            throw new IllegalArgumentException("n < 1");
        }
        Objects.requireNonNull(supplier, "supplier is null");
        return () -> {
            for (int i = 1; i <= n; i++) {
                try {
                    return supplier.get();
                } catch(Throwable x) {
                    if (Cause.isFatal(x) || i == n) {
                        throw x;
                    }
                }
            }
            // we will never get here - another line not covered by unit tests
            return null;
        };
    }
}
```

Btw. the `Cause.of(x).isFatal()` should be changed to `Cause.isFatal(x)`. This saves intermediate object creation.

**Comment by RobWin** [comment]
+1 :)

**Comment by RobWin** [comment]
We could even easily add memorization (cache) for requests.

**Comment by danieldietrich** [comment]
I'm now clear regarding the question which of these should be implemented:

1. `Try.retry(3, supplier).get()`
2. `Try.of(supplier).retry(3).get()`
3. `Try.of(Retry.of(3, suppllier)).get()`
4. `Try.of(retry(3, supplier)).get()`, with `CheckedSupplier.retry(3, supplier)`


The first and second solutions 'pollute' the purity of the `Try` monad. It is not the _composable_ way.

The third solution is a viable alternative. But there is no need for an additional Type `Retry`. The type encapsulates no _knowledge_, which can be used via public API. It just has a constructor/factory method `Retry.of`.

This leads to the fourth solution, providing a factory method on the CheckedSupplier/CheckedRunnable, which delivers specific instances. There it is, where it belongs to.

**Comment by danieldietrich** [comment]
@RobWin yes, that's right! This is a great way to do it!

**Comment by szarnekow** [comment]
Which exception would be passed into the failure? The first one or the last one? A composite of all exceptions?
Reasoning behind this question:
Assuming to try / retry a web request. The request may be invalid thus the first one gets a proper error message but the server may respond smth like 'too many requests from host' for the last n requests.
Also a delay for the retry or a filter (RetryIf) may be helpful.

**Comment by danieldietrich** [comment]
@szarnekow You are right. This is a signal that Javaslang should offer core functionality and additions should be built on top of it. Yesterday I wrote:

> Although these additions, especially Retry, are very sweet, I think that Javaslang should be kept as a thin core. Applications, and maybe other libs, should be built on top. Also I tend to keep async collections out of Javaslang. An additional module would make more sense. Scala for example made the 'mistake' to integrate Xml natively into the language. Now they regret it. The key to maintainability is simplicity.

The question is, does it help to include a `retry` (which fails by default with the last exception)?

Maybe we should make it configurable (return first/last/all exception(s)). But my impression is that we blow up the API. However, we may not meet all cases...

**Comment by danieldietrich** [comment]
Retry functionality is domain specific and will not be implemented by Javaslang (core).

**Comment by RobWin** [comment]
The retry logic can be refined anyway. The question here is where to put the logic.
Keep in mind that we also need factory methods which return Runnable, Supplier and Function. Not only the Checked versions. Otherwhise I must always use Try and can't use Completablefuture directly.
This brings me back to a Rety.of() as a container for multiple static factory methods. What do you think?

**Comment by RobWin** [comment]
Or we need a generic solution.

**Comment by danieldietrich** [comment]
@RobWin I have mixed feelings to retry unchecked functions because the do not fail by contract. However, I see the need and would use a Retry type with factory methods for checked and unchecked versions.

**Comment by RobWin** [comment]
The signature for a more complex retry logic could be: Retry.of(supplier, retryConfig) so that the config is extendable.

**Comment by danieldietrich** [comment]
@RobWin Maybe the decorate methods have to have different names because of ambiguities but I'm not sure.

For now, I don't want to create additional Javaslang modules except a [http://blog.higher-order.com/blog/2012/09/13/what-purity-is-and-isnt/](purely) functional core (baking purity directly into the Javaslang core is not a good idea. It is a higher kind of functional abstraction).

Maybe there will be an addition for async/reactive streaming module (and circuit breaking would fit then in there) but that is currently out of focus.

My future plan for Javaslang is to reduce it instead of growing it. It should not be a collection of modules, like the all-mighty spring framework. My hope is, that future Java versions make parts of Javaslang unnecessary or enable us to rewrite current features in a more elegant way.

**Comment by RobWin** [comment]
Okidoki :) Totally comprehensible
