### ISSUE TITLE
Investigate if types should be declared as @FunctionalInterfaces (again...)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#294]
**Goal:**

Better compositionality and conciseness.

**Candidates:**

* Try could extends CheckedSupplier (which in turn has to move out of Try then)
* Option and Either projections could extend Supplier
* Gen and Arbitrary could extend Function or IntFunction

Sequences `Seq` already implement `Function`

**Comment by RobWin** [comment]
If Try would implement CheckedSupplier, I could not do anymore: `Completablefuture.supplyAsync(() -> Try.of())`

**Comment by danieldietrich** [comment]
If in doubt, leave it. Can be added later if necessary.
