### ISSUE TITLE
Add immutable Random Access List (one-sided flexible Array)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#295]
See "Purely Functional Data Structures", ch. 9.2.1 "Binary Random-Access List", p. 119 ff.

**Comment by danieldietrich** [comment]
Decision needed
---

It turns out that the current `RandomAccessList` is more a candidate for a `Vector` implementation (O(1) cons, O(log n) get) rather than to be a candidate for an `Array` implementation.

Scala has no immutable `Array`. Instead they have an `ArrayWrapper` which wraps a mutable Java array. We may also do this and call it `Array`. My idea: back `Array` by an array `T[]`. This fill be fully copied internally (fast, via `System.arrayCopy()`) on each resize operation (remove, insert, ...).

Also we will not re-implement `Vector` with a _back_ of `RandomAccessList` (RAL) because the RAL is currently not balanced. I'm not sure if this behaves as good as HAMT does in practice. On the other hand we may add balancing by using red-black trees instead of binary leaf trees. However, the red-black tree currently have values at all nodes. It has to be further investigated, if a special red-black tree implementation with values only at leafs can be made.

The `RandomAccessList` may be a substitute for the lists used in a HAMT at ArrayNodes. Also, if not balanced.

**Comment by ruslansennov** [comment]
> Decision needed

I agree with both ideas and will try to implement them

**Comment by ruslansennov** [comment]
I believe we should use Array backed by T[] in ArrayNodes. Searching in RAL is too slow

**Comment by danieldietrich** [comment]
Yes, we should do this! We need O(1) here if possible. Don't know if there is any use for RAL. Thought of using it as back of Vector instead of HAMT to reduce the number of intermediate objects - but I think HAMT is a good choice for Vector if we back the ArrayNodes by T[].

**Comment by danieldietrich** [comment]
Fixed by @ruslansennov

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://stock-bazar.ir/day.php?d>

 

arnon@moscona.com
