### ISSUE TITLE
Scala style Futures

### ISSUE THREAD

**Issue by DillonJettCallis** [javaslang/javaslang#301]
Continuing on the goals of javaslang, I propose a Future api modeled on the
Scala Future api, but focused on Java compatibility.

Some features I think would be useful are ...

1. Both Future's built from CheckedSuppliers and Promises, as well as compatibility for java.util.concurent.Future and CompletableFuture. 

2. Most of the usual methods from Scala's Future, map, flatMap, recover, recoverWith, onSuccess, onFailure, onComplete, forEach, filter. 

3. I had in mind two onComplete methods, one that takes a single (Consumer\<Try\<T>> completed) and the other that takes two, (Consumer\<T> success, Consumer\<Throwable> failure). Just as a matter of preference. 

4. I also thought about having a mapTry and flatMapTry, which map the full Try, allowing full conversions between success and failures. (IE: handling some failures but not others). Not as sure about that. 

5. Promises will have success(T value), failure(Throwable exception), complete(Try\<T> result) and completeWith(Future\<T> result). 

6. Methods to convert collections of Futures into Future collections, like Akka's sequence() and traverse(). Example:  Future\<List\<T>> sequence(List\<Future\<T>>)

7. The same for Tuples.

**Comment by danieldietrich** [comment]
This sounds great!

First thing to mention is that Future should reside in the package `javaslang.concurrent`. This aligns with Scala's and Java's concurrent package (although you are right that a Future is some sort of deferred Try, which is a control).

I will add some line comments to your [Future prototype](https://github.com/LordBlackhole/javaslang/commit/7f7e5abf13835d4a95a68643d4cf02a84b31f2ef).

**Comment by LordBlackhole** [comment]
Ah, sure, Concurrent makes perfect sense too. Also, I realized after committing that I'd done so in Master instead of a branch. I haven't made many pull-requests, should I put this in a Futures branch or does it not matter?

**Comment by danieldietrich** [comment]
It does not matter - your branch is merged in each case in Javaslang master.

**Comment by danieldietrich** [comment]
I have to sleep one night on the xxxTry methods. Better would be to omit the Try. But I see the ambiguities after type erasure. We will see...

**Comment by LordBlackhole** [comment]
Exactly. I added the Try parts after having trouble with type erasure in the Testing methods. It doesn't help that Executor is actually a FunctionalInterface.

**Comment by danieldietrich** [comment]
I was busy the last days but did not forget it... I will check the Try parts until this weekend.

**Comment by danieldietrich** [comment]
@DillonJettCallis My Lord, we should pull a first version of the `futures` branch to `javaslang/master`. Your's is fine! Refactoring can be made later.

(Much has changed within the last month. You may want to `git fetch upstream`, `git merge upstream/master`.)

**Comment by danieldietrich** [comment]
Fixed by Dillon.
