### ISSUE TITLE
Match to allow Scala style matching on a range of values.

### ISSUE THREAD

**Issue by martincooper** [javaslang/javaslang#302]
It would be nice to extend Match functionality to allow a range of possible values to match on. An example being the following case in Scala...

```scala
def toBool(choice: String): Boolean = choice match {
    case "Y" | "YES" | "T" | "TRUE" | "1" => true
    case "N" | "NO" | "F" | "FALSE" | "0" => false
    case _ => false
  }
```
Currently this would require multiple 'caze' statements and is a bit more verbose. EG:
```java
Match
	.caze("Y", o -> true)
	.caze("YES", o -> true)
	.caze("T", o -> true)
	.caze("TRUE", o -> true)
	.caze("1", o -> true)
    .caze("N", o -> false) ... etc
```
Maybe allowing...
```java
Match.caze("Y", "YES", "T", o -> true)
```
Or if this is not possible, something like...
```java
Match.cazeIn(new String[] { "Y", "YES", "T", "TRUE" }, o -> true)
```

**Comment by danieldietrich** [comment]
See PR #315

**Comment by danieldietrich** [comment]
Now we are able to write:

```java
Match
    .when(1).then(i -> i)   // before: when(1, i -> i)
    .when(2).then(() -> 1)  // before: when(2, ignored -> 1)
    .whenIn(3, 4, 5).then(i -> i)
    .whenIn(6, 7, 8).then(() -> 1)
    .whenNull().then(n -> 1)
    .whenNull().then(() -> 1)
    .apply(1000);
```

In the meantime the Match API emerged. Instead of using it as function (as shown above), we now may use it as Monad by capturing the value to be matched at the beginning with 'of'.

The new when().then() / whenIn().then() syntax has also to be added to the Match.of() branch of the API. Then we will also able to write:

```java
Match.of(1000)
    .when(1).then(i -> i)   // before: when(1, i -> i)
    .when(2).then(() -> 1)  // before: when(2, ignored -> 1)
    .whenIn(3, 4, 5).then(i -> i)
    .whenIn(6, 7, 8).then(() -> 1)
    .whenNull().then(n -> 1)
    .whenNull().then(() -> 1)
    .get(); // .orElse(...) .orThrow(...) etc.
```

**Comment by danieldietrich** [comment]
**Note:**

Because of ambiguities we cannot use `when(null).then(...)`. Therefore `whenNull().then(...)` was introduced.

TODO: `whenNull().then(...)` should be simplified to `whenNull(...)`, where arguments are `Supplier` and `Function`.

**Comment by danieldietrich** [comment]
@martincooper [First shot](https://github.com/danieldietrich/javaslang/blob/4ade2070e52953c4e77c7e7b80a48ecc03bf6be1/src/main/java/javaslang/control/Match.java) of Match rework finished.

Also added a `whenTypeIn(class_1, ..., class_n).then(...)`. Removed `whenNull`, it is not necessary any more.

The generic type bounds are currently cluttered. Will do this next.

Unit tests and javadoc + the website have to be updated before the release. I think end of next week is realistic.

**Comment by martincooper** [comment]
Great, thanks!

**Comment by danieldietrich** [comment]
@martincooper I'm afraid, I can't push the current master to maven central. The Match rework isn't finished yet. At least we have to cover the new API with unit tests. I hacked it from the brain to my git fork. Also, I'm on a trip for a few days and can go back to my notebook within the next week.
We have to do it right, publishing a version before makes no sense.
But luckily I have now vacation (4 weeks) and more time to work on Javaslang.

**Comment by martincooper** [comment]
That's fine. No rush. Better to do it right. I'm on holiday for a couple of weeks too so won't have much time to pick up the update for a while anyway. 

Thanks
Enjoy your hols. :)

**Comment by danieldietrich** [comment]
Thanks! I will put it all together the next days.

Enjoy your hols, too :)
