### ISSUE TITLE
Further simplification of Match API

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#325]
Which syntax is more valuable?

1) Concise syntax

```java
final String result = Match
        .whenNull(x -> "null")
        .when((Integer i) -> "int")
        .whenIn(1, 3, 5, 7).then(x -> "true")
        .whenIn(2, 4, 6, 8).then(x -> "false")
        .when(10).then(x -> "other")
        .apply(6);
```

2) Consistent syntax

```java
final String result = Match
        .whenNull().then(x -> "null")
        .whenType(Integer.class).then(x -> "int")
        .whenIn(1, 3, 5, 7).then(x -> "true")
        .whenIn(2, 4, 6, 8).then(x -> "false")
        .when(10).then(x -> "other")
        .apply(6);
```

However, the `whenType` syntax would eliminate the use of lambda reflection completely within Match.

---

Additionally we should think about removing support for primitive functions (like `IntFunction`). Are they really needed? We will have the following benefits:

- functionality remains same because of boxing/unboxing (which is currently used internally in case processing nevertheless)
- improvement of speed when Match is used as Function because no more lambda reflection is needed
- less or no ambiguities, `when(null).then(...)` instead of `whenNull().then(...)` or `whenNull(...)`
- reduces the complexity of the code generator
- reduces the size of Match source by factor 8

**Comment by martincooper** [comment]
Personally I prefer that it be concise unless it adds ambiguity. I think there is definite benefit having a whenType method for both clarity and reduction in the code required to implement it. The first example is only marginally more concise than the second one anyway. 

Thanks

**Comment by danieldietrich** [comment]
Yes, me too. I also think that the second one is concise anyway.

I'm currently not sure if there is any benefit having the primitive functions to match by type. See [these examples](https://github.com/javaslang/javaslang/blob/master/src/test/java/javaslang/control/MatchTest.java#L186-L208). I think we may safely remove them...

**Comment by martincooper** [comment]
I can't see why they would be required any more once you could pass the class name to whenType().
