### ISSUE TITLE
Report IntelliJ bugs

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#381]
**This bug is not related to Javaslang!**

There are still some _false_ IntelliJ bugs. JDK compiles fine.

* `ArbitraryTest.java`
  ![_arbitrarytest](https://cloud.githubusercontent.com/assets/743833/8954048/52f7624e-35e3-11e5-99e2-2c6b8bcaf529.png)
  ![arbitrarytest2](https://cloud.githubusercontent.com/assets/743833/8954055/5b119288-35e3-11e5-9728-9057eb03319d.png)
* `AbstractSeqTest.java`
  ![abstractseqtest](https://cloud.githubusercontent.com/assets/743833/8954067/6dea337e-35e3-11e5-951f-7b606426ed73.png)
* `OptionTest.java`
  ![optiontest](https://cloud.githubusercontent.com/assets/743833/8954074/7b08d236-35e3-11e5-96d6-8fbbbd98063b.png)

* `Stack.java`
  ![stack](https://cloud.githubusercontent.com/assets/743833/8984626/0dc2d9ba-36d3-11e5-96f0-1e909c68cfd2.png)
  ![stack2](https://cloud.githubusercontent.com/assets/743833/8984628/17e8efce-36d3-11e5-9bb9-b5be8c9e9b8a.png)

* `Stream.java`
  ![stream](https://cloud.githubusercontent.com/assets/743833/8984910/d6e2dbd2-36d4-11e5-89b9-80b3c8946a69.png)

* `TraversableOnce`
![traversableonce](https://cloud.githubusercontent.com/assets/743833/9028737/86a011c0-3982-11e5-98cf-8a3ed3eec407.png)

**Comment by mkorobeynikov** [comment]
There is another one with Match.caze I suppose
![1klfzz6 1](https://cloud.githubusercontent.com/assets/5910625/9007429/c908ae0e-3799-11e5-8f69-59413ebf8bc8.png)

**Comment by danieldietrich** [comment]
Maybe. Please ensure, that `log.error()` returns a String. Does it currently return `void`?

At least this one compiles with the current Javaslang 2.0.0 master branch:

![match](https://cloud.githubusercontent.com/assets/743833/9008346/009cc058-379a-11e5-8aaa-e2805a52e416.png)

Please note that the API slightly changed. The naming was aligned to other matching frameworks. Also it is more powerful now. You may also write:

![match2](https://cloud.githubusercontent.com/assets/743833/9008586/9d4cbac4-379b-11e5-9900-fca2be0c12d1.png)

Thanks for using Javaslang!

Daniel

**Comment by danieldietrich** [comment]
@mkorobeynikov In your case please try:

```java
        final String result = Try.of(this::toString)
                .recover(x -> Match
                        .caze((IOException e) -> {
                            log.error(e.getMessage());
                            return "";
                        })
                        .apply(x))
                .orElse("");
```

**Comment by mkorobeynikov** [comment]
Daniel, thankyou very much! Good library for me!

**Comment by danieldietrich** [comment]
It's my pleasure!
:+1:

**Comment by danieldietrich** [comment]
There aren't any distracting bugs any more other than [this](https://youtrack.jetbrains.com/issue/IDEA-150224) I recently opened at IntelliJ and which seems to be already fixed.
