### ISSUE TITLE
travis-ci build fails, locally build succeeds

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#434]
```
basicMapTest(javaslang.concurrent.FutureTest)  Time elapsed: 0.112 sec  <<< FAILURE!
java.lang.AssertionError: Checker was supposed to be empty, but was not.  expected:<0> but was:<1>
```

**Comment by ruslansennov** [comment]
My maven locally build fails in 50% of cases.
Replacement

<code>
        third.await(200, TimeUnit.MILLISECONDS);
</code>

on

<code>
        third.await(1000, TimeUnit.MILLISECONDS);
</code>

fixes this bug in most cases, but it's bad solution

**Comment by danieldietrich** [comment]
Yes, that's 'not so nice'. I temporary remove the test.

**Comment by danieldietrich** [comment]
Build fixed. Follow-up: #438
