### ISSUE TITLE
Interoperability with Xtend

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#447]
Hi @szarnekow,

it would be cool, if Xtend could flawlessly use Javaslang.

Are there any things which come to your mind I have to consider?

Do Xtend's lambdas/function literals work well together with java.util.function.*, e.g. with methods that take functions (higher order functions)?

/cc @svenefftinge

**Comment by szarnekow** [comment]
Yes, Xtend doesn't care which SAM type is to be implemented by a lambda expressions. Default methods do also work well with Xtend on a Java8 VM. Let me know if you face any issues. I'll be more than happy to resolve them.

**Comment by danieldietrich** [comment]
Thank you!

**Comment by danieldietrich** [comment]
According to Sebastian, it should word. We will wait for feedback from the community, if Xtend is used in conjunction with Javaslang.
