### ISSUE TITLE
Add Seq.remove(int)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#454]
To remove an element at a specific index.

```java
remove(index) = splitAt(index).transform(t -> t._2.isEmpty() ? t._1 : t._1.appendAll(t._2.tail()))
```

Given this, remove `HashArrayMappedTrie.IndexedNode.removeIndx(List, int)`.

Also provide a better implementation of `List.splitAt()` which currently costs O(2n) = O(n). This can be reduced by constant factor 2, by removing `take` and `drop` calls. Instead the elements should be iterated until the index is reached. Instead of calling drop, we just use the tail then. We have to take care of changing the interface. take and drop do not throw. splitAt should throw(?), on an illegal index. We have to take a look at Scala here, how non-existing indices are handled.

**Comment by ruslansennov** [comment]
Scala accept illegal index in <code>splitAt()</code>

**Comment by danieldietrich** [comment]
ok, splitAt should not throw

**Comment by danieldietrich** [comment]
Thanks @ruslansennov, awesome!
