### ISSUE TITLE
Further improvements of HAMT

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#455]
@ruslansennov To get the most out of List used in HAMT we should do the following:

* use prepend() and prependAll() instead of append() and appendAll(). Note: I hope the order of entries does not matter in a HAMT!? However, the iterator() will then return the entries in a different order. Does this matter for HashMaps/HashSets?
* use findFirst() instead of filter().headOption()
* in mergeLeaves() please replace List.empty() with this.entries() and delete the appendAll(this.entries) below

Additionally I have created two issues to improve [removeIndx()](https://github.com/javaslang/javaslang/issues/454) and [iterator()](https://github.com/javaslang/javaslang/issues/452).

**Comment by danieldietrich** [comment]
What if we put the entries in a (Sorted)Set instead? E.g. containing Tuple2 with compared by ._1/key?

**Comment by ruslansennov** [comment]
As I know nobody promises that the return set of keys should be in certain order. We can do it as our feature, but I'm not sure. All another your proposals are very good.

**Comment by danieldietrich** [comment]
Using List, we have O(n), using Set it is O(log_2(n)) for operations on entries.

I have to take a look on other HAMT impls and need also to understand, why a HAMT backed by a Set (RedBlackTree) performs better than using just a RedBlackTree (containing Entries compared by key). How do Scala and Closure store the entries in a HAMT?

Interesting!

**Comment by danieldietrich** [comment]
Good reading: http://lampwww.epfl.ch/papers/idealhashtrees.pdf

**Comment by ruslansennov** [comment]
just for clarify: <code>HashMap.keySet()</code> should be return <code>Set</code> and only <code>Set</code>. But sorted set or hash set, that is the question

**Comment by danieldietrich** [comment]
Our API will declare return type `Set`, that makes it flexible for other impls.

Our implementation may use SortedSet for performance reasons, if it makes sense.

**Comment by danieldietrich** [comment]
(minor thing) We could make the number of slots (currently 32) a constant SLOTS, just for clarity.

**Comment by danieldietrich** [comment]
@ruslansennov Is there still something to do here? https://github.com/javaslang/javaslang/blob/master/src/main/java/javaslang/collection/HashArrayMappedTrie.java#L208-L216

**Comment by ruslansennov** [comment]
Of course no! After last <code>List</code> improvements It can be changed to 
<code>
{ List.removeAt() } else { List.set() }
</code>
I'll fix it later

**Comment by ruslansennov** [comment]
I thought the idea to change <code>javaslang.collection.List&lt;Tuple2&lt;K,V&gt;&gt;</code> on <code>java.util.TreeMap&lt;K,V&gt;</code> in <code>HashArrayMappedTrie.LeafNode</code>...
It only makes sense if we have a lot of collisions as in case of <code>HashArrayMappedTrieTest.WeakInteger</code> (completely stupid hashCode algorithm). In all other cases <code>java.util.TreeMap</code> will require more memory but did not give us a big win in CPU

**Comment by danieldietrich** [comment]
thanks for investigating! then let's stay with our List.

**Comment by danieldietrich** [comment]
Finished with #457
