### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#463]
Reaching 2.0.0, we should prepare that Javaslang will be used in the broad. Therefore I expect more minor releases than we have yet. To separate new features from maintenance releases, we need to follow a release/development model tailored to our needs.

E.g. git-flow by Vincent Driessen

Note: This will be relevant **after** the release of 2.0.0

**Comment by ggalmazor** [comment]
You have to take into account that Gitflow is designed for a scenario with only one repository. The flow for contributions in Github uses to be a Forking flow, in which contributors have their repo and can request pull requests.

Here's a nice summary of different git flows: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by danieldietrich** [comment]
Thanks, that helps. I'm not used to it, at $work we still use a self-hosted svn...

**Comment by ggalmazor** [comment]
Well, we can discuss this after 2.0.0 release :)

—
Guille

**Comment by danieldietrich** [comment]
yep!

**Comment by danieldietrich** [comment]
We will do the following:

```
                         master
                           |
                           |     v2.0.x
release v2.0.0 - - - - - - + - - - + 2.0.1-SNAPSHOT
                           |       |
                  featureA |       |
                     |     |       |
                  PR x---->|<------+ cherry-picking featureA
                           |       |
                  featureB |       |
                     |     |       |
                  PR x---->|       |
                           |       |
release v2.0.1 - - - - - - | - - - + 2.0.2-SNAPSHOT
                           |       |
                           |       |     v2.1.x
release v2.1.0 - - - - - - + - - - X - - - + 2.1.1-SNAPSHOT
                           |               |
                           |               |
                  featureC |               |
                     |     |               |
                  PR x---->|               |
                          ...             ...
```

**Comment by danieldietrich** [comment]
I've documented this in CONTRIBUTION.md. I will close this ticket for now.
