### ISSUE TITLE
Add an immutable Vector (implementds IndexedSeq)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#464]

**Comment by ruslansennov** [comment]
What algorithm you prefer to implement here? If something like <code>java.util.ArrayList</code> then we can use it in <code>HashArrayMappedTrie</code>. If no, then I'd like to remove <code>HashArrayMappedTrie.ArrayNode</code> because of high cost of <code>List.set(index, element)</code> operation

**Comment by danieldietrich** [comment]
An internal `HAMT<Integer, T>` makes sense for `Vector<T>`.

Please tell me a little bit more about the details why we can remove ArrayNode and what changes regarding our performance characteristics (time/memory) if we do so.

**Comment by ruslansennov** [comment]
<code>HashArrayMappedTrie.ArrayNode</code> is useful only if cost of <code>set()</code> operation is <code>O(1)</code>. We have <code>O(n)</code>, so we can use <code>HashArrayMappedTrie.IndexedNode</code> only

**Comment by ruslansennov** [comment]
... with some modifications, of course :)

**Comment by danieldietrich** [comment]
Why is the cost of set O(n)? I know Tries in general but haven't read the paper about HAMT in depth. The Integer-keys should be distributed equally. I would expect O(1) then. Or has the complete Trie to be rewritten on set()? If so, why is the performance then better for other key-types. If the performance is not better for other key-types, why the ArrayNode is then used at all?

**Comment by danieldietrich** [comment]
Nevertheless, do it with the best performance possible. You know the characteristics best. Although I want to understand it in depth.

**Comment by ruslansennov** [comment]
No, I mean that cost of <code>List.set(index, element)</code> is <code>O(n)</code>. If <code>HashArrayMappedTrie.ArrayNode</code> backed by <code>List</code>, then there is no general difference between <code>HashArrayMappedTrie.ArrayNode</code> and <code>HashArrayMappedTrie.IndexedNode</code>, and they may be combined into <code>NoLeafNode</code> without loosing CPU or memory

**Comment by danieldietrich** [comment]
From what I understand is, that we generally traded in our HAMT List against Array. In other words, this affects also our Map impls.

Then I would keep our ArrayNode and substitute List with Array when we implemented it (see #295). This should boost it from O(n) to O(1), right?

**Comment by ruslansennov** [comment]
Oh, I have not seen #295 before. Of course in this case we should keep ArrayNode

**Comment by danieldietrich** [comment]
Fine, let's do it this way.

**Comment by danieldietrich** [comment]
Fixed with #480
