### ISSUE TITLE
Add an immutable String implements IndexedSeq<Character>

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#465]
java.lang.String is already immutable but javaslang.collection.String will be feature-rich.

I expect, that this feature will be a magnet (similar to Try) because Strings are probably the most popular native language feature (of Java) `> Hello world!`.

Example:

```java
// = {
//   'J' -> 1,
//   'a' -> 3,
//   'v' -> 1,
//   's' -> 1,
//   'l' -> 1,
//   'n' -> 1,
//   'g' -> 1
// }
final Map<Character, Integer> occurrences = String.of("Javaslang").countOccurrences();
```

**Comment by patrox** [comment]
hi @danieldietrich, so the future `javaslang.collection.String` will be very similiar to: 
`scala.collection.immutable.WrappedString` ?

**Comment by danieldietrich** [comment]
Hi @patrox, yes - exactly. It will be an IndexedSeq of Character that wraps a java.lang.String

**Comment by danieldietrich** [comment]
Then we should name it WrappedString

**Comment by ruslansennov** [comment]
I'll name it <code>WrappedString</code> right now

**Comment by patrox** [comment]
@ruslansennov are you working currently on the implementation? Because to be honest I like this project a lot and if it's possible I would like to help you somehow - and I was wondering if I can work on this one? :)

**Comment by danieldietrich** [comment]
@patrox :+1: you're welcome!

**Comment by ruslansennov** [comment]
@patrox It seems all ready, I'll finish soon

**Comment by danieldietrich** [comment]
@patrox to start getting your hands dirty you could implement 1-2 euler tests. I like the Scala project of @shadaj as reference: https://github.com/shadaj/euler. The existing tests are located in src/test/java/javaslang/collection/euler

**Comment by patrox** [comment]
@ruslansennov so I was a bit late ... but it will be quite interesting to compare the implementations :)
@danieldietrich I'll have a look at these tests

**Comment by danieldietrich** [comment]
Great! There will be more todo - much more :-)

**Comment by ruslansennov** [comment]
@danieldietrich There is problem to make test for String. I see no other way except make it independent from <code>AbstractSeqTest</code>

**Comment by danieldietrich** [comment]
Alright!

**Comment by danieldietrich** [comment]
@ruslansennov @patrox Guys, I urgently need some high quality sleep - I will come back tomorrow...

**Comment by danieldietrich** [comment]
@ruslansennov @patrox 

Btw - Vector as return type in many places is the best choice because both, WrappedString and Vector, are of type IndexedSeq and therefore have similar performance characteristics (get, set, append, ...).

However, I'm not completely convinced about the name `WrapperString`. In Scala it is 'hidden', i.e. not instantiable. But I have no better name, yet.

* I don't like `String2` very much.
* Also `Str` and `Chars` are not so good.
* Maybe `IndexedString` - but that is redundant. Or shorter `IString` (sounds like a new Apple product o_O)
* `RichString` is taken by formatted strings
* Wikipedia: 'a string is traditionally a sequence of characters'. Maybe then `CharSeq`. Also `CharArray` or `Word` are possible.

**Comment by danieldietrich** [comment]
`class CharSeq implements IndexedSequence<Character>` makes sense, doesn't it?

**Comment by patrox** [comment]
nah, `String2` was just a product of a my very tired mind :)

**Comment by ruslansennov** [comment]
I like <code>CharSeq</code>

**Comment by patrox** [comment]
I think it's the best name we have now currently, `IString` sounds like an interface in Microsoft parlance

**Comment by ruslansennov** [comment]
in other side <code>WrappedString</code> <b>assumes</b> big list of <code>java.lang.String</code> methods and it is good

**Comment by danieldietrich** [comment]
mmhh, yes, it would be good to see it is a String by just looking at the API...

**Comment by danieldietrich** [comment]
StringOnSteroids :-)

**Comment by danieldietrich** [comment]
Stringoid - like Monoid - sounds algebraic... ok, time to relax and make some coffee... :-)

**Comment by danieldietrich** [comment]
I will rename it to `CharSeq < IndexedSeq < Seq` for now. It is lightweight and easy to remember. WrappedString sounds too bulky.

**Comment by patrox** [comment]
if you'll rename it, then can you please rename the test as well, to be consisten, as now it's `StringTest`, there is a bit of inconsistency in packages too, as the `WrappedString` is currently located in `javaslang`, but the corresponding test suite is located in `javaslang.collection`

**Comment by danieldietrich** [comment]
yep, already done - thx! they reside in javaslang.collection

**Comment by patrox** [comment]
alright! I've to go get some sleep - found some interesting info regarding how String-like behave in the context of transforming functions like map ... I'll create some tests to capture the behaviour, so we can discuss if further. But for now - good night !

**Comment by danieldietrich** [comment]
thanks for your help! good night!
