### ISSUE TITLE
Fix the test coverage in direction of 100% (until release)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#477]
> Untested code is broken code.

**Comment by ruslansennov** [comment]
@danieldietrich please reopen this issue. Now we have &lt;90% tests coverage, this is not good

**Comment by danieldietrich** [comment]
@ruslansennov You're right - I closed it accidentally

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://lauraclauvi.ro/conduct.php?wb3g8>

 

arnon@moscona.com

**Comment by danieldietrich** [comment]
See #936

**Comment by danieldietrich** [comment]
Missing conversion tests:

* Map/HashMap/LinkedHashMap/TreeMap#toJavaMap()
* Set/HashSet/LinkedHashSet/TreeSet#toJavaSet()

Missing narrow tests:

* Future#narrow(Future)
* Lazy#narrow(Lazy)
* Option#narrow(Option)
* Promise#narrow(Promise)
* Try#narrow(Try)
* Value#narrow(Value)

**Comment by danieldietrich** [comment]
we are at 96% - I will close this issue, tests are an ongoing task
