### ISSUE TITLE
Add a table of collection performance characteristics to collection/package-info.java

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#479]
Like this: http://docs.scala-lang.org/overviews/collections/performance-characteristics.html

Could be a HTML table:

```java
/**
 * <table cellpadding="0" cellspacing="0" border="1">
 *     <thead><tr><th>&nbsp;</th><th>contains</th><th>...</th></tr></thead>
 *     <tbody>
 *         <tr><td>Array</td><td>O(1)</td><td>...</td></tr>
 *         <tr>...</tr>
 *     </tbody>
 * </table>
 */
```

**Comment by danieldietrich** [comment]
@ruslansennov Hi, could you make a review of the correctness of the table contents? Thx! http://javaslang.com/javadoc/latest/javaslang/collection/package-summary.html#package.description

**Comment by sedovalx** [comment]
I'm afraid the table has gone...

**Comment by danieldietrich** [comment]
The web page points to the right link - here it is:

http://static.javadoc.io/io.javaslang/javaslang/2.0.1/javaslang/collection/package-summary.html
