### ISSUE TITLE
Revise all collection return types

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#490]
E.g. Map.merged takes and currently returns a HashMap, not a Map.

CharSeq (aka WrappedString) return Vector, not IndexedSeq.

etc.

We need a clear picture how to operate here. One solution is to return most specific types. E.g. the 'end points' HashSet, HashMap, CharSeq, Queue, are final and have slightly better API regarding composed return types. E.g. returning `Tuple2<Queue, Queue>` instead of `Tuple2<? extends LinearSeq, ? extends LinearSeq>`.

Which is better to handle in practice? The rule of thumb in Java is to use interfaces instead of concrete classes for variables to be more flexible. On the other side it should be possible to assign a concrete impl to an interface type.

We need a consistent way to do it with the best user experience but also preserving maximum flexibility.

**Comment by danieldietrich** [comment]
As I wrote [here](https://github.com/javaslang/javaslang/issues/121#issuecomment-89431651) we should return the most specific type. This is the way to go. I will check, where the return types can be adjusted.

**Comment by danieldietrich** [comment]
@ruslansennov @patrox Hey, can anyone please tell me why some of Scala's HashMap methods do return Iterable or Iterator instead of collection types? E.g. groupBy(), sliding(), values(), ...

**Comment by danieldietrich** [comment]
We need to differentiate the dogma a bit to _always_ return the _most specific type_. In this context the following fits best, taken from [Scala docs](https://github.com/scala/scala/blob/2.11.x/src/library/scala/collection/readme-if-you-want-to-add-something.txt):

> We distinguish in the following between two kinds of methods
>
> - **Accessors** access some of the elements of a collection, but return a result which is unrelated to the collection. Example of accessors are: head, foldLeft, indexWhere, toSeq.
>
> - **Transformers** access elements of a collection and produce a new collection of related type as a result. The relation might either be direct (same type as receiver) or indirect, linked by a CanBuildFrom implicit. Example of transformers are: filter, map, groupBy, zip.

Given this, our _transformers_ should return the most specific type, e.g. `HashMap.map(...)` should return `HashMap`. E.g. `zipWithIndex` is also a transformer.

Out _accessors_ should return  an interface instead to keep our library extensible for future enhancements. E.g. `HashMap.groupBy` should return `Map` because we may decide in future that returning another Map implementation than HashMap is more efficient. Returning now HashMap would break API on future changes. The only disadvantage is that Map's methods have generic parameters with wildcards, which reduces usability slightly.

More specific, methods like `Seq.combinations()` or `Seq.crossProduct()` should return `Seq`. This applies also to subclasses of `Seq`. E.g. `CharSeq.combinations()` should also return `Seq`. Of course the concrete object returned remains `Vector`.

**Comment by ruslansennov** [comment]
:+1:

**Comment by patrox** [comment]
sounds reasonable and I think it will make the life of end users more simpler !

**Comment by danieldietrich** [comment]
More info on why some Scala methods return Iterator or Iterable instead of a collection: http://www.scala-lang.org/docu/files/collections-api/collections_4.html

**Comment by danieldietrich** [comment]
I now have a (relative) clear picture how to improve the collections:

1) Introduce `javaslang.Iterable`

```java
interface Iterable<T> extends java.lang.Iterable<T> {

    @Override
    Iterator<T> iterator();

    default Iterator<IndexedSeq<T>> grouped(int size) {
        return sliding(size, size);
    }

    default Iterator<IndexedSeq<T>> sliding(int size) {
        return sliding(size, 1);
    }

    default Iterator<IndexedSeq<T>> sliding(int size, int step) {
        return iterator().sliding(size, step);
    }
}
```

2) Let `Value` extends `javaslang.Iterable`

```
  java.lang.Iterable
          ^
          |
  javaslang.Iterable
          ^
          |
   javaslang.Value
          ^
         / \
     Lazy   TraverableOnce
control.*         ^
 test.xxx        / \
         Iterator   Traversable
                        ^
                       /|\
                 Seq Set Map Tree
```

**Comment by danieldietrich** [comment]
Half the way there. Moved many static factory methods to Iterator. Collections may use these by delegating their static factory methods via ofAll(() -> Iterator.xxx(...)). TODOs added in Iterator. Currently the stuff is in my fork... Will be pulled soon into master.

**Comment by danieldietrich** [comment]
There is still one thing: We have `subSequence(from, to)` and `subSequence(from)`. The former is `slice(from, to)` in Scala. The latter is similar to `drop(n)` but takes an index instead of a number of elements.

Because `CharSeq` implements `IndexedSeq` _and_ `CharSequence`, we cannot rename `subSequence(from, to)` to `slice(from, to)`. We need to override `CharSequence.subSequence`. However, there are `Seq.indexOfSlice(Iterable)` and `Seq.lastIndexOfSlice(Iterable)` instead of `indexOfSubSequence(...)` and `lastIndexOfSubSequence(...)`.

Putting this all together, it makes sense to rename `subSequence(...)`to `slice(...)` to be consistent with `indexOfSlice(...)` and `lastIndexOfSlice(...)`. We should not drift away from Scala's API now that we are so close to it. Additionally there will be a `CharSequence.subSequence(from, to)`.

I will do that.

**Comment by danieldietrich** [comment]
Mmhh, just realized we may change

```java
Value.flatMapValue(Function<? super T, ? extends Value<? extends U>)
```

to

```java
Value.flatMap(Function<? super T, ? extends Iterable<? extends U>)
```

Then we can use `!iterator.hasNext()` instead of `value.isEmpty()`.

Will check that tomorrow...
