### ISSUE TITLE
Rewrite prime numbers

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#492]
```
Running javaslang.collection.euler.Euler10Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 97.8 sec
```

**Comment by patrox** [comment]
is it the performance that's worrying you ?

**Comment by ruslansennov** [comment]
Yes. Travis builds JavaSlang by few steps and converts these 90+ seconds to minutes

**Comment by danieldietrich** [comment]
Maybe [Sieve of Atkin](https://en.wikipedia.org/wiki/Sieve_of_Atkin) as `Stream` in conjunction with `Function.lift(stream).memoized()`. The memoization lets multiple euler tests share cached prime numbers, if needed.

**Comment by ruslansennov** [comment]
yep

**Comment by patrox** [comment]
I'm working on another euler test (problem 12) and most probably I will also need to have a stream of  prime numbers to find large number of divisors in a reasonable time, so this will be helpful !

**Comment by ruslansennov** [comment]
Sieve may be created not as boolean map which say you about the number's status, but as integer map, which say you one of divisor. This trick helps to find all divisors very easy

**Comment by ruslansennov** [comment]
hmmm... answer is <b>76576500</b>, to big for sieve.
Sorry, this trick can't help you :)

**Comment by patrox** [comment]
My first approach was too naive (I don't even want to mention it ;)),
the second (a bit smarter/faster) was to lookup the divisors in pairs -
so when I found that **m** is a divisor of **n**, I was calculating the other divisor by: `n/m` - this has limited the search space from `n/2` to `sqrt(n)` - but this was still taking very long (~60 secs to calculate 400 divisors)),
the third (and I hope the last one) ... will be to implement the **Tau function** aka **divisor function**:
https://en.wikipedia.org/wiki/Divisor_function

**Comment by danieldietrich** [comment]
oh, sounds not that simple

**Comment by danieldietrich** [comment]
Fixed with @ruslansennov 's implementation of Sieve of Atkin. Thx!
