### ISSUE TITLE
Store collection length

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#502]
All `Lazy<Integer> length` fields for calculating collections lengths should be replaced by `int length` fields, if possible.

**Comment by danieldietrich** [comment]
Stream is the only place where we have a `Lazy<Integer> length`. Is it worth it to store a wrapped in at each element of the stream? The main use case of Stream is to represent an infinite long stream of data. There we are in general not interested in the length....

**Comment by ruslansennov** [comment]
It's simple: lazy collection == lazy length

**Comment by danieldietrich** [comment]
that makes sense - we will keep it
