### ISSUE TITLE
Rewrite equals of all Iterable classes

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#547]
There is a pretty good reason to let `iterable1.equals(iterable2) == true`, if iterable1 containts the same elements as iterable2: **inheritance**.

```java
Seq<T> seq1 = List.of(1, 2, 3);
Seq<T> seq2 = Stream.of(1, 2, 3);
seq1.equals(seq2); // = true, as expected!
```
Exception: Iterator - because it is short-lived and therefore should not be evaluated

/cc @ruslansennov - thx for talking about it!

**Comment by danieldietrich** [comment]
This can be used for all _sequential_ classes:

```java
boolean equals(Iterable<? extends T> iterable1, Iterable<? extends T> iterable2) {
    Objects.requireNonNull(iterable1, "iterable1 is null");
    Objects.requireNonNull(iterable2, "iterable2 is null");
    final Iterator<T> iterator1 = iterable1.iterator();
    final Iterator<T> iterator2 = iterable2.iterator();
    while (iterator1.hasNext() && iterator2.hasNext()) {
        if (!Objects.equals(iterator1.next(), iterator2.next())) {
            return false;
        }
    }
    return iterator1.hasNext() == iterator2.hasNext();
}
```

For classes with no specific order (e.g. Set, Map, ...) we need to take another approach.

For Values with one element (e.g. Option, Try, Lazy, ...) we should also take the sequential approach (see above):

```java
new Some<>(1).equals(List.of(1)); // = true

new Some<>(1).equals(List.of(1, 2, 3)); // = false

None.instance().equals(List.empty()); // = true
```

**Comment by danieldietrich** [comment]
Maybe it makes sense to add an additional, exact equality match (by comparing the type via instanceof), e.g.

```java
new Some<>(1).equals(List.of(1)); // = false
new Some<>(1).equals(new Some<>(1)); // = true
```

**Comment by ruslansennov** [comment]
Our goal is to make <code>equals()</code> behavior exactly as in Scala, right?

**Comment by danieldietrich** [comment]
> When you call equals directly, you are skipping all that softening logic and instead treated to java's theory that two boxed values of different types are always unequal. 

\- Paul Phillips

We should keep our equals methods as they are. This is how Java devs would expect them to work. However, I will change Iterator.equals most probably to work like `==`. This will be documented in the interface.

In a future version of Javaslang we may add `eq`, which behaves like `==` in Scala (with softening logic). But before starting implementation, we may check other alternatives, e.g. an _implicit_ (additional method argument) `Eq` or `Equals` instance, which works like `Comparator`...

I will push this issue to the backlog for now.

**Comment by ruslansennov** [comment]
> I will change Iterator.equals most probably to work like ==. This will be documented in the interface.

very well

**Comment by danieldietrich** [comment]
We keep equals as is. We introduce a _smoothing_ javaslang.Iterable.eq, similar to Scala's ==, such that

```java
List.of(1, 2, 3).eq(Stream.of(1, 2, 3)) // = true
```

**Comment by danieldietrich** [comment]
Iterable.eq checks **congruence of structures** and **equality of contained values**:

```java
// ((1, 2), ((3))) => structure: (()(())) values: 1, 2, 3
final Iterable&lt;?&gt; i1 = List.of(List.of(1, 2), Arrays.asList(List.of(3)));
final Iterable&lt;?&gt; i2 = Queue.of(Stream.of(1, 2), List.of(Lazy.of(() -> 3)));
assertThat(i1.eq(i2)).isTrue();
```
