### ISSUE TITLE
Boost our HAMT time complexity for some operations from O(n) to effectively O(1)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#560]
As stated in #559 our following HAMT operations are currently linear instead of effectively constant:

* tail()
* prepend()
* insert()

Scala also does use the HAMT, at least for HashSet, with eff. const. time for all operations. See http://docs.scala-lang.org/overviews/collections/performance-characteristics.html. Also the [LAMP paper](http://lampwww.epfl.ch/papers/idealhashtrees.pdf) says that HAMT operations are O(1), e.g. remove(key).

We need to investigate further if and how to get eff. const. time for the operations mentioned above.

**Comment by ruslansennov** [comment]
@danieldietrich no! All HAMT operations costs O(1). But some Vector operations cost O(n)

**Comment by danieldietrich** [comment]
@ruslansennov Ok, that's nice!

But then this whole operation should be O(1) and no further index update is needed, right?

```java
Vector<T> tail() {
    final Iterator<T> iterator = iterator(); // O(1)
    if (!iterator.hasNext()) { // O(1)
        throw new UnsupportedOperationException("tail of empty Vector");
    }
    final T key = iterator.next(); // O(1)
    return new Vector<>(tree.remove(key)); // O(1) and tree indices are aligned new, right?
}
```

**Comment by danieldietrich** [comment]
And yes, now I understand why prepend() and insert() are O(n). Because indices need an update. Yes, yes, yes...

And also yes: when removing an element, subsequent indices have to be updated.

This issue should be obsolete. But still the question how Scala does the trick :-)

**Comment by ruslansennov** [comment]
> return new Vector<>(tree.remove(key)); // O(1) and tree indices are aligned new, right?

No :)
Let's imagine Vector(a, b, c). It's corresponds to Trie(0 -&gt; a, 1 -&gt; b, 2 -&gt; c)
After removing first element we will have  Trie(1 -&gt; b, 2 -&gt; c)
But it is not correct trie object, because first element has index=1 but not 1

**Comment by ruslansennov** [comment]
> But still the question how Scala does the trick :-)

Yes!

**Comment by danieldietrich** [comment]
This does not to be changed/fixed before release 2.0.0. We can go live and boost the performance in a follow-up release...

**Comment by ruslansennov** [comment]
I believe all is OK for HAMT and this issue can be closed

**Comment by danieldietrich** [comment]
:+1: Done.

**Comment by danieldietrich** [comment]
Btw - welcome back! :-)

**Comment by ruslansennov** [comment]
I see there are big changes in project :)
