### ISSUE TITLE
Implement Vector as bit-mapped vector trie

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#568]
...to obtain eff. const. time complexity. Maybe we will not target this for 2.0.0 but taking only a look at it...

More on that here:

* [Scala's immutable Vector](http://docs.scala-lang.org/overviews/collections/concrete-immutable-collection-classes.html#vectors)
* [Implementation in Rust](https://bitbucket.org/astrieanna/bitmapped-vector-trie)
* [How does Scala's Vector work?](http://stackoverflow.com/questions/20612729/how-does-scalas-vector-work)
* [Extreme Cleverness: Functional Data Structures in Scala [video]](http://www.infoq.com/presentations/Functional-Data-Structures-in-Scala)
* [Strangeloop 2011 'Functional Data' Slides by Daniel Spiewak](https://github.com/strangeloop/2011-slides/blob/master/Spiewak-FunctionalData.pdf)
* [Understanding Clojure's Persistent Vectors, Part 1 ](https://news.ycombinator.com/item?id=6445628)

Understanding Clojure's Persistent Vectors

* [pt. 1](http://hypirion.com/musings/understanding-persistent-vector-pt-1)
* [pt. 2](http://hypirion.com/musings/understanding-persistent-vector-pt-2)
* [pt. 3](http://hypirion.com/musings/understanding-persistent-vector-pt-3)

**Comment by danieldietrich** [comment]
As examined in #571 we need to replace occurrences of

* `List.insert(int, Object)`
* `Array.update(int, Object)`

within HashArrayMappedTrie (HAMT).

We accomplish this by using Vector as default Seq implementation throughout our HAMT.

**Comment by paplorinc** [comment]
FYI: https://github.com/andrewoma/dexx/blob/master/collection/src/main/java/com/github/andrewoma/dexx/collection/Vector.java

**Comment by danieldietrich** [comment]
Thx!

**Comment by paplorinc** [comment]
@danieldietrich, please assign this to me.

cc? @mvh77

**Comment by paplorinc** [comment]
@danieldietrich I'm currently testing the correctness of the `slice` method for the new `Vector`, but since it has very many states, I would only be able to sleep at night by being able to validate the majority of the corner cases.
Obviously that's not possible - it would probably take months to run the test that tries out every combination.

```java
@Test
public void shouldSlice() {
    for (byte depth = 1; depth <= 4; depth++) {
        for (int size = 1, end = getMaxSizeForDepth(depth) + 1; size <= end; size++) {
            final Seq<Integer> expected = Array.range(0, size);
            final Vector<Integer> actual = Vector.ofAll(expected);

            for (int i = 0; i <= size; i++) {
                for (int j = i; j <= size; j++) {
                    final Seq<Integer> expectedSlice = expected.slice(i, j);
                    final Vector<Integer> actualSlice = actual.slice(i, j);
                    assertThat(expectedSlice.toJavaList()).isEqualTo(actualSlice.toJavaList());
                }
            }
        }
        System.out.println("Depth " + depth + " ok!");
    }
}
```

Since there is a property based testing part of `Javaslang` (that isn't documented or advertised well enough), I would definitely like to go in this direction.

It should test the boundaries (e.g. `splice` with `start` index in one sub-array and `end` index in another) and run enough examples to mimic the behavior of a full-blown brute-force permutation.

Could you please help me in rewriting the above example?

**Comment by danieldietrich** [comment]
Of course! We need to formulate an invariant (read: predicate) for slice that holds for each collection of size `0 <= n`, and variables `-bound <= i, j <= bound`, where `0 <= bound <= 2*n` to cover all corner cases.

A property test would like this:

```java
final Arbitrary<Vector<Integer>> vectors = n -> Vector.ofAll(Array.range(0, n));
final Arbitrary<Integer> i = bound -> Gen.choose(-(bound * 2), bound * 2);
final Arbitrary<Integer> j = bound -> Gen.choose(-(bound * 2), bound * 2);
final Function2<Integer, Integer, Boolean> invariant = (i, j) -> /* TODO */;

Property.def("Vector.slice")
    .forAll(vectors, i, j)
    .suchThat(invariant)
    .check()
    .assertIsSatisfied();
```

Something like that (from the top of my head)...

**Comment by paplorinc** [comment]
https://github.com/andrewoma/dexx seems to have the same speed as Scala.
No suprise, as even the TODO comments are copied from there.

@danieldietrich, what is your opinion about the whole library, how is Javaslang compared to that? (e.g. it copies Scala a lot more than we do, but it dared to rename `head` to `first`, which is a big :+1: from me ... it kept `tail` though, which doesn't really make sense that way, why not `rest`, if `first` :-1:)

Are there any other libraries that I should benchmark againts?

**Comment by danieldietrich** [comment]
@paplorinc Please let not benchmark against it. It makes not much sense because it is not popular. Also I question that it is a copy-paste of Scala. This should be a license problem for the library!

**Comment by paplorinc** [comment]
> I question that it is a copy-paste of Scala

It even has the Scala header: https://github.com/andrewoma/dexx/blob/master/collection/src/main/java/com/github/andrewoma/dexx/collection/Vector.java#L23

**Comment by danieldietrich** [comment]
Then **IT IS** Scala ;-p

**Comment by paplorinc** [comment]
Any other lib I should compara against?

**Comment by danieldietrich** [comment]
No, not for now, thank you.
