### ISSUE TITLE
Implement Queue as 2-3 Finger Tree

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#569]
In his talk [Extreme Cleverness: Functional Data Structures in Scala](http://www.infoq.com/presentations/Functional-Data-Structures-in-Scala) (position 13:00) Daniel Spiewak explains why we prefer a 2-3 Finger Tree over a Banker's Queue (with front/rear List) to implement a persistent Queue.

The question remains, why does Scala uses a Queue with front/rear List?

(This does not need to go into the 2.0.0 release because we already have a suitable Queue implementation.)

**Comment by danieldietrich** [comment]
NO! We won't do that.

As Daniel Spiewak explains, a 2-3 Finger Tree is sloooow. No one uses them in practice. You will always find Banker's Queue. It's because of JVM organization of Linked List data (holds it together) vs. 2-3 Finger Tree memory mess (all dropped unrelated somewhere on the heap).

See also http://www.infoq.com/presentations/Functional-Data-Structures-in-Scala (minute 42:00).

**Comment by pivovarit** [comment]
> It's because of JVM organization of Linked List data (holds it together) vs. 2-3 Finger Tree memory mess (all dropped unrelated somewhere on the heap).

Did some investigation on my own and that's partially true (more likely to be a side-effect of compaction than a conscious optimization). Will implement it and benchmark to see accurate difference between the current Banker's-based implementation, and the Finger-tree-based one.

I will post the data here once I'm done. However, I don't expect any surprising results (there's indeed quite a lot of indirection there), just want to see what performance degradation are we talking about

**Comment by danieldietrich** [comment]
Hey @pivovarit, that sounds interesting! Have you played around with it a bit?

**Comment by pivovarit** [comment]
Not yet, quite busy with different things now, but want to circle back here in July (and explore CHAMP for HashMap)

**Comment by danieldietrich** [comment]
Nice, thx!
