### ISSUE TITLE
Remove optimizations that rely on HashArrayMappedTrie.size()

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#578]
We use size() to determine if the newly created collections has the same size as the current collection. To save mem, we return the current instance if sizes are equal.

Because HAMT.size() is now O(n) (at least once, if lazy evaluated), then cannot use this optimization any more.

Candidates to check are HashSet, HashMap and Vector. Maybe also other collections...

**Comment by danieldietrich** [comment]
We will also move back from storing the size/length in a Stream. The use-case of a stream is lazy evaluation, like Iterator. Both have indefinite size. Therefore it is not common to ask a Stream for its size... If it is really, really needed, the user may memoize the size him/herself.

**Comment by ruslansennov** [comment]
I don't understand this, sorry, can you explain? <code>HashArrayMappedTrie</code>'s length() can be O(1), like <code>List</code>, <code>Vector</code> and any other not lazy collection

**Comment by danieldietrich** [comment]
It can be - at the cost of computing the size at construction time, e.g. via `subNodes.map(AbstractNode::size).sum().intValue()`. But my performance measures showed, that this costs too much time.

An alternative is, that we add a lazy field `Lazy<Integer> size = ...`. But when we want to calculate the size of a big collection, we first have to calculcate (once) all these lazy values in O(n). Ok, we do it only once, but at the cost of extra garbage/memory.

Having *not* a Lazy length is not really a disadvantage. If we need the size in an app more than once, we can introduce a local var instead of having an instance variable, e.g.

```java
final int length = myMap.length(); // calculated once
```

Let's have a look at other languages.

**Comment by danieldietrich** [comment]
Or did you mean Stream? I also look at the memory footprint. And at the use-case for a specific collection type. Stream's strength is not size(). It's size is indefinite and maybe infinite. Vector is the right collection for that.

**Comment by danieldietrich** [comment]
This is copied from Scala's source code (just for teaching purpose, we will not include that in Javaslang!):

```scala
override def length: Int = {
    var len = 0
    var left = this
    while (!left.isEmpty) {
      len += 1
      left = left.tail
    }
    len
  }
```

Source: https://github.com/scala/scala/blob/v2.11.5/src/library/scala/collection/immutable/Stream.scala#L307-L315

**Comment by ruslansennov** [comment]
> It can be - at the cost of computing the size at construction time, e.g. via subNodes.map(AbstractNode::size).sum().intValue(). But my performance measures showed, that this costs too much time.

No. We can store size in every AbstractNode and update it with every changing. It can't be O(n). For example if AbstractNode was added, then total new size = old size + size of added AbstractNode and so on

 > Or did you mean Stream?

Stream is a lazy collection. Its length() can be O(n), OK

**Comment by danieldietrich** [comment]
Ok, let's try it. HAMT has to be changed than according to your description. Will you do it?

I will keep an eye on the performance and optimize where necessary to get the best we can achieve for our collection...

**Comment by ruslansennov** [comment]
> subNodes.map(AbstractNode::size).sum().intValue()

it was very bad idea, but it can be improved! :)

> Will you do it?

Of course

**Comment by danieldietrich** [comment]
Don't worry - these discussion bring us forward. Code is changing. If it turns worse (like my change) we turn it even better as before.

**Comment by danieldietrich** [comment]
Great ideas by @ruslansennov to improve or HAMT size() calculation and also Vector optimization.

Regarding this issue we will only remove the cached length and hashCode of Stream because it is a collection of indefinite size and not the best choice to be stored in a HashSet/HashMap.

In general we should look at Scala. I'm not convinced of storing extra lazy fields per collection node to cache information. The need for a lazy hashCode in general should be re-considered again.

**Comment by danieldietrich** [comment]
Stream has now size with O(n), as expected for undetermined length.

HAMT.size calculation was optimized by Ruslan.
