### ISSUE TITLE
Local classes and anonymous classes leak enclosing this reference to the outside

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#588]
Currently we use local classes within default methods of interfaces because of the lack of private interface methods. E.g. Stream needs inner util classes for recursions. This leaks the enclosing this to the outside and blocks garbage collection of possibly a huge amount of memory.

See http://stackoverflow.com/questions/5054360/do-anonymous-classes-always-maintain-a-reference-to-their-enclosing-instance

**Comment by lukaseder** [comment]
Yes, that's a common mistake. See also: http://blog.jooq.org/2014/12/08/dont-be-clever-the-double-curly-braces-anti-pattern.

The only exception are local/anonymous classes in static methods.

I just realised, I made the same mistake just recently o_O.

**Comment by danieldietrich** [comment]
Yes, I got aware of it as I read your blog some months ago :) Should have linked it. Thx!

**Comment by danieldietrich** [comment]
Local classes are moved to the outside within the same file and are made package private. By convention the class will be named like the (probably one and only) public method of the local class.

Before:

```
interface Stream<T> {
    default Stream<T> appendSelf() {
        class Recursion { 
            ...
            stream();
        }
        return isEmpty() ? this : new Recursion(this).stream();
    }
}
```

After:

```
interface Stream<T> {
    default Stream<T> appendSelf() {
        return isEmpty() ? this : new AppendSelf(this).stream();
    }
}

// command pattern, equivalent to a function, may be moved to a private interface class with Java 9+
final class AppendSelf {
    ...
    stream();
}
```

**Comment by danieldietrich** [comment]
Lambdas do _not_ hold a reference to the enclosing instance by default (see ["State of the Lambda", Pt. 7](http://cr.openjdk.java.net/~briangoetz/lambda/lambda-state-4.html) and ["Trying Out Lambda Expressions in the Eclipse IDE", Section "this in Lambda Expressions"](http://www.oracle.com/technetwork/articles/java/lambda-1984522.html)).
