### ISSUE TITLE
Hide non-puplic API by moving inner classes of interfaces to the outside within the same file

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#592]
HAMT (see also #591), RedBlackTree, ...

**Comment by danieldietrich** [comment]
Example:

```java
public interface Stream<T> {
    final class Nil<T> implements Stream<T> {
        ...
    }
}
```

will be

```java
public interface Stream<T> {
}

// formerly Nil to avoid name clash with List.Nil
final class EmptyStream<T> implements Stream<T> {
}
```

**Comment by danieldietrich** [comment]
TODO:

* Stream.combinations()
* Stream.dropRight()

**Comment by danieldietrich** [comment]
We prefix names of auxiliary classes with the name of the public class or with an abbr. that makes sense. This will avoid name clashes.

Example:

* `Stream.Cons` will be renamed to `StreamCons`

**Comment by danieldietrich** [comment]
`List.Nil` and `List.Cons` will be moved top-level into a package, i.e. `Nil` and `Cons`.

**Comment by danieldietrich** [comment]
It is ugly to prefix the auxiliary classes with the public interface name, e.g.

```java
// file Stream.java

public interface Stream {
}

final class StreamEmpty {
}

final class StreamCons {
}
```

Therefore we will define modules / namespaces:

```java
// file Stream.java

public interface Stream {
}

interface StreamModule {

    final class Empty {
    }

    final class Cons {
    }
}
```

**Comment by ruslansennov** [comment]
<code>new StreamEmpty()</code> vs <code>new StreamModule.Empty()</code>?
I vote for StreamEmpty :)

**Comment by danieldietrich** [comment]
The trick is

```java
import javaslang.collection.StreamModule.*;
```

The it is just `new Empty()`.

The classes within StreamModule are used only within Stream (within the same file). Otherwise the javac -Xlint generates a warning and compiler errors because of our maven config.

**Comment by danieldietrich** [comment]
But you are right - if we cover other public classes within the same package, like List `Cons`, we have to fully qualify them. But I think these cases currently not exist (or are extremely rare).

**Comment by danieldietrich** [comment]
Yep, StreamModule.Cons clashes with javaslang.collection.Cons (in my local fork).

**Comment by danieldietrich** [comment]
We need to explicitely import Cons like so:

```java
import javaslang.collection.StreamModule.*;
import javaslang.collection.StreamModule.Cons;
```

The static typing makes it safe to use unqualified Cons and prevents us from confusing it with List Cons.

**Comment by danieldietrich** [comment]
Yep, compiling with maven config

```xml
<compilerArgs>
    <arg>-Xlint:all</arg>
    <arg>-Werror</arg>
</compilerArgs>
```

(which is default for Javaslang) leads to a compile error if we access an auxiliary module from the outside of a file:

```
[WARNING] /Users/daniel/git/javaslang/src/test/java/javaslang/collection/RedBlackTreeTest.java:[9,28] auxiliary class javaslang.collection.RedBlackTreeModule in RedBlackTree.java should not be accessed from outside its own source file
```

This makes auxiliary modules great for designing Java 8 APIs based on interfaces which need additional, internal types, which should not be part of the public API. Especially these modules allow to declare classes with names, which may otherwise be ambiguous if located in the same package.

**Comment by danieldietrich** [comment]
Disadvantage: the internal classes, part of the auxiliary module, are not accessible from a unit test :(

**Comment by danieldietrich** [comment]
On the other hand this is also an advantage regarding clean interface design. I'm not a big fan of whitebox tests. Tests are more robust against refactoring and changes of implementation details when they are formulated on a high level. The variety of business cases implies the coverage quality.

**Comment by danieldietrich** [comment]
I'm not sure if we really need to make Cons and Nil (of List) public. Java (and Javaslang) currently do not have deep, structural pattern matching. The `List.isEmpty()` method should be sufficient for now to distinguish between Cons and Nil.

* `List.of(elem)` is the same as `new Cons<>(elem)`
* `List.empty()` is the same as `Nil.instance()`

We should keep it simple and hide Cons and Nil. They can be still added later as public API, if needed, without affecting/breaking existing code.

**Comment by danieldietrich** [comment]
I'm torn back and forth regarding Cons an Nil. We need a consistent way to integrate structural collection types.

Status Quo:

* List has Cons and Nil which are public first-level API (located in the same package).
* Stream has Cons and Empty which are hidden in a module interface and not public API

To keep it consistent, we will move Cons & Nil and Cons & Empty back to List and Stream (as static inner classes. This avoids name clashes and makes these types available for pattern matching via Match.

**Comment by danieldietrich** [comment]
`AbstractIterator` is public API and will remain in `javaslang.collection`.

**Comment by danieldietrich** [comment]
Fixed
