### ISSUE TITLE
Map::zipAll(Iterable<U> that, Entry<K, V> thisElem, U thatElem)

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#595]
I believe this method should be removed.
* we can't produce resulting map if <code>thisElem</code> is <code>null</code>
* we can't produce resulting map if <code>thisElem</code> repeats more than once
* this method completely crazy in this case

**Comment by danieldietrich** [comment]
Scala has it (http://www.scala-lang.org/api/2.11.5/index.html#scala.collection.immutable.Map). We should stay with it, too.

REPL says:

```
# this is longer than that
scala> Map(1 -> 'a', 2 -> 'b', 3 -> 'c').zipAll(List(6, 7), (99 -> 'z'), 99)
res0: scala.collection.immutable.Map[Any,Int] = Map((1,a) -> 6, (2,b) -> 7, (3,c) -> 99)

# this is shorter than that
scala> Map(1 -> 'a', 2 -> 'b', 3 -> 'c').zipAll(List(4, 5, 6, 7), (99 -> 'z'), 99)
res1: scala.collection.immutable.Map[(Int, Char),Int] = Map((1,a) -> 4, (2,b) -> 5, (3,c) -> 6, (99,z) -> 7)

# thisElem is null
scala> Map(1 -> 'a', 2 -> 'b', 3 -> 'c').zipAll(List(4, 5, 6, 7), null, 99)
res2: scala.collection.immutable.Map[(Int, Char),Int] = Map((1,a) -> 4, (2,b) -> 5, (3,c) -> 6, null -> 7)

# thisElem repeats more than once
scala> Map(1 -> 'a', 2 -> 'b').zipAll(List(4, 5, 6, 7), (99 -> 'z'), 99)
res3: scala.collection.immutable.Map[(Int, Char),Int] = Map((1,a) -> 4, (2,b) -> 5, (99,z) -> 7)
```

> * we can't produce resulting map if thisElem is null

we allow null keys, aren't we?

> * we can't produce resulting map if thisElem repeats more than once

it is defined behavior to overwrite values

**Comment by ruslansennov** [comment]
> we allow null keys, aren't we?

in HasMap keys should have hash code
in TreeMap keys should be comparable :)

**Comment by danieldietrich** [comment]
of cause :)

We allow null to be inserted into RedBlackTree and therefore into (future) TreeMap, if the comparator is able to compare nulls. I.e. java.util.Comparator.nullsFirst().

If we use Objects.hashCode(object), we are fine with inserting null into HashMap:

> ```public static int hashCode(Object o) {
        return o != null ? o.hashCode() : 0;
    }```

**Comment by ruslansennov** [comment]
do you mean that the user has to choose the right generic type if he uses this method?

**Comment by ruslansennov** [comment]
but Tuple hasn't right comparator or right hash code calculator

**Comment by danieldietrich** [comment]
For SortedSet / TreeSet this is true. Similar to java.util.TreeSet, there can occur RuntimeException, if the generic type is not comparable. When we create a new SortedSet, we are fine - the factory methods are safe and take care of choosing the right comparator. But Java's type system doesn't allow us to change the inherited generics of Set. So, for example, the `map` method's result component type `U` has to be comparable by convention.

**Comment by danieldietrich** [comment]
If Tuple needs these, we will implement them. E.g. component-wise comparision.

**Comment by danieldietrich** [comment]
What's wrong with Tuple's hashCode? Looks good to me...

**Comment by ruslansennov** [comment]
Sorry, Tuple's hash code is fine.
OK, HashMap has now only one TODO, this strange method (for me).

**Comment by danieldietrich** [comment]
Top! :+1:

**Comment by danieldietrich** [comment]
All is done here. Comparable Tuples is part of #605

**Comment by danieldietrich** [comment]
Sorry, thought #603 fixed it, but HashMap.zipAll is still open. TreeMap is another story.

**Comment by danieldietrich** [comment]
The original issue is finished. We will take care of comparable tuples returned by TreeMap.zipAll (see #428).

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://imsomemphis.us/caught.php?suo>

 

arnon@moscona.com

**Comment by arnonmoscona** [comment]
Hello!

 

New message, please read <http://consultorajimenez.com/feeling.php?4f>

 

arnon@moscona.com
