### ISSUE TITLE
Seq.slice should not throw

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#597]
Scala's slice does not throw, so we should also not throw:

```
scala> List(1, 2, 3, 4).slice(1, 2)
res0: List[Int] = List(2)

scala> List(1, 2, 3, 4).slice(1, 3)
res1: List[Int] = List(2, 3)

scala> List(1, 2, 3, 4).slice(1, 10)
res2: List[Int] = List(2, 3, 4)

scala> List(1, 2, 3, 4).slice(-10, 10)
res3: List[Int] = List(1, 2, 3, 4)
```

**Comment by danieldietrich** [comment]
Take care of `CharSeq.subSequence()` (inherited from CharSequence) and `CharSeq.substring()` (from String).

**Comment by danieldietrich** [comment]
We may add `Seq.subSequence(int)` and `Seq.subSequence(int, int)` in addition to `slice(int)` and `slice(int, int)`.

The difference is that `subSequence` throws IndexOutOfBoundsException.

Let's have both methods.

**Comment by danieldietrich** [comment]
TODO: let CharSeqTest extends AbstractSeqTest if possible and remove code duplication.

TODO: Merge CharSeqTest and StringTest

**Comment by jasoet-gdp** [comment]
I think we need to take care all of `Seq` sub class such as `List`, `Stream` etc.

**Comment by danieldietrich** [comment]
@jasoet-gdp Yes, you are right. All sub-classes need to be changed.

**Comment by danieldietrich** [comment]
We will remove slice(beginIndex) since it has exactly the same semantics as drop(count) (even if slice() takes an index and drop() take a count).

However, subSequence(beginIndex) is still needed because it throws on invalid index.
