### ISSUE TITLE
Add LinkedHashMap & LinkedHashSet

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#612]
These will be backed by List + HashMap/HashSet.

See also https://github.com/abasko/linkedhashmap/tree/master/src/Data

It is interesting to see that Scala (and Clojure?) currently do not seem to have immutable LinkedHash* implementations. It is a very common feature in real-world applications. IMO we should providede them, even if some ops make take O(n). This may be further optimized by internally using Vector instead of List.

**Comment by danieldietrich** [comment]
Map implementations:

* HashMap implements Map (no order)
* LinkedHashMap extends HashMap (insertion order)
* TreeMap implements SortedMap (ascending key order, natural order by default, alternatively by user-defined comparator)

**Comment by danieldietrich** [comment]
One limitation of Java's type system is that method return types are only _partially_ covariant. This comes into play when providing more hash-based Set or Map implementations.

Let's take a look at the Set interface.

```java
interface Set<T> {

    Set<T> take(int n);

    Option<? extends Set<T>> initOption();
}
```

Then this is a simple example to make the return type of a method more specific in a sub-class (public modifiers omitted):

```java
class HashSet<T> implements Set<T> {
    @Override
    HashSet<T> take(int n) { ... }
}
```

But if the return type has more complex generics, this is not possible any more:

```java
class HashSet<T> implements Set<T> {
    @Override
    Option<HashSet<T>> initOption() { ... }
}

class LinkedHashSet<T> extends HashSet<T> {
    @Override
    // DOES NOT COMPILE
    Option<LinkedHashSet<T>> initOption() { ... }
}
```

There are two solution:

**1) Open the return type for extension**

```java
/*
     Set
      ^
      |
   HashSet
      ^
      |
LinkedHashSet
*/
class HashSet<T> implements Set<T> {
    @Override
    Option<? extends HashSet<T>> initOption() { ... }
}

class LinkedHashSet<T> extends HashSet<T> {
    @Override
    Option<? extends LinkedHashSet<T>> initOption() { ... }
}
```

**2) Flatten the hierarchy**

```java
/*
       Set
        ^
       / \
HashSet   LinkedHashSet
*/
final class HashSet<T> implements Set<T> {
    @Override
    Option<HashSet<T>> initOption() { ... }
}

final class LinkedHashSet<T> extends Set<T> {
    @Override
    Option<LinkedHashSet<T>> initOption() { ... }
}
```

Currently I tend to take the second approach and not let `LinkedHashSet` extends `HashSet`. It should be sufficient to specify the nature of a data structure (like being a sequence or a set of unique elements) at the declaration site.

I think the situation is rare that an API specifies a class `HashSet` instead of an interface `Set` (which is always preferable) and then returns a `LinkedHashSet`. If the information, that insertion order is preserved, is important, then the API will specify `LinkedHashSet` directly and not `HashSet`.

**Comment by chronodm** [comment]
Is there a reason `LinkedHashSet` doesn't override `toLinkedSet()` to `return this`?

And is there a reason `toLinkedSet()` returns `Set` rather than `LinkedHashSet`?

**Comment by danieldietrich** [comment]
@chronodm 

> Is there a reason LinkedHashSet doesn't override toLinkedSet() to return this?

We designed the conversion methods the way that they are implemented in `Value` and not overridden by any class. For example `toTreeSet()` is implemented like this:

```java
default SortedSet<T> toSortedSet() throws ClassCastException {
        if (this instanceof TreeSet<?>) {
            return (TreeSet<T>) this;
        } else {
            final Comparator<T> comparator = (this instanceof Ordered<?>)
                    ? ((Ordered<T>) this).comparator()
                    : (Comparator<T>) Comparator.naturalOrder();
            return toSortedSet(comparator);
        }
    }
```

We should do the same for `LinkedHashSet`.

> And is there a reason toLinkedSet() returns Set rather than LinkedHashSet?

Once, there was a discussion about returning implementations or interfaces. We decided to return interfaces (but there exist no Linked* interfaces, yet - like in Scala).

There was also a discussion about adding Linked* interfaces but we decided to align to Scala.

However, I see the benefit of making it clear on the type level that a Set or Map ist linked. I would prefer to add LinkedSet and LinkedMap interfaces over returning concrete implementation classes.
