### ISSUE TITLE
Add missing range, rangeBy, rangeClosed, rangeClosedBy methods

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#613]
The range* methods are part of the Seq interfaces.

Iterator provides implementations used by List, Stream et al. It needs the following additional implementations:

* range* of char (calls range* of int and casts)
* range* of double
* range* of float (calls range* of double and casts)
* range* of short (calls range* of int and casts)
* range* of byte ( (calls range* of int and casts)

The linear sequences List, Stack, Stream, Queue and the indexed sequences Array, CharSeq, Vector need to implement the missing rage* methods (e.g. by delegating to Iterator).

**Comment by danieldietrich** [comment]
To keep it simple, we concentrate on char, double, int and long. Java does the same for java.util.stream.Stream. If byte, float or short is needed, map needs to be called with a cast. If it is really needed, a future version of Javaslang may support byte, float and short here.

**The following types need to have the range* methods:**

* Array
* Vector
* List
* Queue
* Stream
* Stack

**Exceptions:**

* CharSeq: It only implements range*(char) because it acts on Character elements only.
* Iterator: It does not extends Seq but it implements all range* methods.

**Static factory methods of Seq implementations (example: List):**

```java

// java.util.stream
static <T> Collector<T, ArrayList<T>, List<T>> collector()

// default
static <T> List<T> empty()
static <T> List<T> of(T element)
static <T> List<T> of(T... elements)
static <T> List<T> ofAll(java.lang.Iterable<? extends T> elements)

// primitive arrays
static List<Boolean> ofAll(boolean[] array)
static List<Byte> ofAll(byte[] array)
static List<Character> ofAll(char[] array)
static List<Double> ofAll(double[] array)
static List<Float> ofAll(float[] array)
static List<Integer> ofAll(int[] array)
static List<Long> ofAll(long[] array)
static List<Short> ofAll(short[] array)

// range/rangeBy
static List<Character> range(char from, char toExclusive)
static List<Character> rangeBy(char from, char toExclusive, int step)
static List<Double> range(double from, double toExclusive)
static List<Double> rangeBy(double from, double toExclusive, double step)
static List<Integer> range(int from, int toExclusive)
static List<Integer> rangeBy(int from, int toExclusive, int step)
static List<Long> range(long from, long toExclusive)
static List<Long> rangeBy(long from, long toExclusive, long step)

// rangeClosed/rangeClosedBy
static List<Character> rangeClosed(char from, char toExclusive)
static List<Character> rangeClosedBy(char from, char toExclusive, int step)
static List<Double> rangeClosed(double from, double toExclusive)
static List<Double> rangeClosedBy(double from, double toExclusive, double step)
static List<Integer> rangeClosed(int from, int toInclusive)
static List<Integer> rangeClosedBy(int from, int toInclusive, int step)
static List<Long> rangeClosed(long from, long toInclusive)
static List<Long> rangeClosedBy(long from, long toInclusive, long step)
```

Stream and Iterator additionally have (modulo return type):

```java
static Stream<Integer> from(int value)
static Stream<Long> from(long value)
static <T> Stream<T> gen(Supplier<? extends T> supplier)
static <T> Stream<T> gen(T seed, Function<? super T, ? extends T> f)

// Stream only
static <T> Stream<T> cons(T head, Supplier<? extends Stream<T>> tailSupplier)

// Iterator only
static <T> Iterator<T> ofIterators(Iterator<? extends T>... iterators)
static <T> Iterator<T> ofIterables(java.lang.Iterable<? extends T>... iterables)
static <T> Iterator<T> ofIterators(Iterator<? extends Iterator<? extends T>> iterators)
static <T> Iterator<T> ofIterables(Iterator<? extends java.lang.Iterable<? extends T>> iterables)
static <T> Iterator<T> ofIterators(java.lang.Iterable<? extends Iterator<? extends T>> iterators)
static <T> Iterator<T> ofIterables(java.lang.Iterable<? extends java.lang.Iterable<? extends T>> iterables)
```

**Comment by lukaseder** [comment]
What's the semantics of a non-discrete range without `step`? :)

E.g. `range(double from, double toExclusive)` or `rangeClosed(double from, double toExclusive)`

**Comment by danieldietrich** [comment]
Like the others, 1.0d. I haven't thought about real-world relevance here...

**Comment by danieldietrich** [comment]
Simplification: It is sufficient to use

```java
static <T> Iterator<T> concat(java.lang.Iterable<? extends java.lang.Iterable<? extends T>> iterables)
```

in favor of the following methods, which will be removed:

```java
// Iterator only
static <T> Iterator<T> ofIterators(Iterator<? extends T>... iterators)
static <T> Iterator<T> ofIterables(java.lang.Iterable<? extends T>... iterables)
static <T> Iterator<T> ofIterators(Iterator<? extends Iterator<? extends T>> iterators)
static <T> Iterator<T> ofIterables(Iterator<? extends java.lang.Iterable<? extends T>> iterables)
static <T> Iterator<T> ofIterators(java.lang.Iterable<? extends Iterator<? extends T>> iterators)
static <T> Iterator<T> ofIterables(java.lang.Iterable<? extends java.lang.Iterable<? extends T>> iterables)
```

**Comment by danieldietrich** [comment]
@lukaseder Yep - will remove `range(double from, double toExclusive)` and `rangeClosed(double from, double toExclusive)`.

**Comment by danieldietrich** [comment]
Scala has `rangeBy(from: T, to: T, step: T)` and implicit type conversion, e.g. from `char` to `int`. We do not have this kind of type conversion in Java and therefore cannot provide a `rangeBy(char from, char toExclusive, char step)`. Instead we will have a `rangeBy(char from, char toExclusive, short step)`. The type `short` fits best here, because it is the same precision as `char`.

**Comment by danieldietrich** [comment]
double is fun...

* NaN (we should throw an IllegalArgumentException)
* positive, negative infinity (have to test, if we set infinity as start)
* fortunately == treats positive zero +0d and negative zero -0d the same
* included/excluded cases are different than in the discrete methods

**Comment by danieldietrich** [comment]
Basically there are the following tests scenarios:

* step == 0
* from == to, step arbitrary
* from < to, step < 0
* from < to, step > 0
* from > to, step < 0
* from > to, step > 0

Additionally we have to test these special cases
(where MIN/MAX may also be NEGATIVE_INFINITY, POSITIVE_INFINITY):

* from = MAX, to = MAX, step < 0
* from = MAX, to = MAX, step > 0
* from = MIN, to = MIN, step < 0
* from = MIN, to = MIN, step > 0
* from = MAX - x, to = MAX, step > 0, 0 < x < step
* from = MAX - step, to = MAX, step > 0
* from = MAX - x, to = MAX, step > 0, x > step
* from = MIN, to = MIN - x, step < 0, 0 > x > step
* from = MIN, to = MIN - step, step < 0
* from = MIN, to = MIN - x, step < 0, x < step

All of these scenarios are multiplied with

* the inclusive and exclusive case
* the with and without step

**Comment by danieldietrich** [comment]
Without loss of generality (POS/NEG INF) it should make sense to allow

```java
// = empty
range(Double.POSITIVE_INFINITY, Double.POSITIVE_INFINITY, step);

// = rangeClosed(finiteDouble, Double.MAX_VALUE, positiveStep)
range(finiteDouble, Double.POSITIVE_INFINITY, positiveStep);
```

**Comment by danieldietrich** [comment]
We have to live with some floating point arithmetic blur:

```java
Double.MAX_VALUE                     // = 1.7976931348623157E308
Double.MAX_VALUE - 3.0E307           // = 1.4976931348623158E308
Double.MAX_VALUE - 3.0E307 + 3.0E307 // = Infinity
```

Given that it might be, that the last, inclusive number of a closed range of doubles is not part of the result.

**Comment by danieldietrich** [comment]
Additionally we need some sort of emergency exit for double ranges because

```java
Double.MAX_VALUE + 1.0 = Double.MAX_VALUE
```

I.e. we may loop forever.
