### ISSUE TITLE
Implement crossProduct(int)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#614]
There already exists `crossProduct()` which returns a `Seq<Tuple2<T, T>>`.

It would be helpful to have additionally a `crossProduct(int n)` that returns a `Seq<? extends Seq<T>>`.

Example:

```java
// ((1, 1, 1), (1, 1, 2), (1, 2, 1), (1, 2, 2), (2, 1, 1), (2, 1, 2), (2, 2, 1), (2, 2, 2))
List.of(1, 2).crossProduct(3);
```

Caution:

```java
seq.crossProdukt(k) = ⏳ // for relatively small seq.length() and k
```

**Comment by danieldietrich** [comment]
#613, #614 and #615 are driven by the jOOQ blog post [How to use Java 8 Functional Programming to Generate an Alphabetic Sequence](http://blog.jooq.org/2015/09/09/how-to-use-java-8-functional-programming-to-generate-an-alphabetic-sequence/).

Having these, we should be able to write the following to solve the puzzle:

```java
CharSeq alphabet = CharSeq.rangeClosed('A', 'Z');
Stream.from(1)
      .flatMap(alphabet::crossProduct)
      .map(Seq::mkString)
      .takeUntil("AAA"::equals);
```

/cc @lukaseder

**Comment by lukaseder** [comment]
That's an elegant approach. Although, I wonder if the naming is perhaps a bit confusing. I'd expect `(1, 2) x (3)` to yield `(1, 3), (2, 3)`, not what you're suggesting. Perhaps, there's a more accurate name for taking a list "to the power of 3"

**Comment by danieldietrich** [comment]
Yes, you are right. I have to think about it. Maybe power()...

**Comment by lukaseder** [comment]
Cartesian power, indeed:
https://en.wikipedia.org/wiki/Cartesian_product#Cartesian_power

**Comment by danieldietrich** [comment]
Yes, http://de.mathworks.com/help/symbolic/mupad_ref/solvelib-cartesianpower.html

I like your generalization using tuples.

**Comment by lukaseder** [comment]
Hmm, I mixed informal tuple and list notations, if that's what you meant....

**Comment by danieldietrich** [comment]
Oh, I just meant the API for cross-joining multiple Seqs - I realized that Javaslang is missing such API. It is not really a generalization but there is no other possibility to capture different generic component types.

**Comment by lukaseder** [comment]
Ah, you mean the implementation of jOOλ's static `crossJoin()` methods... Well, if you're strictly in maths world, cross join is not an associative operation:
https://en.wikipedia.org/wiki/Cartesian_product#Non-commutativity_and_non-associativity

This means that it might not really make sense, mathematically, to "generalise" this over multiple seqs. In SQL, like all operations derived from cartesian products, cross join always flattens nested tuples into a single top-level tuple, which is generally more useful and user-friendly than the mathematical nested tuples. I'm a pragmatic SQL person, not a maths person :)

**Comment by danieldietrich** [comment]
I will stay with the name _crossProduct_ to 'keep the API together'.

The most general form of a _cartestian product_ (or _cross product_ or simply _product_) is the _n-ary cartesian product_, e.g. `X1 x X2 x ... x Xn = (x1, x2, ..., xn)` with `x1 ∈ X1, ..., Xn ∈ Xn`.

The _cartesian power_ is a special case of the _n-ary cartesian product_, where the `Xi = Xj` for all `i, j ∈ {1, ..., n}`.

Here `crossProduct(int n)` denotes `Xⁿ = X x X ... x X` (n times).

To make it more clear I will name the parameter _power_: `crossProduct(int power)`.

**Comment by lukaseder** [comment]
> To make it more clear I will name the parameter power

Fair enough

**Comment by danieldietrich** [comment]
> which is generally more useful and user-friendly than the mathematical nested tuples.

:+1:

> I'm a pragmatic SQL person, not a maths person :)

we need pragmatic solutions and not 'in theory there exists a solution - I can prove it' :-)

**Comment by danieldietrich** [comment]
Another, relatively fast solution for the blog post puzzle using Javaslang:

```java
static <T> Stream<IndexedSeq<T>> solvePuzzle(TraversableOnce<T> alphabet, int power) {
    if (power < 0) {
        throw new IllegalArgumentException("negative power");
    }
    return alphabet.sliding(1).toStream()
            .appendSelf(stream -> stream.flatMap(product -> alphabet.map(product::append)))
            .take(sumOfPowers(alphabet.length(), power));
}

//  n
//  Σ kⁱ = k¹ + k² + ... + kⁿ
// i=1
private static int sumOfPowers(int k, int n) {
    int product = k;
    int sum = product;
    for (int i = 1; i < n; i++) {
        product *= k;
        sum += product;
    }
    return sum;
}
```

**Comment by danieldietrich** [comment]
Made some benchmarks.

**Result:**

```
alphabetic sequence using cartesian product bench(4) took 0.191 sec.
alphabetic sequence using append self bench(4) took 0.033 sec.
```

We see that appendSelf() is great in reusing result which where calculated before.

**Setup:**

```java
public class AlphabeticSequenceBench {

    private static final int COUNT = 4;
    private static final int WARMUP = 2;

    private static final Seq<Character> ALPHABET = CharSeq.rangeClosed('A', 'Z').toStream();

    public static void main(String[] args) {
        benchAlphabeticSequenceUsingCartesianPower();
        benchAlphabeticSequenceUsingAppendSelf();
    }

    static void benchAlphabeticSequenceUsingCartesianPower() {
        bench("alphabetic sequence using cartesian product", COUNT, WARMUP, AlphabeticSequenceBench::cartesianPower);
    }

    static void benchAlphabeticSequenceUsingAppendSelf() {
        bench("alphabetic sequence using append self", COUNT, WARMUP, AlphabeticSequenceBench::appendSelf);
    }

    private static List<String> cartesianPower(int n) {
        return Stream.from(1)
                .flatMap(ALPHABET::crossProduct)
                .map(IndexedSeq::mkString)
                .takeWhile(s -> s.length() <= n)
                .toList();
    }

    private static List<String> appendSelf(int n) {
        return ALPHABET.sliding(1).toStream()
                .appendSelf(stream -> stream.flatMap(product -> ALPHABET.map(product::append)))
                .map(IndexedSeq::mkString)
                .take(sumOfPowers(ALPHABET.length(), n))
                .toList();
    }

    //  n
    //  Σ kⁱ = k¹ + k² + ... + kⁿ
    // i=1
    private static int sumOfPowers(int k, int n) {
        int product = k;
        int sum = product;
        for (int i = 1; i < n; i++) {
            product *= k;
            sum += product;
        }
        return sum;
    }
}
```

**Comment by danieldietrich** [comment]
@lukaseder wanted to benchmark jOOL also, but it seems `Seq.range*()` and `Seq.crossJoin()` are not yet in Maven Central, right?

**Comment by lukaseder** [comment]
No, not yet.

**Comment by danieldietrich** [comment]
Ok. What I've seen so far is that java.util.stream.Stream is really fast. Looking forward to check how it performs.
