### ISSUE TITLE
Benchmark Collection Against Major Alternative Collections API

### ISSUE THREAD

**Issue by sirinath** [javaslang/javaslang#628]
E.g. http://java-performance.info/hashmap-overview-jdk-fastutil-goldman-sachs-hppc-koloboke-trove-january-2015/

**Comment by danieldietrich** [comment]
It would be an unequal comparison because trove4j, goldman-sachs and fast-util target special collections for primitive data types.
Javaslang will target these when project valhalla (brian goetz) is released with the jdk.

**Comment by danieldietrich** [comment]
We should compare with standard Java, Scala, ...

**Comment by sirinath** [comment]
I do not know how long you have to wait for Valhalla. Also look at: https://github.com/miniboxing

**Comment by danieldietrich** [comment]
One 'feature' of Javaslang is, that the only dependency is the JDK. We intentionally keep the library small and clean.

**Comment by danieldietrich** [comment]
Will be done in #725
