### ISSUE TITLE
Organizational Structure

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#632]
Hi all,

Javaslang is now an organization. I really struggled with the setup of teams. We should keep it as simple as possible. It does not make much sense to put all people into a big group/team. I've looked at other github organizations. The teams of really big orgs are often very small. Javaslang will also start small. Therefore I will cancel all invitations and really apologize for all the trouble.

In general, creating teams with write permissions does not make any sense for Javaslang. Like other open source projects we need PRs and code reviews. Nobody should push directly into a source code repository here, including me.

Over the time I will include committers who helped to significantly shape Javaslang.

Also I need volunteers for components like documentation, examples etc. We will create teams for that with persons who are responsible.

Thank you all for your ongoing help!

Daniel

PS: If you have any thoughts, ideas etc. on that, please comment!

/cc
@jorander
@jbgi
@patrox
@martincooper 
@jasoet-gdp
@RobWin
@talios
@ggalmazor
@DillonJettCallis

**Comment by danieldietrich** [comment]
Sorry @DillonJettCallis, I am really messy :) Added you to core library team now. Please find your invitation email...

**Comment by jasoet-gdp** [comment]
@danieldietrich how about if we use concept like this. 

when one of contributor "promote" a project under javaslang organisation then you review it, after you **approve** that, the project will be under javaslang and the contributor will be one who responsible. then you can create team with access to certain project not all project. 

of course the project must have strong relation with base javaslang project such as javaslang usage Example, Jackson Module to Marshall/Unmarshall object with javaslang datastructure, etc.

**Comment by danieldietrich** [comment]
@jasoet-gdp this a really great and thoughtful suggestion. Let's do it that way!

**Comment by danieldietrich** [comment]
I described the new methodology on the main Javaslang organization page.

Are there any volunteers for a `javaslang-jackson` module for serialization/deserialization of Javaslang classes?

**Comment by danieldietrich** [comment]
Organization is running nicely now. People have write-access to sub-projects. Will close this ticket.
