### ISSUE TITLE
Why does Map<K, V> not extend Traversable<Tuple<K, V>>

### ISSUE THREAD

**Issue by lukaseder** [javaslang/javaslang#651]
I'm looking at this from a usability / interoperability perspective. A `Map.Entry` is a very historic type in Java, and I've never been very fond of the idea of dealing with such entries differently than with ordinary tuples.

In Scala, for instance, the type is declared as:

```scala
trait Map[A, +B] extends Iterable[(A, B)] ...
```

So, an `Iterable<Tuple2<A, B>>`. Since you're re-writing all the collections anyway, wouldn't it make sense to reuse `Tuple2` here as well?

**Comment by danieldietrich** [comment]
Sorry Lukas, I've overseen this one. My notification were turned off for weeks o_O

This. Sounds. Absolutely. Right.

Entry should be removed.

**Comment by danieldietrich** [comment]
@lukaseder what do you think - is it ok for the developers to have synonyms `entry._1` for _key_ and `entry._2` for _value_?

**Comment by danieldietrich** [comment]
But yes, I will do it. HashArrayMappedTrie also uses Tuples. Currently we have to convert the entries back and forth. Additionally tuples would nicely integrate, e.g. with `HashMap.ofAll(list.zip(...))`.

**Comment by lukaseder** [comment]
I haven't thought this through... What's in a name :)

**Comment by danieldietrich** [comment]
:-)

thx for this issue - it was a good idea
