### ISSUE TITLE
Create jdk collection views

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#652]
as @jbgi suggested: https://twitter.com/jb9i/status/648427409532932096

**Comment by danieldietrich** [comment]
@jbgi Would you also allow to create a Set view on a List? But Map view on List would clearly make no sense...

**Comment by johnmcclean-aol** [comment]
@danieldietrich  Would this work? To produce a map view on a list, the key = index, value = value ( Map<Integer,T> ). And vice versa List<Map.Entry<K,V>>

**Comment by danieldietrich** [comment]
@johnmcclean-aol Yes, that would be a viable option.

In general, I think it is too much to define all possible views for each Javaslang collection (= number of Javaslang collections * number of Java collections). In a first step we could create a 1:1 dependecy, namely List to ListView, Set to SetView, ...

**Comment by danieldietrich** [comment]
Martin Odersky wants to re-design Scala's views, as [stated in a recent talk](https://www.youtube.com/watch?v=NW5h8d_ZyOs).

Here is the corresponding issue: [Wanted: Strawman proposals for new collections architecture](https://github.com/lampepfl/dotty/issues/818)

Daniel Spiewak wrote down a first idea of redesigning Scala's collections in his [Collections Redesign Proposal](https://gist.github.com/djspiewak/2ae2570c8856037a7738) gist.

**Comment by netzwerg** [comment]
+1 for this issue.

I am particularly keen on getting a `ListView` from an `IndexedSeq`, which would allow usage of `java.util.Collections.binarySearch` without memory overhead.

**Comment by danieldietrich** [comment]
What about adding binarySearch to Seq (List, Stream, Vector, ...)?

**Comment by netzwerg** [comment]
That would work well for my specific needs!

**Comment by danieldietrich** [comment]
It does not make sense to provide java.util Collection views. These are mutable. Javaslang collections are immutable. If we have a java.util.ListView listView on a javaslang.colleciton.List and call listView.add(x), nothing will happen to the view because the immutable change returns a new instace but java.util.List#add returns boolean.
