### ISSUE TITLE
Add factory method 'fill' and 'tabulate' to collections

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#659]
The `fill` create a collection of a specific size and fills the values using a Supplier or Function:

```java
static <T> Xxx<T> fill(int size, Supplier<? extends T> supplier);

static <T> Xxx<T> tabulate(int size, Function<Integer, ? extends T> function);
```

Examples:

```java
List.fill(5, () -> "test");

Map.tabulate(5, i -> new Entry<>(i, "test");
```

_29.12.15: Renamed `fill(int, Function)` to 'tabulate(int, Function)'_

**Comment by simonecarriero** [comment]
Hi,
about the static helper method in Collections we were talking about in #984 I think there are two options.
The first one is to return an array of elements, to be passed to the of(T...) method
```
static <T> T[] tabulate(int n, Function<? super Integer, ? extends T> f) {
    n = n < 0 ? 0 : n;
    @SuppressWarnings("unchecked")
    T[] elements = (T[]) new Object[n];
    for (int i = 0; i < n; i++) {
        elements[i] = f.apply(i);
    }
    return elements;
}
```

The second one is to return an iterator, to be passed to the ofAll(Iterable) method
```
static <T> Iterable<T> tabulate(int n, Function<? super Integer, ? extends T> f) {
    Objects.requireNonNull(f, "f is null");
    return new AbstractIterator<T>() {

        int i = 0;

        @Override
        public boolean hasNext() {
            return i < n;
        }

        @Override
        protected T getNext() {
            return f.apply(i++);
        }
    };
}
```

The bad thing of the first approach is that we have to iterate through the elements twice, one inside Collections.tabulate and one inside of(T...). With the second approach we iterate only once, inside ofAll(Iterator).

Thoughts?

**Comment by danieldietrich** [comment]
Hi,

thank you! Looks great. I made some slight changes similar to the collection conversion methods in Value, which look like this:

```java
@Override
default Set<T> toSet() {
    return ValueModule.toTraversable(this, HashSet.empty(), HashSet::of, HashSet::ofAll);
}

@Override
default Stack<T> toStack() {
    return ValueModule.toTraversable(this, Stack.empty(), Stack::of, Stack::ofAll);
}

@Override
default Stream<T> toStream() {
    return ValueModule.toTraversable(this, Stream.empty(), Stream::of, Stream::ofAll);
}
```

where

```java
static <T extends Traversable<V>, V> T toTraversable(Value<V> value, T empty,
                                                     Function<V, T> ofElement,
                                                     Function<java.lang.Iterable<V>, T> ofAll) {
    if (value.isEmpty()) {
        return empty;
    } else if (value.isSingletonType()) {
        return ofElement.apply(value.get());
    } else {
        return ofAll.apply(value);
    }
}
```

We could do s.th. similar. The methods then look like this (not tested yet):

```java
// called by eager collections
static <T extends Traversable<V>, V> T tabulate(int n, Function<? super Integer, ? extends V> f, T empty, Function<V, T> ofElement, Function<V[], T> ofArray) {
    Objects.requireNonNull(f, "f is null");
    if (n <= 0) {
        return empty;
    } else if (n == 1) {
        return ofElement.apply(f.apply(1));
    } else {
        @SuppressWarnings("unchecked")
        V[] elements = (V[]) new Object[n];
        for (int i = 0; i < n; i++) {
            elements[i] = f.apply(i);
        }
        return ofArray.apply(elements);
}

// called by lazy collections
static <T> Iterator<T> tabulate(int n, Function<? super Integer, ? extends T> f) {
    Objects.requireNonNull(f, "f is null");
    if (n <= 0) {
        return Iterator.empty();
    } else if (n == 1) {
        return Iterator.of(f.apply(1));
    } else {
        return new AbstractIterator<T>() {

            int i = 0;

            @Override
            public boolean hasNext() {
                return i < n;
            }

            @Override
            protected T getNext() {
                return f.apply(i++);
            }
        };
    }
}
```

The lazy version returns an Iterator instead of an Iterable to make it clear that it can be traversed only once.

**Comment by simonecarriero** [comment]
I have an issue due to generics implementing HashMap.tabulate.

Given this Collections.tabulate
```
static <C extends Traversable<T>, T> C tabulate(int n, Function<? super Integer, ? extends T> f, C empty, Function<T[], C> of) {
    Objects.requireNonNull(f, "f is null");
    if (n <= 0) {
        return empty;
    } else {
        @SuppressWarnings("unchecked")
        T[] elements = (T[]) new Object[n];
        for (int i = 0; i < n; i++) {
            elements[i] = f.apply(i);
        }
        return of.apply(elements);
    }
}
```
And this HashMap.tabulate
```
public static <K, V> HashMap<K, V> tabulate(Integer n, Function<? super Integer, ? extends Tuple2<? extends K, ? extends V>> f) {
    return Collections.tabulate(n, (Function<? super Integer, ? extends Tuple2<K, V>>) f, HashMap.empty(), HashMap::ofEntries);
}
```

`HashMap.tabulate(2, i -> new Tuple2<>(i,i))` fails with a java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljavaslang.Tuple2; at the line`return of.apply(elements);` of Collections.tabulate

Replacing Collections.tabulate with the following one everything works fine, but i would avoid it if possible. Any idea?
```
static <C extends Traversable<T>, T> C tabulatee(int n, Function<? super Integer, ? extends T> f, C empty, Function<Iterator<T>, C> of) {
    Objects.requireNonNull(f, "f is null");
    if (n <= 0) {
        return empty;
    } else {
        @SuppressWarnings("unchecked")
        java.util.List<T> l = new java.util.ArrayList<>();
        for (int i = 0; i < n; i++) {
            l.add(f.apply(i));
        }
        return of.apply(Iterator.ofAll(l));
    }
}
```

**Comment by danieldietrich** [comment]
@simonecarriero Hi, I've tested around a bit. Seems it works only if we add a component-type hint:

```java
    static <C extends Traversable<T>, T> C tabulate(int n, Function<? super Integer, ? extends T> f, C empty, Function<T[], C> of, Class<?> componentType) {
        Objects.requireNonNull(f, "f is null");
        if (n <= 0) {
            return empty;
        } else {
            @SuppressWarnings("unchecked")
            T[] elements = (T[]) java.lang.reflect.Array.newInstance(componentType, n);
            for (int i = 0; i < n; i++) {
                elements[i] = f.apply(i);
            }
            return of.apply(elements);
        }
    }
```

Usage:

```java
    @SuppressWarnings("unchecked")
    public static <K, V> HashMap<K, V> tabulate(Integer n, Function<? super Integer, ? extends Tuple2<? extends K, ? extends V>> f) {
        return Collections.tabulate(n, (Function<? super Integer, ? extends Tuple2<K, V>>) f, HashMap.<K, V> empty(), HashMap::<K, V> ofEntries, Tuple2.class);
    }
```

However, this works only for types we already know, like Tuple2. If the type is a generic like T for Set<T>, then we are not able to derive an instance of Class<T>.

I would suggest to keep the method as-is and use 'lazy'  tabulate method for HashMap that returns an Iterator.

What do you think?

**Comment by danieldietrich** [comment]
I ask myself why the cast works in javaslang.collection.Array#of(T) when T is a Tuple2<K, V>:

```java
@SuppressWarnings("unchecked")
public static <T> Array<T> of(T element) {
    return wrap((T[]) new Object[] { element });
}
```

but #tabulate it produces an exception when T is Tuple2:

```java
@SuppressWarnings("unchecked")
T[] elements = (T[]) new Object[n];
```
/cc @ruslansennov 

@simonecarriero this might be also a problem for List.tabulate if T is Tuple2. Could you verify it, please?

**Comment by simonecarriero** [comment]
With Lists everything works fine. Probably the point is that the cast is present only in for Maps. With Array, List and so on the cast it's simply not done! Notice that the exception is not on `T[] elements = (T[]) new Object[n]` but on `of.apply(elements)`, so it's the type-erasure cast.

Collections.tabulate takes a parameter of type `Function<T[], List<T>>`.

In the case of List, the type of the function we are passing is exactly the same. I think the compiler doesn't put a cast to call it with `elements` as argument, because the type of 'elements' is exactly `T[]`

In the case of HashMap, the input type of the function is an actual type, not `T` (the type of f is `Function<Tuple2<? extends K, ? extends V>[], HashMap<K, V>>` and not `Function<T[], List<T>>`). In this case instead, the compiler needs to cast it from T[] to Tuple2[].

**Comment by ruslansennov** [comment]
Ok, what if we will make two tabulate methods, which will have different signatures for seq and maps?

BTW, cast to <code>T[]</code> here
```java
@SuppressWarnings("unchecked")
public static <T> Array<T> of(T element) {
    return wrap((T[]) new Object[] { element });
}
```
is not necessary. This is ancient cast, when <code>Array::wrap()</code> took <code>T[]</code> only. See #994

**Comment by danieldietrich** [comment]
thx @simonecarriero @ruslansennov  ok, it is good that all works for List, Array etc.

Then let's take the tabulate method for HashMap that returns an Iterator, it is fine!

**Comment by simonecarriero** [comment]
OK, I'll do it. Thank you guys!

**Comment by danieldietrich** [comment]
Thx!

**Comment by danieldietrich** [comment]
@simonecarriero Thank you for implementing the methods and the tests! I think we are done now and can close the issue, right?

**Comment by simonecarriero** [comment]
Yes sure :+1:

**Comment by danieldietrich** [comment]
Yay! :+1:
