### ISSUE TITLE
exposing Right<A, B> and Left<A,B> may be a mistake because of the lousy type inference in Java.

### ISSUE THREAD

**Issue by hamnis** [javaslang/javaslang#674]
Useful constructors to help Javas typer like

```Java
    public <L, R> Either<L, R> right(R right) { return new Right<>(right); }
    public <L, R> Either<L, R> left(L left) { return new Left<>(left); }
```

This way we can help the type inference allow to use in combinations with Option better.

**Comment by danieldietrich** [comment]
Hi, thx - great suggestion!

Sorry for the late answer. I just realized that I didn't watch my own project any more o_O and therefore received no notifications. Fixed that.

**Comment by danieldietrich** [comment]
Could you also check, if Either behaves ok for you? The return types are slightly different than in Scala.

In Javaslang we stay in the projection when performing operations, in Scala we leave the projection and return to Left or Right. Subsequent operations need in Scala to project every time.

What do you think which is better? The Scala behavior or the Javaslang behavior?

**Comment by hamnis** [comment]
When writing Scala, I never use scala.Either. In almost all cases I want a right biased Either like `scalaz.\/` or `cats.data.Xor`. 
If I need aggregation of errors, I need a Applicative functor, so `scalaz.Validation` works better there.

**Comment by danieldietrich** [comment]
Need help! Two questions:

You see these...

```java
    public <L, R> Either<L, R> right(R right) { return new Right<>(right); }
    public <L, R> Either<L, R> left(L left) { return new Left<>(left); }
```

...as static factory methods of interface Either, right? You suggest _not_ to expose the specific type, like so, right?

```java
public interface Either<L, R> {
    static <L, R> Right<L, R> right(R right) {
        return new Right<>(right);
    }
    static <L, R> Left<L, R> left(L left) {
        return new Left<>(left);
    }
}
```

Do you have an example where it causes trouble regarding Java's type inference?

> This way we can help the type inference allow to use in combinations with Option better.

Could you please give me an example / combination with Option?

Nearly finished. Thx!

**Comment by hamnis** [comment]
>...as static factory methods of interface Either, right? You suggest not to expose the specific type, like so, right?

Correct. 

For some reason I have removed all examples I had for the failing type inference.
I remember that I quickly got `cyclic inference` whenever I was working with Eithers.

The general case is actually not option, but `Either.fold`

Definition of Either.fold.
```java
interface Either<A,B> {
  <C> C fold(Function<A, C> leftF, Function<B, C> rightf);
}

class Right<A, B> {
  
  public <C> C fold(Function<A, C> leftF, Function<B, C> rightf) {
    rightf.apply(this.right.get());
  }
}

class Left<A, B> {
  
  public <C> C fold(Function<A, C> leftf, Function<B, C> rightf) {
    leftf.apply(this.left().getLeftValue());
  }
}
```
Everything else can be implemented in terms of fold.

example of use:

```java 
either.fold(ex => Option.none(), right => Option.of(right));
```

**Comment by danieldietrich** [comment]
Ok. In a first step I will provide the factory methods.

Sounds like an interface `Foldable` also makes sense. Could be located as internal/auxiliary interface in `Value`, like `FilterMonadic`, `Convertible`, ... Then almost all types will get `fold`, not only `Traversable`s.

**Comment by danieldietrich** [comment]
left and right methods added. Other ideas are tracked in other issues.

Thx!
