### ISSUE TITLE
Static factory method for TupleN

### ISSUE THREAD

**Issue by ggalmazor** [javaslang/javaslang#679]
It could be nice to have static factory method in all arities of Tuple classes to be able to do a static import and write more concise code like:

```java
import static javaslang.Tuple2.t;
import static javaslang.Tuple3.t;

Tuple2<Integer, String> value2 = t(42, "doge");
Tuple3<Integer, String, String> value3 = t(42, "doge", "wow");
```

t() static methods would be named the same accross all arities of Tuple making this API coherent regardless of the size of the tuples that you need to instantiate.

**Comment by jasoet-gdp** [comment]
There are already Static Factory Method for TupleN.

```java
Tuple2<Integer, String> value2 = Tuple.of(42, "doge");
Tuple3<Integer, String, String> value3 = Tuple.of(42, "doge", "wow");
```

**Comment by ggalmazor** [comment]
Oh, I was searching on TupleN classes. Didn't occur to me looking in Tuple. Closing Issue...

Thanks!
