### ISSUE TITLE
Higher Order Types

### ISSUE THREAD

**Issue by sirinath** [javaslang/javaslang#713]
You might be interested in this project also: https://github.com/DanielGronau/highj

**Comment by danieldietrich** [comment]
Thanks. A few months ago I wrote `Kind` as semi-higher order type abstraction and then removed it from the project. It may re-appear when creating a project `javaslang-pure`, which will be a thin, algebraic abstraction layer above `javaslang`.

**Comment by danieldietrich** [comment]
Higher order types as we know them from other languages, like Scala, are not possible in Java.

We already investigated the `Kind` type in Javaslang. But from my currently viewpoint it is still only a partial workaround which clutters the API a lot. Therefore I will close this ticket.

Please let me know if I missed s.th. or give me more details on how to bring this feature into Java/Javaslang.

**Comment by jbgi** [comment]
an annotation processor is being worked on to add type-safety to the highj encoding. See derive4j/hkt#1 (input welcomed).
