### ISSUE TITLE
List<T>.sliding() should return List<List<T>>

### ISSUE THREAD

**Issue by ggalmazor** [javaslang/javaslang#722]
As mentioned in Gitter, in version 2.0.0, List.sliding() returns an Iterator<IndexedSeq<T>> instead of a List<List<T>> (as in previous 1.2.2 version).

It seems reasonable to go back to 1.2.2 version's return type to avoid having to call toList() everytime we call List<T>.sliding()

**Comment by danieldietrich** [comment]
Thinking again about it justifies the current implementation. sliding() and grouped() are Iterable operations. Forcing a Set to return a Set when sliding is not a good idea. Iterator is a good choice, it also lets us convert the sliding() elements to a Traversable.
