### ISSUE TITLE
Create collection benchmarks

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#725]
We could use this as basis:

https://github.com/CodeFX-org/lab-java8streamperformancebenchmark

**Comment by ruslansennov** [comment]
btw <code>benchmark.collection.MapSetBench</code> is wrong.
You can try to modify <code>main(String[] args)</code> on something like this
```java
    public static void main(String[] args) {
        benchHashSet_put();
        benchHashSet_put();
        benchHashSet_put();
        ...
```
and output will be
```
Java HashMap.put bench(1000000) took 0.05 sec.
HashMap.put bench(1000000) took 5.98 sec.
Java HashMap.put bench(1000000) took 0.041 sec.
HashMap.put bench(1000000) took 3.293 sec.
Java HashMap.put bench(1000000) took 0.081 sec.
HashMap.put bench(1000000) took 3.15 sec.
Java TreeSet.add bench(1000000) took 0.317 sec.
```

**Comment by danieldietrich** [comment]
thx! not good. we should delete our little benchmark framework and create a separate `javaslang-benchmark` project containing something more sophisticated.

**Comment by danieldietrich** [comment]
Just wanted to save this snippet here:

```java
public class Bench {

    static final int COUNT = 100000;
    static final int ITERATIONS = 100;
    static final int WARMUP = 10;

    public static void main(String[] args) {

        // Average time after 100 iterations: 6.490000 ms
        timed(() -> scala.collection.immutable.Stream.range(0, COUNT, 1, new scala.math.Numeric.IntIsIntegral$()).length());

        // Average time after 100 iterations: 7.070000 ms (using Lazy with synchronized)
        // Average time after 100 iterations: 5.500000 ms (using Lazy without synchronized)
        timed(() -> javaslang.collection.Stream.range(0, COUNT).length());

        // Average time after 100 iterations: 0.600000 ms
        timed(() -> java.util.stream.IntStream.range(0, COUNT).boxed().count());
    }

    static void timed(Runnable stuff) {
        long vs = 0;
        for (int i = 0; i < WARMUP; i++) {
            System.gc(); // try to get rid of potential GC pauses
            stuff.run();
        }
        for (int i = 0; i < ITERATIONS; i++) {
            System.gc(); // try to get rid of potential GC pauses
            long t = System.currentTimeMillis();
            stuff.run();
            vs += System.currentTimeMillis() - t;
        }
        System.out.printf("Average time after %d iterations: %f ms\n", ITERATIONS, ((double) vs) / ITERATIONS);
    }

}

**Comment by danieldietrich** [comment]
Interesting benchmarks in derive4j/derive4j#30, especially [here](https://github.com/derive4j/derive4j/issues/30#issuecomment-184898626).

It shows, that the _synchronized_ variant fits best for or `Lazy` impl:

```bash
not synchronized:
Average time after 200 iterations: 14.260000 ms

Lazy synchronized:
Average time after 200 iterations: 17.850000 ms

Lazy AtomicReference:
Average time after 200 iterations: 18.785000 ms

Lazy synchronized WeakReference:
Average time after 200 iterations: 20.530000 ms

Lazy AtomicReference of WeakReference:
Average time after 200 iterations: 18.230000 ms
```

**Comment by malduarte** [comment]
@danieldietrich : Is using jmh (http://openjdk.java.net/projects/code-tools/jmh/) an option?

**Comment by danieldietrich** [comment]
Yes, it is! Are you interested in writing benchmarks? That would be really great.

**Comment by mping** [comment]
The blog (from one of the authors I think) has some really neat code: http://shipilev.net/blog/2016/arrays-wisdom-ancients/#_benchmark

@malduarte I can also lend a hand

**Comment by malduarte** [comment]
@mping That's a really good post. Serious benchmarking is really hard. 

> At this point, most people make the major mistake: they run with these numbers as if they are the truth. But these numbers are just data, they don’t mean anything unless we extract the insights out of them. To do that, we need to see why the numbers are like that.

**Comment by danieldietrich** [comment]
@mping @malduarte it is great to have you both on board! To warm up I would add the needed dependency/dependencies to the `javaslang/pom.xml`. @RobWin did that already in his project javaslang-circuitbreaker (which has a grade build): https://github.com/javaslang/javaslang-circuitbreaker/tree/master/src/jmh/java/javaslang/circuitbreaker

My vision is to just make it run with the test-build. Later we might extract the benchmarks to a separate module or project but that's not important for now. First we can concentrate of very simple benchmarks, e.g. having a specific collection, we measure some basic operations, all one-liners. These operations could be those documented in our [javadoc](http://www.javaslang.io/javadoc/snapshot/javaslang/collection/package-summary.html):

These operations:

* head()
* tail()
* get(int)
* update(int, T)
* prepend(T)
* append(T)

Starting with these collections:

* List
* Stream
* Vector

Later I want to find a way to compare Javaslang vs Scala vs Clojure (and maybe Kotlin?)

**Comment by mping** [comment]
@danieldietrich after much fiddling with maven, I got something here: https://github.com/javaslang/javaslang/pull/1162

I haven't touched maven/java for a while, so feel free to comment

**Comment by malduarte** [comment]
@danieldietrich , @mping  Added https://github.com/javaslang/javaslang/pull/1187. Currently only the javaslang implementations. Next step will be to provide Scala implementation of the same benchmarks

**Comment by mping** [comment]
@malduarte great! Gonna take it for a spin

**Comment by danieldietrich** [comment]
Great!

**Comment by danieldietrich** [comment]
Tests are ongoing. I will release 2.0.0 final this week. The benchmarks will be part of 2.1.0.

**Comment by danieldietrich** [comment]
Another candidate to compare with Javaslang: http://pcollections.org/

**Comment by danieldietrich** [comment]
We have a great javaslang-benchmark module now. Test are ongoing. This issue can be closed.
