### ISSUE TITLE
I'm tempted to remove Value.flatten(), again.

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#751]
Reasons:

* I haven't seen a real-world use-case yet.
* The result is untyped, casting may lead to runtime exceptions (which is not acceptable).
* It is one of the most complex methods.
* There is a workaround with `flatMap(Funtion.identity())` that cascades one level.
* There will be an additional workaround `transform(Xxx::flatten)` that will flatten a Traversable to another collection type.

**Comment by danieldietrich** [comment]
See #723

**Comment by danieldietrich** [comment]
@ggalmazor Do you need/use `flatten()` directly? Is it a viable option for you to use one of the alternatives mentioned above?

**Comment by ggalmazor** [comment]
We don't really have more than one level depth monadic structures... therefore we don't need a cascading `.flatten()`.

In our case, 100% of the times that we want to flatten a structure, we want to retain types by applying `.flatMap(Function.identity())` because it's always a one level depth structure.

It would be great to replace the current (v2) implementation of `.flatten()` for an alias to `.flatMap(Function.identity())`as it would produce a more compact and easy to read code (as in v1).

**Comment by danieldietrich** [comment]
Thx for the feedback, I will implement your idea to use flatten() as shortcut for flatMap(identity()).

**Comment by ggalmazor** [comment]
Great to hear that, thx!

**Comment by danieldietrich** [comment]
Some specs...

### Flatten

```java
interface FilterMonadic<T> {
    /**
     * Flattens this {@code Value} by one level.
     * <p>
     * Example:
     *
     * <pre><code>List(Some(1), Some(2), None).flatten() = List(1, 2)</code></pre>
     *
     * <strong>Caution:</strong> Effectively {@code flatMap(Function.identity())} is called. That requires this
     * elements to be of type {@code java.lang.Iterable<U>}. More specifically this type {@code FilterMonadic<T>}
     * has to be of type {@code FilterMonadic<? extends java.lang.Iterable<U>>} for some given {@code U}.
     * We (currently) can't express this constraint with Java's type system. If this type does not fulfill the
     * requirement at runtime, a {@code ClassCastException} is thrown.
     * <p>
     * <strong>It is unsafe to use {@code flatten()}.</strong> Especially this compiles but throws at runtime:
     *
     * <pre><code>// Compiles. Throws at runtime because elements are not Iterable!
     * List<String> list = List(1, 2, 3).flatten();</code></pre>
     *
     * <strong>Also beware of the following exceptional cases:</strong> {@link CharSeq#flatten()} and {@link Map#flatten()}.
     *
     * @param <U> the nested component type
     * @return A flattened version of this {@code Value}.
     * @throws ClassCastException if this elements are not of type {@code ? extends java.lang.Iterable<? extends T>}.
     */
    <U> FilterMonadic<U> flatten();
}
```

Here are some interesting corner-cases:

### CharSeq (a String wrapper)

```java
public final class CharSeq implements CharSequence, IndexedSeq<Character>, Serializable {
    /**
     * Elements of a {@code CharSeq} are flattened to identical characters.
     * <p>
     * <strong>Caution:</strong> Behaves different than most other {@code Value.flatten()} implementations.
     * <p>
     * Example:
     *
     * <pre><code>// = IndexedSeq('a', 'b', 'c')
     * CharSeq.of("abc").flatten();</code></pre>
     *
     * @param <U> the component type of the result, needs to be {@code Character}
     * @return an indexed sequence of characters
     * @throws ClassCastException if {@code U} is not {@code Character}.
     */
    @SuppressWarnings("unchecked")
    @Override
    public <U> IndexedSeq<U> flatten() {
        return (IndexedSeq<U>) Vector.ofAll(this);
    }
}
```

### Map (namely HashMap, TreeMap)

```java
public interface Map<K, V> extends Traversable<Map.Entry<K, V>>, Function<K, V> {
    /**
     * Entries of a {@code Map} are flattened to the elements of their {@code Iterable} values.
     * <p>
     * <strong>Caution:</strong> Behaves different than most other {@code Value.flatten()} implementations.
     * <p>
     * Example:
     *
     * <pre><code>// = Seq(1, 2)
     * HashMap.empty()
     *     .put(0, Option.of(1))
     *     .put(1, Option.of(2))
     *     .flatten();</code></pre>
     *
     * @param <U> the component type of the resulting sequence
     * @return an indexed sequence of elements of type U
     * @throws ClassCastException if the value of a map entry {@code (key, value)} is not {@code Iterable}.
     */
    @Override
    <U> Seq<U> flatten();
}
```

**Comment by danieldietrich** [comment]
@ggalmazor It is unsafe but there is no other possibility to express it with Java's type system.

In particular this is now possible:

```java
// = List(1, 2)
List<Integer> ints = List.of(new Some<>(1), new Some<>(2), None.instance());
```

But this also compiles and will throw at runtime:

```java
// two errors: elements not iterable *and* wrong return type assumed
List<String> unsafe = List.of(1, 2, 3).flatten();
```

**Question:** Will you use that in production?

The question is not rhetoric. If you will use it will stay in Javaslang :-)

**Comment by ggalmazor** [comment]
(Just writing this to reason about your quesion... My answer in next comment)

If we're talking about one-level depth, same container .flatten(): yes, we are writing something like this in prod:

```
// = List(1, 2, 3, 4, 5, 6)
List<Integer> flat = List.ofAll(List.ofAll(1, 2, 3), List.ofAll(4, 5, 6)).flatten()
```
(with a `List<List<T>>`)

We aren't using `.flatten()` with structures like the one in your last example:
```
// = List(1, 2)
List<Integer> ints = List.of(new Some<>(1), new Some<>(2), None.instance()).flatten()
```
(with a `List<Option<T>>`)

In this particular case, we are currenlty using filter & map:
```
List<Integer> ints = List.of(new Some<>(1), new Some<>(2), None.instance())
                         .filter(Option::isDefined)
                         .map(Option::get)
```

Now I'm realizing that we could use `.flatten()` for the two cases. The tradeoff is a possible runtime exception if we're not careful, but we already are risking that if we switch to `.flatMap(Function.identity()`.

**Comment by ggalmazor** [comment]
My answer is **YES**, we would use `.flatten()`a lot. The tradeoff is worth the value we are getting.

I'd focus now on producing the most clear error message with the best stacktrace we're able to for when it goes south.

**Comment by danieldietrich** [comment]
@ggalmazor thx for the fast answer - I'm totally agreeing. Haven't thought of providing a better error message, great idea. Will do that!

**Comment by ggalmazor** [comment]
:+1:
