### ISSUE TITLE
Idea for ConsumerN

### ISSUE THREAD

**Issue by ggalmazor** [javaslang/javaslang#756]
It would be great to have ConsumerN implementations just like we have FunctionN implementations.

This would enable us to create curryfied Runnable functions:

```
Consumer2<Dependency1, Dependency2> feature = (dep1, dep2) -> dep1.doStuff(dep2.getStuff());

Runnable featureEnv1 = feature.curried().apply(dep1).apply(dep2);
```

**Comment by danieldietrich** [comment]
IMO its not worth to blow up the type hierarchy. We currently can express the above like so:

```java
// -- using functions

// if dep1.doStuff returns void
Function2<Dependency1, Dependency2, Runnable> feature = (dep1, dep2) -> () -> dep1.doStuff(dep2.getStuff());
        
// if dep1.doStuff returns Runnable
Function2<Dependency1, Dependency2, Runnable> feature = (dep1, dep2) -> dep1.doStuff(dep2.getStuff());

Runnable featureEnv1 = feature.curried().apply(dep1).apply(dep2);

// -- eager way using Try

Try.of(dep2::getStuff).andThen(dep1::doStuff);

// -- cuncurrent way using Future (chaining operations)
Future.of(dep2::getStuff).andThen(dep1::doStuff);
```

(Impl of Future is in the works)

Is this sufficient for you?

**Comment by ggalmazor** [comment]
You're absolutely right! I didn't think of that option...

**Comment by danieldietrich** [comment]
We once had (for a short time) the consumers. But I liked Scala's view on types:

* all is an object / no primitive types
* all is in between Any, AnyRef and Nothing
* Unit is void

This is the foundation for all is a value / an Expression. And all can be expresses using Function*.

I will close this issue then.

Thank you for your ideas! They are very helpful.
