### ISSUE TITLE
Add Xor (right-biased Either)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#762]
See #674

**Comment by mvh77** [comment]
Is there an existing (Scala) implementation of Xor? I'm working on a Java port of Scalactic Or and Every (http://www.scalactic.org/user_guide/OrAndEvery) that's based on javaslang 2.

**Comment by danieldietrich** [comment]
hi, just saw that this is a duplicate of #673. There are links of implementations!

**Comment by danieldietrich** [comment]
> I'm working on a Java port of Scalactic Or and Every (http://www.scalactic.org/user_guide/OrAndEvery) that's based on javaslang 2.

Do you plan to contribute it? (c:

**Comment by mvh77** [comment]
Yes, soon. :)

**Comment by danieldietrich** [comment]
Cool!
