### ISSUE TITLE
Add sequence methods

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#767]
We already have

```java
List<Future<T>> list = ...;
Future<Seq<T>> future = Future.sequence(list);
```

@talios suggested to do this In a similar way for all other `Value` types, also singleton types like Option, Try, Match etc.

**Comment by danieldietrich** [comment]
this is very similar to #716

**Comment by danieldietrich** [comment]
Can't handle this until 2.0.0. Will move this to 2.0.1 which will come soon after...

Example: Lazy.sequence

```java
    /**
     * Reduces many {@code Lazy} values into a single {@code Lazy} by transforming an
     * {@code Iterable<Lazy<? extends T>>} into a {@code Lazy<Seq<T>>}.
     *
     * @param lazyValues An iterable of lazy values.
     * @return A lazy sequence of values.
     */
    public Lazy<Seq<T>> sequence(Iterable<? extends Lazy<? extends T>> lazyValues) {
        Objects.requireNonNull(lazyValues, "lazyValues is null");
        return Lazy.of(() -> Stream.ofAll(lazyValues).map(v -> v.get()));
    }
```

**Comment by enelson** [comment]
Thanks @danieldietrich. I'll start taking a look at this.

**Comment by danieldietrich** [comment]
:+1:

**Comment by danieldietrich** [comment]
We have finished:

* Lazy
* Future
* Option
* Try

We add sequence to:

* Validation

We will leave sequence for the following:

* Either/LeftProjection/RightProjection
* MatchValue
* all collections
