### ISSUE TITLE
Add Validation Applicative Functor

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#803]
See

* [learning Scalaz — Validation](http://eed3si9n.com/learning-scalaz/Validation.html)
* [Scalaz Validation](http://docs.typelevel.org/api/scalaz/nightly/index.html#scalaz.Validation)
* [A Monad in Practicality: First-Class Failures](http://robotlolita.me/2013/12/08/a-monad-in-practicality-first-class-failures.html)

Note: As [John stated](https://gitter.im/javaslang/javaslang?at=5640848fc712fe074e4e9eac), a list of errors can also be collected with the `sequence` function (which will be rolled out in the broad with #767) by turning a `List<Either>` to `Either<List>`.

**Comment by danieldietrich** [comment]
@enelson The `Validation` type should be located in `javaslang.control`. I would use `Try` as reference impl (some function args will be re-visited soon with #865).

We should keep an eye on the functional interfaces Try.Checked*. We use them also in Future and maybe in Validation. There was a recent discussion in #865 if it would make sense to move them outside of Try. But I'm not convinced yet.

**Comment by enelson** [comment]
@danieldietrich Thanks for the info. I'll do some initial work in another branch and see what you think about it. I want to make sure its something that feels right for this project based on your ideas and goals.

**Comment by danieldietrich** [comment]
:+1:

**Comment by danieldietrich** [comment]
We need to take care that Validation is no monad, it is an applicative functor.

See also http://robotlolita.me/2013/12/08/a-monad-in-practicality-first-class-failures.html

**Comment by enelson** [comment]
Yep, exactly what I was going for. If it was a Monad, it would short circuit after the first error, and we want an aggregation of all errors.

**Comment by danieldietrich** [comment]
Great, I will clear the way (see #947)

**Comment by enelson** [comment]
Thanks @danieldietrich.

**Comment by enelson** [comment]
@danieldietrich I would assume that you'd like to keep your current pattern of putting classes with multiple permutations (ie. Function0, Function1, etc) in src-gen, instead of embedding each one as static classes in one Java file? I'm working on a ValidationBuilder class that will have up to ValidationBuilder8 (coinciding with Function8).

**Comment by danieldietrich** [comment]
@enelson Yes, we generate redundant code. However, it better to first write a stable 'prototype' which later is moved to the generator (because writing generator code is not really fun) :-)

I would like to take a look at the builders. I ask myself if we really need them. I have state transitions in mind when I think of Validation. I'm very excited to see your approach!

**Comment by enelson** [comment]
@danieldietrich I'll send over a pull request of what I have so far and see what you think about the approach. I'm VERY frustrated with the lack of support for higher kinded types in Java, so I want to see what ideas you have for a more generic approach.

**Comment by danieldietrich** [comment]
Thx

**Comment by danieldietrich** [comment]
Here is an interesting discussion at a PR of Eric: https://github.com/javaslang/javaslang/pull/986/files#r48573515

A possible implementation of Applicative could make use the Kind type:

```java
// trait Apply[F[_]] extends Functor[F]
public interface Applicative<F extends Kind<F, ?>, A> extends Functor<A> {

    // def ap[A,B](fa: => F[A])(f: => F[A => B]): F[B]
    <B> Applicative<F, B> ap(Kind<F, ? extends Function<? super A, ? extends B>> f);

    @Override
    <B> Applicative<F, B> map(Function<? super A, ? extends B> f);
}

// type constructor: TYPE<T> is split in TYPE<?> and T
interface Kind<TYPE extends Kind<TYPE, ?>, T> {
}

interface Validation<E, A> extends Kind<Validation<E, ?>, A>, Applicative<Validation<E, ?>, A> {

    // def ap[EE >: E, B](x: => Validation[EE, A => B])(implicit E: Semigroup[EE]): Validation[EE, B]
    <B> Validation<E, B> ap(Validation<E, ? extends Function<? super A, ? extends B>> f);

    @Override
    <B> Validation<E, B> map(Function<? super A, ? extends B> f);

    // def ap[A, B](fa: => Validation[L, A])(f: => Validation[L, A => B]) = fa ap f
    @SuppressWarnings("unchecked")
    @Override
    default <B> Validation<E, B> ap(Kind<Validation<E, ?>, ? extends Function<? super A, ? extends B>> f) {
        return ap((Validation<E, ? extends Function<? super A, ? extends B>>) (Object) f);
    }
}
```

**Comment by enelson** [comment]
@danieldietrich Concerning our discussion on ApplicativeBuilder, scalaz does use them (you'll see I modeled mine after theirs). I'm not sure if cats uses them, I don't really see any indication that they do. They combine their `Validated` types with `map(n)` functions (i.e. map2, map3, etc). Here are a couple links to look at:

https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/syntax/ApplicativeBuilder.scala
http://non.github.io/cats//tut/validated.html

**Comment by danieldietrich** [comment]
Thank you for the links! The builder looks good, I have no better alternative.

Do they really _combine_ their results with map. I thought combining takes place with |@|.

I like the names Valid and Invalid instead of Success and Failure, like Cats does. It is a better distinction from Try.

**Comment by danieldietrich** [comment]
After further reading I now understand how map2..n combine Validations. In fact these map ops are map in the context of given Validations.

**Comment by enelson** [comment]
Yeah, I agree with the Valid/Invalid types. They are more descriptive. I'll change them to that and you can see if you like it better for Javaslang. 

I'm glad you agree with the Builder pattern. I really think it removes complexity out of the `Validation` class. And yes, the combining does take place with the `|@|` method, its simply a method that accumulates `Validation`s into `ValidationBuilder`s. Basically the same thing as my `combine()` function. 

Ok, so I'll leave the builder in then, and clean up some code to submit for further review. I wanted to know if you liked the method name `combine()`? Also, did I see that you changed your mind on renaming `ap()` to `apply()`? So you want to keep it as `ap()`? 

Thanks for you continued help on this Daniel.

**Comment by danieldietrich** [comment]
Yes, I like the name _combine_ and also _ap_. It prevents from possible future ambiguities of Applicative types that extend Function. You did a great job!

Happy new year! :)

**Comment by enelson** [comment]
Happy New Year to you as well! You're closer to it than I am, so enjoy 2016 before me! :)

**Comment by enelson** [comment]
@danieldietrich I'm still here. :) Just getting back into the work groove, so my progress on this issue has slowed for a bit. I'll commit some updated stuff soon for review. Hope you had a great New Year.

**Comment by danieldietrich** [comment]
@enelson Good to hear :) I thought of you the last days. Thx, the New Year was huge, hope yours too. Looking forwards to the review!

**Comment by danieldietrich** [comment]
I think we finished adding Validation. Implementing Value is another topic.
