### ISSUE TITLE
Implement these methods on Seq and Traversable

### ISSUE THREAD

**Issue by mvh77** [javaslang/javaslang#822]
Seq:
<B> boolean endsWith(Seq<B> that)
int prefixLength(Predicate<? super T> p)
int segmentLength(Predicate<? super T> p, int from)
Seq<T> union(Seq<T> that)

Traversable:
Traversable<T> scan(T z, BiFunction<? super T, ? super T, ? extends T> op)
<B> Traversable<B> scanLeft(B z, BiFunction<? super B, ? super T, ? extends B> op)
<B> Traversable<B> scanRight(B z, BiFunction<? super T, ? super B, ? extends B> op)

I'll work on these when I get the time.

**Comment by danieldietrich** [comment]
Please have a look at #484: 'Get Traversable and Seq right (towards clean Set and Map interface)'.

> Seq union(Seq that)

Instead of `Seq.union(Seq)` we use `Seq.appendAll(Iterable)`. It is more general. Please see #570: ' appendAll vs addAll vs union vs concat'

**Comment by mvh77** [comment]
Ok. I started implementing endsWith on Seq and noticed that startsWith is implemented in IndexedSeq, LinearSeq & Queue when it could (just like in Scala) be implemented just in Seq. Is there a reason for that? Maybe the one in IndexedSeq is more efficient if iterator.drop is not optimised for indexed sequences?

**Comment by ruslansennov** [comment]
> Is there a reason for that? 

No :smile:

**Comment by danieldietrich** [comment]
Haha, very hood

**Comment by mvh77** [comment]
Ok, so next question is, should the argument be a Seq and not an Iterable? endsWith 'needs' a Seq, because you need to know the size upfront (unless you want to iterate over it once to get the size, but that's ugly). In Scala, they take a GenSeq.

**Comment by ruslansennov** [comment]
I believe <code>endsWith()</code> should accept java pure collections. To know size of <code>Iterable</code> you can convert it to any <code>Seq</code>

**Comment by danieldietrich** [comment]
Yes, we should accept Iterable and have a shortcut for Seq (tested with instanceof for example)

**Comment by mvh77** [comment]
Well, I think if you need a Seq you should ask for a Seq. Hiding  the fact that supplying a Seq is more optimal than someting else will not be visible to the caller. Instead, if you ask for a Seq the caller might be able to work with a Seq to begin with, and he will be made aware of the performance hit of transforming his Iterable into a Seq if he has to do it himself. Just my .02$ :smile:

**Comment by danieldietrich** [comment]
@mvh77 I think you are right, let us use Seq as argument. If we think it has to be relaxed we can switch to Iterable later. The outher way (changing it from Iterable to Seq) is not possible without breaking the API.

It is the _functional way_ to pass the argument which are expected. However, there are still methods where it makes sense to pass an Iterable, especially when there are no assumptions about the characteristics of the collection. Examples are filter and flatMap.

**Comment by mvh77** [comment]
YES! I'm glad we think alike on this issue!

**Comment by danieldietrich** [comment]
Thx @mvh77 for bringing this to Javaslang!
