### ISSUE TITLE
Add Value.orElseTry(Try.CheckedSupplier)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#851]
**Semantics:** If the Value is defined, the underlying value is returned. If the Value is empty, `Try.of(checkedSupplier).get()` is returned. In particular, a NoSuchElementException is thrown, if the Try fails.

**Example:** Instead of

```java
Option.of(valueCanBeNull).orElse(Try.of(checkSupplier).get());
```

we want to write

```java
Option.of(valueCanBeNull).orElseTry(checkSupplier);
```

**Comment by RobWin** [comment]
+1 :dancers:

**Comment by danieldietrich** [comment]
Done 🦄
