### ISSUE TITLE
Outline the Javaslang Features on the Front Page (README.md)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#858]

**Comment by RobWin** [comment]
Why not just reference the AsciiDoc documentation?

**Comment by danieldietrich** [comment]
Yes that's better - less is more! It reduces the complexity.

**Comment by RobWin** [comment]
Can we close this issue?

**Comment by danieldietrich** [comment]
yes, it is obsolete now that we have the docs
