### ISSUE TITLE
Lack of Match.MatchFunction.When<T,R> then method which could consume matching object

### ISSUE THREAD

**Issue by krzysztofik** [javaslang/javaslang#862]
It is quite frequent that we want to initiate some action on matching object and not exactly return some value. I know that it is not in agree with functional paradigm, but other way it is impossible to map many switch statements written in java to java.slang pattern matching. Adding methods which could consume matching object, for example	then(java.util.function.Consumer<? super T> consumer)  would solve this gap.

Example:
of(obj).
    whenType(Foo.class).then(out::println)

**Comment by mariuszs** [comment]
:+1:

**Comment by danieldietrich** [comment]
I see the use case.

In fact `Match` is the generalization of an `If`. In other words eventually someone may ask to implement an _else_ case:

```java
Match.of(...).when(...).then(v -> performSideEffects(v)).otherwise(v -> performOtherSideEffects(v));
```

`then` and `otherwise` need the following arg types:

* Consumer
* Runnable

Please not that it will be possible to create:

```java
Match.of(...)
    .when(...).then(function1)
    .when(...).then(function2)
    .when(...).then(consumer) // after this call only otherwise(Consumer) is possible
    .otherwise(consumer); // optional
```

**Comment by krzysztofik** [comment]
It is great that You will include this use case in the upcoming release but Your proposition only partially solve presented (admittedly, poorly described) problem. What I am really talking about is such example scenario:
```
Match.of(msg)
    .whenType(Date.class).then(date -> println(date.getTime()))
    .whenType(String.class).then(str -> println(str.length()))
    .whenType(Number.class).then(num -> println(num.intValue()))
    .otherwise(obj -> println("Unknown " + obj));
```
Similarly 
```
when().then()
```
should be possible.
For more info take a look
https://github.com/nurkiewicz/typeof

**Comment by danieldietrich** [comment]
Thanks for clarification, that is possible. I will do it.

**Comment by krzysztofik** [comment]
Awesome :)

**Comment by mariuszs** [comment]
Wow, great news :)

**Comment by RobWin** [comment]
The question is when do you want to do that when I look at the issue list. Maybe it would be a nice PR or a :santa: gift. :) Looking at @krzysztofik

**Comment by krzysztofik** [comment]
I have reserved nearest weekend for that. I will do my best :)

**Comment by danieldietrich** [comment]
Cool to hear that, I will assist you!

Here come some first informations:

**Match** is implemented as internal [Domain-Specific Language](https://en.wikipedia.org/wiki/Domain-specific_language) (DSL). The types are modeled as inner classes. The structure of the type hierarchy helps to understand how to write sentences in the DSL:

```
Match
    MatchFunction
        WhenUntyped
        When
            Then
        WhenApplicable
        Otherwise
        Case<R>
    MatchMonad
        Of
        WhenUntyped
        When
            Then
        WhenApplicable
        Otherwise
```

Basically we distinguish between two types of `Match` expressions.

1. Match Function: `Function<Object, R> f = Match.when(...).then(...);`
2. Match Monad: `R result = Match.of(obj).when(...).then(...).get();`

Our goal is to add these functions:

public Then<R> then(Supplier<? extends R> supplier) {

to these types:

* WhenUntyped
* When
* Otherwise

**Comment by krzysztofik** [comment]
Hello, I have 2 open questions.

1. I have prepared pull request with implementation for *MatchFunction*. Unfortunately overloaded methods with *Function* and *Consumer* introduce ambiguity. Any idea? :)

2. Regarding *MatchMonad*, internals assumes that any action for matching condition should return something other than *null*.
```
private static <T, R> Option<Supplier<? extends R>> computeResult(...) {
...
return Option.of(() -> f.apply(value)); 
}
```
*Consumer* or *Runnable* returns *null*, so *MatchMonad* will consume each *matching case* and *otherwise case* too :/

**Comment by danieldietrich** [comment]
Should be all ok FWICS (but haven't tested it in depth). Have you tried it? It should not matter if the function `f` does return null because we create an Option of a Supplier (which is always Some(Supplier)) instead of an Option of a Value.

```java
// Some(Supplier)
Option<Supplier<Void>> opt1 = Option.of(() -> null);

// None
Option<Void> opt2 = Option.of(null);
```

**Comment by danieldietrich** [comment]
Thx for your contribution!

**Comment by krzysztofik** [comment]
Yes you have right. It was my mistake. I will correct it and create another pull request :)

**Comment by danieldietrich** [comment]
Thx :)

**Comment by danieldietrich** [comment]
Mmhh - but you didn't change anything regarding the `computeResult` method (see [PR](https://github.com/javaslang/javaslang/pull/951/files)). It should be all fine as it is.

Could you please test the expected behavior? Then we will see if we have a todo.

Thx!

**Comment by krzysztofik** [comment]
No, i do not have to change any line of existing code and of course all will cover all changes with tests.

**Comment by danieldietrich** [comment]
Great, I'm looking forward to it!
