### ISSUE TITLE
Finally remove flatten()

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#871]
Hi @ggalmazor,

a [recent Twitter discussion](https://twitter.com/danieldietrich/status/669534660561629185) with discussions with Brian Goetz has taught me better - we need to stay strict (see also [this Gist](https://gist.github.com/danieldietrich/8a748156a12d031b3aa2)).

Casting to anything will eventually lead to unpredictable behavior. This is not what we expect from robust Java programs.

I hope you don't mind if I finally remove `flatten()`. The workaround is `flatMap(Function.identity())`.

\- Daniel

**Comment by danieldietrich** [comment]
Note to myself: `catch(ClassCastException)` is a smell

**Comment by ggalmazor** [comment]
I declare myself unable (yet) to fully understand that twitter conversation :P (It's clear that I have a long path ahead of me yet to be walked)...

I understand your position in this matter... I'll handle my `unchecked`'s in my code :D

**Comment by danieldietrich** [comment]
Thx!
