### ISSUE TITLE
Stream.groupBy and Iterator.groupBy are not lazy

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#900]

**Comment by ruslansennov** [comment]
I believe <code>{lazy collection}.groupBy()</code> should be greedy.
To make it lazy we must implement immutable <code>Map&lt;K, Traversable&lt;T&gt;&gt;</code> with <code>get()</code> method like this:
```java
Option<Traversable<T>> get(K key) {
    return Option.of(source.filter(s -> classifier.apply(s).equals(key));
}
```
But some other methods (like <code>entrySet()</code>) doesn't make sense

**Comment by danieldietrich** [comment]
Mmhh, ok - will defer this until 2.0.1. We may close it after digging deeper into Scala's behavior.

**Comment by danieldietrich** [comment]
A lazy groupBy would be a deferred execution. I agree that it makes no sense here.
