### ISSUE TITLE
Create Tree factory method of(T...)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#935]
`Tree.of(1, 2, 3, 4)` would produce:

```
   1
 / | \
2  3  4
```

**Comment by danieldietrich** [comment]
This would be the solution:

```java
@SuppressWarnings("varargs")
@SafeVarargs
static <T> Tree<T> of(T... values) {
    final List<T> list = List.of(values);
    return list.isEmpty() ? empty() : of(list.head(), list.tail().map(Tree::of));
}
```

However, IntelliJ IDEA 15.0.1 does not compile calls like `Tree.of(1, Tree.of(2), Tree.of(3))` now with the error message:

```
Could not resolve method 'of(int, javaslang.collection.Tree.Node<java.lang.Integer>, javaslang.collection.Tree.Node<java.lang.Integer>)'
```

But jdk1.8.0_66 and Eclipse Neon M2 do compile it.

I will defer this addition until 2.0.1 and hope that this issue will be fixed by IntelliJ. Maybe we should create an issue on the bug tracker...

**Comment by simonecarriero** [comment]
I did this as part of #659, Tree.of was needed to implement the tabulate method.

**Comment by danieldietrich** [comment]
Yes, I've seen it. It is ok - IntelliJ IDEA 15.0.2 has still compile errors. I will file close this issue and file a bug.

**Comment by danieldietrich** [comment]
Issue: [IDEA-150224](https://youtrack.jetbrains.com/issue/IDEA-150224)
