### ISSUE TITLE
Exceptions coverage

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#936]
codecov.io shows a lot of red lines in similar places of <code>Iterator</code> code.
```java
public T next() {
    if (!hasNext) {
        EMPTY.next();  //  <- red line, here it should throw
    }
    // other code
}
```
But we have needed tests!

The explanation is on the [FAQ page](http://eclemma.org/jacoco/trunk/doc/faq.html):
> Source code lines with exceptions show no coverage. Why?

> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

We can keep these lines red, but I believe we should change <code>EMPTY.next()</code> to <code>throw new NoSuchElementException(...)</code>
Yes, it would lead to duplication of exception message, but would achieve 100%

**Comment by danieldietrich** [comment]
Wow, didn't know that.

It is more important to be sure to have all covered.

Lets

```java
throw new NoSuchElementException(ERR_NEXT_ON_EMPTY);
```

with

```java
abstract class AbstractIterator<T> implements Iterator<T> {
    
    protected static final String ERR_NEXT_ON_EMPTY = "next() on empty iterator";

    @Override
    public String toString() {
        return (isEmpty() ? "" : "non-") + "empty iterator";
    }
}
```

**Comment by danieldietrich** [comment]
May I assign you to this task?

**Comment by ruslansennov** [comment]
you can assign me to any task :)

**Comment by danieldietrich** [comment]
oookay - I will come back to that offer ;-)
