### ISSUE TITLE
Has a type 'Validation' been started or considered?

### ISSUE THREAD

**Issue by enelson** [javaslang/javaslang#938]
If you ware familiar with scalaz, you'll know about the Validation type. This type is an applicative functor, and differs from Monads in that they don't short circuit as soon as they hit an error (or null, etc). They continue to process their chain and gather all errors together. I'm including a link that describes these types. Has any work begun on such a type? If not, I may begin work on implementing it. Just let me know what you think. Thanks!

http://eed3si9n.com/learning-scalaz/Validation.html

**Comment by danieldietrich** [comment]
A contribution is greatly appreciated! There is already an issure: #803 

I added it to the next minor release 2.0.1, targeted for Q1/2016. For the 2.0.0 we have closed shop now, so it would be best if you create a separate branch for that feature.

**Comment by danieldietrich** [comment]
Please let's move the discussion to #803. I close this as duplicate.

**Comment by enelson** [comment]
@danieldietrich Great. Thanks for the update. I'll start looking into this for 2.0.1.
