### ISSUE TITLE
A pretty-printing class for laying out text in two dimensions, using a simple box model.

### ISSUE THREAD

**Issue by romildo** [javaslang/javaslang#950]
I would like to have a pretty-printing library for laying out text in two dimensions, using a simple box model.
The book *Programming in Scala* (by Martin Odersky and others) presents such a library in its tenth chapter ([see here](https://books.google.com.br/books?id=MFjNhTjeQKkC&pg=PA177&lpg=PA177&dq=two+dimensional+layout+library&source=bl&ots=FMqeSGKNqu&sig=CziUyBl38vtoqwChRqrj_bj9SPk&hl=en&sa=X&ved=0ahUKEwiljKGXrdnJAhUDiZAKHU_pC84Q6AEINTAE#v=onepage&q=two%20dimensional%20layout%20library&f=false)).
There is also a Haskell library for that: [boxes](http://hackage.haskell.org/package/boxes).
Such a library can be helpful to draw a tree as a graph, with nodes and arcs connecting the nodes, in text mode.
I would like to have this feature in `javaslang`. If the developers think it is a good idea, please add it to the project.

**Comment by romildo** [comment]
A preliminary version can be seen at: [java-box](https://github.com/romildo/java-box).

**Comment by romildo** [comment]
Example of output:
```
                     ┌───┐                     
                     │Ann│                     
                     └───┘                     
             ┌─────────┴─────────────┐         
          ┌────┐                  ┌─────┐      
          │Mary│                  │Peter│      
          └────┘                  └─────┘      
   ┌───────┬─┴───────┐          ┌────┴────┐    
┌────┐  ┌─────┐ ┌────────┐  ┌───────┐ ┌───────┐
│John│  │Karen│ │ Steven │  │ Paul  │ │Anthony│
└────┘  └─────┘ │ Abbot  │  │Palucci│ └───────┘
  │             │Braddock│  └───────┘          
┌─────┐         └────────┘                     
│Avila│                                        
└─────┘                                        
```

**Comment by danieldietrich** [comment]
I would love to see this in a render library. I think it goes beyond functional extensions to Java and is worth to get a place of its own.

A render library could also house other pretty-printing related utilities, image renderers (for trees) etc.

Ideas for text renderers:

* arbitrary strings could be aligned to a specific column length (also interesting for the Box model)
* rendering of string templates, including aligning (I used s.th. similar as basis for Javaslang's Generator.scala)
* ...

Ideas for image renderers:

* compute svg vector graphics
* graph aligning algorithms
* ...

I could create a repository `javaslang-render` to include the Box model and Javaslang Tree renderer.

What do you think?

**Comment by romildo** [comment]
I like the idea.

**Comment by danieldietrich** [comment]
Hi @romildo ,

I have invited you to participate.

Once you joined I will give you write permissions to our new repository [javaslang/javaslang-render](https://github.com/javaslang/javaslang-render).

The file structure has to be created accordingly to our other projects. Also I will enable travis-ci etc.

**Comment by danieldietrich** [comment]
@romildo Thanks for joining! I created the repo and gave you write permissions.You find the initial Boxes impl there. You might change it as you want.

**Comment by romildo** [comment]
@danieldietrich Ok. Thank you for the invitation and  for setting up the repository.

**Comment by danieldietrich** [comment]
You're welcome. Short after Javaslang 2.0.0 is released we should also release a version of javaslang-render. But we take the time to get all right and in shape. No hurry.

Note: The versioning will be semantic, namely javaslang-render and javaslang-jackson will have (almost) the same release-cycle as the core project javaslang because they depend on it.

**Comment by danieldietrich** [comment]
Added with the project javaslang-render
