### ISSUE TITLE
FunctionX.lift does not work as expected

### ISSUE THREAD

**Issue by RobWin** [javaslang/javaslang#961]
This fails
```
Map<String, String> jdk8Map = new HashMap<>();
Function1<String, Option<String>> liftedMapGet = Function1.lift(jdk8Map::get);
Option<String> optionalValue = liftedMapGet.apply("NoExistingKey");

assertThat(optionalValue.isEmpty()).isTrue();
```
because optionalValue is not empty. 
I know why it happens, but it feels wrong, because the User does not know that `Try` is used internally and `Success.isEmpty()` returns false.

Maybe `Success` should overwrite `getOption` and return `Option.of(get())`.
What do you think @danieldietrich ?

**Comment by RobWin** [comment]
If you agree, this would be my first PR :)

**Comment by danieldietrich** [comment]
> Maybe Success should overwrite getOption and return Option.of(get()).

That would introduce inconsistencies because

`getOption() == None <=> isEmpty() == true <=> get() throws NoSuchElementException`

We would introduce magic special cases. Especially because Try is of type Value and we expect getOption(), isEmpty() and get() to work the same for every instance of Value.

**Comment by RobWin** [comment]
But it is incosistent right now, because 
`Option.of(() -> jdk8Map.get("unkownKey")) returns `None`

**Comment by danieldietrich** [comment]
Depends - it works correct in the way you defined it. We talk about partial functions. This would be correct in the sense you want it to behave:

```java
Function1<String, Option<String>> liftedMapGet = Function1.lift(key -> {
    if (jdk8Map.containsKey(key)) {
        return jdk8Map.get(key);
    } else {
        throw new NoSuchElementException("unefined at " + key);
    }
});
```

You implicitly interpreted lift in a way it is not specified.

**Comment by RobWin** [comment]
The code above works, because you know that `Try` is used internally, but I bet most users do not know it and think the  function returns None, if the lifted method returns null.

**Comment by danieldietrich** [comment]
Please keep in mind that _lift_ takes a _partial function_.

Look at the docs of Scala's PartialFunction: http://www.scala-lang.org/api/current/index.html#scala.PartialFunction.

Here are the relevant parts:

>  partial function of type PartialFunction[A, B] is a unary function where the domain does not necessarily include all values of type A. The function isDefinedAt allows to test dynamically if a value is in the domain of the function.

and

> It is the responsibility of the caller to call isDefinedAt before calling apply, because if isDefinedAt is false, it is not guaranteed apply will throw an exception to indicate an error condition. If an exception is not thrown, evaluation may result in an arbitrary value.

We could add a method `isDefined(T)` to `Function*`.

**Comment by danieldietrich** [comment]
And the javadoc of Javaslang's Function1 says:

```java
/**
 * Lifts the given {@code partialFunction} into a total function that returns an {@code Option} result.
 *
 * @param partialFunction a function that is not defined for all values of the domain (e.g. by throwing)
 * @param <R> return type
 * @param <T1> 1st argument
 * @return a function that applies arguments to the given {@code partialFunction} and returns {@code Some(result)}
 *         if the function is defined for the given arguments, and {@code None} otherwise.
 */
```

Nothing said here about null - that's your interpretation.

**Comment by RobWin** [comment]
Ok. Then I missunderstood lift.

**Comment by danieldietrich** [comment]
![map get undef null](https://cloud.githubusercontent.com/assets/743833/11903261/36aaa28c-a5b8-11e5-8a60-fd5d6e768c4f.jpg)

**Comment by RobWin** [comment]
<a href="https://imgflip.com/i/vzxk3"><img src="https://i.imgflip.com/vzxk3.jpg" title="made at imgflip.com"/></a>

**Comment by danieldietrich** [comment]
![Some(null)](http://i.imgur.com/NjVta71.jpg)
