### ISSUE TITLE
Tighten pattern matching of Values

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#968]
Currently we have

```java
// match-monad
Match.of(value).when(...).then(...).get();

// match-function
Match.when(...).then(...).apply(value);
```

Scala offers

```scala
value match {
  case ... => ...
}
```

Javaslang has a `Convertible` interface to equip Values with conversion methods. We need to add a `match()` method as convenience method for creating a match-monad `Match.of(...)`.

```java
value.match()
    .when(...).then(...)
    .get();
```

This is syntactic sugar for

```java
Match.of(value)
    .when(...).then(...)
    .get();
```

and especially great when we write fluent APIs and the expression to compute `value` is big.

**Comment by mbarbieri** [comment]
Hi,
I'm trying to do that.
Any suggestion on how to test it?

**Comment by danieldietrich** [comment]
Hi, great to hear!

There are two flavors of match - the MatchMonad and the MatchFunction (see image below).

Implementing equality for functions, especially for MatchFunction, is not possible (or practicable). A function `f: X -> Y` equals `g: X -> Y` if for all `x in X` either `f(x) = g(x)` or `f(x)` and `g(x)` are undefined.

For the two MatchMonads m1 and m2 equality can be defined as:

m1 equals m2 <=> (m1.isEmpty() && m2.isEmpty()) || Objects.equals(m1.get(), m2.get())

Currently I'm re-implementing parts of Match, I will implement the equals method for MatchMonad.

![match](https://cloud.githubusercontent.com/assets/743833/12065491/9cf8a0fa-afd8-11e5-8777-25e275688a73.png)

**Comment by danieldietrich** [comment]
I think I'm tomorrow able to commit my Match changes...

**Comment by mbarbieri** [comment]
Happy New Year! :cocktail:

**Comment by danieldietrich** [comment]
Happy New Year! :fireworks:

**Comment by danieldietrich** [comment]
Recognized a cast error. Already fixed it and will commit it soon.

**Comment by danieldietrich** [comment]
I changed Monad.match() from

```java
Match.MatchMonad.Of<T> match();
```

to

```java
Match.MatchMonad.Of<? extends Convertible<T>> match();
```

Value got:

```java
// currently a default method but should be abstract
Match.MatchMonad.Of<? extends Value<T>> match();
```

All sub-interfaces and -classes need to override match() appropriately, e.g.

```java
interface Seq<T> {
    @Override
    Match.MatchMonad.Of<? extends Seq<T>> match();
}

interface List<T> {
    // Same for Cons and Nil
    @Override
    default Match.MatchMonad.Of<? extends List<T>> match() {
        ...
    }
}
```
