### ISSUE TITLE
Add Convertible.toLeft(R right) and Convertible.toRight(L left)

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#969]
Currently we accept only Suppliers, e.g. `toLeft(Supplier<R>)` and `toRight(Supplier<L>)`.

There may be situations where it is unnecessary to create an additional lambda instance.

**Comment by enelson** [comment]
@danieldietrich I'd be happy to take this on if it hasn't been started. Or if so, are there any un-started issues left in 2.0.0 milestone that I could help with?

**Comment by danieldietrich** [comment]
@enelson great, it's yours! I haven't started to work on it.

The method declarations can be found in Monad.java (see Monad.Convertible), which is generated by Generator.scala.

The implementations reside in Value.java.

**Comment by enelson** [comment]
@danieldietrich Thanks! I imagine that my changes for `Monad` will be made in `Generator.scala` instead of directly to `Monad.java`, yes? If so, how do I run the generator to create the changes in Monad.java?

**Comment by danieldietrich** [comment]
@enelson yes, right. You run it with Maven.

* Command line (also IntelliJ IDEA):  `mvn generate-sources`, or better: `mvn clean test`
* Eclipse: Right click project / run / Maven build... then specify goals `generate-sources` or `clean test`
