### ISSUE TITLE
Bring Javaslang to the Android platform

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#985]
What do we need to do in order to backport Javaslang to Android?

**Goal** is to create a separate build for the Android platform. When necessary, specific features are excluded from the Android version of Javaslang.

**Non-Goal** is to change the actual Javaslang version in order to get it work with Java 7. The original Javaslang project should build only for Java 8 and above.

See also

* [RetroLambda](https://github.com/orfjackal/retrolambda)
* [StreamSupport](http://sourceforge.net/projects/streamsupport/)

**Comment by ruslansennov** [comment]
It may be more realistic to do Javaslang port to Kotlin

**Comment by danieldietrich** [comment]
Mmhh, maybe we should wait for [Jack & Jill](http://tools.android.com/tech-docs/jackandjill) supporting Java 8 on Android.

**Comment by ruslansennov** [comment]
> When necessary, specific features are excluded from the Android version of Javaslang

Anyway it is not enough. 
Android Dalvik format accept only 65k methods in one *.dex file.
There is [solution](http://developer.android.com/intl/ru/tools/building/multidex.html) in modern versions of Android, but this is followed by a lot of troubles

In case of Javaslang it is big problem.

**Comment by danieldietrich** [comment]
Yes. Maybe it is not a good idea.

Output of `du -ah . | grep -v "/$" | sort -r` in `target/classes/javaslang`:

```
 68K	./collection/List.class
 64K	./collection/Stream.class
 60K	./collection/Vector.class
 60K	./collection/CharSeq.class
 60K	./collection/Array.class
 60K	./algebra
 56K	./concurrent
 56K	./collection/Queue.class
 48K	./collection/TreeMap.class
 44K	./collection/TreeSet.class
 40K	./collection/LinkedHashSet.class
 40K	./collection/LinkedHashMap.class
 40K	./collection/Iterator.class
 40K	./collection/HashSet.class
 40K	./collection/HashMap.class
 32K	./concurrent/Future.class
 32K	./collection/Tree.class
 32K	./collection/Stack.class
 32K	./algebra/Monad.class
 24K	./collection/Traversable.class
 24K	./collection/RedBlackTreeModule$Node.class
 24K	./collection/IndexedSeq.class
 24K	./Function8.class
 24K	./CheckedFunction8.class
 20K	./test/Gen.class
 20K	./control/Try.class
 20K	./control/Match$MatchMonad$When$Then.class
 20K	./collection/Seq.class
 20K	./collection/Map.class
 20K	./collection/LinearSeq.class
 20K	./Value.class
 20K	./Function7.class
 20K	./Function6.class
 20K	./CheckedFunction7.class
 20K	./CheckedFunction6.class
 16K	./test/Property$Property8.class
 16K	./test/Property$Property7.class
 16K	./test/Property$Property6.class
 16K	./test/Property$Property5.class
 16K	./test/Arbitrary.class
 16K	./collection/SortedSet.class
 16K	./collection/SortedMap.class
 16K	./Function5.class
 16K	./Function4.class
 16K	./CheckedFunction5.class
 16K	./CheckedFunction4.class
 12K	./test/Property.class
 12K	./test/Property$Property4.class
 12K	./test/Property$Property3.class
 12K	./test/Property$Property2.class
 12K	./test/Property$Property1.class
 12K	./control/Option.class
 12K	./control/Match$MatchMonad$Of.class
 12K	./control/Match$MatchFunction$When.class
 12K	./control/Match$MatchFunction$When$Then.class
 12K	./control/Either$RightProjection.class
 12K	./control/Either$LeftProjection.class
 12K	./concurrent/FutureImpl.class
 12K	./collection/Set.class
 12K	./collection/RedBlackTree.class
 12K	./Tuple8.class
 12K	./Tuple7.class
 12K	./Tuple6.class
 12K	./Tuple5.class
 12K	./Tuple4.class
 12K	./Lazy.class
 12K	./Function3.class
 12K	./Function2.class
 12K	./Function1.class
 12K	./CheckedFunction3.class
 12K	./CheckedFunction2.class
 12K	./CheckedFunction1.class
8.0K	./λ$Type.class
8.0K	./test/Property$ForAll8.class
8.0K	./test/Property$ForAll7.class
8.0K	./test/Property$ForAll6.class
8.0K	./test/Property$ForAll5.class
8.0K	./test/Property$ForAll4.class
8.0K	./control/Match.class
8.0K	./control/Match$MatchMonad$WhenUntyped.class
8.0K	./control/Match$MatchMonad$When.class
8.0K	./control/Match$MatchMonad$Otherwise.class
8.0K	./control/Match$MatchFunction$WhenUntyped.class
8.0K	./control/Match$MatchFunction$WhenApplicable.class
8.0K	./concurrent/Promise.class
8.0K	./collection/TreeModule$Unzip.class
8.0K	./collection/Tree$Node.class
8.0K	./collection/Stream$Cons.class
8.0K	./collection/List$Cons.class
8.0K	./collection/HashArrayMappedTrieModule$LeafSingleton.class
8.0K	./collection/HashArrayMappedTrieModule$LeafList.class
8.0K	./collection/HashArrayMappedTrieModule$IndexedNode.class
8.0K	./collection/HashArrayMappedTrieModule$ArrayNode.class
8.0K	./collection/HashArrayMappedTrieModule$AbstractNode.class
8.0K	./collection/Collections.class
8.0K	./algebra/Foldable.class
8.0K	./ValueModule$Iterable.class
8.0K	./Tuple3.class
8.0K	./Tuple2.class
8.0K	./Tuple1.class
8.0K	./Tuple.class
8.0K	./Function0.class
8.0K	./CheckedFunction0.class
4.0K	./λModule.class
4.0K	./λModule$ReflectionUtil.class
4.0K	./λ.class
4.0K	./test/Property$ForAll3.class
4.0K	./test/Property$ForAll2.class
4.0K	./test/Property$ForAll1.class
4.0K	./test/Property$Condition.class
4.0K	./test/Gen$1Frequency.class
4.0K	./test/Checkable.class
4.0K	./test/CheckResult.class
4.0K	./test/CheckResult$Satisfied.class
4.0K	./test/CheckResult$Falsified.class
4.0K	./test/CheckResult$Erroneous.class
4.0K	./test/Arbitrary$1.class
4.0K	./control/Try$Success.class
4.0K	./control/Try$NonFatalException.class
4.0K	./control/Try$FatalException.class
4.0K	./control/Try$Failure.class
4.0K	./control/Try$CheckedSupplier.class
4.0K	./control/Try$CheckedRunnable.class
4.0K	./control/Try$CheckedPredicate.class
4.0K	./control/Try$CheckedFunction.class
4.0K	./control/Try$CheckedConsumer.class
4.0K	./control/Try$1.class
4.0K	./control/Option$Some.class
4.0K	./control/Option$None.class
4.0K	./control/Option$1.class
4.0K	./control/MatchError.class
4.0K	./control/Match$MatchMonad.class
4.0K	./control/Match$MatchMonad$WhenApplicable.class
4.0K	./control/Match$MatchFunction.class
4.0K	./control/Match$MatchFunction$Otherwise.class
4.0K	./control/Match$MatchFunction$Case.class
4.0K	./control/Match$1.class
4.0K	./control/Either.class
4.0K	./control/Either$Right.class
4.0K	./control/Either$Left.class
4.0K	./control/Either$1.class
4.0K	./concurrent/PromiseImpl.class
4.0K	./collection/VectorModule.class
4.0K	./collection/VectorModule$Combinations.class
4.0K	./collection/Vector$1.class
4.0K	./collection/TreeModule.class
4.0K	./collection/TreeModule$ZipAll.class
4.0K	./collection/TreeModule$Zip.class
4.0K	./collection/TreeModule$Traversal.class
4.0K	./collection/TreeModule$Replace.class
4.0K	./collection/TreeModule$Map.class
4.0K	./collection/TreeModule$FlatMap.class
4.0K	./collection/TreeMap$EntryComparator.class
4.0K	./collection/Tree$Order.class
4.0K	./collection/Tree$Node$SerializationProxy.class
4.0K	./collection/Tree$Empty.class
4.0K	./collection/Tree$1.class
4.0K	./collection/Traversable$1.class
4.0K	./collection/StreamModule.class
4.0K	./collection/StreamModule$StreamIterator.class
4.0K	./collection/StreamModule$StreamFactory.class
4.0K	./collection/StreamModule$DropRight.class
4.0K	./collection/StreamModule$Combinations.class
4.0K	./collection/StreamModule$AppendSelf.class
4.0K	./collection/Stream$Empty.class
4.0K	./collection/Stream$Cons$SerializationProxy.class
4.0K	./collection/Stream$2.class
4.0K	./collection/Stream$1.class
4.0K	./collection/Seq$1Util.class
4.0K	./collection/RedBlackTreeModule.class
4.0K	./collection/RedBlackTreeModule$Empty.class
4.0K	./collection/RedBlackTree$Color.class
4.0K	./collection/RedBlackTree$1.class
4.0K	./collection/ListModule.class
4.0K	./collection/ListModule$SplitAt.class
4.0K	./collection/ListModule$Combinations.class
4.0K	./collection/List$Nil.class
4.0K	./collection/List$Cons$SerializationProxy.class
4.0K	./collection/List$1.class
4.0K	./collection/LinkedHashSet$SerializationProxy.class
4.0K	./collection/LinkedHashSet$1.class
4.0K	./collection/LinearSeqModule.class
4.0K	./collection/LinearSeqModule$LastIndexOfSlice.class
4.0K	./collection/IteratorModule.class
4.0K	./collection/IteratorModule$DistinctIterator.class
4.0K	./collection/IteratorModule$ConcatIterator.class
4.0K	./collection/Iterator$9.class
4.0K	./collection/Iterator$8.class
4.0K	./collection/Iterator$7.class
4.0K	./collection/Iterator$6.class
4.0K	./collection/Iterator$5.class
4.0K	./collection/Iterator$4.class
4.0K	./collection/Iterator$39.class
4.0K	./collection/Iterator$38.class
4.0K	./collection/Iterator$37.class
4.0K	./collection/Iterator$36.class
4.0K	./collection/Iterator$35.class
4.0K	./collection/Iterator$34.class
4.0K	./collection/Iterator$33.class
4.0K	./collection/Iterator$32.class
4.0K	./collection/Iterator$31.class
4.0K	./collection/Iterator$30.class
4.0K	./collection/Iterator$3.class
4.0K	./collection/Iterator$29.class
4.0K	./collection/Iterator$28.class
4.0K	./collection/Iterator$27.class
4.0K	./collection/Iterator$26.class
4.0K	./collection/Iterator$25.class
4.0K	./collection/Iterator$24.class
4.0K	./collection/Iterator$23.class
4.0K	./collection/Iterator$22.class
4.0K	./collection/Iterator$21.class
4.0K	./collection/Iterator$20.class
4.0K	./collection/Iterator$2.class
4.0K	./collection/Iterator$19.class
4.0K	./collection/Iterator$18.class
4.0K	./collection/Iterator$17.class
4.0K	./collection/Iterator$16.class
4.0K	./collection/Iterator$15.class
4.0K	./collection/Iterator$14.class
4.0K	./collection/Iterator$13.class
4.0K	./collection/Iterator$12.class
4.0K	./collection/Iterator$11.class
4.0K	./collection/Iterator$10.class
4.0K	./collection/Iterator$1.class
4.0K	./collection/IndexedSeqModule.class
4.0K	./collection/IndexedSeqModule$LastIndexOfSlice.class
4.0K	./collection/IndexedSeq$1.class
4.0K	./collection/HashSet$SerializationProxy.class
4.0K	./collection/HashSet$1.class
4.0K	./collection/HashArrayMappedTrieModule.class
4.0K	./collection/HashArrayMappedTrieModule$LeafNode.class
4.0K	./collection/HashArrayMappedTrieModule$LeafList$1.class
4.0K	./collection/HashArrayMappedTrieModule$EmptyNode.class
4.0K	./collection/HashArrayMappedTrieModule$Action.class
4.0K	./collection/HashArrayMappedTrie.class
4.0K	./collection/Comparators.class
4.0K	./collection/Comparators$SerializableComparator.class
4.0K	./collection/CharSeqModule.class
4.0K	./collection/CharSeqModule$Combinations.class
4.0K	./collection/CharSeq$CharUnaryOperator.class
4.0K	./collection/CharSeq$CharFunction.class
4.0K	./collection/CharSeq$1.class
4.0K	./collection/ArrayModule.class
4.0K	./collection/ArrayModule$Combinations.class
4.0K	./collection/Array$1.class
4.0K	./collection/AbstractIterator.class
4.0K	./algebra/Semigroup.class
4.0K	./algebra/Monoid.class
4.0K	./algebra/Monoid$1.class
4.0K	./algebra/Functor.class
4.0K	./algebra/Convertible.class
4.0K	./ValueModule.class
4.0K	./ValueModule$Printable.class
4.0K	./Tuple0.class
4.0K	./Lazy$Undefined.class
4.0K	./Lazy$Defined.class
4.0K	./Lazy$1.class
4.0K	./Function8Module.class
4.0K	./Function8Module$Memoized.class
4.0K	./Function8$Type.class
4.0K	./Function8$1.class
4.0K	./Function7Module.class
4.0K	./Function7Module$Memoized.class
4.0K	./Function7$Type.class
4.0K	./Function7$1.class
4.0K	./Function6Module.class
4.0K	./Function6Module$Memoized.class
4.0K	./Function6$Type.class
4.0K	./Function6$1.class
4.0K	./Function5Module.class
4.0K	./Function5Module$Memoized.class
4.0K	./Function5$Type.class
4.0K	./Function5$1.class
4.0K	./Function4Module.class
4.0K	./Function4Module$Memoized.class
4.0K	./Function4$Type.class
4.0K	./Function4$1.class
4.0K	./Function3Module.class
4.0K	./Function3Module$Memoized.class
4.0K	./Function3$Type.class
4.0K	./Function3$1.class
4.0K	./Function2Module.class
4.0K	./Function2Module$Memoized.class
4.0K	./Function2$Type.class
4.0K	./Function2$1.class
4.0K	./Function1Module.class
4.0K	./Function1Module$Memoized.class
4.0K	./Function1$Type.class
4.0K	./Function1$1.class
4.0K	./Function0Module.class
4.0K	./Function0Module$Memoized.class
4.0K	./Function0$Type.class
4.0K	./Function0$1.class
4.0K	./CheckedFunction8Module.class
4.0K	./CheckedFunction8Module$Memoized.class
4.0K	./CheckedFunction8$Type.class
4.0K	./CheckedFunction8$1.class
4.0K	./CheckedFunction7Module.class
4.0K	./CheckedFunction7Module$Memoized.class
4.0K	./CheckedFunction7$Type.class
4.0K	./CheckedFunction7$1.class
4.0K	./CheckedFunction6Module.class
4.0K	./CheckedFunction6Module$Memoized.class
4.0K	./CheckedFunction6$Type.class
4.0K	./CheckedFunction6$1.class
4.0K	./CheckedFunction5Module.class
4.0K	./CheckedFunction5Module$Memoized.class
4.0K	./CheckedFunction5$Type.class
4.0K	./CheckedFunction5$1.class
4.0K	./CheckedFunction4Module.class
4.0K	./CheckedFunction4Module$Memoized.class
4.0K	./CheckedFunction4$Type.class
4.0K	./CheckedFunction4$1.class
4.0K	./CheckedFunction3Module.class
4.0K	./CheckedFunction3Module$Memoized.class
4.0K	./CheckedFunction3$Type.class
4.0K	./CheckedFunction3$1.class
4.0K	./CheckedFunction2Module.class
4.0K	./CheckedFunction2Module$Memoized.class
4.0K	./CheckedFunction2$Type.class
4.0K	./CheckedFunction2$1.class
4.0K	./CheckedFunction1Module.class
4.0K	./CheckedFunction1Module$Memoized.class
4.0K	./CheckedFunction1$Type.class
4.0K	./CheckedFunction1$1.class
4.0K	./CheckedFunction0Module.class
4.0K	./CheckedFunction0Module$Memoized.class
4.0K	./CheckedFunction0$Type.class
4.0K	./CheckedFunction0$1.class
```

**Comment by ruslansennov** [comment]
> Output of du -ah . | grep -v "/$" | sort -r in target/classes/javaslang:
> 68K    ./collection/List.class

No :smile: 
Not size of *.class file, but number of methods
it's not so tragic like size, but we have problems with this

**Comment by danieldietrich** [comment]
Ah, ok.

This reminds me of good old Google Web Toolkit programming. A subset of Java was supported on the client-side. Simple things were simple, complex things were ... possible.

I think then there is no simple way to support the Android platform. Seems like the Android platform has to be changed then :-) And I'm pretty sure that it will be changed when more and more Java libraries will move to Java 8 over time.

@bruce264 I think there's not much we can do at the moment. Too many hurdles...

**Comment by ruslansennov** [comment]
I have played with Javaslang as applied to GWT 2.8 (which accept Java8) and my first attempt was unsuccessful :imp: To support GWT we should rewrite λ (your favorite class), solve a lot of problems with serializations and so on...

**Comment by danieldietrich** [comment]
Sounds like highway to hell. I will rename Javaslang to 'functional backend library for Java 8+' ;-)

**Comment by danieldietrich** [comment]
I will close this for now as not accomplishable in mid-term.

**Comment by danieldietrich** [comment]
First step in that direction by Google?

[Android N and beyond to ditch Oracle’s Java for open source version](http://www.slashgear.com/android-n-and-beyond-to-ditch-oracles-java-for-open-source-version-29420299/)

**Comment by ruslansennov** [comment]
we will see :)

**Comment by bruce264** [comment]
@danieldietrich Let's hope so

@ruslansennov I'm curious about your comment 

"Android Dalvik format accept only 65k methods in one *.dex file."

 I'm currently developing an app with multidexing and I haven't had any issues so far, what's the issue you foresee here for javaslang, does it have more than 65k methods on its own?

**Comment by ruslansennov** [comment]
Hi @bruce264 
No, of course I think Javaslang have less than 65k methods. But a lot. This need to be investigated.
For example, Foldable::map overridden in each of his implemented classes (including all interfaces like <code>Value</code>, <code>Seq</code>, <code>List</code> etc). All of them give us +1 to total methods counter. Me and my colleagues can't use multidexing in our App and can't use guava and others very big (and awesome) libraries.
Some developers that can't use multidexing maybe will be frustrated of Javaslang's port to Android because of these reasons

**Comment by mhdtouban** [comment]
I would love to use javalang in android sometime near in the future, especially that android is adobting java 8.

**Comment by danieldietrich** [comment]
@mhdtouban Someone needs to try to use the existing Javaslang version with the new Android version. If there are any issues please report them. We will see if it is possible to solve them. Maybe we are able to reduce the method count in the next major version.

**Comment by mariopce** [comment]
I used javaslang ver 2.0.0 on android with jack compiler. 
It works ! 
I have some warnings: 
`/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:98-99: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:123-124: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:123-124: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:135-136: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:135-136: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:162-163: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:148-149: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:162-163: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:177-178: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:148-149: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:177-178: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:192-193: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:192-193: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:197-198: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:197-198: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:229-230: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:229-230: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:208-209: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:208-209: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android
/Users/saramakm/projects/tt/maps-android-sample-apps/LocalRepoApp/Function6.java:187-188: Serializable lambda is not supported on Android`

But it works ! 
I used this example: 
`Function2<String, String, String> fun = (s1, s2) -> {
            return s1 + " " + s2;
        };
        String s =  fun.apply("One", "Two");`

And it works fine.

**Comment by ruslansennov** [comment]
could you calculate number of methods in `apk`?

**Comment by mariopce** [comment]
I.e In app I'm using a lot of libraries ( guava, gson ) and javaslang. I need too use multidex.

**Comment by mariopce** [comment]
Version 2.0.5 - works too. :)

apk analyzer don't return method count :(

**Comment by ersin-ertan** [comment]
**9678** Methods for `compile "io.javaslang:javaslang:2.0.5"`

Build Apk fail due to an issue with the annotation processor in - javaslang-match-2.0.5.jar:
<details>

> Error:Execution failed for task ':app:javaPreCompileDebug'.
> > Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
>     - javaslang-match-2.0.5.jar
>   Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
>   See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
> 

</details>


This workaround is confirmed for now:
`android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true`
```

Be sure to set:
minSdkVersion 24 // or higher

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
```

**Comment by tmtron** [comment]
Now that the final version of Android Studio 3 with direct Java8 support is around the corner, I think it's a good time to revisit this issue: see [New Java8 language features Android Studio 3](https://developer.android.com/studio/write/java8-support.html)

# Method Count
I don't think that the vavr develpers should try to reduce the number of methods: The developers who add a library to their Android-application are responsible to decide about the pros and cons of using an external library.

Moreover, the number of methods in a library does not matter so much, because [Code Shrinking](https://developer.android.com/studio/build/shrink-code.html#shrink-code) will strip away all unused code.  So the real number of added methods depends on what parts of a library you actually use.   
Android has tools [APK Analyzer](https://developer.android.com/studio/build/apk-analyzer.html) so that everybody can check how a new library affects their application and may decide to use Multidex to work around the 64k limit or ditch the library.

It should just be noted, that the [ART runtime](https://source.android.com/devices/tech/dalvik/) (which replaces Dalvik since API level 21) has native multidex support: i.e. better performance and we don't need the multidex support library anymore.
see [About the 64K reference limit](https://developer.android.com/studio/build/multidex.html#about)

# Android Support

Just some thoughts of mine for the discussion.

## Annotation Processors
The actual annotations and annotation processors should be in separate jar files.  
Then you can add `vavr-match.jar` (which includes only the annotations) to the classpath and the `vavr-match-processor` to the processor-classpath.

This improves performance and keeps the classpath clean: see also [Use the annotation processor dependency configuration](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#annotationProcessor_config)
>In previous versions of the Android plugin for Gradle, dependencies on the compile classpath were automatically added to the processor classpath. That is, you could add an annotation processor to the compile classpath and it would work as expected. However, this causes a significant impact to performance by adding a large number of unnecessary dependencies to the processor.

Another disadvantage of the current single-jar is that we must [disable an error check](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#disable_the_error_check)
and setup proguard-rules to exclude the processor dependencies, like so:
    
	# unfortunately vavr does not have 2 separate jars for the annotations and for the processor
    -dontwarn io.vavr.match.*
    -dontwarn io.vavr.match.generator.*
    -dontwarn io.vavr.match.model.**

## Java Language Support

[Use Java 8 language features](https://developer.android.com/studio/write/java8-support.html) does not solve all problems with java-code on Android. As the name says, it only allows the use of java language features (e.g. lambdas, Default interface methods, ..). Those features will be processed by the Android tool-chain and thus you can use these features regardless of the Android version: i.e. you can also use your applicatoin which originated from Java-8 source code on old Android 4.0 devices.

## Java Library Support

But this Java8 support does not magically backfill missing java library classes. So it is in a way similar to GWT development: only a subset of the Java SDK is supported. The level of support depends on the device that you install your app on.  

Example:  
The implementation of [toSortedSet](https://static.javadoc.io/io.vavr/vavr/0.9.1/io/vavr/Value.html#toSortedSet--) calls [Comparator.naturalOrder](https://developer.android.com/reference/java/util/Comparator.html#naturalOrder()) which has been added in API level 24.  
This means, that the application will run fine on API Level 24 or higher, but will cause a runtime-exception on older devices.  

The Android build will show this problem:

    Warning: io.vavr.Value$$CC: can't find referenced method 'java.util.Comparator naturalOrder$$STATIC$$()' in library class java.util.Comparator

To work around this problem, users of the vavar library can simply call the overloaded function [toSortedSet(Comparator)]( https://static.javadoc.io/io.vavr/vavr/0.9.1/io/vavr/Value.html#toSortedSet-java.util.Comparator-) which takes a comparator as parameter.

Other problems may be more tricky to solve.  
e.g. the [Function interface](https://developer.android.com/reference/java/util/function/Function.html) has been added in API Level 24. Maybe something like [Android-Retrostreams](https://github.com/retrostreams/android-retrostreams) could help?
	
I guess this is the tricky part of Android Support. And you may have to decide which API levels to support:  
e.g. According to the [Version dashboard](https://developer.android.com/about/dashboards/index.html) from today (10.10.2017) 
* API level 24 or higher: 18%
* API level 21 or higher: 71%

![2017-10-10_13h43_36](https://user-images.githubusercontent.com/20422904/31384861-12ea8bd8-adc1-11e7-8e4a-c7af3dadaf6e.png)

**Comment by danieldietrich** [comment]
@tmtron thanks for the great overview! I will take the 'Annotation Processors' hints into account!
Maybe the modularization of the upcoming Vavr 1.0.0 will help.
We can't change features because of Android because 'form follows function', i.e. we provide the functionality and frameworks may or may not adapt it.
